(asdf:defsystem "mognitio"
  :description "Mognitio compiler"
  :version "0.10.0"
  :depends-on ("sb-posix")
  :serial t
  :components ((:file "src/packages")
               (:file "src/diagnostics")
               (:file "src/runtime-failure")
               (:file "src/integer")
               (:file "src/source")
               (:file "src/syntax")
               (:file "src/syntax-values")
               (:file "src/syntax-generics")
               (:file "src/syntax-v09")
               (:file "src/lexer")
               (:file "src/parser-state")
               (:file "src/parser-values")
               (:file "src/parser")
               (:file "src/semantic-model")
               (:file "src/type-model")
               (:file "src/generic-types")
               (:file "src/declarations")
               (:file "src/semantic-values")
               (:file "src/semantic-context")
               (:file "src/semantic-control")
               (:file "src/semantic")
               (:file "src/checked-context")
               (:file "src/checked-values")
               (:file "src/checked-generics")
               (:file "src/checked-program")
               (:file "src/specialization-model")
               (:file "src/specialization")
               (:file "src/specialization-verifier")
               (:file "src/text-runtime")
               (:file "src/panic-runtime")
               (:file "src/value-runtime")
               (:file "src/closure-list-runtime")
               (:file "src/backend-common-lisp")
               (:file "src/backend-cl-values")
               (:file "src/target")
               (:file "src/ir-control")
               (:file "src/ir")
               (:file "src/ir-values")
               (:file "src/ir-errors")
               (:file "src/ir-value-verifier")
               (:file "src/root-analysis")
               (:file "src/root-verifier")
               (:file "src/register-allocation")
               (:file "src/object-model")
               (:file "src/native-context")
               (:file "src/native-layout")
               (:file "src/native-list")
               (:file "src/native-values")
               (:file "src/native-frame")
               (:file "src/native-memory")
               (:file "src/native-gc")
               (:file "src/native-text")
               (:file "src/native-panic")
               (:file "src/machine-ir")
               (:file "src/amd64")
               (:file "src/elf")
               (:file "src/native-metadata-verifier")
               (:file "src/backend-native")
               (:file "src/artifact")
               (:file "src/project-manifest")
               (:file "src/project-loader")
               (:file "src/project-resolution")
               (:file "src/project-verifier")
               (:file "src/project-checking")
               (:file "src/driver")
               (:file "src/cli"))
  :in-order-to ((asdf:test-op (asdf:test-op "mognitio/tests"))))

(asdf:defsystem "mognitio/tests"
  :depends-on ("mognitio")
  :serial t
  :components ((:file "tests/kernel-driver")
               (:file "tests/harness")
               (:file "tests/generated")
               (:file "tests/native-ir")
               (:file "tests/native-process")
               (:file "tests/v09-native-support")
               (:file "tests/native-generated")
               (:file "tests/v04-allocation")
               (:file "tests/v05-core")
               (:file "tests/v09-inherited")
               (:file "tests/v09-fixtures")
               (:file "tests/v09-boundaries")
               (:file "tests/v09-revision")
               (:file "tests/v09-frontend")
               (:file "tests/v09-source")
               (:file "tests/v09-runtime")
               (:file "tests/v09-lifetime")
               (:file "tests/v09-abi")
               (:file "tests/v09-proofs")
               (:file "tests/v09-memory-boundaries")
               (:file "tests/v09-oracles")
               (:file "tests/v09-examples")
               (:file "tests/v010-projects"))
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call :mognitio.tests :run-tests)
             (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "mognitio" "tests/v010-projects.py"))) :output *standard-output* :error-output *error-output*)))

(asdf:defsystem "mognitio/v09-frontend-tests"
  :depends-on ("mognitio") :serial t
  :components ((:file "tests/kernel-driver")
               (:file "tests/harness")
               (:file "tests/v09-fixtures")
               (:file "tests/v09-boundaries")
               (:file "tests/v09-frontend")))
