(asdf:defsystem "mognitio"
  :description "Mognitio compiler"
  :version (:read-file-line "VERSION")
  :depends-on ("sb-posix")
  :serial t
  :components ((:file "src/packages")
               (:file "src/diagnostics")
               (:file "src/runtime-failure")
               (:file "src/integer")
               (:file "src/source")
               (:file "src/syntax")
               (:file "src/syntax-values")
               (:file "src/syntax-generics")
               (:file "src/syntax-v09")
               (:file "src/syntax-attributes")
               (:file "src/lexer")
               (:file "src/parser-state")
               (:file "src/parser-values")
               (:file "src/parser-attributes")
               (:file "src/parser")
               (:file "src/semantic-model")
               (:file "src/type-model")
               (:file "src/generic-types")
               (:file "src/declarations")
               (:file "src/semantic-values")
               (:file "src/semantic-context")
               (:file "src/attribute-checking")
               (:file "src/semantic-control")
               (:file "src/semantic")
               (:file "src/checked-context")
               (:file "src/checked-values")
               (:file "src/checked-generics")
               (:file "src/checked-program")
               (:file "src/specialization-model")
               (:file "src/specialization")
               (:file "src/specialization-verifier")
               (:file "src/text-runtime")
               (:file "src/panic-runtime")
               (:file "src/assertion-runtime")
               (:file "src/value-runtime")
               (:file "src/closure-list-runtime")
               (:file "src/text-collection-runtime")
               (:file "src/utf8-runtime")
               (:file "src/argument-runtime")
               (:file "src/io-runtime")
               (:file "src/directory-runtime")
               (:file "src/io-signals")
               (:file "src/backend-common-lisp")
               (:file "src/backend-cl-values")
               (:file "src/target")
               (:file "src/ir-control")
               (:file "src/ir")
               (:file "src/ir-values")
               (:file "src/ir-errors")
               (:file "src/ir-value-verifier")
               (:file "src/ir-io-proof")
               (:file "src/root-analysis")
               (:file "src/root-verifier")
               (:file "src/register-allocation")
               (:file "src/object-model")
               (:file "src/test-protocol")
               (:file "src/native-context-layout")
               (:file "src/native-context")
               (:file "src/native-testing")
               (:file "src/native-testing-proof")
               (:file "src/native-layout")
               (:file "src/native-list")
               (:file "src/native-values")
               (:file "src/native-frame")
               (:file "src/native-memory")
               (:file "src/native-gc")
               (:file "src/native-text")
               (:file "src/native-text-collection")
               (:file "src/native-utf8")
               (:file "src/native-arguments")
               (:file "src/native-io-memory")
               (:file "src/native-directory-memory")
               (:file "src/native-directory")
               (:file "src/native-directory-read")
               (:file "src/native-io")
               (:file "src/native-directory-proof")
               (:file "src/native-io-proof")
               (:file "src/native-scalar-root-proof")
               (:file "src/native-primary-phase-proof")
               (:file "src/native-v014-proof")
               (:file "src/native-panic")
               (:file "src/native-assertion")
               (:file "src/machine-ir")
               (:file "src/amd64")
               (:file "src/elf")
               (:file "src/native-metadata-verifier")
               (:file "src/backend-native")
               (:file "src/artifact")
               (:file "src/project-manifest")
               (:file "src/project-loader")
               (:file "src/project-resolution")
               (:file "src/standard-catalog")
               (:file "src/standard-catalog-proof")
               (:file "src/project-verifier")
               (:file "src/project-checking")
               (:file "src/test-process")
               (:file "src/test-preparation")
               (:file "src/test-plan-proof")
               (:file "src/test-output")
               (:file "src/test-runner")
               (:file "src/invocation")
                             (:file "src/driver")
               (:file "src/cli")
               (:file "src/json")
               (:file "src/analysis")
               (:file "src/analysis-tokens")
               (:file "src/identity"))
  :in-order-to ((asdf:test-op (asdf:test-op "mognitio/tests"))))

(asdf:defsystem "mognitio/tests"
  :depends-on ("mognitio")
  :serial t
  :components ((:file "tests/kernel-driver")
               (:file "tests/harness")
               (:file "tests/generated")
               (:file "tests/native-ir")
               (:file "tests/native-process")
               (:file "tests/v09-native-support")
               (:file "tests/native-generated")
               (:file "tests/v04-allocation")
               (:file "tests/v05-core")
               (:file "tests/v09-inherited")
               (:file "tests/v09-fixtures")
               (:file "tests/v09-boundaries")
               (:file "tests/v09-revision")
               (:file "tests/v09-frontend")
               (:file "tests/v09-source")
               (:file "tests/v09-runtime")
               (:file "tests/v09-lifetime")
               (:file "tests/v09-abi")
               (:file "tests/v09-proofs")
               (:file "tests/v09-memory-boundaries")
               (:file "tests/v09-oracles")
               (:file "tests/v09-examples")
               (:file "tests/v010-projects")
               (:file "tests/v011-proofs")
               (:file "tests/v011-runner")
               (:file "tests/v011-transport")
               (:file "tests/v011-review")
               (:file "tests/v012-proofs")
               (:file "tests/v012-host")
               (:file "tests/v012-native")
               (:file "tests/v012-review")
               (:file "tests/v013-host")
               (:file "tests/v013-native")
               (:file "tests/v013-failures")
               (:file "tests/v013-records")
               (:file "tests/v013-runner")
               (:file "tests/v013-proofs")
               (:file "tests/v013-review")
               (:file "tests/v014-text")
               (:file "tests/v014-io")
               (:file "tests/v014-proofs")
               (:file "tests/v014-review"))
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call :mognitio.tests :run-tests)
             (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "mognitio" "tests/v010-projects.py"))) :output *standard-output* :error-output *error-output*)
             (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "mognitio" "tests/v011-testing.py"))) :output *standard-output* :error-output *error-output*)
             (dolist (file '("tests/v012-entry.py" "tests/v012-io.py" "tests/v012-files.py" "tests/v012-execution.py" "tests/v012-reference.py" "tests/v012-review.py"
                             "tests/v013-directory.py" "tests/v013-inheritance.py" "tests/v013-reference.py" "tests/v013-integration.py" "tests/v014-integration.py" "tests/v11-workloads.py"))
               (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "mognitio" file)))
                                 :output *standard-output* :error-output *error-output*))))

(asdf:defsystem "mognitio/v09-frontend-tests"
  :depends-on ("mognitio") :serial t
  :components ((:file "tests/kernel-driver")
               (:file "tests/harness")
               (:file "tests/v09-fixtures")
               (:file "tests/v09-boundaries")
               (:file "tests/v09-frontend")))
