(in-package #:mognitio.tests)

(defun v11-fd-snapshot ()
  (sort (mapcar #'namestring (directory "/proc/self/fd/*" :resolve-symlinks nil)) #'string<))
(defun v11-assert-released (attempt)
  (is (member (mognitio.testing::attempt-resources-process-state attempt) '(:absent :reaped)))
  (is (every #'minusp (mognitio.testing::attempt-resources-fds attempt))))

(deftest v011-runner-command-boundaries
  ;; T11-E08/E16..E20, D11-R03/R05/R09. Failure hooks are outside commit regions.
  (dolist (case '((:before-delegation 0 3 "" "")
                  (:after-delegation 0 3 "aborted=1 not_run=2" "stage=unknown")
                  (:before-spawn 1 2 "passed=1 failed=0 errors=0 aborted=0 not_run=2" "")
                  (:before-result-output 1 3 "passed=1 failed=1 errors=0 aborted=0 not_run=1" "")
                  (:before-summary 0 3 "passed=2 failed=1 errors=0 aborted=0 not_run=0" "")))
    (destructuring-bind (point at code summary context) case
      (let* ((manifest (project-fixture '(("app.mgn" . "namespace App;@test let a:Function():Unit=function():Unit{unit};@test let b:Function():Unit=function():Unit{assert false;};@test let c:Function():Unit=function():Unit{unit};"))))
             (seen 0) (handles nil) (fired nil) (before (v11-fd-snapshot)))
        (multiple-value-bind (out err actual)
            (v11-driver manifest (lambda (event object)
              (when (eq event :before-spawn) (push object handles))
              (when (and (eq event point) (not fired))
                (when (= seen at)
                  (setf fired t)
                  (if (= code 2) (mognitio.testing::runner-io "Injected launch failure")
                      (internal-error "Injected runner failure")))
                (incf seen))))
          (is fired) (same code actual) (is (search context err))
          (if (string= summary "") (progn (same "" out) (is (not (search "tests:" err)))) (is (search summary out))))
        (mapc #'v11-assert-released handles)
        (same before (v11-fd-snapshot)))))
  ;; Parent errors during a real child body or initialization, not after terminal.
  (dolist (stage '(1 2))
    (let* ((hang "var i:Int=0;loop while(i==0){unit};")
           (manifest (project-fixture
             (list (cons "a.mgn" "namespace App;@test let a:Function():Unit=function():Unit{unit};")
                   (cons "b.mgn" (format nil "namespace App;@test let b:Function():Unit=function():Unit{~A};~A"
                                    (if (= stage 2) hang "unit")
                                    (if (= stage 1) (format nil "let init:Unit={~A};" hang) "")))
                   (cons "c.mgn" "namespace App;@test let c:Function():Unit=function():Unit{unit};"))))
           (handles nil) (before (v11-fd-snapshot)))
      (multiple-value-bind (out err code)
          (v11-driver manifest (lambda (point object)
            (when (eq point :before-spawn) (push object handles))
            (when (and (eq point :draining) (= 1 (mognitio.testing::test-case-ordinal object))
                       (= stage (mognitio.testing::test-case-stage object))) (internal-error "Injected active failure"))))
        (same 3 code) (is (search "total=3 passed=1 failed=0 errors=0 aborted=1 not_run=1" out))
        (is (search (if (= stage 1) "stage=initialization" "stage=body") err)))
      (mapc #'v11-assert-released handles) (same before (v11-fd-snapshot))))
  (let ((handle nil) (before (v11-fd-snapshot)))
    (multiple-value-bind (out err code)
        (v11-driver (v11-manifest) (lambda (point object)
          (when (eq point :before-spawn) (setf handle object))
          (when (eq point :after-reap) (internal-error "Injected after reap"))))
      (declare (ignore err)) (same 3 code) (is (search "aborted=1 not_run=1" out)))
    (v11-assert-released handle)
    (replacing (mognitio.testing::raw-wait (lambda (&rest args) (declare (ignore args)) (error "Repeated wait")))
      (replacing (mognitio.testing::raw-kill (lambda (&rest args) (declare (ignore args)) (error "Repeated kill")))
        (replacing (mognitio.testing::raw-close (lambda (&rest args) (declare (ignore args)) (error "Closed reused descriptor")))
          (mognitio.testing::finalize-attempt handle))))
    (same before (v11-fd-snapshot))))

(deftest v011-preparation-cleanup
  ;; D11-R06/R07: one guard owns the preparation session through runner return.
  (dolist (point '(:before-compile :image-created :suite-prepared :runner-entered))
    (let ((paths nil) (seen 0) (before (v11-fd-snapshot)))
      (multiple-value-bind (out err code)
          (v11-driver (v11-manifest) (lambda (event object)
            (when (eq event :image-created) (push (mognitio.testing::test-case-path object) paths))
            (when (eq event point)
              (when (or (member point '(:suite-prepared :runner-entered)) (= seen 1)) (internal-error "Injected preparation failure"))
              (incf seen))))
        (same 3 code) (same "" out) (is (not (search "tests:" err))))
      (dolist (path paths)
        (is (not (probe-file path)))
        (is (not (probe-file (uiop:pathname-directory-pathname path)))))
      (same before (v11-fd-snapshot))))
  (let ((path nil) (seen 0))
    (replacing (mognitio.testing::raw-rmdir (lambda (pointer) (declare (ignore pointer)) -1))
      (multiple-value-bind (out err code)
          (v11-driver (v11-manifest) (lambda (event object)
            (when (eq event :image-created) (setf path (mognitio.testing::test-case-path object)))
            (when (eq event :before-compile) (when (= seen 1) (internal-error "Primary compile failure")) (incf seen))))
        (same "" out) (same 3 code) (is (search "Primary compile failure" err))
        (is (search "cleanup incomplete:" err))
        (is (search (string-right-trim "/" (namestring (uiop:pathname-directory-pathname path))) err))))
    (is (not (probe-file path)))
    (sb-posix:rmdir (namestring (uiop:pathname-directory-pathname path)))))

(deftest v011-real-signal-and-fresh-instances
  ;; T11-E02/E07/E15: external termination is not a language assertion or success.
  (let ((current nil) (pids nil) (killed nil) (before (v11-fd-snapshot)))
    (multiple-value-bind (out err code)
        (v11-driver (project-fixture '(("app.mgn" . "namespace App;@test let hanging:Function():Unit=function():Unit{var i:Int=0;loop while(i==0){unit};};@test let next:Function():Unit=function():Unit{assert true;};")))
          (lambda (point object)
            (when (eq point :after-spawn)
              (setf current object) (push (mognitio.testing::attempt-resources-pid object) pids))
            (when (and (eq point :draining) (= 0 (mognitio.testing::test-case-ordinal object))
                       (= 2 (mognitio.testing::test-case-stage object)) (not killed))
              (setf killed t) (sb-posix:kill (mognitio.testing::attempt-resources-pid current) sb-posix:sigkill))))
      (same 6 code) (is (search "ERROR abnormal" out)) (is (search "PASS src/app.mgn::App::next" out))
      (is (search "passed=1 failed=0 errors=1" out)) (is (search "stage=body" err)))
    (is killed) (same 2 (length (remove-duplicates pids)))
    (same before (v11-fd-snapshot))))

(deftest v011-shared-initialization
  (let* ((manifest (project-fixture
           '(("dep.mgn" . "namespace App;public let shared:Int={assert true;42};")
             ("a.mgn" . "namespace App;use App\\{shared};@test let a:Function():Unit=function():Unit{assert shared==42;};")
             ("b.mgn" . "namespace App;use App\\{shared};@test let b:Function():Unit=function():Unit{assert shared==42;};"))))
         (plan (v11-plan manifest)) (pids nil) (stages nil)
         (original (fdefinition 'mognitio.testing::accept-event)))
    ;; Each wrapper contains the shared declaration once, independently of runner counts.
    (loop for test across (mognitio.testing::test-plan-cases plan) do
      (let ((program (mognitio.project::project-program (mognitio.testing::test-plan-project plan)
                       (mognitio.testing::test-case-declaration test))))
        (same 1 (count "src/dep.mgn#shared" (program-statements program)
                       :test #'string= :key (lambda (node) (token-text (local-binding-name node)))))))
    (replacing (mognitio.testing::accept-event
      (lambda (reader) (funcall original reader)
        (when (and (= 1 (mognitio.testing::event-reader-stage reader))
                   (= 2 (mognitio.testing::event-reader-sequence reader)))
          (push (mognitio.testing::event-reader-ordinal reader) stages))))
      (multiple-value-bind (out err code)
          (v11-driver manifest (lambda (point object)
            (when (eq point :after-spawn) (push (mognitio.testing::attempt-resources-pid object) pids))))
        (same 0 code) (same "" err) (is (search "passed=2" out))))
    (same '(0 1) (reverse stages)) (same 2 (length (remove-duplicates pids)))))

(deftest v011-output-io-failures
  ;; T11-E21: a broken report sink must not preserve the source success exit.
  (dolist (sink '(:result :summary :payload))
    (let ((original (fdefinition 'mognitio.testing::output-bytes)) (fired nil))
      (replacing (mognitio.testing::output-bytes
        (lambda (output bytes count)
          (let ((text (sb-ext:octets-to-string bytes :end count :external-format :utf-8)))
            (when (and (not fired) (search (ecase sink (:result "PASS ") (:summary "tests:") (:payload "panic:")) text))
              (setf fired t) (mognitio.testing::runner-io "Injected report I/O failure")))
          (funcall original output bytes count)))
        (multiple-value-bind (out err code) (v11-driver (v11-manifest (if (eq sink :payload) "panic{\"payload\"}" "unit")))
          (declare (ignore out)) (same 2 code) (is fired) (is (search "Injected report I/O failure" err)))))))
