(in-package #:mognitio.tests)

(defparameter *v12-imports* "use Std\\Io\\{readTextFile,writeTextFile,readStdin,writeStdout,writeStderr,IoError,IoErrorKind,IoOperation};")
(defun v12-manifest (body &optional (extra ""))
  (project-fixture (list (cons "app.mgn" (format nil "namespace App;~A~Alet main:Function(List<String>):Int=function(args:List<String>):Int{~A};" *v12-imports* extra body)))))
(defun v12-driver (manifest)
  (let ((out (make-string-output-stream)) (err (make-string-output-stream)))
    (let ((code (mognitio.driver:run-cli (list "run" (namestring manifest)) out err)))
      (values (get-output-stream-string out) (get-output-stream-string err) code))))
(defun v12-text (text)
  (mognitio.io::decoded-text (sb-ext:string-to-octets text :external-format :utf-8)))
(defun v12-native (manifest &optional options)
  (let ((mognitio.native.runtime::*test-options* options))
    (let ((path (put-bytes (fresh-path ".elf") (mognitio.backend.native:compile-program
                    (project-checked manifest) (mognitio.target:linux-amd64)))))
      (sb-posix:chmod (namestring path) #o700) path)))

(deftest v012-catalog-and-order-proofs
  (dolist (mutation '(:origin :source :identity :nominal :payload :field-type :standard-edge :missing-reexport))
    (let* ((manifest (project-fixture
                     '(("app.mgn" . "namespace App;use Std\\Io\\{IoError};use App\\{writer};let main:Function(List<String>):Int=function(args:List<String>):Int{discard writer(\"\");0};")
                       ("alias.mgn" . "namespace App;use Std\\Io\\{writeStdout,IoError};public let writer:Function(String):Result<Unit,IoError>=writeStdout;"))))
           (checked (project-checked manifest)) (program (checked-program-program checked))
           (project (mognitio.syntax::program-project program))
           (catalog (mognitio.project::project-standard project))
           (decls (mognitio.project::standard-catalog-declarations catalog))
           (types (program-declarations (mognitio.project::standard-catalog-program catalog)))
           (entry (mognitio.project::project-entry project)))
      (ecase mutation
        (:origin (setf (mognitio.project::module-declaration-origin (first decls)) :user))
        (:source (setf (mognitio.source::source-origin (program-source (mognitio.project::standard-catalog-program catalog))) :user))
        (:identity (setf (mognitio.project::module-declaration-key (third decls)) "forged"))
        (:nominal (setf (data-declaration-kind (aref types 0)) :struct))
        (:payload (setf (named-member-value (aref (data-declaration-members (aref types 0)) 0)) #(:int)))
        (:field-type (setf (named-member-value (aref (data-declaration-members (aref types 2)) 0))
                           (named-member-value (aref (data-declaration-members (aref types 2)) 2))))
        (:standard-edge (push (first decls) (mognitio.project::source-module-dependencies entry)))
        (:missing-reexport (setf (mognitio.project::source-module-dependencies entry) nil)))
      (signals internal-failure (verify-checked-program checked)))))

(deftest v012-core-io-proof
  (dolist (mutation '(:effect :operation :caller :type))
    (let* ((ir (mognitio.ir:lower-program (project-checked (v12-manifest "discard writeStdout(\"x\");0"))))
           (function (find-if (lambda (f) (some (lambda (b) (find :io.call (mognitio.ir:basic-block-instructions b)
                    :key #'mognitio.ir:instruction-op)) (mognitio.ir:ir-function-blocks f))) (mognitio.ir:module-functions ir)))
           (instruction (loop for b in (mognitio.ir:ir-function-blocks function)
                            thereis (find :io.call (mognitio.ir:basic-block-instructions b) :key #'mognitio.ir:instruction-op))))
      (ecase mutation
        (:effect (setf (mognitio.ir::instruction-effects instruction) nil))
        (:operation (setf (mognitio.ir:instruction-value instruction) :unknown))
        (:caller (setf (mognitio.ir::ir-function-capture-types function) '(:string)))
        (:type (setf (mognitio.ir:instruction-type instruction) :int)))
      (signals internal-failure (mognitio.ir:verify-module ir)))))

(deftest v012-machine-resource-proof
  (dolist (mutation '(:callee-save :frame :context :cleanup :roots :failure-bridge))
    (let* ((ir (mognitio.ir:lower-program (project-checked (v12-manifest "0"))))
           (mognitio.native.runtime::*runtime-module* ir) (units nil)
           (original (fdefinition 'mognitio.native.runtime::verify-io-units)))
      (replacing (mognitio.native.runtime::verify-io-units (lambda (value) (setf units value) (funcall original value)))
        (mognitio.machine:lower-module ir))
      (let* ((unit (find-if (lambda (u) (let ((entry (mognitio.object:code-unit-entry u)))
                        (and (consp entry) (consp (second entry)) (eq (car (second entry)) :io.call)))) units))
             (instructions (mognitio.object:code-unit-instructions unit)))
        (labels ((matches (opcode operands) (find-if (lambda (i) (and (eq opcode (mognitio.machine:instruction-opcode i))
                                                          (equal operands (mognitio.machine:instruction-operands i)))) instructions)))
          (ecase mutation
            (:callee-save (setf (mognitio.machine:instruction-operands (matches :imm-rax '(0))) '(0))
             (push (mognitio.machine:make-instruction :opcode :mov-reg :operands '(:r12 :rax))
                   (mognitio.object:code-unit-instructions unit)))
            (:frame (setf (mognitio.object:code-unit-instructions unit) (remove (fourth instructions) instructions :test #'eq)))
            (:context (setf (mognitio.machine:instruction-operands (matches :store-word '(:r15 272 :rax))) '(:r15 280 :rax)))
            (:cleanup (setf (mognitio.object:code-unit-instructions unit)
                            (remove (matches :call '((:runtime :io.cleanup))) instructions :test #'eq)))
            (:roots (setf (mognitio.machine:instruction-operands (matches :imm-rax '(4))) '(3)))
            (:failure-bridge
             (let ((runtime (find :runtime units :key #'mognitio.object:code-unit-owner)))
               (setf (mognitio.object:code-unit-instructions runtime)
                 (remove-if (lambda (i) (and (eq (mognitio.machine:instruction-opcode i) :call)
                                     (equal (mognitio.machine:instruction-operands i) '((:runtime :io.cleanup-all)))))
                            (mognitio.object:code-unit-instructions runtime))))))
          (signals internal-failure (mognitio.native.runtime::verify-io-units units)))))))

(deftest v012-context-encoded-metadata
  (dolist (test-p '(nil t))
    (let* ((manifest (v12-manifest "0" "@test let check:Function():Unit=function():Unit{unit};"))
           (plan (when test-p (v11-plan manifest)))
           (mognitio.ir::*test-ordinal* (when test-p 0))
           (checked (if test-p
                        (check-program (mognitio.project::project-program
                          (mognitio.testing::test-plan-project plan)
                          (mognitio.testing::test-case-declaration (aref (mognitio.testing::test-plan-cases plan) 0))))
                        (project-checked manifest)))
           (ir (mognitio.ir:lower-program checked)))
      (multiple-value-bind (bytes symbols) (mognitio.amd64:encode (mognitio.machine:lower-module ir))
        (is (mognitio.backend.native::verify-native-metadata ir bytes symbols))
        (let ((at (mognitio.object:image-symbol-offset (gethash '(:runtime-context 6) symbols))))
          (dolist (offset '(0 16 48 96))
            (let ((bad (copy-seq bytes)))
              (incf (aref bad (+ at offset)))
              (signals internal-failure (mognitio.backend.native::verify-native-metadata ir bad symbols)))))))))

(deftest v012-utf8-state-boundaries
  (dolist (bytes '(#(0) #(239 187 191) #(194 128) #(223 191) #(224 160 128) #(237 159 191)
                   #(238 128 128) #(239 191 191) #(240 144 128 128) #(244 143 191 191)))
    (loop for split from 0 to (length bytes) do
      (let ((state (mognitio.runtime::make-utf8-state)))
        (is (mognitio.runtime::utf8-feed state (subseq bytes 0 split)))
        (is (mognitio.runtime::utf8-feed state (subseq bytes split)))
        (same 0 (mognitio.runtime::utf8-state-pending state))
        (same 1 (mognitio.runtime::utf8-state-count state)))))
  (let ((state (mognitio.runtime::make-utf8-state :count mognitio.integer:+maximum+)))
    (signals mognitio.runtime:program-runtime-failure (mognitio.runtime::utf8-feed state #(65)))))
