(in-package #:mognitio.tests)

(defun v12-action (number)
  (let ((state (mognitio.io::make-signal-state :number number
                  :original (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)
                  :replacement (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0))))
    (mognitio.io::signal-action state :read) state))
(defun v12-signals ()
  (mapcar (lambda (n) (mognitio.io::signal-state-original (v12-action n))) '(13 25)))

(deftest v012-host-signal-restoration
  (let ((saved (mapcar #'v12-action '(13 25))))
    (unwind-protect
         (progn
           ;; Nontrivial handler/mask/flags ensure this is not just SIG_IGN -> SIG_IGN.
           (dolist (state saved)
             (let ((bytes (mognitio.io::signal-state-replacement state)))
               (setf (aref bytes 0) 1 (aref bytes 25) 2 (aref bytes 11) 16)
               (mognitio.io::signal-action state :install)))
           (let ((before (v12-signals)))
             (dolist (mode '(:normal :nested :error :storage :escape :partial))
               (let ((events nil) (mognitio.io::*signal-secondary* nil))
                 (let ((mognitio.io::*signal-guard-hook*
                         (lambda (stage number)
                           (push (list stage number) events)
                           (when (and (eq mode :partial) (eq stage :install) (= number 25))
                             (internal-error "Injected partial signal setup")))))
                   (flet ((body ()
                            (ecase mode
                              (:normal (values 7 nil))
                              (:nested (mognitio.io::call-with-io-signals (lambda () (values 7 nil))))
                              (:error (error "Injected body failure"))
                              (:storage (error 'storage-condition))
                              (:escape (throw 'v12-exit 7))
                              (:partial (error "Body must not start")))))
                     (case mode
                       ((:normal :nested) (same 7 (mognitio.io::call-with-io-signals #'body)))
                       (:escape (same 7 (catch 'v12-exit (mognitio.io::call-with-io-signals #'body))))
                       (:storage (signals storage-condition (mognitio.io::call-with-io-signals #'body)))
                       (t (signals error (mognitio.io::call-with-io-signals #'body))))))
                 (same (if (eq mode :partial) 1 2) (count :restore events :key #'car))
                 (same before (v12-signals))))
             (dolist (primary '(nil t))
               (let ((original (fdefinition 'mognitio.io::signal-action)) (mognitio.io::*signal-secondary* nil))
                 (replacing (mognitio.io::signal-action
                              (lambda (state mode) (funcall original state mode)
                                (when (and (eq mode :restore) (= (mognitio.io::signal-state-number state) 25))
                                  (internal-error "Injected restoration report failure"))))
                   (if primary
                       (same 4 (mognitio.io::call-with-io-signals (lambda () (values 4 t))))
                       (signals internal-failure (mognitio.io::call-with-io-signals (lambda () (values 7 nil))))))
                 (same 1 (length mognitio.io::*signal-secondary*)))
               (same before (v12-signals)))))
      (dolist (state saved) (mognitio.io::signal-action state :restore)))))

(deftest v012-host-guard-command-boundaries
  (let ((mognitio.io::*signal-guard-hook* (lambda (mode number) (declare (ignore number))
                                         (when (eq mode :install) (internal-error "Guard setup")))))
    (multiple-value-bind (out err code) (v11-driver (v11-manifest) (lambda (&rest args) (declare (ignore args)) (error "Runner started")))
      (same 3 code) (same "" out) (is (not (search "tests:" err)))))
  (dolist (body '("7" "panic{\"primary\"}"))
    (let ((original (fdefinition 'mognitio.io::signal-action)))
      (replacing (mognitio.io::signal-action
                   (lambda (state mode) (funcall original state mode)
                     (when (eq mode :restore) (internal-error "Guard restore"))))
        (multiple-value-bind (out err code) (v12-driver (v12-manifest body))
          (same "" out) (same (if (equal body "7") 3 4) code)
          (is (search (if (equal body "7") "guard failure" "panic: primary") err))))))
  (let ((original (fdefinition 'mognitio.io::signal-action)))
    (replacing (mognitio.io::signal-action
                 (lambda (state mode) (funcall original state mode)
                   (when (eq mode :restore) (internal-error "Guard restore after commit"))))
      (multiple-value-bind (out err code) (v11-driver (v11-manifest "unit" 1))
        (same 3 code) (is (search "total=1 passed=1 failed=0 errors=0 aborted=0 not_run=0" out))
        (is (search "guard failure" err))))))

(deftest v012-host-owned-cleanup-and-precedence
  (dolist (mode '(:ok :read :decode :opened :storage :close :body-close :runtime-close))
    (let* ((path (put-bytes (fresh-path ".txt") (if (eq mode :decode) #(255) #(65 66))))
           (before (v11-fd-snapshot)) (closed 0) (mognitio.io::*operation-secondary* nil)
           (mognitio.io::*operation-hook*
             (lambda (stage &rest args)
               (declare (ignore args))
               (when (eq stage :close)
                 (incf closed)
                 (when (member mode '(:close :body-close :runtime-close))
                   (error 'sb-posix:syscall-error :name "close" :errno sb-posix:enospc)))
               (when (and (eq stage :opened) (member mode '(:opened :runtime-close)))
                 (mognitio.runtime:runtime-error :allocation-failed))
               (when (eq stage :read)
                 (case mode
                   ((:read :body-close) (error 'sb-posix:syscall-error :name "read" :errno sb-posix:efbig))
                   (:storage (error 'storage-condition)))))))
      (handler-case
          (let ((data (mognitio.io::file-operation :read-file (v12-text (namestring path)) nil)))
            (same :ok mode) (same #(65 66) data))
        (mognitio.io::io-failure (condition) (same :decode mode) (same 1 (mognitio.io::io-failure-kind condition)))
        (sb-posix:syscall-error (condition)
          (is (member mode '(:read :close :body-close)))
          (same (if (eq mode :close) sb-posix:enospc sb-posix:efbig) (sb-posix:syscall-errno condition)))
        (mognitio.runtime:program-runtime-failure () (is (member mode '(:opened :runtime-close))))
        (storage-condition () (same :storage mode)))
      (same 1 closed) (same before (v11-fd-snapshot))
      (same (if (member mode '(:body-close :runtime-close)) 1 0) (length mognitio.io::*operation-secondary*)))))

(deftest v012-host-short-transfer-and-interrupt
  (let* ((path (put-bytes (fresh-path ".txt") #(65 66 67))) (text (v12-text (namestring path)))
         (original (fdefinition 'mognitio.io::read-chunk)) (calls 0) (before (v11-fd-snapshot)))
    (replacing (mognitio.io::read-chunk
                 (lambda (fd bytes)
                   (incf calls)
                   (if (= calls 1) (error 'sb-posix:syscall-error :name "read" :errno sb-posix:eintr)
                       (let* ((one (make-array 1 :element-type '(unsigned-byte 8))) (n (funcall original fd one)))
                         (when (plusp n) (setf (aref bytes 0) (aref one 0))) n))))
      (same #(65 66 67) (mognitio.io::file-operation :read-file text nil)) (same 5 calls))
    (dolist (operation '(sb-posix:stat sb-posix:open sb-posix:fstat sb-posix:ftruncate))
      (let ((saved (fdefinition operation)) (count 0))
        (unwind-protect
             (progn (setf (fdefinition operation) (lambda (&rest args)
                      (if (= (incf count) 1) (error 'sb-posix:syscall-error :name "injected" :errno sb-posix:eintr)
                          (apply saved args))))
                    (mognitio.io::file-operation :write-file text (v12-text "ABC")) (same 2 count))
          (setf (fdefinition operation) saved))))
    (dolist (mode '(:short :eintr :again :zero))
      (let ((saved (fdefinition 'mognitio.runtime::write-chunk)) (count 0))
        (replacing (mognitio.runtime::write-chunk
                     (lambda (fd bytes offset size)
                       (incf count)
                       (cond ((and (= count 1) (eq mode :eintr)) (- sb-posix:eintr))
                             ((eq mode :again) (- sb-posix:eagain)) ((eq mode :zero) 0)
                             (t (funcall saved fd bytes offset (min 1 size))))))
          (if (member mode '(:again :zero))
              (handler-case (progn (mognitio.io::file-operation :write-file text (v12-text "ABC")) (error "Missing failure"))
                (mognitio.io::io-failure (condition) (same 7 (mognitio.io::io-failure-kind condition))))
              (progn (mognitio.io::file-operation :write-file text (v12-text "ABC"))
                     (same #(65 66 67) (read-bytes path)) (same (if (eq mode :eintr) 4 3) count))))))
    (same before (v11-fd-snapshot))))

(deftest v012-host-result-allocation-cleanup
  (dolist (invalid '(nil t))
    (dolist (ordinal (if invalid '(1 2 3 4) '(1 2)))
      (let* ((path (put-bytes (fresh-path ".txt") (if invalid #(255) #(65))))
             (manifest (v12-manifest (format nil "discard readTextFile(~S);0" (namestring path))))
             (count 0) (closed 0) (fired nil) (before (v11-fd-snapshot))
             (mognitio.io::*operation-hook* (lambda (stage &rest args) (declare (ignore args))
                                            (when (eq stage :close) (incf closed))))
             (mognitio.runtime::*allocation-hook* (lambda (kind)
               (when (and (member kind '(:data :string)) (= (incf count) ordinal))
                 (same 1 closed) (setf fired t) (error 'storage-condition)))))
        (multiple-value-bind (out err code) (v12-driver manifest)
          (same 4 code) (same "" out) (is fired) (is (search "allocation failure" err)))
        (same 1 closed) (same before (v11-fd-snapshot))))))

(deftest v012-private-protocol-and-extra-pipe
  (dolist (version '(1 2 3 5))
    (let ((record (v11-record 1 0 0 0 0)))
      (setf (aref record 4) version)
      (signals internal-failure (v11-feed (mognitio.testing::make-event-reader :ordinal 0 :site-count 1) record))))
  (loop for ordinal from 1 to 5 do
    (let ((count 0) (before (v11-fd-snapshot)) (original (fdefinition 'mognitio.testing::raw-pipe)))
      (replacing (mognitio.testing::raw-pipe (lambda (&rest args)
        (if (= (incf count) ordinal) -1 (apply original args))))
        (multiple-value-bind (out err code) (v11-driver (v11-manifest "unit" 1))
          (same 2 code) (same "" out) (is (not (search "tests:" err)))))
      (same before (v11-fd-snapshot)))))

(deftest v012-raw-invocation-framing
  (dolist (bytes '(#() #(0) #(120 0) #(49 0) #(49 0 65) #(48 0 65) #(49 0 65 0 66)))
    (let ((path (put-bytes (fresh-path ".argv") bytes)))
      (with-open-file (stream path :element-type '(unsigned-byte 8))
        (signals usage-or-io-failure (mognitio.driver::read-raw-invocation stream)))))
  (let ((path (put-bytes (fresh-path ".argv") #(50 0 0 255 0))))
    (with-open-file (stream path :element-type '(unsigned-byte 8))
      (same '(#() #(255)) (mognitio.driver::raw-invocation-arguments (mognitio.driver::read-raw-invocation stream))))))
