(in-package #:mognitio.tests)

(deftest v013-catalog-negative-proofs
  (dolist (mutation '(:entry-field :kind-payload :entry-nominal :result :operation :capture))
    (let* ((checked (project-checked (v13-manifest "discard readDirectory(\".\");0")))
           (project (mognitio.syntax::program-project (checked-program-program checked)))
           (catalog (mognitio.project::project-standard project))
           (program (mognitio.project::standard-catalog-program catalog))
           (types (program-declarations program)) (bindings (program-statements program))
           (function (local-binding-initializer (aref bindings 6))) (body (function-expression-body function)))
      (same 6 (length types)) (same 8 (length bindings))
      (ecase mutation
        (:entry-field (setf (named-member-value (aref (data-declaration-members (aref types 4)) 1))
                           (named-member-value (aref (data-declaration-members (aref types 4)) 0))))
        (:kind-payload (setf (named-member-value (aref (data-declaration-members (aref types 3)) 0)) #(:int)))
        (:entry-nominal (setf (data-declaration-kind (aref types 4)) :enum))
        (:result (setf (mognitio.syntax::io-expression-result-type body)
                       (function-expression-result-type (local-binding-initializer (aref bindings 5)))))
        (:operation (setf (mognitio.syntax::io-expression-operation body) :read-file))
        (:capture (setf (mognitio.syntax::io-expression-arguments body) #())))
      (signals internal-failure (verify-checked-program checked)))))

(deftest v013-core-nominal-proofs
  (dolist (mutation '(:entry-name :kind-name :field :effect))
    (let* ((ir (mognitio.ir:lower-program (project-checked (v13-manifest "discard readDirectory(\".\");0"))))
           (context (mognitio.ir:module-values ir))
           (instruction (loop for f in (mognitio.ir:module-functions ir) thereis
                          (loop for b in (mognitio.ir:ir-function-blocks f) thereis
                            (find :read-directory (mognitio.ir:basic-block-instructions b) :key #'mognitio.ir:instruction-value))))
           (args (mognitio.semantic::canonical-result-arguments context (mognitio.ir:instruction-type instruction)))
           (entry (context-type context (second (first args))))
           (kind (context-type context (cdr (second (type-info-fields entry))))))
      (ecase mutation
        (:entry-name (setf (type-info-name entry) "user#DirectoryEntry"))
        (:kind-name (setf (type-info-name kind) "user#DirectoryEntryKind"))
        (:field (setf (type-info-fields entry) '(("name" . :string) ("kind" . :int))))
        (:effect (setf (mognitio.ir::instruction-effects instruction) nil)))
      (signals internal-failure (mognitio.ir:verify-module ir)))))

(deftest v013-machine-negative-proofs
  (dolist (mutation '(:roots :callee-save :frame :cleanup :link :terminal-status :terminal-call))
    (let* ((ir (mognitio.ir:lower-program (project-checked (v13-manifest "0"))))
           (mognitio.native.runtime::*runtime-module* ir) (units nil)
           (original (fdefinition 'mognitio.native.runtime::verify-io-units)))
      (replacing (mognitio.native.runtime::verify-io-units (lambda (value) (setf units value) (funcall original value)))
        (mognitio.machine:lower-module ir))
      (let* ((unit (if (member mutation '(:terminal-status :terminal-call))
                       (find '(:runtime :directory.internal) units :test #'equal :key #'mognitio.object:code-unit-entry)
                       (find-if (lambda (u) (let ((entry (mognitio.object:code-unit-entry u)))
                                             (and (consp entry) (consp (second entry)) (eq (third (second entry)) :read-directory)))) units)))
             (instructions (mognitio.object:code-unit-instructions unit)))
        (flet ((matches (opcode operands)
                 (or (find-if (lambda (i) (and (eq opcode (mognitio.machine:instruction-opcode i))
                                             (equal operands (mognitio.machine:instruction-operands i)))) instructions)
                     (error "Missing independent mutation target"))))
          (ecase mutation
            (:roots (setf (mognitio.machine:instruction-operands (matches :imm-rax '(8))) '(7)))
            (:callee-save (setf (mognitio.machine:instruction-opcode (matches :imm-rax '(8))) :imm-reg
                               (mognitio.machine:instruction-operands (matches :imm-reg '(8))) '(:r12 8)))
            (:frame (setf (mognitio.machine:instruction-operands (matches :store-frame '(-96 :rax))) '(-900 :rax)))
            (:cleanup (setf (mognitio.object:code-unit-instructions unit)
                            (remove (matches :call '((:runtime :directory.cleanup))) instructions :test #'eq)))
            (:link (setf (mognitio.machine:instruction-operands (matches :lea-base '(:rax :rbp -368))) '(:rax :rbp -360)))
            (:terminal-status (setf (mognitio.machine:instruction-operands (matches :mov-edi '(3))) '(124)))
            (:terminal-call (setf (mognitio.machine:instruction-operands (matches :call '((:runtime :io.cleanup-all)))) '((:runtime :allocate)))))
          (signals internal-failure (mognitio.native.runtime::verify-io-units units)))))))

(deftest v013-encoded-protocol-negative-proof
  (let* ((plan (v11-plan (v11-manifest "unit" 1)))
         (mognitio.ir::*test-ordinal* 0)
         (checked (check-program (mognitio.project::project-program (mognitio.testing::test-plan-project plan)
                                   (mognitio.testing::test-case-declaration (aref (mognitio.testing::test-plan-cases plan) 0)))))
         (ir (mognitio.ir:lower-program checked)))
    (multiple-value-bind (bytes symbols) (mognitio.amd64:encode (mognitio.machine:lower-module ir))
      (is (mognitio.backend.native::verify-native-metadata ir bytes symbols))
      (let* ((start (mognitio.object:image-symbol-offset (gethash '(:helper :test.bootstrap) symbols)))
             (header (search #(72 184 77 71 78 84 4 0 1 0) bytes :start2 start)))
        (is header)
        (dolist (version '(1 2 3 5))
          (let ((bad (copy-seq bytes)))
            (setf (aref bad (+ header 6)) version)
            (signals internal-failure (mognitio.backend.native::verify-native-metadata ir bad symbols))))))))
