(in-package #:mognitio.tests)

(defun v13-assert-map-cleanup (trace)
  ;; Observe OS ownership independently of compiler frame slots. The first map
  ;; is the managed heap; every subsequent successful map is directory scratch.
  (let ((first t) (live nil) (report (search "write(2," trace)))
    (is report)
    (dolist (line (uiop:split-string (subseq trace 0 report) :separator '(#\Newline)))
      (cond
        ((uiop:string-prefix-p "mmap(" line)
         (let ((result (search " = 0x" line)))
           (cond (first (is result) (setf first nil))
                 (result
                  (let* ((commas (uiop:split-string line :separator '(#\,)))
                         (address (string-trim '(#\Space) (subseq line (+ result 3))))
                         (size (parse-integer (second commas) :junk-allowed t)))
                    (push (cons address size) live))))))
        ((uiop:string-prefix-p "munmap(" line)
         (let* ((comma (position #\, line))
                (mapping (cons (subseq line 7 comma) (parse-integer line :start (1+ comma) :junk-allowed t))))
           (is (search " = 0" line))
           (is (member mapping live :test #'equal))
           (setf live (remove mapping live :test #'equal :count 1))))))
    (same nil live)
    (when (search "openat(" trace :end2 report)
      (same 1 (count-if (lambda (line) (search "close(3)" line))
                        (uiop:split-string (subseq trace 0 report) :separator '(#\Newline)))))))

(deftest v013-review-map-syscall-errors
  (let ((root (v13-directory)))
    (loop for n below 100 do
      (put-text (pathname (format nil "~A/entry-~3,'0D-~A" root n (make-string 90 :initial-element #\x))) "x"))
    (let ((image (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root)))))
      (multiple-value-bind (out err code trace) (v13-trace image)
        (same "" out) (same "" err) (same 0 code)
        (let ((maps (count-if (lambda (line) (uiop:string-prefix-p "mmap(" line))
                             (uiop:split-string trace :separator '(#\Newline)))))
          (is (> maps 7))
          ;; Fault every directory acquisition, including both grow/copy paths.
          (loop for ordinal from 2 to maps do
            (dolist (errno '("ENOMEM" "EINVAL"))
              (multiple-value-bind (out err code trace)
                  (v13-trace image (format nil "mmap:error=~A:when=~D" errno ordinal))
                (same "" out) (same (if (equal errno "EINVAL") 3 4) code)
                (is (search (if (equal errno "EINVAL") "internal error" "allocation failure") err))
                (is (search "(INJECTED)" trace)) (v13-assert-map-cleanup trace)))))))
    (let* ((path (concatenate 'string root "/new"))
           (image (v12-native (v13-manifest (format nil "discard createDirectory(~S);0" path)))))
      (dolist (errno '("ENOMEM" "EINVAL"))
        (multiple-value-bind (out err code trace) (v13-trace image (format nil "mmap:error=~A:when=2" errno))
          (same "" out) (same (if (equal errno "EINVAL") 3 4) code)
          (is (search (if (equal errno "EINVAL") "internal error" "allocation failure") err))
          (is (search "(INJECTED)" trace)) (v13-assert-map-cleanup trace)
          (is (not (probe-file path))))))
    ;; The older file helper retains its allocation-failure boundary.
    (let ((file (concatenate 'string root "/text")))
      (put-text (pathname file) "content")
      (multiple-value-bind (out err code trace)
          (v13-trace (v12-native (v13-manifest (format nil "discard readTextFile(~S);0" file))) "mmap:error=EINVAL:when=2")
        (same "" out) (same 4 code) (is (search "allocation failure" err)) (is (search "(INJECTED)" trace))))))

(deftest v013-review-map-runner-errors
  (dolist (stage '(1 2))
    (dolist (status '(-22 -12))
      (let* ((root (v13-directory)) (marker (namestring (fresh-path ".marker")))
             (before (v11-fd-snapshot)) (attempts nil) (paths nil)
             (mognitio.native.runtime::*test-options* (list :directory-faults (list (list :map 2 status)))))
        (multiple-value-bind (out err code)
            (v11-driver (v13-internal-suite root marker stage)
              (lambda (point object)
                (when (eq point :before-spawn) (push object attempts))
                (when (eq point :image-created) (push (mognitio.testing::test-case-path object) paths))))
          (same (if (= status -22) 3 4) code)
          (cond ((= status -22)
                 (is (search "total=3 passed=1 failed=0 errors=0 aborted=1 not_run=1" out))
                 (is (search (if (= stage 1) "stage=initialization" "stage=body") err))
                 (is (search "Native child detected an internal runtime inconsistency" err))
                 (is (not (probe-file marker))) (same 2 (length attempts))
                 (same (* 123 256) (mognitio.testing::attempt-resources-status (first attempts))))
                (t (is (search "total=3 passed=2 failed=0 errors=1 aborted=0 not_run=0" out))
                   (is (search "ERROR allocation-failed" out)) (is (search "allocation failure" err))
                   (is (probe-file marker)) (same 3 (length attempts)))))
        (mapc #'v11-assert-released attempts) (same before (v11-fd-snapshot))
        (dolist (path paths) (is (not (probe-file path))))))))

(defun v13-review-module (test-p)
  (if test-p
      (let* ((plan (v11-plan (project-fixture (list (cons "app.mgn"
                       (format nil "namespace App;~A~A@test let check:Function():Unit=function():Unit{unit};" *v12-imports* *v13-imports*))))))
             (mognitio.ir::*test-ordinal* 0))
        (mognitio.ir:lower-program
          (check-program (mognitio.project::project-program (mognitio.testing::test-plan-project plan)
                           (mognitio.testing::test-case-declaration (aref (mognitio.testing::test-plan-cases plan) 0))))))
      (mognitio.ir:lower-program (project-checked (v13-manifest "0")))))

(defun v13-review-instructions (forms)
  (mapcar (lambda (form) (mognitio.machine::make-instruction :opcode (first form) :operands (rest form))) forms))

(deftest v013-review-latch-flow-proofs
  (dolist (test-p '(nil t))
    (let* ((ir (v13-review-module test-p)) (mognitio.native.runtime::*runtime-module* ir)
           (units nil) (original (fdefinition 'mognitio.native.runtime::verify-io-units)))
      (replacing (mognitio.native.runtime::verify-io-units (lambda (value) (setf units value) (funcall original value)))
        (mognitio.machine:lower-module ir))
      (dolist (operation '(:join-path :read-directory :create-directory))
        (let* ((unit (find-if (lambda (u) (let ((entry (mognitio.object:code-unit-entry u)))
                           (and (consp entry) (consp (second entry)) (eq (third (second entry)) operation)))) units))
               (saved (mognitio.object:code-unit-instructions unit))
               (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i) (mognitio.machine:instruction-operands i))) saved))
               (branch (position '(:jnz (:runtime :directory.internal)) forms :test #'equal))
               (load (position '(:load-frame :rax -104) forms :test #'equal :from-end t)))
          (is branch) (is load)
          (dolist (mutation '(:delete :invert :clear-register :clear-latch :bypass :equivalent))
            (let ((bad (copy-list forms)))
              (ecase mutation
                (:delete (setf bad (append (subseq bad 0 branch) (nthcdr (1+ branch) bad))))
                (:invert (setf (nth branch bad) '(:jz (:runtime :directory.internal))))
                (:clear-register (setf (nth load bad) '(:imm-rax 0)))
                (:clear-latch (setf bad (append (subseq bad 0 load) '((:imm-rax 0) (:store-frame -104 :rax)) (nthcdr load bad))))
                (:bypass (setf bad (append (subseq bad 0 load) '((:jmp :review-bypass))
                                          (subseq bad load (1+ branch)) '((:label :review-bypass)) (nthcdr (1+ branch) bad))))
                (:equivalent (setf bad (append (subseq bad 0 branch)
                                   '((:jz :review-clear) (:jmp (:runtime :directory.internal)) (:label :review-clear)) (nthcdr (1+ branch) bad)))))
              (unwind-protect
                  (progn (setf (mognitio.object:code-unit-instructions unit) (v13-review-instructions bad))
                         (if (eq mutation :equivalent)
                             (progn (mognitio.native.runtime::verify-io-units units) (is t))
                             (signals internal-failure (mognitio.native.runtime::verify-io-units units))))
                (setf (mognitio.object:code-unit-instructions unit) saved))))))
      (let* ((unit (find '(:runtime :directory.map) units :test #'equal :key #'mognitio.object:code-unit-entry))
             (saved (mognitio.object:code-unit-instructions unit)))
        (unwind-protect
            (progn (setf (mognitio.object:code-unit-instructions unit)
                         (append (butlast saved) (v13-review-instructions '((:imm-rax 0) (:ret)))))
                   (signals internal-failure (mognitio.native.runtime::verify-io-units units)))
          (setf (mognitio.object:code-unit-instructions unit) saved)))
      (let* ((unit (find-if (lambda (u) (let ((entry (mognitio.object:code-unit-entry u)))
                        (and (consp entry) (consp (second entry)) (eq (third (second entry)) :read-directory)))) units))
             (saved (mognitio.object:code-unit-instructions unit))
             (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i) (mognitio.machine:instruction-operands i))) saved))
             (call (position '(:call (:runtime :directory.map)) forms :test #'equal)))
        (is call)
        (dolist (mutation '(:adapter :errno))
          (let ((bad (copy-list forms)))
            (ecase mutation
              (:adapter (setf (nth call bad) '(:call (:runtime :io.map))))
              (:errno (let ((compare (position '(:cmp-imm :rax -22) forms :start call :test #'equal)))
                        (is compare) (setf (nth compare bad) '(:cmp-imm :rax -12)))))
            (unwind-protect
                (progn (setf (mognitio.object:code-unit-instructions unit) (v13-review-instructions bad))
                       (signals internal-failure (mognitio.native.runtime::verify-io-units units)))
              (setf (mognitio.object:code-unit-instructions unit) saved))))))))
