(in-package #:mognitio.tests)

(defun v13-child-script (mode)
  (format nil "#!/usr/bin/python3~%import os,struct,signal~%sequence=0~%def event(tag,stage=0,kind=0,version=3):~% global sequence~% os.write(3,struct.pack('<IHHQQIIQ',0x544e474d,version,tag,0,sequence,stage,kind,2**64-1));sequence+=1~%~A~%"
    (case mode
      (:before-ready "os._exit(123)")
      (:after-ready (format nil "event(1)~%os._exit(123)"))
      (:old-version (format nil "event(1,version=2)~%os.read(4,1)~%os._exit(0)"))
      (otherwise
       (format nil "event(1)~%os.read(4,1)~%event(2,1)~%event(2,2)~%~A~%"
         (ecase mode
           (:partial (format nil "os.write(3,b'partial')~%os._exit(123)"))
           (:terminal (format nil "event(3,2)~%os._exit(123)"))
           (:plain-three "os._exit(3)") (:transport "os._exit(124)")
           (:signal "os.kill(os.getpid(),signal.SIGKILL)")
           (:invalid-kind (format nil "event(3,2,99)~%os._exit(4)"))))))))

(deftest v013-runner-status-transport
  (dolist (mode '(:before-ready :after-ready :old-version :partial :terminal :plain-three :transport :signal :invalid-kind))
    (let ((before (v11-fd-snapshot)) (attempts nil) (first t) (paths nil) (cases nil))
      (multiple-value-bind (out err code)
          (v11-driver (v11-manifest "unit" 2)
            (lambda (point object)
              (when (eq point :image-prepared)
                (push (mognitio.testing::test-case-path object) paths)
                (when (zerop (mognitio.testing::test-case-ordinal object))
                  (put-text (pathname (mognitio.testing::test-case-path object)) (v13-child-script mode))))
              (when (eq point :suite-prepared) (setf cases (mognitio.testing::preparation-session-cases object)))
              (when (eq point :before-spawn) (push object attempts))
              (when (and (eq point :after-spawn) first)
                (setf first nil)
                (when (member mode '(:before-ready :after-ready))
                  (loop repeat 1000 until (mognitio.testing::collect-wait object) do (sleep 0.002))
                  (same :reaped (mognitio.testing::attempt-resources-process-state object))))))
        (same (case mode ((:plain-three :signal) 6) (:transport 2) (otherwise 3)) code)
        (cond
          ((member mode '(:before-ready :after-ready :old-version))
           (same "" out) (is (not (search "tests:" err)))
           (same nil (mognitio.testing::attempt-resources-execution-delegated (first attempts))))
          ((member mode '(:plain-three :signal)) (is (search "passed=1 failed=0 errors=1 aborted=0 not_run=0" out)))
          (t (is (search "passed=0 failed=0 errors=0 aborted=1 not_run=1" out))))
        (when (member mode '(:before-ready :after-ready))
          (is (search "stage=unknown" err)) (is (search "App::check0" err))
          (same '(:not-run :not-run) (map 'list #'mognitio.testing::test-case-state cases))))
      (mapc #'v11-assert-released attempts) (same before (v11-fd-snapshot))
      (dolist (path paths) (is (not (probe-file path)))))))

(deftest v013-runner-primary-and-runtime
  (let* ((root (v13-directory)) (marker (namestring (fresh-path ".marker"))))
    (put-text (pathname (concatenate 'string root "/entry")) "x")
    (dolist (prior '(nil t))
      (let ((mognitio.native.runtime::*test-options* '(:directory-faults ((:scan 1 -9))))
            (before (v11-fd-snapshot)) (attempts nil) (count 0))
        (multiple-value-bind (out err code)
            (v11-driver (v13-internal-suite root marker 2)
              (lambda (point object)
                (when (eq point :before-spawn) (push object attempts))
                (when (and prior (eq point :after-reap) (= (incf count) 2))
                  (mognitio.testing::runner-io "Prior report I/O failure"))
                (when (and (not prior) (eq point :before-summary))
                  (mognitio.testing::runner-io "Secondary report I/O failure"))))
          (same (if prior 2 3) code) (is (search "aborted=1 not_run=1" out))
          (is (search (if prior "Prior report I/O failure" "Native child detected") err)))
        (mapc #'v11-assert-released attempts) (same before (v11-fd-snapshot))))
    (let ((mognitio.native.runtime::*test-options* '(:fail-allocation 2 :directory-cleanup-fault -22)))
      (multiple-value-bind (out err code)
          (v11-driver (project-fixture (list (cons "app.mgn" (format nil "namespace App;~A~A@test let check:Function():Unit=function():Unit{discard readDirectory(~S);unit};" *v12-imports* *v13-imports* root)))))
        (same 4 code) (is (search "ERROR allocation-failed" out)) (is (search "allocation failure" err))
        (is (not (search "Native child detected" err)))))))

(deftest v013-host-internal-driver-and-version-pair
  (let ((root (v13-directory)))
    (dolist (phase '(:scan :close))
      (let ((before (v11-fd-snapshot))
            (mognitio.io::*directory-fault-hook* (lambda (at) (when (eq phase at) -9))))
        (multiple-value-bind (out err code) (v12-driver (v13-manifest (format nil "discard readDirectory(~S);0" root)))
          (same "" out) (same 3 code) (is (search "internal" err)))
        (same before (v11-fd-snapshot)))))
  ;; An independent v2 reader boundary rejects the real v3 child's first ready
  ;; record. The opposite direction is the v2 child fixture above, not a claim
  ;; that a second installed compiler build was used.
  (let ((original (fdefinition 'mognitio.testing::accept-event)) (attempt nil) (seen nil))
    (replacing (mognitio.testing::accept-event
      (lambda (reader)
        (let ((bytes (mognitio.testing::event-reader-buffer reader)))
          (setf seen (aref bytes 4))
          (unless (and (= (aref bytes 4) 2) (= (aref bytes 5) 0))
            (internal-error "Independent v2 reader rejects this ready version")))
        (funcall original reader)))
      (multiple-value-bind (out err code)
          (v11-driver (v11-manifest "unit" 1) (lambda (point object) (when (eq point :before-spawn) (setf attempt object))))
        (same 3 code) (same "" out) (same 3 seen) (is (search "v2 reader rejects" err))
        (same nil (mognitio.testing::attempt-resources-execution-delegated attempt))))
    (v11-assert-released attempt)))
