(in-package #:mognitio.tests)

(defun v13-raw-records (names &optional (dtype 0))
  ;; Independent getdents64 fixture encoder. Kind always comes from real fstatat.
  (let ((result (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (dolist (name names)
      (let* ((bytes (sb-ext:string-to-octets name :external-format :utf-8))
             (size (* 8 (ceiling (+ 20 (length bytes)) 8)))
             (record (make-array size :element-type '(unsigned-byte 8) :initial-element 0)))
        (setf (aref record 16) (logand size 255) (aref record 17) (ash size -8) (aref record 18) dtype)
        (replace record bytes :start1 19)
        (loop for byte across record do (vector-push-extend byte result))))
    (coerce result '(simple-array (unsigned-byte 8) (*)))))

(deftest v013-record-boundaries
  (let ((root (v13-directory)) (original (fdefinition 'mognitio.io::directory-getdents)))
    (dolist (mutation '(:count :header :reclen :alignment :end :empty :slash :nul))
      (let ((before (v11-fd-snapshot)))
        (replacing (mognitio.io::directory-getdents
          (lambda (fd buffer count)
            (let ((actual (funcall original fd buffer count)))
              (when (plusp actual)
                (ecase mutation
                  (:count (setf actual 65537)) (:header (setf actual 19))
                  (:reclen (setf (sb-sys:sap-ref-16 buffer 16) 0))
                  (:alignment (setf (sb-sys:sap-ref-16 buffer 16) 25))
                  (:end (setf (sb-sys:sap-ref-16 buffer 16) 65535))
                  (:empty (setf (sb-sys:sap-ref-8 buffer 19) 0))
                  (:slash (setf (sb-sys:sap-ref-8 buffer 19) 47))
                  (:nul (loop for i from 19 below 24 do (setf (sb-sys:sap-ref-8 buffer i) 120))))) actual)))
          (signals internal-failure (mognitio.io::scan-directory (v12-text root))))
        (same before (v11-fd-snapshot)))
      (multiple-value-bind (out err code trace)
          (v13-trace (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root))
                                (list :directory-scan-mutation mutation)))
        (same "" out) (same 3 code) (is (search "internal error" err))
        (is (search "close(3)" trace)) (is (search "munmap(" trace))))
    ;; Decode must precede metadata, and a cleanup error cannot replace it.
    (same 0 (v13-native-code (v13-error-body (format nil "readDirectory(~S)" root) "List<DirectoryEntry>" "ReadDirectory" "InvalidEncoding" root)
      "" '(:directory-scan-mutation :utf8 :directory-faults ((:child-stat 1 -9) (:close 1 -5)))))))

(deftest v013-order-ties-and-dtype
  (let* ((root (v13-directory)) (names '("日本" "aa" "a" "é" "é" ".dot"))
         (records (v13-raw-records (append names '("a" "aa")) 4))
         (expected (sort (copy-list names) #'string<))
         (body (format nil "let expected:List<String>=List<String>[~{~S~^,~}];branch on readDirectory(~S){Result<List<DirectoryEntry>,IoError>::Err=>1,Result<List<DirectoryEntry>,IoError>::Ok(entries:List<DirectoryEntry>)=>{assert entries->length()==~D;var i:Int=0;loop over(entries as entry:DirectoryEntry){assert branch on entry->kind{DirectoryEntryKind::File=>true,DirectoryEntryKind::Directory=>false,DirectoryEntryKind::Symlink=>false,DirectoryEntryKind::Other=>false};assert branch on expected->at(i){Result<String,IndexError>::Ok(name:String)=>name==entry->name,Result<String,IndexError>::Err=>false};i=i+1;};0}}" expected root (length names))))
    (dolist (name names) (put-text (pathname (concatenate 'string root "/" name)) "x"))
    (let ((calls 0))
      (replacing (mognitio.io::directory-getdents
        (lambda (fd buffer count)
          (declare (ignore fd count))
          (if (= (incf calls) 1)
              (progn (dotimes (i (length records)) (setf (sb-sys:sap-ref-8 buffer i) (aref records i))) (length records)) 0)))
        (same 0 (v13-host-code body))))
    (same 0 (v13-native-code body "" (list :directory-scan-records records)))))

(deftest v013-cleanup-map-boundaries
  (let ((root (v13-directory)))
    (put-text (pathname (concatenate 'string root "/child")) "x")
    (dolist (option '((:directory-cleanup-fault -22) (:directory-corrupt-record :zero-size)
                      (:directory-corrupt-record :unaligned) (:directory-corrupt-record :cycle) (:directory-corrupt-record :fd)))
      (multiple-value-bind (out err code trace)
          (v13-trace (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root)) option))
        (same "" out) (same 3 code) (is (search "internal error" err))
        (is (search "close(3)" trace))))
    (same 0 (v13-native-code (v13-error-body (format nil "readDirectory(~S)" root) "List<DirectoryEntry>" "ReadDirectory" "ResourceExhausted" root)
      "" '(:directory-cleanup-fault -12)))
    (same 0 (v13-native-code (v13-error-body (format nil "readDirectory(~S)" root) "List<DirectoryEntry>" "ReadDirectory" "NotFound" (concatenate 'string root "/child"))
      "" '(:directory-cleanup-fault -12 :directory-faults ((:child-stat 1 -2)))))
    (multiple-value-bind (out err code)
        (process-result (list (namestring (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root))
                              '(:fail-allocation 2 :directory-cleanup-fault -22)))))
      (same "" out) (same 4 code) (is (search "allocation failure" err)))
    (multiple-value-bind (out err code)
        (process-result (list (namestring (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root)) '(:directory-fail-map t)))))
      (same "" out) (same 4 code) (is (search "allocation failure" err)))))

(deftest v013-growth-and-subject-allocation
  (let ((root (v13-directory)))
    (dotimes (i 100) (put-text (pathname (format nil "~A/long-name-~4,'0D" root i)) "x"))
    (dolist (when '(:directory-fail-growth-before :directory-fail-growth-after))
      (dolist (region '(:table :arena))
        (multiple-value-bind (out err code trace)
            (v13-trace (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root)) (list when region)))
          (same "" out) (same 4 code) (is (search "allocation failure" err))
          (let* ((report (search "write(2," trace))
                 (unmaps (count-if (lambda (line) (search "munmap(" line))
                                   (uiop:split-string (subseq trace 0 report) :separator '(#\Newline)))))
            (is report) (is (search "close(3)" trace :end2 report))
            (is (>= unmaps (if (eq when :directory-fail-growth-after) 5 4)))))))
    (loop for ordinal from 2 to 7 do
      (multiple-value-bind (out err code trace)
          (v13-trace (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root))
                                (list :directory-faults '((:child-stat 1 -13)) :fail-allocation ordinal)))
        (same "" out) (same 4 code) (is (search "allocation failure" err))
        (let ((report (search "write(2," trace)))
          (is (search "close(3)" trace :end2 report)) (is (search "munmap(" trace :end2 report)))))
    (multiple-value-bind (out err code trace)
        (v13-trace (v12-native (v13-manifest (format nil "discard readDirectory(~S);0" root)) '(:directory-faults ((:scan 1 -9))))
                   "write:error=EPIPE:when=1")
      (same 3 code) (same "" out) (same "" err) (is (search "INJECTED" trace)))))

(deftest v013-duplicate-first-observation
  (let* ((root (v13-directory)) (records (v13-raw-records '("a" "a")))
         (body (format nil "branch on readDirectory(~S){Result<List<DirectoryEntry>,IoError>::Err=>1,Result<List<DirectoryEntry>,IoError>::Ok(xs:List<DirectoryEntry>)=>{assert xs->length()==1;loop over(xs as e:DirectoryEntry){assert branch on e->kind{DirectoryEntryKind::File=>false,DirectoryEntryKind::Directory=>false,DirectoryEntryKind::Symlink=>false,DirectoryEntryKind::Other=>true};};0}}" root)))
    (put-text (pathname (concatenate 'string root "/a")) "x")
    (let ((scans 0) (stats 0))
      (let ((mognitio.io::*directory-fault-hook* (lambda (phase) (when (and (eq phase :child-stat) (= (incf stats) 1)) 0))))
        (replacing (mognitio.io::directory-getdents
          (lambda (fd buffer count) (declare (ignore fd count))
            (if (= (incf scans) 1)
                (progn (dotimes (i (length records)) (setf (sb-sys:sap-ref-8 buffer i) (aref records i))) (length records)) 0)))
          (same 0 (v13-host-code body)))))
    (same 0 (v13-native-code body "" (list :directory-scan-records records :directory-faults '((:child-stat 1 0)))))))
