(in-package #:mognitio.tests)

(deftest v09-line-comments
  (dolist (ending (list "" (string #\Newline) (string #\Return)
                       (format nil "~C~C" #\Return #\Newline)))
    (expect-source (format nil "true // ignored _ 00 ~A" ending) :true)
    (unless (string= ending "")
      (let* ((source (text-source (format nil "// ignored~Afalse" ending)))
             (tokens (lex-source source))
             (diag (span-diagnostic (token-span (aref tokens 0)) :lex "test")))
        (same '(:false :eof) (map 'list #'token-kind tokens))
        (same 2 (diagnostic-line diag)) (same 1 (diagnostic-column diag)))))
  (expect-source (format nil "8 / 2 // division~%==4") :true)
  (expect-source "\"// text\"->length()==7" :true)
  (expect-invalid "/* no block comments */ true" "parse")
  ;; Comments cannot hide an invalid UTF-8 byte from the source decoder.
  (expect-cli (list "run" (namestring (put-bytes (fresh-path) #(47 47 255))))
              1 :phase "source"))

(deftest v09-identifiers-and-decimals
  (dolist (text '("00" "010" "0_1" "0x10" "1_000" "1u"))
    (expect-invalid (concatenate 'string text " == 0") "lex"))
  (let* ((tokens (lex-source (text-source "_value value_ __ X0")))
         (kinds (map 'list #'token-kind tokens)))
    (same '(:identifier :identifier :identifier :identifier :eof) kinds))
  (dolist (source '("0==0" "10==10" "-10<0"
                    "9223372036854775807>0" "-9223372036854775808<0"))
    (expect-source source :true))
  (expect-source "let _value:Int=1; _value==1" :true))

(deftest v09-unicode-escapes
  (dolist (pair '(("0" 0) ("000000" 0) ("7f" 127) ("80" 128)
                  ("D7FF" 55295) ("e000" 57344) ("feff" 65279)
                  ("10ffff" 1114111) ("1F600" 128512)))
    (let* ((source (format nil "\"\\u{~A}\"" (first pair)))
           (payload (token-payload (aref (lex-source (text-source source)) 0))))
      (same 1 (text-payload-scalar-count payload))
      (same (sb-ext:string-to-octets (string (code-char (second pair))) :external-format :utf-8)
            (text-payload-octets payload))))
  (dolist (escape '("\\u{}" "\\u{0000000}" "\\u{110000}" "\\u{D800}" "\\u{dfff}"
                    "\\u{xyz}" "\\u{ 41}" "\\u{+41}" "\\u0041" "\\u{41" "\\q"))
    (expect-invalid (format nil "\"~A\"" escape) "lex"))
  (dolist (source '("\"\\u" "\"\\u{" "\"\\u{41"))
    (expect-invalid source "lex"))
  (dolist (code '(0 9 31 127 65279))
    (let* ((source (format nil "\"~C\"->length()==1" (code-char code))))
      (expect-source source :true)
      (v06-expect-native source :true)))
  (dolist (source '("\"\\u{41}\\u{1f600}\\0\"->length()==3"
                    "\"\\u{41}\"==\"A\""
                    "\"\\u{e9}\"!=\"e\\u{301}\""
                    "\"\\u{A}\\u{D}\\u{22}\\u{5c}\"->length()==4"))
    (expect-source source :true)
    (v06-expect-native source :true '(:stress t :validate t))))

(deftest v09-byte-spans
  (let* ((source (text-source (format nil "// あ~C~C\"😀\" $" #\Return #\Newline)))
         (diag (diagnostic-of (lambda () (lex-source source)))))
    (same :lex (diagnostic-phase diag))
    (same 2 (diagnostic-line diag)) (same 5 (diagnostic-column diag))
    (same 15 (diagnostic-start-byte diag)) (same 16 (diagnostic-end-byte diag)))
  (let* ((source (text-source "\"あ\\q\""))
         (diag (diagnostic-of (lambda () (lex-source source)))))
    (same 3 (diagnostic-column diag))
    (same 4 (diagnostic-start-byte diag)) (same 6 (diagnostic-end-byte diag)))
  (let* ((source (text-source "\"😀\""))
         (tokens (lex-source source))
         (eof (span-diagnostic (token-span (aref tokens 1)) :parse "eof")))
    (same 6 (diagnostic-start-byte eof)) (same 6 (diagnostic-end-byte eof)))
  (dolist (case '((#(65 255) 1 2) (#(65 226 130 0) 3 4)
                  (#(65 226 130) 3 3) (#(65 237 160 128) 2 3)))
    (let* ((bytes (first case))
           (diag (diagnostic-of (lambda () (decode-source "invalid.mgn" bytes))))
           (err (expect-cli (list "run" (namestring (put-bytes (fresh-path) bytes)))
                            1 :phase "source")))
      (same (second case) (diagnostic-start-byte diag))
      (same (third case) (diagnostic-end-byte diag))
      (is (search (format nil "[bytes ~D,~D)" (second case) (third case)) err))))
  (let ((err (expect-cli (list "run" (namestring (put-text (fresh-path) "$")))
                          1 :phase "lex")))
    (is (search "[bytes 0,1)" err))))

(deftest v09-source-native-integration
  (let ((source (format nil "// header~%\"\\u{41}\\u{1f600}\"->length()==2 // end")))
    (expect-source source :true)
    (v06-expect-native source :true '(:stress t :validate t)))
  (dolist (bytes '(#(239 187 191 116 114 117 101) #(47 47 255) #(48 48)))
    (let* ((source (put-bytes (fresh-path) bytes))
           (output (fresh-path ".elf"))
           (sentinel #(11 22 33)))
      (put-bytes output sentinel)
      (expect-cli (list "build" (namestring source) "-o" (namestring output))
                  1 :phase (if (= (aref bytes 0) 48) "lex" "source"))
      (same sentinel (mognitio.source::read-octets (namestring output))))))
