(in-package #:mognitio.tests)

(defparameter *v09-positive-fixtures*
 '(
  ("primitives" "unit==unit && true!=false && !false && 7%3==1 && -7/3 == -2")
  ("minimum" "-(9223372036854775808)%(-1)==0")
  ("snapshot" "var n:Int=1; let f:Function():Int=function():Int{n};n=2;f()==1")
  ("nested" "let outer:Function(Int):Function():Int=function(n:Int):Function():Int{function():Int{n}};let f:Function():Int=outer(42);f()==42")
  ("transitive-capture" "let a:Int=9;let f:Function():Function():Int=function():Function():Int{function():Int{a}};f()()==9")
  ("higher-order" "let apply:Function(Function(Int):Int,Int):Int=function(f:Function(Int):Int,x:Int):Int{f(x)}; apply(function(x:Int):Int{x+1},41)==42")
  ("mutable-function" "var f:Function():Int=function():Int{1};f=function():Int{2};f()==2")
  ("function-product" "type Box=product{f:Function(Int):Int;};let b:Box=Box{f:function(x:Int):Int{x+2}};b->f(40)==42")
  ("function-sum" "type Choice=sum{Done;F(Function():Int);};branch on Choice::F(function():Int{42}){Choice::Done=>false,Choice::F(f:Function():Int)=>f()==42}")
  ("generic-closure" "template make<T>=function(x:T):Function():T{function():T{x}};make<Int>(42)()==42 && make<Unit>(unit)()==unit")
  ("generic-value" "template identity<T>=function(value:T):T{value};let f:Function(Int):Int=identity<Int>;f(42)==42")
  ("generic-nested-list" "template make<T>=function(x:T):List<Function():T>{List<Function():T>[function():T{x}]}; var n:Int=0;loop over(make<Int>(42) as f:Function():Int){n=f();};n==42")
  ("unused-type-param" "type UnitBox<T>=product{}; template fixed<T>=function():Int{42};let b:UnitBox<Int>=UnitBox<Int>{};discard b;fixed<Bool>()==42")
  ("generic-discard-list" "alias Items<T>=List<T>;template consume<T>=function(x:T):Unit{discard Items<T>[x];};consume<Unit>(unit);true")
  ("isolated-template" "let value:Int=1;template identity<T>=function(value:T):T{value};identity<Int>(value)==1")
  ("forward-types" "type A=product{b:B;};type B=product{n:Int;};A{b:B{n:42}}->b->n==42")
  ("alias-list" "alias Items<T>=List<T>;let a:Items<Int>=Items<Int>[1,2,3];a->length()==3")
  ("list-persistence" "let a:List<Int>=List<Int>[1];let b:List<Int>=a->append(2);let c:List<Int>=a->append(3);var n:Int=0;loop over(b as x:Int){n=n+x;};loop over(c as y:Int){n=n+y;};a->length()==1 && n==7")
  ("list-at" "branch on List<Int>[10,20]->at(1){Result<Int,IndexError>::Ok(x:Int)=>x==20,Result<Int,IndexError>::Err=>false}")
  ("list-error" "branch on List<Int>[10]->at(-1){Result<Int,IndexError>::Ok=>false,Result<Int,IndexError>::Err(e:IndexError)=>e->index == -1 && e->length==1}")
  ("list-unit" "var n:Int=0;loop over(List<Unit>[unit,unit] as value:Unit){value;n=n+1;};n==2")
  ("loop-snapshot" "var xs:List<Int>=List<Int>[1,2,3];var total:Int=0;loop over(xs as x:Int){total=total+x;xs=List<Int>[];};total==6 && xs->length()==0")
  ("iteration-capture" "var fs:List<Function():Int>=List<Function():Int>[];loop over(List<Int>[1,2,3] as x:Int){fs=fs->append(function():Int{x});};var n:Int=0;loop over(fs as f:Function():Int){n=n*10+f();};n==123")
  ("over-control" "var n:Int=0;loop over(List<Int>[1,2,3,4] as x:Int){branch when{x==2=>{continue;},x==4=>{break;},else=>unit};n=n+x;};n==4")
  ("while-control" "var n:Int=0;var s:Int=0;loop while(n<5){n=n+1;branch when{n==2=>{continue;},else=>unit};s=s+n;};s==13")
  ("outer-control-header" "var n:Int=0;loop while(n<3){n=n+1;loop while({continue;}){unit};};n==3")
  ("outer-over-target" "var n:Int=0;loop while(true){loop over({break;} as item:Int){discard item;};};n==0")
  ("panic-control" "let f:Function():Int=function():Int{panic{return 42;}};f()==42")
  ("short-circuit" "false && panic{\"unreached\"} || true")
  ("short-circuit-effects" "var n:Int=0;discard (true || {n=1;false});discard (false && {n=2;true});n==0")
  ("sum-optional-binder" "type S=sum{A(Int);B;};branch on S::A(42){S::A=>true,S::B=>false}")
  ("try-result" "let f:Function(Int):Result<Int,String>=function(n:Int):Result<Int,String>{let x:Int=try Result<Int,String>::Ok(n);Result<Int,String>::Ok(x+1)};branch on f(41){Result<Int,String>::Ok(x:Int)=>x==42,Result<Int,String>::Err=>false}")
  ("try-err" "let f:Function():Result<Unit,String>=function():Result<Unit,String>{discard try Result<Int,String>::Err(\"err\");Result<Unit,String>::Ok(unit)};branch on f(){Result<Unit,String>::Ok=>false,Result<Unit,String>::Err(e:String)=>e==\"err\"}")
  ("string-slice" "branch on \"A😀B\"->slice(1,2){Result<String,SliceError>::Ok(x:String)=>x==\"😀\",Result<String,SliceError>::Err=>false}")
  ("slice-error" "branch on \"abc\"->slice(2,1){Result<String,SliceError>::Ok=>false,Result<String,SliceError>::Err(e:SliceError)=>e->start==2 && e->end==1 && e->length==3}")
  ("contract-primitive" "contract Read{read(self:Self):Int;}witness Int implements Read{read(value:Self):Int{value}}Read(42)->read()==42")
  ("contract-closure" "contract Run{run(self:Self):Int;}witness Function():Int implements Run{run(f:Self):Int{f()}}let n:Int=42;Run(function():Int{n})->run()==42")
  ("contract-list" "contract Size{size(self:Self):Int;}witness List<Unit> implements Size{size(self:Self):Int{self->length()}}Size(List<Unit>[unit,unit])->size()==2")
  ("contract-list-storage" "contract Read{read(self:Self):Int;}witness Int implements Read{read(x:Self):Int{x}}var n:Int=0;loop over(List<Read>[Read(20),Read(22)] as r:Read){n=n+r->read();};n==42")
  ("recursive-dispatch" "type Worker=product{n:Int;};contract Run{run(self:Self):Int;}witness Worker implements Run{run(self:Self):Int{branch when{self->n==0=>0,else=>1+Run(Worker{n:self->n-1})->run()}}}Run(Worker{n:42})->run()==42")
  ("isolated-implementation" "let self:Int=1;let x:Int=2;contract Add{add(self:Self,x:Int):Int;}witness Int implements Add{add(self:Self,x:Int):Int{self+x}}Add(self)->add(x)==3")
  ("implementation-nested-capture" "contract Make{make(self:Self):Function():Int;}witness Int implements Make{make(self:Self):Function():Int{function():Int{self}}}Make(42)->make()()==42")
  ("normal-arm-unreachable-condition" "let f:Function():Int=function():Int{branch when{{return 42;}=>1,else=>2}};f()==42")
  ("generic-equal-types" "template probe<T,U>=function(flag:Bool):Int{1+(branch when{flag=>List<T>[panic{\"left\"}],else=>List<U>[panic{\"right\"}]})};true")))

(setf *v09-positive-fixtures*
      (append *v09-positive-fixtures*
        '(("forward-generic-scopes" "type A<T>=product{b:B<T>;};type B<T>=product{v:T;};A<Int>{b:B<Int>{v:42}}->b->v==42")
          ("remainder-minimum" "-9223372036854775808%(-1)==0"))))
