(in-package #:mognitio.tests)
(defun v09-abi-bad () '((:label :bad) (:mov-edi 99) (:mov-eax 60) (:syscall) (:ud2)))
(deftest v09-generated-caller-handwritten-closure
  (let ((source "let captured:String=\"cap\"+\"ture\";let probe:Function(String,Unit,Int,Bool):String=function(s:String,u:Unit,n:Int,b:Bool):String{captured+s};var i:Int=0;var good:Bool=true;loop while(i<50){let r:String=probe(\"a\",unit,7,true);good=good&&(r==\"a\");i=i+1;};good")
        (callee (append
          '((:label (:function 1)) (:push-rbp) (:mov-reg :rbp :rsp)
            (:mov-reg :rax :rsp) (:imm-rcx 16) (:cqo) (:idiv) (:mov-rax-rdx) (:test) (:jnz :bad)
            (:load-frame :r8 16) (:load-word :rdx :r8 32) (:lea-code (:function 1)) (:cmp-rax-rdx) (:jnz :bad)
            (:load-word :rax :r8 40) (:load-word :rax :rax 24) (:cmp-imm :rax 7) (:jnz :bad)
            (:load-frame :rax 32) (:test) (:jnz :bad)
            (:load-frame :rax 40) (:cmp-imm :rax 7) (:jnz :bad)
            (:load-frame :rax 48) (:cmp-imm :rax 1) (:jnz :bad)
            (:load-word :rcx :r15 0) (:cmp-imm :rcx 0) (:jz :bad)
            (:load-word :rax :rcx 8) (:cmp-imm :rax 2) (:jb :bad)
            (:imm-rax 99) (:mov-reg :r8 :rax) (:mov-reg :r9 :rax) (:mov-reg :r10 :rax) (:mov-reg :r11 :rax)
            (:mov-reg :rcx :rax) (:mov-reg :rdx :rax) (:mov-reg :rsi :rax) (:mov-reg :rdi :rax)
            (:load-frame :rax 24) (:mov-reg :rsp :rbp) (:pop-rbp) (:ret)) (v09-abi-bad))))
    (multiple-value-bind (out err code) (v05-cross-abi source 1 callee)
      (same 0 code) (same (format nil "true~%") out) (same "" err))))
(deftest v09-handwritten-caller-generated-closure
  (let* ((source "let probe:Function(String,Unit,Int,Bool):String=function(s:String,u:Unit,n:Int,b:Bool):String{branch when{u==unit&&n==7&&b=>s+\"\",else=>\"bad\"}};let unused:String=\"a\";true")
         (caller (append
           (v06-raw-frame)
           '((:store-frame -8 :r15) (:store-frame -16 :rsp)
             (:lea-object (:static-object :closure 1)) (:store-frame -32 :rax)
             (:lea-text (:text 2)) (:store-frame -24 :rax)
             (:imm-rax 50) (:store-frame -64 :rax) (:label :again)
             (:load-frame :rax -32) (:store-out 0 :rax)
             (:load-frame :rax -24) (:store-out 8 :rax)
             (:imm-rax 0) (:store-out 16 :rax) (:imm-rax 7) (:store-out 24 :rax)
             (:imm-rax 1) (:store-out 32 :rax)
             (:load-frame :rax -32) (:load-word :rax :rax 32) (:call-rax)
             (:load-word :rax :rax 24) (:cmp-imm :rax 1) (:jnz :bad)
             (:mov-reg :rax :r15) (:load-frame :rcx -8) (:cmp) (:jnz :bad)
             (:mov-reg :rax :rsp) (:load-frame :rcx -16) (:cmp) (:jnz :bad)
             (:load-word :rdx :r15 0) (:lea-base :rax :rbp -48) (:cmp-rax-rdx) (:jnz :bad)
             (:load-frame :rax -64) (:imm-rcx 1) (:sub) (:store-frame -64 :rax) (:test) (:jnz :again))
           (v06-raw-finish) (v09-abi-bad)))
         (mognitio.native.runtime::*test-options* '(:stress t :validate t)))
    (multiple-value-bind (out err code) (v05-cross-abi source 0 caller)
      (same 0 code) (same (format nil "true~%") out) (same "" err))
    (multiple-value-bind (out err code)
        (v05-cross-abi source 0 caller
          (lambda (forms) (remove '(:store-word :r15 0 :rcx) forms :test #'equal)))
      (same 99 code) (same "" out) (same "" err))))
(deftest v09-new-machine-proof-mutations
  (dolist (kind '(:incoming :result :hidden :table))
    (let ((source (if (eq kind :table)
                      "contract C{f(self:Self):Int;}witness Int implements C{f(self:Self):Int{self}}C(42)->f()==42"
                      "let f:Function(Int):Int=function(n:Int):Int{n+1};f(41)==42")))
      (let* ((captures (v06-frame-capture source))
             (capture (if (eq kind :incoming) (second captures) (first captures))))
        (destructuring-bind (function allocation roots layout sections body) capture
          (let* ((section (find-if (lambda (s) (and (eq (first s) :operation)
                                                   (find '(:call-rax) (third s) :test #'equal))) sections))
                 (forms (when section (copy-tree (third section)))))
            (ecase kind
              (:incoming (setf (nth 14 body) '(:load-frame :rax 24)))
              (:result (setf (car (last forms)) '(:imm-rax 0)))
              (:hidden (let ((store (find '(:store-out 0 :rax) forms :test #'equal)))
                         (setf (second store) 8)))
              (:table (let ((load (find '(:load-word :rax :rax 24) forms :test #'equal)))
                        (setf (fourth load) 32))))
            (unless (eq kind :incoming)
              (setf (third section) forms) (replace body forms :start1 (fourth section)))
            (signals internal-failure (mognitio.frame:verify-sections function allocation roots layout sections body))))))))
