(in-package #:mognitio.tests)
(defun v06-runtime-artifact (source options)
  (let* ((mognitio.native.runtime::*test-options* options)
         (path (put-bytes (fresh-path ".elf") (native-image source))))
    (sb-posix:chmod (namestring path) #o700) path))
(defun v06-expect-native (source expected &optional options)
  (expect-artifact (v06-runtime-artifact source options) expected))
(defun v03-positive (source expected)
  (same expected (compiled-result source))
  (v06-expect-native source expected))
