#!/usr/bin/env python3
"""Generate ordinary Mognitio data, never native code or runtime blobs."""
from pathlib import Path
import argparse
ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "compiler/mgnc/src/Width/width.mgn"
def literal(values):
    return '"' + "".join("\\u{" + format(value, "x") + "}" for value in values) + '"'
def generated():
    ranges = [range(128), range(128, 2048),
              [c for c in range(2048, 65536) if not 0xD800 <= c <= 0xDFFF]]
    text = "namespace Mgnc\\Width;\n// Generated by tests/mgnc/generate-width.py; ordinary immutable scalar data.\n"
    for i, values in enumerate(ranges, 1):
        text += f"let width{i}: List<String> = {literal(values)}->scalars();\n"
    text += """public let scalarWidth: Function(String): Int = function(scalar: String): Int {
    loop over (width1 as candidate1: String) {
        branch when { candidate1 == scalar => { return 1; }, else => unit };
    };
    loop over (width2 as candidate2: String) {
        branch when { candidate2 == scalar => { return 2; }, else => unit };
    };
    loop over (width3 as candidate3: String) {
        branch when { candidate3 == scalar => { return 3; }, else => unit };
    };
    4
};
"""
    return text, ranges
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text, ranges = generated()
    if args.check:
        assert TARGET.read_text() == text
        widths = {value: width for width, values in enumerate(ranges, 1) for value in values}
        for value in range(0x110000):
            if 0xD800 <= value <= 0xDFFF:
                continue
            assert widths.get(value, 4) == len(chr(value).encode("utf-8")), value
        print("MGNC_WIDTH_OK unicode_scalars=1112064")
    else:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text)
if __name__ == "__main__":
    main()
