(defpackage #:mognitio.analysis
  (:use #:cl #:mognitio.source #:mognitio.syntax #:mognitio.diagnostics)
  (:export #:analyze-snapshot #:worker-main))
(in-package #:mognitio.analysis)
(defun field (x name &optional default) (mognitio.json:get-field x name default))
(defun text-source (path text)
  (decode-source path (sb-ext:string-to-octets text :external-format :utf-8)))
(defun diagnostic-record (d)
  (mognitio.json:object "path" (mognitio.diagnostics::diagnostic-path d)
    "start" (mognitio.diagnostics::diagnostic-start-byte d)
    "end" (mognitio.diagnostics::diagnostic-end-byte d)
    "phase" (string-downcase (symbol-name (or (mognitio.diagnostics::diagnostic-phase d) :input)))
    "message" (mognitio.diagnostics::diagnostic-message d)
    "related" (map 'vector #'diagnostic-record (mognitio.diagnostics::diagnostic-related d))))
(defun snapshot-project (snapshot)
  (let* ((manifest (text-source "mognitio.toml" (field snapshot "manifest")))
         (modules nil))
    (multiple-value-bind (name namespace name-span) (mognitio.project::manifest-values manifest)
      (unless (and (plusp (length name)) (char<= #\a (char name 0) #\z)
                   (every (lambda (c) (or (char<= #\a c #\z) (char<= #\0 c #\9) (eql c #\_))) name)
                   (mognitio.project::namespace-parts namespace)
                   (not (mognitio.project::standard-namespace-p namespace)))
        (mognitio.project::input-error "mognitio.toml" "Invalid project name or root namespace"))
      (maphash
        (lambda (path text)
          (let* ((parts (uiop:split-string path :separator '(#\/))) (dirs (butlast (rest parts))))
            (unless (and (equal (first parts) "src") (every #'mognitio.project::identifier-p dirs))
              (mognitio.project::input-error path "Invalid namespace directory"))
            (push (mognitio.project::make-source-module
                   :path path :source (text-source path text)
                   :namespace (format nil "~{~A~^\\~}" (append (mognitio.project::namespace-parts namespace) dirs)))
                  modules)))
        (field snapshot "sources"))
      (setf modules (sort modules #'string< :key #'mognitio.project::source-module-path))
      (mognitio.project::make-project
        :manifest "mognitio.toml" :manifest-source manifest :root (field snapshot "root")
        :entry-policy :analysis :name name :namespace namespace :name-span name-span
        :modules modules :entry (find (format nil "src/~A.mgn" name) modules
                                     :key #'mognitio.project::source-module-path :test #'equal)))))
(defun analyze-snapshot (snapshot)
  (let ((mognitio.frontend::*nesting-limit* 256)
        (mognitio.frontend::*syntax-depth* 0)
        (diagnostics nil) (tokens (make-hash-table :test #'equal)) (complete t))
    (handler-case
        (if (field snapshot "root")
            (let* ((project (snapshot-project snapshot))
                   (program (mognitio.project::project-program (mognitio.project::resolve-project project)))
                   (checked (mognitio.semantic:check-program program)))
              (setf tokens (project-semantic-tokens project checked)))
            (maphash (lambda (path text)
                       (handler-case
                           (syntax-only path text tokens)
                         (source-failure (e)
                           (setf complete nil)
                           (push (diagnostic-record (failure-diagnostic e)) diagnostics))))
                     (field snapshot "sources")))
      ((or source-failure usage-or-io-failure) (e)
        (setf complete nil) (push (diagnostic-record (failure-diagnostic e)) diagnostics)
        (maphash (lambda (path text)
                   (handler-case (syntax-only path text tokens)
                     (source-failure (other)
                       (let ((item (diagnostic-record (failure-diagnostic other))))
                         (unless (find (mognitio.json:encode item) diagnostics
                                       :key #'mognitio.json:encode :test #'equal)
                           (push item diagnostics))))))
                 (field snapshot "sources"))))
    (mognitio.json:object "complete" (if complete :true :false)
                          "diagnostics" (coerce (nreverse diagnostics) 'vector) "tokens" tokens)))
(defun worker-main ()
  (handler-case
      (let* ((text (read-line *standard-input* nil nil))
             (snapshot (and text (mognitio.json:decode text))))
        (unless snapshot (error "Missing snapshot"))
        (write-line (mognitio.json:encode (analyze-snapshot snapshot)))
        (finish-output))
    ((or error storage-condition) ()
      (write-line "mognitio-lsp: internal analysis failure" *error-output*)
      (sb-ext:exit :code 3))))
