(in-package #:mognitio.semantic)

(defun binary-builtin-declaration-p (node)
  (and (typep node 'data-declaration)
       (eq (mognitio.source::source-origin (span-source (node-span node))) :standard)
       (equal (token-text (data-declaration-name node)) "standard:Std\\Binary#Bytes")))
(defun declare-binary-builtin (context node)
  (setf (gethash (token-text (data-declaration-name node)) (value-context-names context)) :bytes
        (gethash node (value-context-members context)) (make-member-info :kind :builtin-type))
  :bytes)
(defun verify-binary-builtin (node type)
  (v-check (and (eq type :bytes) (binary-builtin-declaration-p node)
                (eq :struct (data-declaration-kind node)) (null (data-declaration-target node))
                (zerop (length (data-declaration-members node)))
                (zerop (length (data-declaration-type-parameters node))))
           "Invalid builtin Bytes identity"))

(defun binary-result (context success name)
  (let ((error (gethash name (value-context-names context))))
    (unless error (internal-error "Missing binary standard identity"))
    (instantiate-generic-type context (gethash :result (value-context-templates context))
                              (list success error))))
(defun binary-intrinsic-signature (context op)
  (ecase op
    (:bytes.from-ints (values '((:list :int)) (binary-result context :bytes "standard:Std\\Binary#ByteValueError")))
    (:bytes.from-bits (values '((:list (:bits (:integer-value 8)))) :bytes))))
(defun c-binary-intrinsic (node)
  (let* ((op (mognitio.syntax::binary-intrinsic-operation node))
         (args (coerce (mognitio.syntax::binary-intrinsic-arguments node) 'list))
         (children (mapcar #'c-expression args)))
    (multiple-value-bind (parameters result) (binary-intrinsic-signature (c-context) op)
      (unless (and (= (length args) (length parameters))
                   (equal result (resolve-type-token (c-context) (mognitio.syntax::binary-intrinsic-result-type node))))
        (internal-error "Invalid binary intrinsic signature"))
      (loop for child in children for arg in args for expected in parameters do (c-context-check arg child expected))
      (c-operation node op args parameters result)
      (c-summary node result (every #'c-normal children) children))))
(defun v-binary-intrinsic (node)
  (let* ((op (mognitio.syntax::binary-intrinsic-operation node))
         (args (coerce (mognitio.syntax::binary-intrinsic-arguments node) 'list)))
    (multiple-value-bind (parameters result) (binary-intrinsic-signature (v-context) op)
      (v-check (and (= (length args) (length parameters))
                    (equal result (v-resolve (mognitio.syntax::binary-intrinsic-result-type node))))
               "Invalid binary intrinsic proof")
      (loop for child in args for expected in parameters do (v-visit child) (v-exact child expected))
      (v-operation node op args parameters result)
      (v-finish node result (every #'v-normal args) args))))

(defun binary-method-receiver-p (type node)
  (or (eq type :bytes) (and (bits-type-p type) (equal "toBytes" (token-text (method-call-name node))))))
(defun binary-method-p (op)
  (member op '(:bytes.length :bytes.at :bytes.append :bytes.concat :bytes.slice :bytes.to-bits :bits.to-bytes)))
(defun binary-method-signature (context node type)
  (let* ((name (token-text (method-call-name node)))
         (syntax (mognitio.syntax::method-call-type-arguments node))
         (decode (and (eq type :bytes) (equal name "toBits")))
         (order (gethash "standard:Std\\Binary#ByteOrder" (value-context-names context))))
    (unless (= (length syntax) (if decode 1 0))
      (fail-at (node-span node) :type "Wrong binary method argument count"))
    (cond
      ((and (bits-type-p type) (equal name "toBytes"))
       (values :bits.to-bytes (list order) (binary-result context :bytes "standard:Std\\Binary#BitWidthError")))
      ((eq type :bytes)
       (cond
         ((equal name "length") (values :bytes.length nil :int))
         ((equal name "at") (values :bytes.at '(:int) (binary-result context '(:bits (:integer-value 8)) "IndexError")))
         ((equal name "append") (values :bytes.append '((:bits (:integer-value 8))) :bytes))
         ((equal name "concat") (values :bytes.concat '(:bytes) :bytes))
         ((equal name "slice") (values :bytes.slice '(:int :int) (binary-result context :bytes "SliceError")))
         (decode
          (let ((width (resolve-integer-argument context (aref syntax 0))))
            (require-numeric-width context width 1 (node-span node))
            (values :bytes.to-bits (list order)
                    (binary-result context (list :bits width) "standard:Std\\Binary#BinaryDecodeError"))))
         (t (fail-at (node-span node) :semantic "Unknown Bytes method"))))
      (t (fail-at (node-span node) :semantic "Invalid binary method receiver")))))
