(in-package #:mognitio.semantic)

(defun verify-source-type-records (program)
  (let ((context (v-context)) (edges (make-hash-table :test #'equal)) (names nil))
    (loop for name in '("Int" "Bool" "String" "Unit" "List")
          for type in '(:int :bool :string :void :list-constructor) do
      (v-check (eq type (gethash name (value-context-names context))) "Invalid predeclared type"))
    (loop for entry in '(("IndexError" ("index" . :int) ("length" . :int))
                        ("SliceError" ("start" . :int) ("end" . :int) ("length" . :int)))
          for id from 0 for info = (context-type context (gethash (first entry) (value-context-names context))) do
      (v-check (and (= id (type-info-id info)) (eq :struct (type-info-kind info))
                    (string= (first entry) (type-info-name info))
                    (equal (rest entry) (type-info-fields info))
                    (null (type-info-variants info)) (null (type-info-methods info))) "Invalid built-in error layout"))
    (let ((result (gethash "Result" (value-context-names context))))
      (v-check (and (generic-template-p result) (eq :result (generic-template-id result))
                    (equal '((:parameter (:builtin :result) 0) (:parameter (:builtin :result) 1))
                           (generic-template-parameters result))
                    (eq :enum (generic-template-kind result))
                    (equal (mapcar (lambda (v) (list (variant-info-id v) (variant-info-name v) (variant-info-types v)))
                                   (generic-template-variants result))
                           '((0 "Ok" ((:parameter (:builtin :result) 0))) (1 "Err" ((:parameter (:builtin :result) 1))))))
               "Invalid Result family"))
    (labels ((name-of (node)
               (token-text (if (typep node 'contract-declaration) (contract-declaration-name node) (data-declaration-name node))))
             (dependencies (syntax)
               (typecase syntax
                 (function-type-syntax (append (mapcan #'dependencies (coerce (function-type-syntax-parameters syntax) 'list))
                                               (dependencies (function-type-syntax-result syntax))))
                 (type-syntax (cons (token-text (type-syntax-name syntax)) (mapcan #'dependencies (coerce (type-syntax-arguments syntax) 'list))))
                 (token (list (token-text syntax)))))
             (verify-shape (node type)
               (let* ((contract (typep node 'contract-declaration))
                      (kind (if contract :interface (data-declaration-kind node))) (seen nil))
                 (if (eq kind :alias)
                     (v-check (equal type (v-resolve (data-declaration-target node))) "Invalid alias proof")
                     (let ((info (context-type context type)))
                       (v-check (eq kind (type-info-kind info)) "Invalid nominal category")
                       (flet ((unique (token)
                                (let ((name (token-text token)))
                                  (v-check (not (member name seen :test #'string=)) "Duplicate member") (push name seen))))
                         (case kind
                           (:struct
                            (v-check (equal (type-info-fields info)
                              (loop for member across (data-declaration-members node) do (unique (named-member-name member))
                                    collect (cons (token-text (named-member-name member)) (v-resolve (named-member-value member)))))
                              "Invalid product layout"))
                           (:enum
                            (v-check (and (plusp (length (data-declaration-members node)))
                                          (= (length (type-info-variants info)) (length (data-declaration-members node)))) "Invalid sum layout")
                            (loop for member across (data-declaration-members node) for variant in (type-info-variants info) for ordinal from 0 do
                              (unique (named-member-name member))
                              (v-check (and (= ordinal (variant-info-id variant))
                                            (string= (variant-info-name variant) (token-text (named-member-name member)))
                                            (<= (length (named-member-value member)) 1)
                                            (equal (variant-info-types variant) (map 'list #'v-resolve (named-member-value member)))) "Invalid variant layout")))
                           (:interface
                            (v-check (= (length (type-info-methods info)) (length (contract-declaration-methods node))) "Invalid contract layout")
                            (loop for member across (contract-declaration-methods node) for expected in (type-info-methods info)
                                  for function = (named-member-value member) for params = (coerce (function-expression-parameters function) 'list) do
                              (unique (named-member-name member))
                              (v-check (and params (typep (parameter-type (first params)) 'token)
                                            (string= "Self" (token-text (parameter-type (first params))))
                                            (string= (requirement-name expected) (token-text (named-member-name member)))
                                            (equal (requirement-parameters expected) (mapcar (lambda (p) (v-resolve (parameter-type p))) (rest params)))
                                            (equal (requirement-result expected) (v-resolve (function-expression-result-type function))))
                                       "Invalid contract signature"))))))))))
      (loop for node across (program-declarations program) when (typep node '(or data-declaration contract-declaration)) do
        (let* ((name (name-of node)) (stored (gethash name (value-context-names context)))
               (generic (typep stored 'generic-template)) (refs nil))
          (v-check (not (member name names :test #'string=)) "Duplicate compile-time declaration")
          (push name names)
          (if generic
              (call-with-type-parameters context (data-declaration-type-parameters node) (list :type (generic-template-id stored))
                (lambda (parameters)
                  (v-check (equal parameters (generic-template-parameters stored)) "Invalid generic type parameters")
                  (verify-shape node (if (eq :alias (generic-template-kind stored)) (generic-template-target stored)
                                       (list :application (generic-template-kind stored) (generic-template-id stored) parameters)))))
              (verify-shape node stored))
          (typecase node
            (contract-declaration
             (loop for member across (contract-declaration-methods node) for function = (named-member-value member) do
               (setf refs (append refs (dependencies (function-expression-result-type function))
                                  (mapcan (lambda (p) (dependencies (parameter-type p))) (rest (coerce (function-expression-parameters function) 'list)))))))
            (data-declaration
             (setf refs (if (eq :alias (data-declaration-kind node)) (dependencies (data-declaration-target node))
                            (loop for member across (data-declaration-members node)
                                  append (if (eq :struct (data-declaration-kind node)) (dependencies (named-member-value member))
                                             (mapcan #'dependencies (coerce (named-member-value member) 'list))))))))
          (setf (gethash name edges) (mapcar (lambda (x) (cons x (node-span node)))
                                            (remove-if-not (lambda (x) (typep (gethash x (value-context-declarations context)) '(or data-declaration contract-declaration))) refs)))))
      (check-call-graph names edges (lambda (span) (declare (ignore span)) (internal-error "Cyclic type proof"))))))
