(in-package #:mognitio.semantic)

(defun v-visit (node)
  (typecase node
    (boolean-literal
     (v-check (member (boolean-literal-value node) '(:true :false)) "Invalid Bool literal") (v-finish node :bool t nil))
    (void-literal (v-finish node :void t nil))
    (integer-literal
     (let ((value (parse-integer (token-text (integer-literal-token node)))))
       (v-check (and (<= 0 value mognitio.integer:+maximum+) (= value (checked-literal (v-program) node))) "Invalid Int literal"))
     (v-finish node :int t nil))
    (string-literal
     (let* ((payload (string-literal-payload node))
            (text (sb-ext:octets-to-string (text-payload-octets payload) :external-format :utf-8)))
       (v-check (= (length text) (text-payload-scalar-count payload)) "Invalid UTF-8 literal"))
     (v-finish node :string t nil))
    (variable-reference (v-finish node (local-symbol-type (v-reference node (variable-reference-name node))) t nil))
    (function-expression
     (let ((signature (checked-function (v-program) node)))
       (v-body signature nil) (v-finish node (signature-type signature) t nil)))
    (specialization-reference
     (let* ((signature (gethash (token-text (specialization-reference-name node)) (value-context-function-templates (v-context))))
            (arguments (map 'list #'v-resolve (specialization-reference-arguments node)))
            (call (checked-call (v-program) node)))
       (v-check (and signature (= (length arguments) (length (signature-type-parameters signature)))) "Invalid template reference")
       (let ((type (substitute-generic-type (v-context) (signature-type signature) (pairlis (signature-type-parameters signature) arguments))))
         (v-check (and (= (call-info-owner call) (v-owner)) (= (call-info-template call) (signature-id signature))
                       (equal arguments (call-info-type-arguments call)) (equal type (call-info-type call))
                       (equal (list (signature-id signature)) (call-info-targets call))) "Invalid specialization reference")
         (loop for id = (v-owner) then (signature-parent (aref (checked-program-signatures (v-program)) id))
               while (plusp id) for owner = (aref (checked-program-signatures (v-program)) id)
               when (signature-template-node owner) do
                 (push (cons (signature-id signature) (node-span node)) (gethash id (verification-state-edges *verification*))) (return))
         (v-finish node type t nil))))
    ((or struct-expression enum-expression list-expression field-expression) (v-values node))
    ((or method-call call-expression) (v-invocation node))
    ((or unary-expression binary-expression) (v-primitive node))
    (branch-expression (v-branch node))
    (grouping
     (let ((child (grouping-expression node))) (v-visit child) (v-finish node (v-structure child) (v-normal child) (list child))))
    (sequence-node
     (let ((*verification* (copy-verification-state *verification*)))
       (push (make-hash-table :test #'equal) (verification-state-scopes *verification*))
       (v-sequence node (sequence-node-statements node) (sequence-node-terminal node))))
    (local-binding
     (let* ((type (v-resolve (local-binding-annotation node))) (child (local-binding-initializer node)))
       (v-bind node (local-binding-name node) type (local-binding-mutability node) t)
       (v-visit child) (v-exact child type) (setf (cdr (v-lookup (local-binding-name node))) t)
       (v-finish node :void (v-normal child) (list child))))
    (assignment
     (let ((symbol (v-reference node (assignment-name node))) (child (assignment-rhs node)))
       (v-check (and (eq :var (local-symbol-mutability symbol)) (= (v-owner) (local-symbol-owner symbol))) "Invalid assignment")
       (v-visit child) (v-exact child (local-symbol-type symbol)) (v-finish node :void (v-normal child) (list child))))
    (expression-statement
     (let ((child (expression-statement-expression node)))
       (v-visit child)
       (v-check (if (expression-statement-discard-p node)
                    (and (v-normal child) (not (member (v-normal child) '(:void nil))) (not (rigid-type-p (v-normal child))))
                    (member (v-normal child) '(nil :void))) "Invalid discard or expression statement")
       (v-finish node :void (v-normal child) (list child))))
    (loop-expression
     (let* ((*verification* (copy-verification-state *verification*))
            (binder (loop-expression-binder node)) (info (checked-loop (v-program) node))
            (head (or (loop-expression-target node) (loop-expression-condition node)))
            (body (loop-expression-body node)) (type (when binder (v-resolve (parameter-type binder)))))
       (push (make-hash-table :test #'equal) (verification-state-scopes *verification*))
       (v-check (and (= (v-owner) (loop-info-owner info)) (eq node (loop-info-node info))) "Invalid loop identity")
       (when binder (v-bind binder (parameter-name binder) type :element t))
       (when head (v-visit head) (v-exact head (if binder (list :list type) :bool)))
       (when binder (setf (cdr (v-lookup (parameter-name binder))) t) (v-finish binder type t nil))
       (push info (verification-state-loops *verification*))
       (v-visit body) (v-exact body :void)
       (let* ((incoming (remove-if-not (lambda (edge) (and (eq :break (first edge))
                                                           (= (loop-info-id info) (second edge)))) (v-exits body)))
              (types (remove-duplicates (mapcar #'third incoming) :test #'equal))
              (structure (if head :void (first types)))
              (normal (if head (v-normal head) (not (null incoming)))))
         (v-check (and (null (rest types)) (equal (loop-info-normal-type info) (when normal structure))) "Invalid loop flow")
         (v-finish node structure normal nil
           (union (when head (v-exits head))
                  (when (or (null head) (v-normal head))
                    (remove-if (lambda (edge) (and (member (first edge) '(:break :continue))
                                                  (= (second edge) (loop-info-id info)))) (v-exits body))) :test #'equal)))))
    ((or break-statement continue-statement)
     (let* ((info (first (verification-state-loops *verification*)))
            (break-p (typep node 'break-statement)) (child (when break-p (break-statement-value node))))
       (v-check (and info (eq info (checked-control (v-program) node))) "Invalid loop target")
       (let ((target (loop-info-node info)))
         (v-check (or (not break-p)
                      (eq (not (null child)) (not (or (loop-expression-condition target) (loop-expression-target target)))))
                  "Invalid break operand form"))
       (when child (v-visit child))
       (v-finish node nil nil (when child (list child))
         (when (or (null child) (v-normal child))
           (list (list (if break-p :break :continue) (loop-info-id info) (if child (v-normal child) :void) nil))))))
    (return-statement
     (let ((child (return-statement-value node)))
       (v-check (and (plusp (v-owner)) (= (v-owner) (checked-return (v-program) node))) "Invalid return owner")
       (v-visit child) (v-exact child (signature-result-type (aref (checked-program-signatures (v-program)) (v-owner))))
       (v-finish node nil nil (list child) (when (v-normal child) (list (list :return (v-owner) nil nil))))))
    ((or panic-expression try-expression)
     (let* ((panic (typep node 'panic-expression)) (child (if panic (panic-expression-block node) (try-expression-operand node)))
            (record (checked-error (v-program) node)) (type nil) (returned nil) (extra nil))
       (v-visit child)
       (if panic (progn (v-exact child :string) (when (v-normal child) (setf extra (list (list :failure (v-owner))))))
           (let* ((input (canonical-result-arguments (v-context) (v-structure child)))
                  (target (progn (v-check (plusp (v-owner)) "Try lacks owner")
                                 (setf returned (signature-result-type (aref (checked-program-signatures (v-program)) (v-owner))))
                          )))
             (setf target (canonical-result-arguments (v-context) returned))
             (v-check (and input target (equal (second input) (second target))) "Invalid Result propagation")
             (setf type (first input) extra (when (v-normal child) (list (list :return (v-owner) nil nil))))))
       (v-check (and record (eq (error-info-kind record) (if panic :panic :try))
                     (= (error-info-owner record) (v-owner)) (equal (error-info-operand-type record) (v-structure child))
                     (equal (error-info-result-type record) type) (equal (error-info-return-type record) returned)) "Invalid error proof")
       (v-finish node type (and (not panic) (v-normal child)) (list child) extra)))
    (t (internal-error "Unknown source proof node"))))

(defun verify-checked-program-internal (checked)
  (v-check (checked-program-p checked) "Expected CheckedProgram")
  (let* ((context (copy-instantiation-context (checked-program-values checked)))
         (*verification* (make-verification-state :checked checked :context context
                                                   :scopes (list (make-hash-table :test #'equal))))
         (program (checked-program-program checked)) (signatures (checked-program-signatures checked)))
    (setf (value-context-declarations context) (copy-type-names (value-context-declarations (checked-program-values checked)))
          (value-context-function-templates context) (copy-type-names (value-context-function-templates (checked-program-values checked))))
    (v-check (and (plusp (length signatures)) (null (signature-declaration (aref signatures 0)))
                  (eq (if (mognitio.syntax::program-project program) :void :bool) (signature-result-type (aref signatures 0)))) "Invalid entry")
    (verify-source-type-records program)
    (loop for declaration across (program-declarations program) do
      (typecase declaration
        (template-declaration
         (let* ((node (template-declaration-function declaration)) (sig (checked-function checked node)))
           (call-with-type-parameters context (template-declaration-parameters declaration) (list :function (signature-id sig))
             (lambda (parameters)
               (v-check (equal parameters (signature-type-parameters sig)) "Invalid template binders")
               (v-body sig t) (v-finish node (signature-type sig) t nil)))))
        (implementation-declaration
         (let* ((concrete (v-resolve (implementation-declaration-target declaration)))
                (contract (v-resolve (implementation-declaration-contract declaration)))
                (impl (find-implementation (checked-program-values checked) concrete contract))
                (methods (type-info-methods (context-type context contract))) (seen nil))
           (v-check impl "Missing implementation evidence")
           (loop for member across (implementation-declaration-methods declaration)
                 for name = (token-text (local-binding-name member))
                 for node = (local-binding-initializer member)
                 for sig = (checked-function checked node)
                 for method = (find name methods :key #'requirement-name :test #'string=) do
             (v-check (and method (not (member name seen :test #'string=))
                           (eq sig (cdr (assoc name (implementation-info-methods impl) :test #'string=)))
                           (equal (signature-method sig) (list concrete contract name))
                           (equal (signature-parameter-types sig) (requirement-parameters method))
                           (equal (signature-result-type sig) (requirement-result method))) "Invalid implementation signature")
             (push name seen) (v-body sig t) (v-finish node (signature-type sig) t nil))
           (v-check (= (length seen) (length methods)) "Incomplete implementation")))))
    (if (mognitio.syntax::program-project program)
        (mognitio.project::verify-project-bodies checked)
        (progn (v-sequence program (program-statements program) (program-root program)) (v-exact program :bool)))
    (loop for sig across signatures for id from 0 do
      (v-check (and (= id (signature-id sig))
                    (v-set-equal (signature-captures sig) (gethash id (verification-state-captures *verification*)))) "Invalid capture snapshot layout"))
    (let ((ids (loop for info being the hash-values of (checked-program-loops checked) collect (loop-info-id info))))
      (v-check (and (every (lambda (id) (typep id '(integer 0 *))) ids)
                    (equal (sort ids #'<) (loop for id below (hash-table-count (checked-program-loops checked)) collect id)))
               "Duplicate or invalid loop identity"))
    (v-check (= (1- (length signatures)) (hash-table-count (verification-state-functions *verification*))) "Unverified function")
    (v-check (= (length (checked-program-bindings checked)) (hash-table-count (verification-state-bindings *verification*))) "Unverified binding")
    (v-check (= (hash-table-count (checked-program-summaries checked)) (hash-table-count (verification-state-visited *verification*))
                (hash-table-count (checked-program-node-owners checked))) "Unverified node proof")
    (check-call-graph (loop for sig across signatures when (signature-template-node sig) collect (signature-id sig))
                      (verification-state-edges *verification*) (lambda (span) (declare (ignore span)) (internal-error "Cyclic template proof")))
  checked))
(defun verify-checked-program (checked)
  (when (and (checked-program-p checked) (checked-program-specialization checked))
    (return-from verify-checked-program (verify-specialization checked)))
  (handler-case (verify-checked-program-internal checked)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed CheckedProgram"))))
