(in-package #:mognitio.semantic)

;; The verifier derives flow independently of c-summary and the producer walk.
(defstruct verification-state checked context (owner 0) scopes loops
  (visited (make-hash-table :test #'eq)) (bindings (make-hash-table :test #'eq))
  (functions (make-hash-table)) (captures (make-hash-table)) (edges (make-hash-table))
  (results (make-hash-table :test #'eq)))
(defvar *verification*)
(defun v-check (ok message) (unless ok (internal-error message)))
(defun v-program () (verification-state-checked *verification*))
(defun v-context () (verification-state-context *verification*))
(defun v-owner () (verification-state-owner *verification*))
(defun v-result (node) (gethash node (verification-state-results *verification*)))
(defun v-structure (node) (first (v-result node)))
(defun v-normal (node) (second (v-result node)))
(defun v-exits (node) (third (v-result node)))
(defun v-exact (node expected)
  (v-check (or (null (v-normal node)) (equal (v-normal node) expected)) "Normal type mismatch in verification"))
(defun v-set-equal (a b) (and (subsetp a b :test #'equal) (subsetp b a :test #'equal)))
(defun v-prefix (children)
  (let ((result nil))
    (dolist (child children result)
      (setf result (union result (v-exits child) :test #'equal))
      (unless (v-normal child) (return result)))))
(defun v-finish (node structure normal children &optional extra)
  (let* ((exits (union (v-prefix children) extra :test #'equal))
         (summary (checked-completion (v-program) node)) (type (when normal structure)))
    (v-check (and (or (not normal) structure)
                  (equal structure (completion-structure summary))
                  (equal type (completion-normal-type summary))
                  (v-set-equal exits (completion-exits summary))
                  (eql (not (null (find :return exits :key #'first))) (completion-may-return summary))
                  (null (completion-targets summary))
                  (eql (v-owner) (gethash node (checked-program-node-owners (v-program)))))
             "Invalid structure, completion, or owner proof")
    (setf (gethash node (verification-state-visited *verification*)) t
          (gethash node (verification-state-results *verification*)) (list structure type exits))
    type))
(defun v-resolve (syntax) (resolve-type-token (v-context) syntax))
(defun v-lookup (token)
  (loop for scope in (verification-state-scopes *verification*)
        for entry = (gethash (token-text token) scope) when entry return entry))
(defun v-bind (node token type mutability &optional reserved)
  (let* ((checked (v-program)) (symbol (checked-symbol checked node))
         (bindings (checked-program-bindings checked)) (name (token-text token)))
    (v-check (and (not (v-lookup token))
                  (not (gethash name (value-context-names (v-context))))
                  (not (gethash name (value-context-declarations (v-context))))
                  (typep (local-symbol-id symbol) `(integer 0 ,(1- (length bindings))))
                  (eq symbol (aref bindings (local-symbol-id symbol)))
                  (not (gethash symbol (verification-state-bindings *verification*)))
                  (equal type (local-symbol-type symbol)) (eql (v-owner) (local-symbol-owner symbol))
                  (eq mutability (local-symbol-mutability symbol)) (string= name (local-symbol-name symbol))
                  (null (local-symbol-static-target symbol)) (null (local-symbol-template symbol)))
             "Invalid local declaration proof")
    (setf (gethash symbol (verification-state-bindings *verification*)) t
          (gethash name (first (verification-state-scopes *verification*))) (cons symbol (not reserved)))
    symbol))
(defun v-reference (node token)
  (let* ((entry (v-lookup token)) (symbol (checked-symbol (v-program) node)))
    (v-check (and entry (cdr entry) (eq symbol (car entry))) "Invalid lexical resolution")
    (loop for id = (v-owner) then (signature-parent (aref (checked-program-signatures (v-program)) id))
          until (= id (local-symbol-owner symbol)) do
      (v-check (plusp id) "Capture crossed an isolated body")
      (pushnew symbol (gethash id (verification-state-captures *verification*)) :test #'eq))
    symbol))
(defun v-operation (node kind operands parameters result)
  (let ((record (checked-operation (v-program) node)))
    (v-check (and record (eq kind (operation-info-kind record))
                  (equal operands (operation-info-operands record))
                  (equal parameters (operation-info-parameter-types record))
                  (equal result (operation-info-result-type record))) "Invalid selected operation")))
(defun v-member (node kind type &key index variant contract)
  (let ((record (checked-member (v-program) node)))
    (v-check (and record (eq kind (member-info-kind record)) (equal type (member-info-type record))
                  (equal index (member-info-index record)) (eql variant (member-info-variant record))
                  (equal contract (member-info-contract record))) "Invalid member selection")))
(defun v-sequence (node statements tail)
  (let ((children nil) (reachable t))
    (loop for statement across statements do
      (v-check reachable "Unreachable checked sequence")
      (v-visit statement) (push statement children) (setf reachable (v-normal statement)))
    (when tail (v-check reachable "Unreachable checked tail") (v-visit tail) (push tail children))
    (v-finish node (if tail (v-structure tail) (when reachable :void))
              (and reachable (or (null tail) (v-normal tail))) (reverse children))))
(defun v-body (signature isolated)
  (let* ((node (signature-declaration signature)) (id (signature-id signature))
         (outer *verification*) (*verification* (copy-verification-state outer))
         (receiver (signature-receiver signature))
         (parameters (coerce (function-expression-parameters node) 'list)))
    (v-check (and (eq signature (aref (checked-program-signatures (v-program)) id))
                  (not (gethash id (verification-state-functions *verification*)))
                  (= (signature-parent signature) (v-owner))) "Invalid function identity")
    (setf (gethash id (verification-state-functions *verification*)) t
          (verification-state-owner *verification*) id (verification-state-loops *verification*) nil
          (verification-state-scopes *verification*)
          (cons (make-hash-table :test #'equal) (unless isolated (verification-state-scopes outer))))
    (when receiver
      (let ((p (pop parameters)) (type (first (signature-method signature))))
        (v-check (or (string= "Self" (token-text (parameter-type p)))
                     (equal type (v-resolve (parameter-type p)))) "Invalid receiver annotation")
        (v-check (eq receiver (v-bind p (parameter-name p) type :receiver)) "Invalid receiver identity")
        (v-finish p type t nil)))
    (v-check (and (= (length parameters) (length (signature-parameter-types signature)))
                  (equal (v-resolve (function-expression-result-type node)) (signature-result-type signature)))
             "Invalid function annotation")
    (loop for p in parameters for type in (signature-parameter-types signature) do
      (v-check (equal type (v-resolve (parameter-type p))) "Invalid parameter annotation")
      (v-bind p (parameter-name p) type :parameter) (v-finish p type t nil))
    (v-visit (function-expression-body node))
    (v-exact (function-expression-body node) (signature-result-type signature))))
(defun v-branch (node)
  (let* ((on (eq :on (branch-expression-mode node))) (subject (branch-expression-subject node))
         (normal-types nil) (structures nil) (normal nil) (exits nil) (reachable t) (seen nil) (fallback nil) type)
    (when on (v-visit subject) (setf type (v-structure subject) reachable (v-normal subject) exits (v-exits subject))
      (v-check (nominal-type-p type :enum) "Branch without a sum"))
    (loop for arm across (branch-expression-arms node) for selector = (branch-arm-selector arm) do
      (v-check (not fallback) "Arm follows else")
      (let ((*verification* (copy-verification-state *verification*)))
        (push (make-hash-table :test #'equal) (verification-state-scopes *verification*))
        (cond (on
               (v-check (and selector (equal type (v-resolve (variant-pattern-name selector)))) "Pattern identity mismatch")
               (let* ((variant (find (token-text (variant-pattern-variant selector)) (type-info-variants (context-type (v-context) type))
                                     :key #'variant-info-name :test #'string=))
                      (binders (variant-pattern-bindings selector)))
                 (v-check (and variant (not (member (variant-info-id variant) seen))) "Invalid variant")
                 (push (variant-info-id variant) seen)
                 (v-member selector :pattern type :variant (variant-info-id variant))
                 (v-check (or (zerop (length binders)) (= (length binders) (length (variant-info-types variant)))) "Invalid binder count")
                 (loop for p across binders for expected in (variant-info-types variant) do
                   (v-check (equal expected (v-resolve (parameter-type p))) "Invalid case annotation")
                   (v-bind p (parameter-name p) expected :pattern) (v-finish p expected t nil))))
              ((null selector) (setf fallback t))
              (t (v-visit selector) (v-exact selector :bool)
                 (when reachable (setf exits (union exits (v-exits selector) :test #'equal) reachable (v-normal selector)))))
        (let ((value (branch-arm-value arm)))
          (v-visit value) (push (v-structure value) structures)
          (when (v-normal value) (pushnew (v-normal value) normal-types :test #'equal))
          (when reachable (setf normal (or normal (v-normal value)) exits (union exits (v-exits value) :test #'equal))))))
    (v-check (and (<= (length normal-types) 1)
                  (if on (= (length seen) (length (type-info-variants (context-type (v-context) type)))) fallback))
             "Invalid branch join or coverage")
    (v-member node :branch type)
    (v-finish node (or (first normal-types)
                       (when (and (first structures) (every (lambda (x) (equal x (first structures))) structures)) (first structures)))
              normal nil exits)))
