(in-package #:mognitio.semantic)

(defun v-values (node)
  (let ((type nil) (children nil))
    (typecase node
      (struct-expression
       (setf type (v-resolve (struct-expression-name node)))
       (let ((fields (type-info-fields (context-type (v-context) type))) (indices nil))
         (v-check (and (nominal-type-p type :struct) (= (length fields) (length (struct-expression-fields node)))) "Invalid product")
         (loop for field across (struct-expression-fields node)
               for index = (position (token-text (named-member-name field)) fields :key #'car :test #'string=)
               for value = (named-member-value field) do
           (v-check (and index (not (member index indices))) "Invalid product field")
           (push index indices) (v-visit value) (v-exact value (cdr (nth index fields))) (push value children))
         (setf children (reverse children))
         (v-member node :struct type :index (reverse indices))))
      (enum-expression
       (setf type (v-resolve (enum-expression-name node)) children (coerce (enum-expression-arguments node) 'list))
       (let ((variant (find (token-text (enum-expression-variant node)) (type-info-variants (context-type (v-context) type))
                            :key #'variant-info-name :test #'string=)))
         (v-check (and (nominal-type-p type :enum) variant (= (length children) (length (variant-info-types variant)))) "Invalid sum construction")
         (loop for child in children for expected in (variant-info-types variant) do (v-visit child) (v-exact child expected))
         (v-member node :enum type :variant (variant-info-id variant))))
      (list-expression
       (setf type (v-resolve (list-expression-type node)) children (coerce (list-expression-elements node) 'list))
       (v-check (list-type-p type) "Invalid List construction")
       (dolist (child children) (v-visit child) (v-exact child (second type)))
       (v-operation node :list.make children (make-list (length children) :initial-element (second type)) type))
      (field-expression
       (let* ((child (field-expression-receiver node)) (head (progn (v-visit child) (v-structure child)))
              (fields (type-info-fields (context-type (v-context) head)))
              (index (position (token-text (field-expression-name node)) fields :key #'car :test #'string=)))
         (v-check (and (nominal-type-p head :struct) index) "Invalid projection")
         (v-member node :field head :index index) (setf type (cdr (nth index fields)) children (list child)))))
    (v-finish node type (every #'v-normal children) children)))
(defun v-invocation (node)
  (let ((pack (checked-pack (v-program) node)) (type nil) (children nil))
    (cond
      (pack
       (v-check (and (typep node 'call-expression) (= 1 (length (call-expression-arguments node)))
                     (typep (call-expression-callee node) 'variable-reference)) "Invalid packaging AST")
       (setf type (v-resolve (variable-reference-name (call-expression-callee node)))
             children (coerce (call-expression-arguments node) 'list))
       (v-visit (first children))
       (v-check (and (nominal-type-p type :interface)
                     (equal type (implementation-info-contract pack))
                     (equal (v-structure (first children)) (implementation-info-concrete pack))
                     (eq pack (aref (value-context-implementations (checked-program-values (v-program))) (implementation-info-id pack))))
                "Invalid packaging evidence"))
      ((typep node 'call-expression)
       (let* ((callee (call-expression-callee node)) (args (coerce (call-expression-arguments node) 'list)))
         (v-visit callee)
         (let ((head (v-structure callee)) (call (checked-call (v-program) node)))
           (v-check (and (function-type-p head) (= (length args) (length (second head)))
                         (equal head (call-info-type call)) (eql (v-owner) (call-info-owner call))
                         (null (call-info-template call)) (null (call-info-targets call))) "Invalid closure call")
           (loop for child in args for expected in (second head) do (v-visit child) (v-exact child expected))
           (setf type (third head) children (cons callee args)))))
      (t
       (let* ((receiver (method-call-receiver node)) (args (coerce (method-call-arguments node) 'list))
              (head (progn (v-visit receiver) (v-structure receiver))) (name (token-text (method-call-name node)))
              (parameters nil) (kind nil))
         (dolist (arg args) (v-visit arg))
         (cond
           ((nominal-type-p head :struct)
            (let* ((fields (type-info-fields (context-type (v-context) head)))
                   (index (position name fields :key #'car :test #'string=))
                   (function (when index (cdr (nth index fields))))
                   (call (checked-call (v-program) node)))
              (v-check (and (function-type-p function) call (equal function (call-info-type call))
                            (= (v-owner) (call-info-owner call)) (null (call-info-template call))
                            (null (call-info-targets call))) "Invalid Function field call")
              (v-member node :field-call head :index index)
              (setf parameters (second function) type (third function))))
           ((list-type-p head)
            (cond ((string= name "length") (setf kind :list.length type :int))
                  ((and (equal head '(:list :string)) (string= name "join"))
                   (setf kind :text.join parameters '(:string) type :string))
                  ((string= name "append") (setf kind :list.append parameters (list (second head)) type head))
                  ((string= name "at")
                   (setf kind :list.at parameters '(:int)
                         type (instantiate-generic-type (v-context) (gethash "Result" (value-context-names (v-context)))
                                                        (list (second head) (gethash "IndexError" (value-context-names (v-context)))))))
                  (t (internal-error "Invalid List method"))))
           ((eq head :string)
            (cond ((string= name "length") (setf kind :text.length type :int))
                  ((string= name "scalars") (setf kind :text.scalars type '(:list :string)))
                  ((string= name "slice")
                   (setf kind :text.slice.result parameters '(:int :int)
                         type (instantiate-generic-type (v-context) (gethash "Result" (value-context-names (v-context)))
                                                        (list :string (gethash "SliceError" (value-context-names (v-context)))))))
                  (t (internal-error "Invalid String method"))))
           ((nominal-type-p head :interface)
            (let* ((methods (type-info-methods (context-type (v-context) head)))
                   (index (position name methods :key #'requirement-name :test #'string=))
                   (method (and index (nth index methods))) (call (checked-call (v-program) node)))
              (v-check method "Unknown contract method")
              (setf type (requirement-result method) parameters (requirement-parameters method))
              (v-member node :interface-call head :index index :contract head)
              (v-check (and (equal (call-info-type call) (list :function parameters type)) (= (call-info-owner call) (v-owner))
                            (v-set-equal (call-info-targets call)
                              (loop for impl across (value-context-implementations (checked-program-values (v-program)))
                                    when (equal head (implementation-info-contract impl))
                                      collect (signature-id (cdr (assoc name (implementation-info-methods impl) :test #'string=))))))
                       "Invalid contract dispatch")))
           (t (internal-error "Invalid method receiver")))
         (v-check (= (length args) (length parameters)) "Invalid method arity")
         (loop for arg in args for expected in parameters do (v-exact arg expected))
         (setf children (cons receiver args))
         (when kind (v-operation node kind children (cons head parameters) type)))))
    (v-finish node type (every #'v-normal children) children)))
(defun v-primitive (node)
  (let* ((unary (typep node 'unary-expression))
         (operator (token-kind (if unary (unary-expression-operator node) (binary-expression-operator node))))
         (children (if unary (list (unary-expression-operand node))
                       (list (binary-expression-left node) (binary-expression-right node)))))
    (when (and unary (checked-literal-p (v-program) node))
      (v-check (and (eq operator :sub) (= (checked-literal (v-program) node) mognitio.integer:+minimum+)) "Invalid folded minimum")
      (labels ((minimum (child)
                 (v-check (gethash child (checked-program-consumed (v-program))) "Missing consumed literal")
                 (typecase child
                   (grouping (minimum (grouping-expression child)))
                   (integer-literal (v-check (= (parse-integer (token-text (integer-literal-token child))) (expt 2 63)) "Invalid minimum magnitude"))
                   (t (internal-error "Invalid minimum syntax")))
                 (v-finish child :int nil nil)))
        (minimum (first children)))
      (return-from v-primitive (v-finish node :int t nil)))
    (dolist (child children) (v-visit child))
    (let* ((domain (cond (unary (if (eq operator :not) '(:bool) '(:int)))
                         ((member operator '(:and :or)) '(:bool))
                         ((eq operator :add) '(:int :string))
                         ((member operator '(:eq :ne)) '(:int :bool :void :string))
                         (t '(:int))))
           (rules (loop for candidate in domain
                        when (every (lambda (child) (or (null (v-structure child)) (equal candidate (v-structure child)))) children)
                          collect candidate)))
      (v-check (= 1 (length rules)) "Ambiguous or invalid primitive proof")
      (let* ((input (first rules))
             (type (if (member operator '(:eq :ne :lt :le :gt :ge :and :or :not)) :bool input))
             (kind (if (eq input :string) (ecase operator (:add :text.concat) (:eq :text.equal) (:ne :text.not-equal)) operator)))
        (dolist (child children) (v-exact child input))
        (v-operation node kind children (make-list (length children) :initial-element input) type)
        (v-finish node type (if (member operator '(:and :or)) (v-normal (first children)) (every #'v-normal children)) children)))))
