(in-package #:mognitio.value)

(defstruct (closure-value (:constructor %make-closure-value (code captures)))
  (code nil :read-only t) (captures #() :read-only t))
(defstruct (list-value (:constructor %make-list-value (length previous element)))
  (length 0 :read-only t) (previous nil :read-only t) (element nil :read-only t))
(defparameter *empty-list* (%make-list-value 0 nil nil))
(defvar *list-operation-observer* nil)
(defun list-event (kind)
  (when *list-operation-observer* (funcall *list-operation-observer* kind)))
(defun closure (code &rest captures)
  (handler-case (progn (when captures (mognitio.runtime::allocation-point :closure)) (%make-closure-value code (coerce captures 'vector)))
    (storage-condition () (mognitio.runtime:runtime-error :allocation-failed))))
(defun closure-call (value &rest arguments)
  (apply (closure-value-code value) value arguments))
(defun capture (value index) (aref (closure-value-captures value) index))
(defun list-length-value (value) (list-event :length-load) (list-value-length value))
(defun list-append-value (value element)
  (let ((length (list-value-length value)))
    (when (= length mognitio.integer:+maximum+) (mognitio.runtime:runtime-error :list-length-overflow))
    (handler-case (progn (mognitio.runtime::allocation-point :list) (list-event :node-create) (%make-list-value (1+ length) value element))
      (storage-condition () (mognitio.runtime:runtime-error :allocation-failed)))))
(defun list-literal (&rest elements)
  (reduce #'list-append-value elements :initial-value *empty-list*))
(defun list-at-value (value index result-type error-type)
  (if (<= 0 index (1- (list-value-length value)))
      (let ((node value))
        (loop repeat (- (list-value-length value) 1 index) do
          (list-event :link-visit) (setf node (list-value-previous node)))
        (construct result-type 0 (list-value-element node)))
      (construct result-type 1 (construct error-type 0 index (list-value-length value)))))
(defun list-buffer (value)
  (handler-case
      (let* ((length (list-value-length value))
             (buffer (progn (when (>= length array-dimension-limit) (mognitio.runtime:runtime-error :allocation-failed))
                            (when (plusp length) (mognitio.runtime::allocation-point :buffer)) (make-array length))) (node value))
        (loop for index downfrom (1- length) to 0 do
          (list-event :buffer-write) (list-event :link-visit)
          (setf (aref buffer index) (list-value-element node) node (list-value-previous node)))
        buffer)
    (storage-condition () (mognitio.runtime:runtime-error :allocation-failed))))
(defun text-slice-result (text start end result-type error-type)
  (if (<= 0 start end (mognitio.text:text-length text))
      (construct result-type 0 (mognitio.text:text-slice text start end))
      (construct result-type 1 (construct error-type 0 start end (mognitio.text:text-length text)))))
