(in-package #:mognitio.semantic)

(defun declaration-name (node)
  (typecase node
    (data-declaration (data-declaration-name node))
    (contract-declaration (contract-declaration-name node))
    (template-declaration (template-declaration-name node))
    (implementation-declaration (mognitio.syntax::implementation-declaration-name node))))
(defun ensure-value-declaration-in-scope (context node)
  (case (gethash node (value-context-declaration-state context))
    (:done (return-from ensure-value-declaration-in-scope))
    (:visiting (fail-at (node-span node) :semantic "Cyclic type declaration")))
  (setf (gethash node (value-context-declaration-state context)) :visiting)
  (when (typep node 'contract-declaration)
    (loop for member across (contract-declaration-methods node)
          for fn = (named-member-value member)
          for params = (function-expression-parameters fn) do
      (unless (and (plusp (length params))
                   (typep (parameter-type (aref params 0)) 'token)
                   (not (typep (parameter-type (aref params 0)) 'type-syntax))
                   (string= (token-text (parameter-type (aref params 0))) "Self"))
        (fail-at (node-span member) :semantic "Contract requires a first Self receiver"))
      (let ((seen nil))
        (loop for param across params for name = (token-text (parameter-name param)) do
          (when (or (member name seen :test #'string=)
                    (gethash name (value-context-declarations context))
                    (gethash name (value-context-names context)))
            (fail-at (node-span param) :semantic "Receiver or parameter name conflicts"))
          (push name seen)))))
  (declare-value-type context node)
  (setf (gethash node (value-context-declaration-state context)) :done))
(defun ensure-value-declaration (context node)
  (when (typep node 'implementation-declaration)
    (fail-at (node-span node) :semantic "Witness is not a type"))
  ;; A forward declaration is checked in its own compile-time scope.
  (let* ((outer (value-context-names context)) (isolated (copy-type-names outer)))
    (maphash (lambda (name type) (when (compile-time-parameter-p type) (remhash name isolated))) outer)
    (unwind-protect
         (progn (setf (value-context-names context) isolated)
                (ensure-value-declaration-in-scope context node))
      (maphash (lambda (name type)
                 (unless (compile-time-parameter-p (gethash name outer))
                   (setf (gethash name outer) type))) isolated)
      (setf (value-context-names context) outer))))
(defun prepare-value-declarations (context program)
  (loop for node across (program-declarations program) for token = (declaration-name node)
        when token do
    (let ((name (token-text token)))
      (when (or (gethash name (value-context-names context))
                (gethash name (value-context-declarations context))
                (member name '("Function" "Self") :test #'string=))
        (fail-at (token-span token) :semantic "Duplicate or reserved declaration name"))
      (setf (gethash name (value-context-declarations context)) node)))
  (loop for node across (program-declarations program)
        when (or (typep node 'data-declaration) (typep node 'contract-declaration))
        do (ensure-value-declaration context node))
  context)
