(in-package #:mognitio.driver)

(defun invocation-error ()
  (fail 'usage-or-io-failure nil "Expected test <mognitio.toml>, run <mognitio.toml> or build <mognitio.toml> -o <artifact>"))
(defun parse-invocation (argv)
  (unless (and (listp argv) (every #'stringp argv)) (invocation-error))
  (let ((command (first argv)) (source (second argv)) (output nil))
    (cond ((and (member command '("run" "test") :test #'equal) (= (length argv) 2)) nil)
          ((and (equal command "build") (= (length argv) 4) (equal (third argv) "-o"))
           (setf output (fourth argv))
           (unless (plusp (length output)) (invocation-error)))
          (t (invocation-error)))
    (unless (and source (plusp (length source)) (not (char= #\- (char source 0)))) (invocation-error))
    (values command source output (when output (mognitio.target:linux-amd64)))))

(defun checked-source (path)
  (let* ((source (read-source path))
         (tokens (lex-source source))
         (program (parse-program source tokens)))
    (check-program program)))

(defun checked-project (project)
  (check-program (mognitio.project::project-program (mognitio.project::resolve-project project))))

(defun run-pipeline (argv stdout &optional (stderr *error-output*))
  (multiple-value-bind (command manifest output target) (parse-invocation argv)
    (when (string= command "test")
      (return-from run-pipeline (mognitio.testing::run-tests manifest stdout stderr)))
    (let ((project (mognitio.project::load-project manifest)))
      (when output (mognitio.project::validate-project-output project output))
      (let ((checked (checked-project project)))
        (if (string= command "run")
            (execute-program (compile-program checked))
            (let* ((image (mognitio.backend.native:compile-program checked target))
                   (mognitio.artifact::*project-validation*
                     (lambda () (mognitio.project::validate-project-output project output))))
              (mognitio.artifact:publish-image image manifest output))))))
  0)

(defun run-cli (argv stdout stderr)
  (labels ((report-failure (diagnostic code)
             ;; A broken diagnostic stream must not cause recursive reporting.
             (handler-case (progn (render-diagnostic diagnostic stderr) code)
               ((or error storage-condition) () 3))))
    (handler-case (run-pipeline argv stdout stderr)
      (mognitio.runtime::program-assertion (condition) (mognitio.runtime::write-assertion condition stderr))
      (mognitio.runtime::program-panic (condition) (mognitio.runtime::write-panic condition stderr))
      (mognitio.runtime:program-runtime-failure (condition)
        (mognitio.runtime:write-runtime-failure condition stderr))
      (source-failure (condition)
        (report-failure (failure-diagnostic condition) 1))
      (usage-or-io-failure (condition)
        (report-failure (failure-diagnostic condition) 2))
      (internal-failure (condition)
        (report-failure (failure-diagnostic condition) 3))
      (storage-condition ()
        (report-failure (make-diagnostic :phase :internal :message "Compiler storage failure") 3))
      (error ()
        (report-failure (make-diagnostic :phase :internal
                                         :message "Unexpected compiler failure") 3)))))
