(in-package #:mognitio.ir)

(defvar *loop-contexts* nil)
(defun lower-loop-node (node checked block env lower emit new-block new-value)
  (labels ((fresh () (funcall new-block (node-span node)))
           (value (where type op &key data operands)
             (funcall emit where type op (node-span node) :value data :operands operands))
           (lookup (id bindings) (or (cdr (assoc id bindings)) (internal-error "Missing loop binding"))))
    (let* ((target (loop-expression-target node)) (binder (loop-expression-binder node))
           (info (checked-loop checked node)) (body (loop-expression-body node))
           (buffer nil) (length-value nil))
      (when target
        (multiple-value-bind (snapshot end updated) (funcall lower target block env)
          (unless end (return-from lower-loop-node (values nil nil nil)))
          (setf block end env updated
                buffer (value block (list :buffer (local-symbol-type (checked-symbol checked binder))) :list.buffer :operands (list snapshot))
                length-value (value block :int :buffer.length :operands (list buffer)))))
      (let* ((ids (sort (remove-duplicates
                    (remove-if-not (lambda (id) (eq :var (local-symbol-mutability (aref (checked-program-bindings checked) id))))
                                   (mapcar #'car env))) #'<))
             (header (fresh)) (exit (when (checked-normal-type checked node) (fresh)))
             (result (when exit (funcall new-value)))
             (header-env env) (exit-env env) (step-env env)
             (body-flow (checked-completion checked body))
             (step (when (and target (or (completion-normal-type body-flow)
                                        (find-if (lambda (e) (and (eq :continue (first e)) (= (second e) (loop-info-id info))))
                                                 (completion-exits body-flow)))) (fresh)))
             (index (when target (funcall new-value))) (context (list (loop-info-id info) (if target step header) exit ids result)))
        (dolist (id ids)
          (let ((type (local-symbol-type (aref (checked-program-bindings checked) id))) (parameter (funcall new-value)))
            (setf (basic-block-parameters header) (append (basic-block-parameters header) (list (cons parameter type)))
                  header-env (acons id parameter header-env)))
          (when step
            (let ((p (funcall new-value)) (type (local-symbol-type (aref (checked-program-bindings checked) id))))
              (setf (basic-block-parameters step) (append (basic-block-parameters step) (list (cons p type))) step-env (acons id p step-env)))))
        (when target (setf (basic-block-parameters header) (append (basic-block-parameters header) (list (cons index :int)))))
        (when exit
          (setf (basic-block-parameters exit) (list (cons result :void)))
          (dolist (id ids)
            (let ((p (funcall new-value)) (type (local-symbol-type (aref (checked-program-bindings checked) id))))
              (setf (basic-block-parameters exit) (append (basic-block-parameters exit) (list (cons p type))) exit-env (acons id p exit-env)))))
        (setf (basic-block-terminator block) (list :jump (basic-block-id header)
                (append (mapcar (lambda (id) (lookup id env)) ids) (when target (list (value block :int :constant :data 0))))))
        (multiple-value-bind (condition end updated)
            (if target (values (value header :bool :lt :operands (list index length-value)) header header-env)
                (funcall lower (loop-expression-condition node) header header-env))
          (when end
            (let ((yes (fresh)) (no (fresh)))
              (setf (basic-block-terminator end) (list :branch condition (basic-block-id yes) (basic-block-id no))
                    (basic-block-terminator no) (list :jump (basic-block-id exit)
                      (cons (value no :void :constant :data 0) (mapcar (lambda (id) (lookup id updated)) ids))))
              (when target
                (setf updated (acons (local-symbol-id (checked-symbol checked binder))
                                    (value yes (local-symbol-type (checked-symbol checked binder)) :buffer.get :operands (list buffer index)) updated)))
              (let ((*loop-contexts* (cons context *loop-contexts*)))
                (multiple-value-bind (body-value body-end body-env) (funcall lower body yes updated)
                  (declare (ignore body-value))
                  (when body-end
                    (setf (basic-block-terminator body-end)
                          (list :jump (basic-block-id (second context)) (mapcar (lambda (id) (lookup id body-env)) ids)))))))))
        (when step
          (setf (basic-block-terminator step)
                (list :jump (basic-block-id header)
                  (append (mapcar (lambda (id) (lookup id step-env)) ids)
                          (list (value step :int :add :operands (list index (value step :int :constant :data 1))))))))
        (if exit (values result exit exit-env) (values nil nil nil))))))
(defun lower-short-circuit (node checked block env lower emit new-block new-value)
  ;; Reuse the branch join, preserving right-hand effects only on its edge.
  (let* ((and-p (eq :and (token-kind (binary-expression-operator node))))
         (left (binary-expression-left node))
         (constant (make-boolean-literal :value (if and-p :false :true) :span (node-span node)))
         (branch (make-branch-expression :mode :when :span (node-span node)
                   :arms (vector (make-branch-arm :selector left :value (if and-p (binary-expression-right node) constant))
                                 (make-branch-arm :selector nil :value (if and-p constant (binary-expression-right node)))))))
    (lower-value-branch branch checked block env lower emit new-block new-value :bool)))
