(in-package #:mognitio.ir)

(defun verify-io-instruction (instruction types context caller functions)
  (let* ((operation (instruction-value instruction)) (result (instruction-type instruction))
         (args (mognitio.semantic::canonical-result-arguments context result))
         (error-type (second args))
         (error-info (when (nominal-type-p error-type :struct) (context-type context error-type)))
         (function (gethash caller functions)))
    (labels ((sum-shape (type name variants)
               (when (nominal-type-p type :enum)
                 (let ((info (context-type context type)))
                   (and (equal (type-info-name info) name)
                        (equal (mapcar #'variant-info-name (type-info-variants info)) variants)
                        (every (lambda (variant) (null (variant-info-types variant))) (type-info-variants info)))))))
      (and (member operation '(:read-file :write-file :read-stdin :write-stdout :write-stderr :join-path :read-directory :create-directory))
           function (plusp caller) (null (ir-function-method function)) (null (ir-function-capture-types function))
           (equal (ir-function-result-type function) result)
           (equal (rest (ir-function-parameter-types function)) types)
           (equal types (case operation (:read-file '(:string)) ((:write-file :join-path) '(:string :string))
                          (:read-stdin nil) (otherwise '(:string))))
           (let ((success (first args)))
             (case operation
               ((:read-file :read-stdin :join-path) (eq success :string))
               (:read-directory
                (and (mognitio.semantic:list-type-p success)
                     (nominal-type-p (second success) :struct)
                     (let* ((entry (context-type context (second success))) (fields (type-info-fields entry)))
                       (and (equal (type-info-name entry) "standard:Std\\Io#DirectoryEntry")
                            (equal (mapcar #'car fields) '("name" "kind"))
                            (eq (cdar fields) :string)
                            (sum-shape (cdr (second fields)) "standard:Std\\Io#DirectoryEntryKind"
                                       '("File" "Directory" "Symlink" "Other"))))))
               (otherwise (eq success :void))))
           error-info (equal (type-info-name error-info) "standard:Std\\Io#IoError")
           (let ((fields (type-info-fields error-info)))
             (and (equal (mapcar #'car fields) '("operation" "kind" "subject"))
                  (eq (cdar (last fields)) :string)
                  (sum-shape (cdar fields) "standard:Std\\Io#IoOperation"
                             '("ReadTextFile" "WriteTextFile" "ReadStdin" "WriteStdout" "WriteStderr" "JoinPath" "ReadDirectory" "CreateDirectory"))
                  (sum-shape (cdr (second fields)) "standard:Std\\Io#IoErrorKind"
                             '("InvalidPath" "InvalidEncoding" "NotFound" "PermissionDenied" "UnsupportedTarget" "BrokenPipe" "ResourceExhausted" "Other"))))))))
