(in-package #:mognitio.ir)

(defun verify-io-instruction (instruction types context caller functions)
  (let* ((operation (instruction-value instruction)) (result (instruction-type instruction))
         (args (mognitio.semantic::canonical-result-arguments context result))
         (error-type (second args))
         (error-info (when (nominal-type-p error-type :struct) (context-type context error-type)))
         (function (gethash caller functions)))
    (labels ((sum-shape (type name variants)
               (when (nominal-type-p type :enum)
                 (let ((info (context-type context type)))
                   (and (equal (type-info-name info) name)
                        (equal (mapcar #'variant-info-name (type-info-variants info)) variants)
                        (every (lambda (variant) (null (variant-info-types variant))) (type-info-variants info)))))))
      (and (member operation '(:read-file :write-file :read-stdin :write-stdout :write-stderr))
           function (plusp caller) (null (ir-function-method function)) (null (ir-function-capture-types function))
           (equal (ir-function-result-type function) result)
           (equal (rest (ir-function-parameter-types function)) types)
           (equal types (case operation (:read-file '(:string)) (:write-file '(:string :string))
                          (:read-stdin nil) (otherwise '(:string))))
           (equal (first args) (if (member operation '(:read-file :read-stdin)) :string :void))
           error-info (equal (type-info-name error-info) "standard:Std\\Io#IoError")
           (let ((fields (type-info-fields error-info)))
             (and (equal (mapcar #'car fields) '("operation" "kind" "subject"))
                  (eq (cdar (last fields)) :string)
                  (sum-shape (cdar fields) "standard:Std\\Io#IoOperation"
                             '("ReadTextFile" "WriteTextFile" "ReadStdin" "WriteStdout" "WriteStderr"))
                  (sum-shape (cdr (second fields)) "standard:Std\\Io#IoErrorKind"
                             '("InvalidPath" "InvalidEncoding" "NotFound" "PermissionDenied" "UnsupportedTarget" "BrokenPipe" "ResourceExhausted" "Other"))))))))
