(in-package #:mognitio.ir)

(defparameter *value-operations* '(:bytes.from-ints :bytes.from-bits :bytes.length :bytes.at :bytes.append :bytes.concat :bytes.slice :bytes.to-bits :bits.to-bytes :bytes.equal :bytes.not-equal :integer.convert :integer.to-bits :bits.integer :bits.length :bits.and :bits.or :bits.xor :bits.not :bits.left :bits.right :bits.at :numeric :io.call :struct.make :enum.make :struct.field :enum.tag :enum.payload :interface.pack :call.interface
    :closure.make :closure.env.get :closure.call :list.empty :list.length :list.append :list.at :list.buffer :buffer.length :buffer.get :text.scalars :text.join :text.slice.result))

(defun verify-core-types (context functions)
  (let ((types (value-context-types context)))
    (labels ((valid (type &optional bound)
               (declare (ignore bound))
               (and (not (mognitio.semantic::symbolic-type-p type)) (valid-value-type-p type)
                    (cond ((function-type-p type)
                           (and (every #'valid (second type)) (valid (third type))))
                          ((list-type-p type) (valid (second type)))
                          ((nominal-type-p type)
                           (and (typep (second type) '(integer 0 *)) (< (second type) (length types))
                                (equal type (canonical-type (aref types (second type))))))
                          (t t))))
             (data (type bound) (valid type bound)))
      (loop for info across types for id from 0 do
        (unless (and (= id (type-info-id info)) (member (type-info-kind info) '(:struct :enum :interface))) (internal-error "Invalid Core type identity"))
        (ecase (type-info-kind info)
          (:struct
           (let ((fields (type-info-fields info)))
             (unless (and (null (type-info-variants info)) (null (type-info-methods info))
                          (= (length fields) (length (remove-duplicates fields :key #'car :test #'string=)))
                          (every (lambda (x) (data (cdr x) id)) fields)) (internal-error "Invalid Core struct"))))
          (:enum
           (let ((variants (type-info-variants info)))
             (unless (and variants (null (type-info-fields info)) (null (type-info-methods info))
                          (= (length variants) (length (remove-duplicates variants :key #'variant-info-name :test #'string=))))
               (internal-error "Invalid Core enum"))
             (loop for variant in variants for index from 0 do
               (unless (and (= index (variant-info-id variant)) (<= (length (variant-info-types variant)) 1) (every (lambda (x) (data x id)) (variant-info-types variant)))
                 (internal-error "Invalid Core payload")))))
          (:interface
           (let ((methods (type-info-methods info)))
             (unless (and (null (type-info-fields info)) (null (type-info-variants info))
                          (= (length methods) (length (remove-duplicates methods :key #'requirement-name :test #'string=)))
                          (every (lambda (x) (and (valid (requirement-result x) id)
                                                 (every (lambda (t1) (valid t1 id)) (requirement-parameters x)))) methods))
               (internal-error "Invalid Core interface"))))))
      ;; Runtime IDs follow canonical keys, not dependency order. Validate the
      ;; complete graph independently instead of assuming every edge points back.
      (let ((edges (make-hash-table)))
        (loop for info across types for id from 0 do
          (dolist (type (append (mapcar #'cdr (type-info-fields info))
                               (mapcan (lambda (variant) (copy-list (variant-info-types variant))) (type-info-variants info))
                               (mapcan (lambda (method) (cons (requirement-result method) (copy-list (requirement-parameters method)))) (type-info-methods info))))
            (labels ((walk (part)
                       (cond ((nominal-type-p part) (push (cons (second part) nil) (gethash id edges)))
                             ((function-type-p part) (mapc #'walk (second part)) (walk (third part)))
                             ((list-type-p part) (walk (second part))))))
              (walk type))))
        (check-call-graph (loop for id below (length types) collect id) edges
                          (lambda (span) (declare (ignore span)) (internal-error "Recursive Core type graph"))))
      (let ((pairs nil))
        (loop for implementation across (value-context-implementations context) for id from 0
              for concrete = (implementation-info-concrete implementation) for contract = (implementation-info-contract implementation)
              for methods = (implementation-info-methods implementation) do
          (unless (and (= id (implementation-info-id implementation)) (valid concrete)
                       (or (null contract) (and (valid contract) (nominal-type-p contract :interface)))
                       (not (member (list concrete contract) pairs :test #'equal))
                       (= (length methods) (length (remove-duplicates methods :key #'car :test #'string=))))
            (internal-error "Invalid Core implementation"))
          (push (list concrete contract) pairs)
          (when contract
            (unless (= (length methods) (length (type-info-methods (context-type context contract)))) (internal-error "Incomplete Core table")))
          (dolist (pair methods)
            (let* ((sig (cdr pair)) (callee (gethash (signature-id sig) functions))
                   (requirement (when contract (find (car pair) (type-info-methods (context-type context contract)) :key #'requirement-name :test #'string=))))
              (unless (and callee (equal (ir-function-method callee) (list concrete contract (car pair)))
                           (equal (ir-function-parameter-types callee) (cons concrete (signature-parameter-types sig)))
                           (equal (ir-function-result-type callee) (signature-result-type sig))
                           (or (null contract) (and requirement (equal (rest (ir-function-parameter-types callee)) (requirement-parameters requirement))
                                                    (equal (ir-function-result-type callee) (requirement-result requirement)))))
                (internal-error "Invalid Core method signature"))))))
      (maphash (lambda (id function)
                 (declare (ignore id))
                 (unless (and (valid (ir-function-result-type function)) (every #'valid (ir-function-parameter-types function)) (every #'valid (ir-function-capture-types function)))
                   (internal-error "Unknown Core signature type"))) functions))))

(defun verify-value-instruction (instruction types context functions id pos defs blocks dom edges caller)
  (declare (ignore pos))
  (let ((op (instruction-op instruction)) (data (instruction-value instruction))
        (result (instruction-type instruction)) (operands (instruction-operands instruction)))
    (labels ((type-info (type) (context-type context type))
             (defined-instruction (value)
               (let ((definition (gethash value defs)))
                 (when (and definition (>= (second definition) 0))
                   (nth (second definition) (basic-block-instructions (gethash (first definition) blocks))))))
             (bounded-index (index)
               (let* ((definition (gethash index defs))
                      (header (when definition (gethash (first definition) blocks)))
                      (position (when header (position index (basic-block-parameters header) :key #'car)))
                      (initial nil) (incoming nil))
                 (and definition (= (second definition) -1) position
                   (loop for predecessor being the hash-values of blocks
                         for term = (basic-block-terminator predecessor)
                         always
                     (or (not (member (basic-block-id header) (successors predecessor)))
                         (and (eq (first term) :jump)
                              (let* ((argument (nth position (third term)))
                                     (value (defined-instruction argument)))
                                (setf incoming t)
                                (and value
                                  (or (and (eq (instruction-op value) :constant)
                                           (eql (instruction-value value) 0) (setf initial t))
                                      (and (eq (instruction-op value) :add)
                                           (eql (first (instruction-operands value)) index)
                                           (let ((one (defined-instruction (second (instruction-operands value)))))
                                             (and one (eq (instruction-op one) :constant)
                                                  (eql (instruction-value one) 1))))))))))
                   incoming initial)))
             (guarded (subject variant)
               (loop for block being the hash-values of blocks for term = (basic-block-terminator block)
                     thereis
                 (and (eq :branch (first term)) (not (eql (third term) (fourth term)))
                      (member (third term) (gethash id dom))
                      (equal (loop for predecessor being the hash-values of blocks
                                   when (member (third term) (successors predecessor))
                                   collect (basic-block-id predecessor))
                             (list (basic-block-id block)))
                      (let ((comparison (defined-instruction (second term))))
                        (and comparison (eq :eq (instruction-op comparison))
                             (loop for pair in (list (instruction-operands comparison) (reverse (instruction-operands comparison)))
                                   thereis
                               (let ((tag (defined-instruction (first pair))) (constant (defined-instruction (second pair))))
                                 (and tag constant (eq :enum.tag (instruction-op tag)) (equal (list subject) (instruction-operands tag))
                                      (eq :constant (instruction-op constant)) (eql variant (instruction-value constant)))))))))))
      (case op
        ((:bytes.from-ints :bytes.from-bits :bytes.length :bytes.at :bytes.append :bytes.concat :bytes.slice :bytes.to-bits :bits.to-bytes :bytes.equal :bytes.not-equal) (verify-binary-instruction instruction types context))
        ((:integer.convert :integer.to-bits :bits.integer :bits.length :bits.and :bits.or :bits.xor :bits.not :bits.left :bits.right :bits.at) (verify-numeric-method-instruction op data result types context))
        (:numeric
         (and (listp data) (= 2 (length data))
              (let* ((kind (first data)) (type (second data)) (unary (eq kind :neg)))
                (and (mognitio.semantic::numeric-scalar-p type)
                     (not (mognitio.semantic::symbolic-type-p type))
                     (mognitio.semantic::numeric-operator-p type (if unary :sub kind) unary)
                     (= (length types) (if unary 1 2)) (every (lambda (x) (equal x type)) types)
                     (equal result (if (member kind '(:eq :ne :lt :le :gt :ge)) :bool type))))))
        (:io.call (verify-io-instruction instruction types context caller functions))
        (:closure.make
         (let ((target (gethash data functions)))
           (and target (plusp data) (null (ir-function-method target))
                (equal result (first (ir-function-parameter-types target)))
                (equal result (list :function (rest (ir-function-parameter-types target)) (ir-function-result-type target)))
                (equal types (ir-function-capture-types target)))))
        (:closure.env.get
         (let* ((target (gethash caller functions)) (definition (gethash (first operands) defs)))
           (and (= (length types) 1) (= (length data) 2) (= caller (first data))
                (null (ir-function-method target)) (equal (first types) (first (ir-function-parameter-types target)))
                (typep (second data) '(integer 0 *)) (< (second data) (length (ir-function-capture-types target)))
                (equal result (nth (second data) (ir-function-capture-types target)))
                (= (first definition) (ir-function-entry target)) (= (second definition) -1)
                (= (first operands) (caar (basic-block-parameters (gethash (ir-function-entry target) blocks)))))))
        (:closure.call
         (and (function-type-p data) (equal (first types) data) (equal (rest types) (second data)) (equal result (third data))))
        (:text.scalars (and (equal result '(:list :string)) (equal types '(:string)) (null data)))
        (:text.join (and (eq result :string) (equal types '((:list :string) :string)) (null data)))
        (:list.empty (and (list-type-p result) (null data) (null types)))
        (:list.length (and (= (length types) 1) (list-type-p (first types)) (eq result :int) (null data)))
        (:list.append (and (list-type-p result) (equal types (list result (second result))) (null data)))
        (:list.at
         (and (= (length types) 2) (list-type-p (first types)) (eq :int (second types)) (null data)
              (let ((arguments (mognitio.semantic::canonical-result-arguments context result)))
                (and arguments (equal (first arguments) (second (first types)))
                     (let ((error (context-type context (second arguments))))
                       (and (string= "IndexError" (type-info-name error))
                            (equal (type-info-fields error) '(("index" . :int) ("length" . :int)))))))))
        (:text.slice.result
         (and (equal types '(:string :int :int)) (null data)
              (let ((arguments (mognitio.semantic::canonical-result-arguments context result)))
                (and (eq :string (first arguments))
                     (let ((error (context-type context (second arguments))))
                       (and (string= "SliceError" (type-info-name error))
                            (equal (type-info-fields error) '(("start" . :int) ("end" . :int) ("length" . :int)))))))))
        (:list.buffer (and (= (length types) 1) (list-type-p (first types)) (equal result (list :buffer (second (first types)))) (null data)))
        (:buffer.length (and (= (length types) 1) (eq :buffer (first (first types))) (eq :int result) (null data)))
        (:buffer.get
         (and (= (length types) 2) (eq :buffer (first (first types))) (eq :int (second types))
              (equal result (second (first types))) (null data) (bounded-index (second operands))
              (loop for predecessor being the hash-values of blocks for term = (basic-block-terminator predecessor)
                    thereis (and (eq :branch (first term)) (member (third term) (gethash id dom))
                                 (not (eql (third term) (fourth term)))
                                 (equal (loop for p being the hash-values of blocks
                                              when (member (third term) (successors p)) collect (basic-block-id p))
                                        (list (basic-block-id predecessor)))
                                 (let* ((test (defined-instruction (second term)))
                                        (size (when test (defined-instruction (second (instruction-operands test))))))
                                   (and test size (eq :lt (instruction-op test))
                                        (= (first (instruction-operands test)) (second operands))
                                        (eq :buffer.length (instruction-op size))
                                        (equal (instruction-operands size) (list (first operands)))))))))
        (:struct.make
         (and (nominal-type-p result :struct)
              (let ((fields (type-info-fields (type-info result))))
                (and (= (length types) (length fields) (length data))
                     (equal (sort (copy-list data) #'<) (loop for n below (length fields) collect n))
                     (equal types (mapcar (lambda (index) (cdr (nth index fields))) data))))))
        (:enum.make
         (and (nominal-type-p result :enum) (typep data '(integer 0 *))
              (let ((variant (nth data (type-info-variants (type-info result))))) (and variant (equal types (variant-info-types variant))))))
        (:struct.field
         (and (= 1 (length types)) (nominal-type-p (first types) :struct) (typep data '(integer 0 *))
              (let ((field (nth data (type-info-fields (type-info (first types)))))) (and field (equal result (cdr field))))))
        (:enum.tag (and (null data) (= 1 (length types)) (nominal-type-p (first types) :enum) (eq result :int)))
        (:enum.payload
         (and (= 1 (length types)) (= 3 (length data)) (equal (first types) (first data)) (nominal-type-p (first data) :enum)
              (typep (second data) '(integer 0 *)) (typep (third data) '(integer 0 *))
              (let* ((variant (nth (second data) (type-info-variants (type-info (first data)))))
                     (slot (when variant (nth (third data) (variant-info-types variant)))))
                (and slot (equal result slot) (guarded (first operands) (second data))))))
        (:interface.pack
         (and (= 1 (length types)) (typep data '(integer 0 *)) (< data (length (value-context-implementations context)))
              (let ((implementation (aref (value-context-implementations context) data)))
                (and (equal (first types) (implementation-info-concrete implementation))
                     (equal result (implementation-info-contract implementation)) (nominal-type-p result :interface)))))
        (:call.interface
         (and (= 3 (length data)) (equal (first types) (first data)) (nominal-type-p (first data) :interface)
              (typep (second data) '(integer 0 *))
              (let* ((requirement (nth (second data) (type-info-methods (type-info (first data)))))
                     (targets (when requirement
                                (loop for implementation across (value-context-implementations context)
                                      when (equal (first data) (implementation-info-contract implementation))
                                        collect (signature-id (cdr (assoc (requirement-name requirement) (implementation-info-methods implementation) :test #'string=)))))))
                (and requirement (equal (rest types) (requirement-parameters requirement)) (equal result (requirement-result requirement))
                     (= (length targets) (length (third data))) (subsetp targets (third data)) (subsetp (third data) targets)
                     (every (lambda (target) (push (cons target (instruction-span instruction)) (gethash caller edges)) (gethash target functions)) targets)))))
        (otherwise nil)))))

(defun verify-numeric-method-instruction (op source result types context)
  (let* ((parts (mognitio.semantic::canonical-result-arguments context result))
         (success (first parts)) (error (second parts))
         (bits (mognitio.semantic::bits-type-p source)))
    (labels ((error-is (name fields)
               (and (nominal-type-p error :struct)
                    (let ((info (context-type context error)))
                      (and (equal name (type-info-name info)) (equal fields (type-info-fields info))))))
             (args (&rest rest) (equal types (cons source rest))))
      (and (equal source (first types))
           (case op
             (:integer.convert
              (and (mognitio.semantic::integer-type-p source) (mognitio.semantic::integer-type-p success)
                   (args) (error-is "standard:Std\\Numeric#IntegerConversionError" nil)))
             (:integer.to-bits
              (and (mognitio.semantic::integer-type-p source) (args)
                   (equal result (list :bits (mognitio.semantic::integer-width source)))))
             (:bits.integer
              (and bits (args) (mognitio.semantic::fixed-integer-p result) (equal (second result) (second source))))
             (:bits.length (and bits (args) (eq result :int)))
             ((:bits.and :bits.or :bits.xor) (and bits (args source) (equal source result)))
             (:bits.not (and bits (args) (equal source result)))
             ((:bits.left :bits.right)
              (and bits (args :int) (equal success source)
                   (error-is "standard:Std\\Numeric#BitShiftError" '(("count" . :int) ("width" . :int)))))
             (:bits.at
              (and bits (args :int) (eq success :bool)
                   (error-is "IndexError" '(("index" . :int) ("length" . :int))))))))))
