(defpackage #:mognitio.json (:use #:cl) (:export #:decode #:encode #:object #:get-field))
(in-package #:mognitio.json)
(defun object (&rest pairs)
  (let ((result (make-hash-table :test #'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key result) value)) result))
(defun get-field (object name &optional default)
  (if (hash-table-p object) (gethash name object default) default))
(defun decode (text)
  (let ((i 0) (n (length text)) (depth 0))
    (declare (special depth))
    (labels ((bad () (error "Invalid JSON"))
             (peek () (when (< i n) (char text i)))
             (space () (loop while (and (peek) (find (peek) '(#\Space #\Tab #\Return #\Newline))) do (incf i)))
             (take (c) (unless (eql (peek) c) (bad)) (incf i))
             (hex4 ()
               (let ((value 0))
                 (dotimes (k 4)
                   (unless (peek) (bad))
                   (let ((digit (digit-char-p (char text i) 16)))
                     (unless digit (bad)) (incf i) (setf value (+ (* value 16) digit))))
                 value))
             (string-value ()
               (take #\")
               (with-output-to-string (s)
                 (loop
                   (unless (peek) (bad))
                   (let ((c (char text i)))
                     (incf i)
                     (cond ((char= c #\") (return))
                           ((< (char-code c) 32) (bad))
                           ((char= c #\\)
                            (unless (peek) (bad))
                            (let ((e (char text i))) (incf i)
                              (case e
                                (#\u (let ((code (hex4)))
                                       (when (<= #xd800 code #xdbff)
                                         (take #\\) (take #\u)
                                         (let ((low (hex4)))
                                           (unless (<= #xdc00 low #xdfff) (bad))
                                           (setf code (+ #x10000 (ash (- code #xd800) 10) (- low #xdc00)))))
                                       (when (<= #xd800 code #xdfff) (bad))
                                       (write-char (or (code-char code) (bad)) s)))
                                (otherwise
                                 (let ((entry (assoc e '((#\" . #\") (#\\ . #\\) (#\/ . #\/)
                                               (#\b . #\Backspace) (#\f . #\Page)
                                               (#\n . #\Newline) (#\r . #\Return) (#\t . #\Tab)))))
                                   (unless entry (bad)) (write-char (cdr entry) s))))))
                           (t (write-char c s)))))))
             (literal (word result)
               (unless (and (<= (+ i (length word)) n)
                            (string= word text :start2 i :end2 (+ i (length word)))) (bad))
               (incf i (length word)) result)
             (value ()
               (space)
               (let ((depth (1+ depth)))
                 (declare (special depth))
                 (when (> depth 128) (bad))
                 (case (peek)
                   (#\" (string-value))
                   (#\{ (incf i) (space)
                    (let ((result (object)))
                      (unless (eql (peek) #\})
                        (loop
                          (space) (let ((key (string-value)))
                            (space) (take #\:)
                            (when (nth-value 1 (gethash key result)) (bad))
                            (setf (gethash key result) (value)))
                          (space) (unless (eql (peek) #\,) (return)) (incf i)))
                      (take #\}) result))
                   (#\[ (incf i) (space)
                    (let ((result nil))
                      (unless (eql (peek) #\])
                        (loop (push (value) result) (space)
                              (unless (eql (peek) #\,) (return)) (incf i)))
                      (take #\]) (coerce (nreverse result) 'vector)))
                   (#\t (literal "true" :true)) (#\f (literal "false" :false))
                   (#\n (literal "null" nil))
                   (otherwise
                    (let ((start i))
                      (when (eql (peek) #\-) (incf i))
                      (unless (and (peek) (digit-char-p (peek))) (bad))
                      (if (eql (peek) #\0) (incf i)
                          (loop while (and (peek) (digit-char-p (peek))) do (incf i)))
                      ;; Internal IPC accepts integral counters only.
                      (parse-integer text :start start :end i)))))))
      (let ((result (value))) (space) (unless (= i n) (bad)) result))))
(defun encode (value)
  (with-output-to-string (out)
    (labels ((quoted (s)
               (write-char #\" out)
               (loop for c across s do
                 (case c
                   (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
                   (#\Newline (write-string "\\n" out)) (#\Return (write-string "\\r" out))
                   (#\Tab (write-string "\\t" out))
                   (otherwise (if (< (char-code c) 32) (format out "\\u~4,'0X" (char-code c))
                                  (write-char c out)))))
               (write-char #\" out))
             (emit (x)
               (cond ((null x) (write-string "null" out))
                     ((eq x :true) (write-string "true" out))
                     ((eq x :false) (write-string "false" out))
                     ((stringp x) (quoted x))
                     ((integerp x) (princ x out))
                     ((hash-table-p x)
                      (write-char #\{ out)
                      (let ((first t))
                        (maphash (lambda (k v) (unless first (write-char #\, out))
                                   (setf first nil) (quoted k) (write-char #\: out) (emit v)) x))
                      (write-char #\} out))
                     ((vectorp x) (write-char #\[ out)
                      (loop for v across x for i from 0 do (when (> i 0) (write-char #\, out)) (emit v))
                      (write-char #\] out))
                     (t (error "Unsupported JSON value")))))
      (emit value))))
