(in-package #:mognitio.frontend)

(defun ascii-letter-p (ch)
  (or (char<= #\A ch #\Z) (char<= #\a ch #\z)))
(defun ascii-digit-p (ch) (char<= #\0 ch #\9))
(defun word-start-p (ch) (or (ascii-letter-p ch) (char= ch #\_)))
(defparameter *keywords*
  '(("assert" . :assert) ("namespace" . :namespace) ("use" . :use) ("public" . :public) ("alias" . :alias) ("implements" . :implements) ("as" . :as) ("branch" . :branch) ("break" . :break) ("continue" . :continue) ("contract" . :contract) ("discard" . :discard) ("else" . :else) ("function" . :function) ("witness" . :witness) ("let" . :let) ("loop" . :loop) ("on" . :on) ("over" . :over) ("panic" . :panic) ("product" . :product) ("return" . :return) ("sum" . :sum) ("template" . :template) ("try" . :try) ("type" . :type) ("var" . :var) ("when" . :when) ("while" . :while) ("true" . :true) ("false" . :false) ("unit" . :unit)))
(defparameter *operators*
  '(("#" . :hash) ("@" . :at) ("\\" . :backslash) ("&&" . :and) ("||" . :or) ("::" . :scope) ("=>" . :fat-arrow) ("->" . :arrow) ("==" . :eq) ("!=" . :ne) ("<=" . :le) (">=" . :ge)
    ("!" . :not) ("." . :dot) ("[" . :left-bracket) ("]" . :right-bracket)
    ("=" . :assign) ("+" . :add) ("-" . :sub) ("*" . :mul)
    ("/" . :div) ("%" . :rem) ("<" . :lt) (">" . :gt)
    ("(" . :left-paren) (")" . :right-paren)
    ("{" . :left-brace) ("}" . :right-brace) (";" . :semicolon) ("," . :comma) (":" . :colon)))
(defun lex-source (source &key recover)
  (let ((text (source-text source)) (cursor 0)
        (tokens (make-array 0 :adjustable t :fill-pointer 0)) (errors nil))
    (labels ((emit (kind start &optional payload)
               (vector-push-extend
                (make-token :kind kind :span (make-span source start cursor) :payload payload) tokens))
             (scan-unicode-escape (start)
               ;; Cursor follows the 'u'; consume braces and exactly 1..6 hex digits.
               (labels ((invalid ()
                          (fail-at (make-span source start cursor) :lex "Invalid Unicode escape")))
                 (unless (and (< cursor (length text)) (char= (char text cursor) #\{))
                   (invalid))
                 (incf cursor)
                 (let ((value 0) (digits 0))
                   (loop
                     (when (= cursor (length text)) (invalid))
                     (let ((ch (char text cursor)))
                       (incf cursor)
                       (when (char= ch #\}) (return))
                       (let ((digit (and (find ch "0123456789abcdefABCDEF")
                                         (digit-char-p ch 16))))
                         (unless (and digit (< digits 6)) (invalid))
                         (setf value (+ (* value 16) digit))
                         (incf digits))))
                   (unless (and (plusp digits) (<= value #x10ffff)
                                (not (<= #xd800 value #xdfff)))
                     (invalid))
                   (or (code-char value) (internal-error "Host cannot represent Unicode scalar")))))
             (scan-string ()
               (let ((start cursor) (chars (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
                 (incf cursor)
                 (loop
                   (when (= cursor (length text))
                     (fail-at (make-span source start (1+ start)) :lex "Unterminated string literal"))
                   (let ((ch (char text cursor)) (at cursor))
                     (incf cursor)
                     (cond
                       ((char= ch #\") (return))
                       ((char= ch #\\)
                        (when (= cursor (length text))
                          (fail-at (make-span source start (1+ start)) :lex "Unterminated string literal"))
                        (let ((escape (char text cursor)))
                          (incf cursor)
                          (let ((value (case escape
                                         (#\" #\") (#\\ #\\) (#\n #\Newline)
                                         (#\r #\Return) (#\t #\Tab) (#\0 (code-char 0))
                                         (#\u (scan-unicode-escape at)))))
                            (unless value (fail-at (make-span source at cursor) :lex "Invalid string escape"))
                            (vector-push-extend value chars))))
                       ((find ch '(#\Newline #\Return))
                        (fail-at (make-span source at cursor) :lex "Raw newline in string literal"))
                       (t (vector-push-extend ch chars)))))
                 (emit :string-literal start
                       (make-text-payload :octets (sb-ext:string-to-octets chars :external-format :utf-8)
                                          :scalar-count (length chars))))))
      (loop while (< cursor (length text)) for ch = (char text cursor) for before = cursor do
        (handler-case
        (cond
          ((find ch '(#\Space #\Tab #\Newline #\Return)) (incf cursor))
          ((and (char= ch #\/) (< (1+ cursor) (length text))
                (char= (char text (1+ cursor)) #\/))
           (incf cursor 2)
           (loop while (and (< cursor (length text))
                            (not (find (char text cursor) '(#\Newline #\Return))))
                 do (incf cursor)))
          ((char= ch #\") (scan-string))
          ((word-start-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text))
                              (or (word-start-p (char text cursor))
                                  (ascii-digit-p (char text cursor))))
                   do (incf cursor))
             (emit (or (cdr (assoc (subseq text start cursor) *keywords* :test #'string=))
                       :identifier) start)))
          ((ascii-digit-p ch)
           (let ((start cursor))
             (loop while (and (< cursor (length text)) (ascii-digit-p (char text cursor)))
                   do (incf cursor))
             (when (and (< cursor (length text)) (word-start-p (char text cursor)))
               (fail-at (make-span source start (1+ cursor)) :lex "Invalid decimal boundary"))
             (when (and (char= ch #\0) (> (- cursor start) 1))
               (fail-at (make-span source start cursor) :lex "Leading zero in decimal literal"))
             (emit :integer start)))
          (t
           (let ((entry (find-if
                         (lambda (pair)
                           (let ((end (+ cursor (length (car pair)))))
                             (and (<= end (length text))
                                  (string= (car pair) text :start2 cursor :end2 end))))
                         *operators*))
                 (start cursor))
             (unless entry
               (fail-at (make-span source cursor (1+ cursor)) :lex "Undefined character"))
             (incf cursor (length (car entry)))
             (emit (cdr entry) start))))
          (source-failure (condition)
            (unless recover (error condition))
            (when (< (length errors) 200) (push (failure-diagnostic condition) errors))
            (setf cursor (min (length text) (max cursor (1+ before)))))))
      (emit :eof cursor))
    (values tokens (nreverse errors))))
