(in-package #:mognitio.machine)

(defstruct instruction opcode operands span)
(defun lower-module (module)
  (mognitio.ir:verify-module module)
  (let ((mognitio.native.runtime::*runtime-module* module)
        (root-plans (mognitio.roots:analyze-roots module))
        (root-plan nil) (frame nil) (sections nil)
        (function nil) (allocation nil) (homes nil) (temporary nil)
        (code nil) (units nil) (block-map (make-hash-table))
        (serial 0) (span (mognitio.ir:module-span module)))
    (labels ((emit (opcode &rest operands)
               (push (make-instruction :opcode opcode :operands operands :span span) code))
             (section (kind key forms)
               (let ((start code))
                 (dolist (form forms) (apply #'emit form))
                 ;; Keep the actual instruction objects, not a second rendering.
                 (push (list kind key (ldiff code start)) sections)))
             (publish-roots (block index)
               (let ((site (find (list block index) (mognitio.roots:root-plan-sites root-plan)
                                 :test #'equal :key (lambda (site)
                                   (list (mognitio.roots:root-site-block-id site)
                                         (mognitio.roots:root-site-instruction-index site))))))
                 (when site
                   (section :publish (list block index)
                     (append (list '(:imm-rax 0))
                       (loop for slot below (mognitio.frame:layout-capacity frame)
                             collect (list :store-frame (+ (mognitio.frame:layout-root-offset frame) 16 (* slot 8)) :rax))
                       (loop for value in (mognitio.roots:root-site-values site) for slot from 0
                             for location = (home value) append
                         (list (if (integerp location) (list :load-frame :rax location) (list :mov-reg :rax location))
                               (list :store-frame (+ (mognitio.frame:layout-root-offset frame) 16 (* slot 8)) :rax))))))))
             (finish-unit (owner entry)
               (push (mognitio.object:make-code-unit :owner owner :entry entry :instructions (nreverse code)) units)
               (setf code nil))
             (label-id (id) (list :block (mognitio.ir:ir-function-id function) id))
             (fresh-label () (list :internal (mognitio.ir:ir-function-id function) (incf serial)))
             (home (id)
               (multiple-value-bind (offset found) (gethash id homes)
                 (unless found (internal-error "Missing value home")) offset))
             (read-location (location reg)
               (if (integerp location) (emit :load-frame reg location)
                   (unless (eq location reg) (emit :mov-reg reg location))))
             (write-location (location reg)
               (if (integerp location) (emit :store-frame location reg)
                   (unless (eq location reg) (emit :mov-reg location reg))))
             (load-value (id &optional (reg :rax)) (read-location (home id) reg))
             (arithmetic (inst)
               (let ((op (mognitio.ir:instruction-op inst)))
                 (case op
                   ((:neg :add :sub :mul) (emit op) (emit :jo :overflow))
                   ((:div :rem)
                    (emit :test-rcx) (emit :jz :division-by-zero)
                    (let ((safe (fresh-label)) (done (fresh-label)))
                      (emit :cmp-rcx-minus-one) (emit :jnz safe)
                      (emit :imm-rdx mognitio.integer:+minimum+) (emit :cmp-rax-rdx)
                      (if (eq op :div) (emit :jz :overflow)
                          (progn (emit :jnz safe) (emit :imm-rax 0) (emit :jmp done)))
                      (emit :label safe) (emit :cqo) (emit :idiv)
                      (when (eq op :rem) (emit :mov-rax-rdx))
                      (emit :label done)))
                   ((:eq :ne :lt :le :gt :ge) (emit :cmp) (emit :set-bool op))
                   (otherwise (internal-error "Unsupported SSA operation")))))
             (runtime ()
               (dolist (form (case (mognitio.ir:ir-function-result-type
                                     (find 0 (mognitio.ir:module-functions module) :key #'mognitio.ir:ir-function-id))
                                 (:void '((:label :print) (:mov-edi 0) (:jmp :exit)))
                                 (:int '((:label :print) (:cmp-imm :rax 255) (:ja :invalid-exit-status)
                                         (:mov-reg :rdi :rax) (:jmp :exit)))
                                 (otherwise '((:label :print) (:test) (:jz :false)
                              (:lea-rsi (:data :true)) (:mov-edx 5) (:jmp :normal-setup)
                              (:label :false) (:lea-rsi (:data :false)) (:mov-edx 6)
                              (:label :normal-setup) (:mov-edi 1) (:mov-r8d 0) (:mov-r9d 1)
                              (:jmp :write-setup)))))
                 (apply #'emit form))
               (dolist (kind '(:overflow :division-by-zero :remainder-by-zero :string-index-out-of-bounds :string-size-overflow :list-length-overflow :allocation-failed :invalid-exit-status))
                 (emit :label kind)
                 (when (mognitio.native.runtime::io-image-p) (emit :call '(:runtime :io.cleanup-all)))
                 (emit :lea-rsi (list :data kind))
                 (emit :mov-edx (length (mognitio.runtime:failure-octets kind)))
                 (emit :mov-edi 2)
                 (emit :mov-r8d (mognitio.runtime:failure-status kind))
                 (emit :mov-r9d (mognitio.runtime:failure-status kind))
                 (emit :jmp :write-setup))
               (emit :label :write-setup) (emit :mov-r10d mognitio.runtime:+retry-budget+)
               (dolist (form '((:label :write-loop) (:mov-eax 1) (:syscall)
                              (:cmp-eintr) (:jz :write-interrupted)
                              (:test) (:jle :write-error) (:add-rsi) (:sub-rdx)))
                 (apply #'emit form))
               (emit :mov-r10d mognitio.runtime:+retry-budget+)
               (dolist (form '((:jnz :write-loop) (:mov-edi-r8d) (:jmp :exit)
                              (:label :write-interrupted) (:cmp-r9d-one) (:jz :write-loop)
                              (:dec-r10d) (:jnz :write-loop)
                              (:label :write-error) (:mov-edi-r9d)
                              (:label :exit) (:mov-eax 60) (:syscall) (:ud2)
                              (:label (:data :true)) (:bytes 116 114 117 101 10)
                              (:label (:data :false)) (:bytes 102 97 108 115 101 10)))
                 (apply #'emit form))
               (dolist (kind '(:overflow :division-by-zero :remainder-by-zero :string-index-out-of-bounds :string-size-overflow :list-length-overflow :allocation-failed :invalid-exit-status))
                 (emit :label (list :data kind))
                 (apply #'emit :bytes (coerce (mognitio.runtime:failure-octets kind) 'list)))))
      (dolist (form (mognitio.native.runtime:entry-forms)) (apply #'emit form))
      (finish-unit :entry-stub nil)
      (dolist (current (sort (copy-list (mognitio.ir:module-functions module)) #'< :key #'mognitio.ir:ir-function-id))
        (setf function current allocation (mognitio.regalloc:allocate-function current)
              homes (mognitio.regalloc:allocation-locations allocation)
              root-plan (find (mognitio.ir:ir-function-id current) root-plans :key #'mognitio.roots:root-plan-function-id)
              frame (mognitio.frame:plan-frame current allocation root-plan)
              temporary (mognitio.frame:layout-temporary frame) sections nil
              serial 0 span (mognitio.ir:ir-function-span current))
        (clrhash block-map)
        (dolist (b (mognitio.ir:ir-function-blocks function))
          (setf (gethash (mognitio.ir:basic-block-id b) block-map) b))
        (emit :label (list :function (mognitio.ir:ir-function-id function)))
        (emit :push-rbp) (emit :mov-reg :rbp :rsp)
        (let ((loop-label (fresh-label)))
          (section :reserve nil `((:imm-rcx ,(/ (mognitio.frame:layout-size frame) 8)) (:label ,loop-label)
                                 (:push-zero) (:dec-rcx) (:jnz ,loop-label))))
        (let ((header (mognitio.frame:layout-root-offset frame)))
          (section :link nil
            `((:load-word :rax :r15 ,mognitio.native.runtime:+root-head+) (:store-frame ,header :rax)
              (:imm-rax ,(mognitio.frame:layout-capacity frame)) (:store-frame ,(+ header 8) :rax)
              (:lea-base :rax :rbp ,header) (:store-word :r15 ,mognitio.native.runtime:+root-head+ :rax))))
        (loop for parameter in (mognitio.ir:basic-block-parameters
                                (gethash (mognitio.ir:ir-function-entry function) block-map))
              for offset from 16 by 8 do
          (emit :load-frame :rax offset) (write-location (home (car parameter)) :rax))
        (emit :jmp (label-id (mognitio.ir:ir-function-entry function)))
      (dolist (block (mognitio.regalloc:allocation-order allocation))
        (setf span (mognitio.ir:basic-block-span block))
        (emit :label (label-id (mognitio.ir:basic-block-id block)))
        (loop for inst in (mognitio.ir:basic-block-instructions block) for index from 0 do
          (let ((start code))
            (publish-roots (mognitio.ir:basic-block-id block) index)
            (setf span (mognitio.ir:instruction-span inst))
            (case (mognitio.ir:instruction-op inst)
              ((:constant :function) (emit :imm-rax (mognitio.ir:instruction-value inst)))
              (:runtime.argv
               (section :arguments (list (mognitio.ir:basic-block-id block) index)
                 `((:load-word :rax :r15 ,mognitio.native.runtime::+arguments+)
                   (:imm-rcx 0)
                   (:store-word :r15 ,(+ mognitio.native.runtime::+argument-root+ 8) :rcx)
                   (:store-word :r15 ,mognitio.native.runtime::+arguments+ :rcx)
                   (:load-word :rcx :r15 ,mognitio.native.runtime::+argument-root+)
                   (:store-frame ,(mognitio.frame:layout-root-offset frame) :rcx))))
              (:const.text (emit :lea-text (list :text (mognitio.ir:instruction-value inst))))
              ((:test.stage :text.length :text.equal :text.not-equal :text.concat :text.slice)
               (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (emit :call (list :helper (mognitio.ir:instruction-op inst))))
              (:call
               (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (emit :call (list :function (mognitio.ir:instruction-value inst))))
              ((:io.call :struct.make :enum.make :interface.pack :closure.make :list.append :list.at :list.buffer :text.slice.result)
               (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (emit :call (mognitio.native.runtime::value-helper-name inst)))
              ((:struct.field :enum.payload :enum.tag)
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (emit :load-word :rax :rax
                 (case (mognitio.ir:instruction-op inst)
                   (:enum.tag 24)
                   (:struct.field (+ 32 (* 8 (mognitio.ir:instruction-value inst))))
                   (otherwise (+ 32 (* 8 (third (mognitio.ir:instruction-value inst))))))))
              (:list.empty (emit :lea-object (mognitio.native.runtime::static-name :list (mognitio.ir:instruction-type inst))))
              ((:list.length :buffer.length)
               (load-value (first (mognitio.ir:instruction-operands inst))) (emit :load-word :rax :rax 32))
              (:buffer.get
               (load-value (second (mognitio.ir:instruction-operands inst))) (emit :imm-rcx 8) (emit :mul)
               (load-value (first (mognitio.ir:instruction-operands inst)) :rdx)
               (emit :add-reg :rdx :rax) (emit :load-word :rax :rdx 40))
              (:closure.env.get
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (emit :load-word :rax :rax (+ 40 (* 8 (second (mognitio.ir:instruction-value inst))))))
              (:closure.call
               (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (emit :load-word :rax :rax 32) (emit :call-rax))
              (:call.interface
               (loop for argument in (mognitio.ir:instruction-operands inst) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (emit :load-word :rcx :rax 32) (emit :store-out 0 :rcx)
               (emit :load-word :rax :rax 24)
               (emit :load-word :rax :rax (+ 24 (* 8 (second (mognitio.ir:instruction-value inst)))))
               (emit :call-rax))
              (:call.value
               (loop for argument in (rest (mognitio.ir:instruction-operands inst)) for offset from 0 by 8 do
                 (load-value argument) (emit :store-out offset :rax))
               (let ((done (fresh-label)) (targets (second (mognitio.ir:instruction-value inst))))
                 (load-value (first (mognitio.ir:instruction-operands inst)))
                 (loop for tail on targets for id = (car tail) do
                   (let ((next (fresh-label)))
                     (when (cdr tail) (emit :imm-rcx id) (emit :cmp) (emit :jnz next))
                     (emit :call (list :function id)) (emit :jmp done) (emit :label next)))
                 (emit :label done)))
              (otherwise
               (load-value (first (mognitio.ir:instruction-operands inst)))
               (when (second (mognitio.ir:instruction-operands inst))
                 (load-value (second (mognitio.ir:instruction-operands inst)) :rcx))
               (arithmetic inst)))
            (write-location (home (mognitio.ir:instruction-result inst)) :rax)
            (when (member (mognitio.ir:instruction-op inst)
                          '(:io.call :test.stage :call :call.value :text.length :text.equal :text.not-equal :text.concat :text.slice :struct.make :enum.make :interface.pack :call.interface :closure.make :closure.call :list.append :list.at :list.buffer :text.slice.result))
              (push (list :operation (list (mognitio.ir:basic-block-id block) index) (ldiff code start)) sections))))
        (let ((term (mognitio.ir:basic-block-terminator block)))
          (ecase (first term)
            (:assert-fail
             (section :assert-fail (list (mognitio.ir:basic-block-id block) :assert-fail)
               `((:lea-meta (:assertion-site ,(second term))) (:store-out 0 :rax)
                 (:call (:helper :assertion)) (:ud2))))
            (:panic
             (let ((start code))
               (load-value (second term)) (emit :store-out 0 :rax) (emit :call '(:helper :panic)) (emit :ud2)
               (push (list :panic (list (mognitio.ir:basic-block-id block) :panic) (ldiff code start)) sections)))
            (:trap (emit :mov-edi 3) (emit :mov-eax 60) (emit :syscall) (emit :ud2))
            (:branch (load-value (second term)) (emit :test)
                     (emit :jz (label-id (fourth term))) (emit :jmp (label-id (third term))))
            (:jump
             (let ((params (mognitio.ir:basic-block-parameters (gethash (second term) block-map)))
                   (args (third term)))
               (dolist (move (mognitio.regalloc:parallel-copies
                              (loop for p in params for a in args collect (cons (home (car p)) (home a))) temporary))
                 (read-location (cdr move) :rax) (write-location (car move) :rax)))
             (emit :jmp (label-id (second term))))
            (:return (load-value (second term)) (emit :jmp (list :internal (mognitio.ir:ir-function-id function) 0))))))
        (emit :label (list :internal (mognitio.ir:ir-function-id function) 0))
        (section :unlink nil `((:load-frame :rcx ,(mognitio.frame:layout-root-offset frame)) (:store-word :r15 ,mognitio.native.runtime:+root-head+ :rcx)))
        (emit :mov-reg :rsp :rbp) (emit :pop-rbp) (emit :ret)
        (let ((body (reverse code)))
          (mognitio.frame:verify-sections function allocation root-plan frame
            (loop for (kind key instructions) in (reverse sections)
                  for ordered = (reverse instructions) collect
              (list kind key (loop for i in ordered collect (cons (instruction-opcode i) (instruction-operands i)))
                    (position (first ordered) body)))
            (loop for i in body collect (cons (instruction-opcode i) (instruction-operands i)))))
        (finish-unit (mognitio.ir:ir-function-id function) (list :function (mognitio.ir:ir-function-id function))))
      (if (mognitio.ir::module-test-ordinal module)
          (dolist (form (mognitio.native.runtime::test-runtime-forms)) (apply #'emit form))
          (runtime))
      (finish-unit :runtime :print)
      (let* ((required-operations (remove-duplicates
                          (loop for f in (mognitio.ir:module-functions module) append
                            (loop for b in (mognitio.ir:ir-function-blocks f) append
                              (loop for i in (mognitio.ir:basic-block-instructions b)
                                    when (member (mognitio.ir:instruction-op i)
                                                 '(:text.length :text.equal :text.not-equal :text.concat :text.slice :text.slice.result))
                                    collect (if (eq :text.slice.result (mognitio.ir:instruction-op i)) :text.slice (mognitio.ir:instruction-op i)))))))
             (operations (remove-if-not (lambda (op) (member op required-operations))
                           '(:text.length :text.equal :text.not-equal :text.concat :text.slice)))
             (value-helpers (mognitio.native.runtime::value-helper-units module))
             (helpers (mognitio.native.runtime:text-helper-units
                        operations (length (mognitio.ir:module-literal-pool module)) (mognitio.ir:module-values module) (or value-helpers (mognitio.native.runtime::argument-image-p))))
             (literals (mognitio.object:make-code-unit :owner :literals :instructions
                         (loop for form in (mognitio.native.runtime:literal-forms (mognitio.ir:module-literal-pool module))
                               collect (make-instruction :opcode (first form) :operands (rest form))))))
        (mognitio.object:layout-units (mognitio.native.runtime::verify-io-units (append (nreverse units) helpers value-helpers (mognitio.native.runtime::argument-helper-units) (mognitio.native.runtime::io-runtime-units) (mognitio.native.runtime::verified-test-helper-units) (mognitio.native.runtime::assertion-units module)
          (when (some (lambda (f) (some (lambda (b) (eq :panic (first (mognitio.ir:basic-block-terminator b))))
                                      (mognitio.ir:ir-function-blocks f))) (mognitio.ir:module-functions module))
            (list (mognitio.native.runtime::panic-helper-unit))) (list (mognitio.native.runtime::context-metadata-unit) (mognitio.native.runtime::metadata-unit (mognitio.ir:module-values module)) literals))))))))
