(in-package #:mognitio.native.runtime)

(defun directory-scan-mutation ()
  (when (option :directory-scan-mutation)
    (scoped-forms :scan-mutation
      (append '((:test) (:jz :done) (:load-frame :rsi -208))
        (ecase (option :directory-scan-mutation)
          (:count '((:imm-rax 65537))) (:header '((:imm-rax 19)))
          (:reclen '((:imm-rdx 0) (:store-byte :rsi 16 :rdx) (:store-byte :rsi 17 :rdx)))
          (:alignment '((:imm-rdx 25) (:store-byte :rsi 16 :rdx)))
          (:end '((:imm-rdx 255) (:store-byte :rsi 16 :rdx) (:store-byte :rsi 17 :rdx)))
          (:empty '((:imm-rdx 0) (:store-byte :rsi 19 :rdx)))
          (:slash '((:imm-rdx 47) (:store-byte :rsi 19 :rdx)))
          (:utf8 '((:imm-rdx 255) (:store-byte :rsi 19 :rdx)))
          (:dtype '((:imm-rdx 8) (:store-byte :rsi 18 :rdx)))
          (:nul (append '((:imm-rdx 120)) (loop for i from 19 below 24 collect (list :store-byte :rsi i :rdx)))))
        '((:label :done))))))

(defun directory-scan-records ()
  (let ((bytes (option :directory-scan-records)))
    (when bytes
      (unless (and (typep bytes '(vector (unsigned-byte 8))) (<= (length bytes) 65536))
        (internal-error "Invalid private directory record fixture"))
      (scoped-forms :scan-records
        (append '((:load-frame :rax -712) (:test) (:jnz :end) (:imm-rax 1) (:store-frame -712 :rax)
                  (:load-frame :rsi -208))
          (loop for byte across bytes for i from 0 append `((:imm-rdx ,byte) (:store-byte :rsi ,i :rdx)))
          `((:imm-rax ,(length bytes)) (:jmp :done) (:label :end) (:imm-rax 0) (:label :done)))))))

(defun directory-read-forms ()
  (append (directory-path-map-forms)
    (directory-syscall-forms :open :open
      '((:imm-reg :rdi -100) (:load-frame :rsi -224) (:mov-edx 589824) (:mov-r10d 0) (:mov-eax 257)))
    '((:store-frame -232 :rax) (:imm-rax 2) (:store-frame -720 :rax)
      (:imm-rax 1) (:store-frame -736 :rax) (:imm-rax 65536) (:store-frame -200 :rax)
      (:store-out 0 :rax))
    (directory-map-forms :scan-map)
    '((:store-frame -208 :rax))
    (when (option :directory-after-accept-kind) '((:jmp :unsupported)))
    '((:label :scan))
    (directory-syscall-forms :scan :scan
      '((:load-frame :rdi -232) (:load-frame :rsi -208) (:mov-edx 65536) (:mov-eax 217)))
    (directory-scan-mutation)
    (directory-scan-records)
    '((:test) (:jz :body-done) (:cmp-imm :rax 65536) (:ja :internal) (:store-frame -168 :rax)
      (:imm-rax 0) (:store-frame -176 :rax)
      (:label :record) (:load-frame :rax -176) (:load-frame :rcx -168) (:cmp) (:jz :scan)
      (:add-imm :rax 20) (:cmp) (:ja :internal) (:load-frame :rsi -208) (:load-frame :rax -176)
      (:add-reg :rsi :rax) (:load-byte :rax :rsi 17) (:imm-rcx 256) (:mul)
      (:load-byte :rdx :rsi 16) (:add-reg :rax :rdx) (:cmp-imm :rax 24) (:jb :internal)
      (:mov-reg :rdx :rax) (:and-imm :rdx 7) (:cmp-imm :rdx 0) (:jnz :internal)
      (:load-frame :rcx -176) (:add-reg :rax :rcx) (:store-frame -544 :rax)
      (:load-frame :rcx -168) (:cmp) (:ja :internal)
      (:add-imm :rsi 19) (:store-frame -536 :rsi) (:load-frame :rdi -208) (:add-reg :rdi :rax)
      (:imm-reg :rcx 0) (:label :name-scan) (:cmp-reg :rsi :rdi) (:jae :internal)
      (:load-byte :rax :rsi 0) (:test) (:jz :name-end) (:add-imm :rsi 1) (:add-imm :rcx 1) (:jmp :name-scan)
      (:label :name-end) (:test-rcx) (:jz :internal) (:store-frame -128 :rcx)
      (:store-out 8 :rcx) (:load-frame :rax -536) (:store-out 0 :rax) (:call (:runtime :utf8.count))
      (:test) (:js :invalid-encoding) (:store-frame -136 :rax)
      (:load-frame :rsi -536) (:load-frame :rcx -128)
      (:label :slash-check) (:load-byte :rax :rsi 0) (:cmp-imm :rax 47) (:jz :internal)
      (:add-imm :rsi 1) (:dec-rcx) (:jnz :slash-check)
      (:load-frame :rsi -536) (:load-byte :rax :rsi 0) (:cmp-imm :rax 46) (:jnz :append-name)
      (:load-frame :rcx -128) (:cmp-imm :rcx 1) (:jz :next-record) (:cmp-imm :rcx 2) (:jnz :append-name)
      (:load-byte :rax :rsi 1) (:cmp-imm :rax 46) (:jz :next-record)
      (:label :append-name) (:load-frame :rax -160) (:store-frame -120 :rax)
      (:load-frame :rcx -128) (:add-reg :rax :rcx) (:jo :allocation-failed) (:add-imm :rax 1)
      (:jo :allocation-failed) (:store-frame -560 :rax))
    (directory-grow-forms :arena -352 -344 -336 -328 -160 -560 1024)
    '((:load-frame :rdi -352) (:load-frame :rax -160) (:add-reg :rdi :rax)
      (:load-frame :rsi -536) (:load-frame :rcx -128))
    (copy-forms :name-copy)
    '((:imm-rax 0) (:store-byte :rdi 0 :rax) (:load-frame :rax -560) (:store-frame -160 :rax))
    (directory-syscall-forms :child-stat :child-stat
      '((:load-frame :rdi -232) (:load-frame :rsi -352) (:load-frame :rax -120) (:add-reg :rsi :rax)
        (:lea-base :rdx :rbp -512) (:mov-r10d 256) (:mov-eax 262)) :child-error)
    '((:load-frame :rax -488) (:and-imm :rax 61440) (:imm-reg :rdx 0) (:cmp-imm :rax 32768) (:jz :kind)
      (:imm-rdx 1) (:cmp-imm :rax 16384) (:jz :kind) (:imm-rdx 2) (:cmp-imm :rax 40960) (:jz :kind)
      (:imm-rdx 3) (:label :kind) (:store-frame -608 :rdx)
      (:load-frame :rax -144) (:imm-rcx 230584300921369394) (:cmp) (:jae :allocation-failed)
      (:imm-rcx 40) (:mul) (:store-frame -568 :rax) (:add-imm :rax 40) (:store-frame -560 :rax))
    (directory-grow-forms :table -288 -280 -272 -264 -568 -560 640)
    '((:load-frame :rdx -288) (:load-frame :rax -568) (:add-reg :rdx :rax)
      (:load-frame :rax -120) (:store-word :rdx 0 :rax) (:load-frame :rax -128) (:store-word :rdx 8 :rax)
      (:load-frame :rax -136) (:store-word :rdx 16 :rax) (:load-frame :rax -608) (:store-word :rdx 24 :rax)
      (:load-frame :rax -144) (:store-word :rdx 32 :rax) (:add-imm :rax 1) (:store-frame -144 :rax)
      (:label :next-record) (:load-frame :rax -544) (:store-frame -176 :rax) (:jmp :record)
      (:label :child-error) (:imm-reg :rdx 1) (:store-frame -112 :rdx) (:jmp :os-error))))

(defun directory-name-forms (slot)
  (append
    `((:load-frame :rax -128) (:store-out 0 :rax) (:load-frame :rax -136) (:store-out 8 :rax)
      (:call (:runtime :allocate)) (:store-frame ,slot :rax) (:lea-base :rdi :rax 32)
      (:load-frame :rsi -352) (:load-frame :rax -120) (:add-reg :rsi :rax) (:load-frame :rcx -128))
    (copy-forms (intern (format nil "MATERIALIZE-NAME-~D" (- slot)) :keyword))))

(defun directory-materialize-forms (list-type context)
  (let* ((entry-type (second list-type))
         (entry-fields (mognitio.semantic:type-info-fields (mognitio.semantic:context-type context entry-type)))
         (kind-type (cdr (second entry-fields))))
    (append
      '((:load-frame :rax -288) (:store-out 0 :rax) (:load-frame :rax -352) (:store-out 8 :rax)
        (:load-frame :rax -144) (:store-out 16 :rax) (:call (:runtime :directory.sort)))
      `((:lea-object ,(static-name :list list-type)) (:store-frame -56 :rax)
        (:label :materialize) (:load-frame :rax -576) (:load-frame :rcx -144) (:cmp) (:jae :materialized)
        (:imm-rcx 40) (:mul) (:load-frame :rdx -288) (:add-reg :rdx :rax) (:store-frame -592 :rdx)
        (:load-frame :rax -584) (:test) (:jz :unique) (:store-out 0 :rax) (:store-out 8 :rdx)
        (:load-frame :rax -352) (:store-out 16 :rax) (:call (:runtime :directory.name-compare))
        (:test) (:jz :skip-duplicate) (:label :unique)
        (:load-frame :rdx -592) (:load-word :rax :rdx 0) (:store-frame -120 :rax)
        (:load-word :rax :rdx 8) (:store-frame -128 :rax) (:load-word :rax :rdx 16) (:store-frame -136 :rax)
        (:load-word :rax :rdx 24) (:store-frame -608 :rax))
      (directory-name-forms -32)
      (loop for kind below 4 append
        (let ((label (intern (format nil "ENTRY-KIND-~D" kind) :keyword)))
          (append `((:load-frame :rax -608) (:cmp-imm :rax ,kind) (:jnz ,label))
            (allocate-object label (list :descriptor (second kind-type) kind) 2 0 kind)
            '((:store-frame -40 :rdx) (:jmp :entry-value)) `((:label ,label)))))
      '((:jmp :internal) (:label :entry-value))
      (allocate-object :entry (list :descriptor (second entry-type) 0) 1 2)
      '((:load-frame :rax -32) (:store-word :rdx 32 :rax) (:load-frame :rax -40) (:store-word :rdx 40 :rax)
        (:store-frame -48 :rdx) (:load-frame :rax -56) (:load-word :rax :rax 32))
      `((:imm-rcx ,(option :directory-length-limit 9223372036854775807)) (:cmp) (:jae :list-length-overflow))
      (allocate-object :list-node (layout-name (list :list list-type)) 5 3)
      '((:load-frame :rax -56) (:store-word :rdx 40 :rax) (:load-word :rax :rax 32) (:add-imm :rax 1)
        (:store-word :rdx 32 :rax) (:load-frame :rax -48) (:store-word :rdx 48 :rax) (:store-frame -56 :rdx)
        (:load-frame :rax -592) (:store-frame -584 :rax)
        (:label :skip-duplicate) (:load-frame :rax -576) (:add-imm :rax 1) (:store-frame -576 :rax) (:jmp :materialize)
        (:label :materialized) (:load-frame :rax -56) (:store-frame -24 :rax)))))
