(in-package #:mognitio.native.runtime)

(defun verify-directory-terminal (forms)
  (unless (and (equal (nth 15 forms) '(:call (:runtime :io.cleanup-all)))
               (= 1 (count :call forms :key #'first))
               (equal (last forms 4) `((:mov-edi ,(if (test-image-p) 123 3)) (:mov-eax 60) (:syscall) (:ud2)))
               (if (test-image-p)
                   (= 1 (count :syscall forms :key #'first))
                   (and (= 2 (count :syscall forms :key #'first))
                        (member '(:imm-reg :r8 8) forms :test #'equal))))
    (internal-error "Invalid nonallocating directory internal terminal")))

(defun verify-directory-ownership (forms)
  ;; The checker reconstructs ownership from emitted instructions, independently
  ;; of the lowering's scratch constants. Joins do not hide a live descriptor.
  (let ((queue (list (list 0 nil 0 :closed))) (seen (make-hash-table :test #'equal)))
    (loop while queue for state = (pop queue) unless (gethash state seen) do
      (setf (gethash state seen) t)
      (destructuring-bind (pc stack published fd) state
        (when (>= pc (length forms)) (internal-error "Directory helper falls through"))
        (let* ((form (nth pc forms)) (op (car form))
               (next-stack stack) (next-count published) (next-fd fd))
          (when (equal form '(:store-word :r15 272 :rax))
            (let ((previous (nth (1- pc) forms)))
              (cond
                ((and (eq (car previous) :lea-base) (equal (subseq previous 1 3) '(:rax :rbp)))
                 (let ((record (fourth previous)))
                   (unless (and (< published 3) (= record (nth published '(-240 -304 -368)))
                                (equal (nth (- pc 3) forms) '(:load-word :rax :r15 272))
                                (equal (nth (- pc 2) forms) (list :store-frame record :rax))
                                (equal (nth (- pc 4) forms) (list :store-frame (+ record 8) :rax))
                                (equal (nth (- pc 5) forms) '(:imm-rax -1)))
                     (internal-error "Invalid directory record publication"))
                   (setf next-stack (cons (cons record :owned) stack) next-count (1+ published))))
                ((and (eq (car previous) :load-frame) stack
                      (equal previous (list :load-frame :rax (caar stack))) (eq (cdar stack) :cleaned))
                 (setf next-stack (cdr stack)))
                (t (internal-error "Uncleaned or forged directory ownership link")))))
          (when (equal form '(:call (:runtime :directory.cleanup)))
            (unless (and stack (eq (cdar stack) :owned)
                         (equal (nth (- pc 2) forms) (list :lea-base :rax :rbp (caar stack)))
                         (equal (nth (1- pc) forms) '(:store-out 0 :rax)))
              (internal-error "Directory cleanup does not name the owned record"))
            (setf next-stack (cons (cons (caar stack) :cleaned) (cdr stack)))
            (when (= (caar stack) -240) (setf next-fd :closed)))
          (when (equal form '(:store-frame -232 :rax))
            (setf next-fd (if (equal (nth (1- pc) forms) '(:imm-rax -1)) :closed :owned)))
          (when (equal form '(:call (:runtime :io.close))) (setf next-fd :closed))
          (when (and (eq fd :owned) (member form '((:call (:runtime :allocate)) (:call (:runtime :allocate-block))) :test #'equal))
            (internal-error "Directory materialization begins before close"))
          (when (or (eq op :ret) (and (member op '(:jmp :jnz)) (equal (second form) '(:runtime :directory.internal))))
            (unless (and (= published 3) (null stack)) (internal-error "Directory exit retains ownership")))
          (unless (member op '(:ret :ud2))
            (unless (eq op :jmp) (push (list (1+ pc) next-stack next-count next-fd) queue))
            (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
              (let ((target (position (list :label (second form)) forms :test #'equal)))
                (when target (push (list target next-stack next-count next-fd) queue))))))))))
