(in-package #:mognitio.native.runtime)

(defun physical-size-unit ()
  (runtime-unit :physical-size
    '((:load-word :rax :rsp 8) (:add-imm :rax 39) (:jb :allocation-failed)
      (:and-imm :rax -8) (:ret))))

(defun take-free-forms ()
  ;; R9 is a known fitting block, R11 the address of its incoming link,
  ;; RCX the requested physical size. No call, allocation, or GC is permitted.
  '((:load-word :r8 :r9 16)
    (:load-word :rdx :r9 0) (:sub-reg :rdx :rcx)
    (:cmp-imm :rdx 40) (:jb :whole)
    (:store-word :r9 0 :rcx) (:mov-reg :rax :r9) (:add-reg :rax :rcx)
    (:store-word :rax 0 :rdx) (:store-word :rax 16 :r8)
    (:imm-rdx 0) (:store-word :rax 8 :rdx) (:store-word :rax 24 :rdx)
    (:store-word :r11 0 :rax) (:jmp :taken)
    (:label :whole) (:store-word :r11 0 :r8)
    (:label :taken) (:imm-rax 1) (:store-word :r9 8 :rax)
    (:imm-rax 0) (:store-word :r9 16 :rax) (:store-word :r9 24 :rax)
    (:mov-reg :rax :r9)))

(defun find-free-unit ()
  (runtime-unit :find-free
    (append
      `((:load-word :rcx :rsp 8)
        (:lea-base :r11 :r15 ,(context-field-offset :free-head (test-image-p)))
        (:load-word :r9 :r11 0)
        (:label :block) (:cmp-imm :r9 0) (:jz :missing))
      (when (option :gc-counters) (bump 112))
      '((:load-word :rax :r9 0) (:cmp-reg :rax :rcx) (:jae :found)
        (:lea-base :r11 :r9 16) (:load-word :r9 :r11 0) (:jmp :block)
        (:label :found))
      (take-free-forms)
      '((:ret) (:label :missing) (:imm-rax 0) (:ret)))))

(defun watch-allocation ()
  ;; Observe one complete block lifecycle in three fixed records. This is a
  ;; lower bound on reuse, not a count of all allocations in reclaimed ranges.
  (when (option :trace)
    `((:load-word :rax :r15 ,+watch-state+) (:test) (:jnz :watch-existing)
      (:store-word :r15 ,+watch-pointer+ :r9)
      (:load-word :rdx :r9 0) (:store-word :r15 ,+watch-size+ :rdx)
      (:imm-rax 1) (:store-word :r15 ,+watch-state+ :rax)
      (:store-word :r15 ,+trace+ :rax) (:store-word :r15 ,(+ +trace+ 8) :r9)
      (:store-word :r15 ,(+ +trace+ 16) :rdx) (:jmp :watch-done)
      (:label :watch-existing) (:cmp-imm :rax 2) (:jnz :watch-done)
      (:load-word :rax :r15 ,+watch-pointer+) (:cmp-reg :rax :r9) (:jnz :watch-done)
      (:imm-rax 3) (:store-word :r15 ,+watch-state+ :rax)
      (:store-word :r15 ,(+ +trace+ 48) :rax) (:store-word :r15 ,(+ +trace+ 56) :r9)
      (:load-word :rax :r9 0) (:store-word :r15 ,(+ +trace+ 64) :rax)
      (:imm-rax 1) (:store-word :r15 ,+observed-reuses+ :rax)
      (:label :watch-done))))

(defun allocate-unit ()
  (let ((unit (option :arena-unit 1048576)) (cap (option :cap)))
    (unless (and (typep unit '(integer 4096 2147483647))
                 (or (null cap) (typep cap '(integer 4096 9223372036854775807))))
      (internal-error "Invalid internal heap configuration"))
    (runtime-unit :allocate-block
      (append (helper-frame 10)
        (when (option :fail-allocation)
          (unless (typep (option :fail-allocation) '(integer 1 2147483647))
            (internal-error "Invalid allocation fault ordinal"))
          (append (bump 232)
                  `((:cmp-imm :rax ,(option :fail-allocation)) (:jz :allocation-failed))))
        '((:load-frame :rax 16) (:store-out 0 :rax) (:call (:runtime :physical-size))
          (:store-frame -8 :rax))
        (when (option :stress) '((:call (:runtime :collect))))
        '((:load-frame :rax -8) (:store-out 0 :rax) (:call (:runtime :find-free))
          (:test) (:jnz :found) (:call (:runtime :collect)))
        '((:load-frame :rax -8) (:store-out 0 :rax) (:call (:runtime :find-free))
          (:test) (:jnz :found)
          ;; One bounded arena extension, after one failed retry.
          (:load-frame :rax -8) (:add-imm :rax 32) (:jb :allocation-failed))
        `((:cmp-imm :rax ,unit) (:jae :round) (:imm-rax ,unit)
          (:label :round) (:load-word :rcx :r15 ,+page-size+)
          (:mov-reg :rdx :rcx) (:add-imm :rdx -1) (:add-reg :rax :rdx) (:jb :allocation-failed)
          (:imm-rdx 0) (:div-rcx) (:mul) (:store-frame -16 :rax)
          (:load-word :rdx :r15 ,+mapped-bytes+) (:add-reg :rdx :rax) (:jb :allocation-failed))
        (when cap `((:imm-rax ,cap) (:cmp-rax-rdx) (:jb :allocation-failed)))
        '((:imm-reg :rdi 0) (:load-frame :rsi -16) (:imm-rdx 3)
          (:imm-reg :r10 34) (:imm-reg :r8 -1) (:imm-reg :r9 0) (:mov-eax 9))
        (if (option :mmap-fail) '((:imm-rax -12)) '((:syscall)))
        '((:cmp-imm :rax -4095) (:jae :allocation-failed) (:mov-reg :r9 :rax)
          (:imm-rdx 0) (:store-word :r9 0 :rdx) (:store-word :r9 24 :rdx)
          (:load-frame :rdx -16) (:store-word :r9 8 :rdx)
          (:imm-rax 32) (:store-word :r9 16 :rax))
        (bump +mapped-bytes+ :rdx)
        `((:load-word :r8 :r15 ,+arena-head+) (:cmp-imm :r8 0) (:jnz :tail)
          (:store-word :r15 ,+arena-head+ :r9) (:jmp :arena-ready)
          (:label :tail) (:load-word :rax :r8 0) (:test) (:jz :append)
          (:mov-reg :r8 :rax) (:jmp :tail)
          (:label :append) (:store-word :r8 0 :r9)
          (:label :arena-ready) (:add-imm :r9 32) (:load-frame :rdx -16) (:add-imm :rdx -32)
          (:store-word :r9 0 :rdx) (:imm-rax 0) (:store-word :r9 8 :rax)
          (:store-word :r9 16 :rax) (:store-word :r9 24 :rax)
          ;; Append in arena order, then consume this known fitting block.
          (:lea-base :r11 :r15 ,(context-field-offset :free-head (test-image-p)))
          (:label :free-tail) (:load-word :rax :r11 0) (:test) (:jz :free-append)
          (:lea-base :r11 :rax 16) (:jmp :free-tail)
          (:label :free-append) (:store-word :r11 0 :r9) (:load-frame :rcx -8))
        (take-free-forms)
        '((:label :found) (:mov-reg :r9 :rax))
        (bump +alloc-count+)
        '((:load-word :rdx :r9 0)) (bump +alloc-bytes+ :rdx)
        (watch-allocation)
        '((:mov-reg :rax :r9)) (helper-return)))))
