(in-package #:mognitio.native.runtime)

(defun verify-text-collection-helper (unit)
  ;; This checker consumes emitted instructions, not a second lowering result.
  (let* ((forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                          (mognitio.machine:instruction-operands i)))
                         (mognitio.object:code-unit-instructions unit)))
         (op (first (second (mognitio.object:code-unit-entry unit))))
         (labels (loop for f in forms when (eq (first f) :label) collect (second f)))
         (link '((:load-word :rax :r15 0) (:store-frame -40 :rax) (:imm-rax 3)
                 (:store-frame -32 :rax) (:lea-base :rax :rbp -40) (:store-word :r15 0 :rax))))
    (unless (and (member op '(:text.scalars :text.join))
                 (equal (subseq forms 1 23) (append '((:push-rbp) (:mov-reg :rbp :rsp))
                                                    (make-list 20 :initial-element '(:push-zero))))
                 (equal (subseq forms 23 29) link)
                 (equal (last forms 5) '((:load-frame :rcx -40) (:store-word :r15 0 :rcx)
                                          (:mov-reg :rsp :rbp) (:pop-rbp) (:ret))))
      (internal-error "Invalid text helper root/frame lifetime"))
    (dolist (form forms)
      (let ((opcode (first form)))
        (when (intersection (if (eq opcode :sub) '(:rax) (io-helper-writes form)) '(:rbx :r12 :r13 :r14 :r15))
          (internal-error "Text helper clobbers preserved register"))
        (when (member opcode '(:load-frame :store-frame :store-out))
          (let ((offset (if (eq opcode :load-frame) (third form) (second form))))
            (unless (and (zerop (mod offset 8))
                         (if (eq opcode :store-out) (member offset '(0 8 16))
                             (or (<= -104 offset -8) (and (eq opcode :load-frame) (member offset '(16 24))))))
              (internal-error "Text helper frame/cursor escapes"))))
        (when (and (eq opcode :store-word) (eq (second form) :r15) (/= (third form) 0))
          (internal-error "Text helper changes context ABI"))
        (when (member opcode '(:jmp :jz :jnz :jae :ja :jb :js :jo))
          (unless (or (member (second form) labels :test #'equal)
                      (member (second form) '(:allocation-failed :string-size-overflow)))
            (internal-error "Unproved text helper exit")))
        (when (eq opcode :call)
          (unless (member (second form) '((:runtime :allocate) (:runtime :allocate-block)) :test #'equal)
            (internal-error "Unknown text helper safepoint")))))
    (unless (and (= 1 (count '(:call (:runtime :allocate)) forms :test #'equal))
                 (= (if (eq op :text.scalars) 1 0)
                    (count '(:call (:runtime :allocate-block)) forms :test #'equal)))
      (internal-error "Text helper allocation topology changed"))
    (when (eq op :text.scalars)
      (verify-scalar-root-flow forms)
      (dolist (required '((:store-frame -8 :rax) (:store-frame -16 :rdx) (:store-frame -24 :rax)
                          (:load-frame :rax -24) (:store-word :rdx 48 :rax)))
        (unless (member required forms :test #'equal) (internal-error "Scalar transient root missing")))
      (let ((text (position '(:call (:runtime :allocate)) forms :test #'equal))
            (node (position '(:call (:runtime :allocate-block)) forms :test #'equal)))
        (unless (and (< text node) (equal (nth (1+ text) forms) '(:store-frame -24 :rax)))
          (internal-error "Scalar result is unrooted at node allocation"))))
    (when (eq op :text.join)
      (let* ((at (position '(:call (:runtime :allocate)) forms :test #'equal))
             (tail (nthcdr (1+ at) forms)))
        (unless (and (equal (first tail) '(:store-frame -24 :rax))
                     (notany (lambda (f) (eq (first f) :call)) tail)
                     (member '(:store-frame -8 :rax) forms :test #'equal)
                     (member '(:store-frame -16 :rax) forms :test #'equal))
          (internal-error "Join copy region allocates or loses its inputs"))))
    unit))

(defun verify-v014-phase-shape (unit)
  (let* ((name (second (mognitio.object:code-unit-entry unit)))
         (directory (member (third name) '(:join-path :read-directory :create-directory)))
         (current (if directory -720 -392)) (primary (if directory -728 -400))
         (root (if directory -56 -32))
         (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                         (mognitio.machine:instruction-operands i)))
                        (mognitio.object:code-unit-instructions unit))))
    (unless (= 1 (count (list :load-frame :rax current) forms :test #'equal))
      (internal-error "Missing or repeated primary phase capture"))
    (let ((at (position (list :load-frame :rax current) forms :test #'equal)))
      (unless (equal (nth (1+ at) forms) (list :store-frame primary :rax))
        (internal-error "Current phase not frozen at primary boundary")))
    (unless (and (= 4 (count (list :load-frame :rax primary) forms :test #'equal))
                 (member (list :load-frame :rax root) forms :test #'equal)
                 (= 1 (count '(:store-word :rdx 56 :rax) forms :test #'equal)))
      (internal-error "IoError phase is not a rooted nominal field"))
    (verify-primary-phase-flow forms directory)
    ;; Every subsequent primary store must select final-cleanup's API phase.
    (loop for form in forms for i from 0 when (equal form (list :store-frame primary :rax)) do
      (unless (or (equal (nth (1- i) forms) (list :load-frame :rax current))
                  (and (not (member (third name) '(:read-stdin :write-stdout :write-stderr)))
                       (equal (nth (1- i) forms) '(:imm-rax 3)))
                  (and (eq (third name) :read-stdin) (equal (nth (1- i) forms) '(:imm-rax 2)))
                  (and (member (third name) '(:write-stdout :write-stderr)) (equal (nth (1- i) forms) '(:imm-rax 2))))
        (internal-error "Primary phase overwritten by current stage")))
    unit))

(defun verify-v014-stream-cleanup-latch (unit)
  ;; Cover both an earlier close latch and both possible final cleanup returns.
  (let* ((forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                          (mognitio.machine:instruction-operands i)))
                         (mognitio.object:code-unit-instructions unit)))
         (at (position '(:call (:runtime :io.cleanup)) forms :test #'equal)))
    (unless at (internal-error "Missing stream/file cleanup boundary"))
    (dolist (earlier '(0 1))
      (dolist (returned '(0 1))
        (verify-directory-latch
          (append (list (list :imm-rax earlier) '(:store-frame -104 :rax) (list :imm-rdx returned))
            (mapcar (lambda (form)
                      (cond ((and (eq (first form) :store-frame) (= (second form) -408))
                             (list :store-frame -104 (third form)))
                            ((and (eq (first form) :load-frame) (= (third form) -408))
                             (list :load-frame (second form) -104))
                            (t form))) (nthcdr (1+ at) forms))))))
    unit))
