(in-package #:mognitio.native.runtime)

(defun io-path-forms (write-p)
  (append
    '((:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:test-rcx) (:jz :invalid-path)
      (:store-frame -72 :rcx) (:add-imm :rsi 32)
      (:label :path-check) (:load-byte :rax :rsi 0) (:test) (:jz :invalid-path)
      (:add-imm :rsi 1) (:dec-rcx) (:jnz :path-check)
      (:load-frame :rax -72) (:add-imm :rax 1) (:jo :allocation-failed)
      (:store-frame -72 :rax) (:store-out 0 :rax) (:call (:runtime :io.map)) (:store-frame -80 :rax)
      (:mov-reg :rdi :rax) (:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-imm :rsi 32))
    (copy-forms :path-copy)
    '((:imm-rax 0) (:store-byte :rdi 0 :rax)
      (:label :stat) (:imm-reg :rdi -100) (:load-frame :rsi -80) (:lea-base :rdx :rbp -320)
      (:mov-r10d 0) (:mov-eax 262) (:syscall) (:cmp-eintr) (:jz :stat))
    (when write-p '((:cmp-imm :rax -2) (:jz :open)))
    '((:test) (:js :os-error) (:load-frame :rax -296) (:and-imm :rax 61440)
      (:cmp-imm :rax 32768) (:jnz :unsupported)
      (:label :open) (:load-frame :rdi -80))
    `((:imm-reg :rsi ,(logior #x80000 #x800 (if write-p 65 0))) (:mov-edx 438)
      (:mov-eax 2) (:syscall) (:cmp-eintr) (:jz :open) (:test) (:js :os-error)
      (:store-frame -120 :rax) (:store-frame -160 :rax)
      (:label :fstat) (:load-frame :rdi -120) (:lea-base :rsi :rbp -320)
      (:mov-eax 5) (:syscall) (:cmp-eintr) (:jz :fstat) (:test) (:js :os-error)
      (:load-frame :rax -296) (:and-imm :rax 61440) (:cmp-imm :rax 32768) (:jnz :unsupported))
    (when write-p
      '((:label :truncate) (:load-frame :rdi -120) (:imm-reg :rsi 0)
        (:mov-eax 77) (:syscall) (:cmp-eintr) (:jz :truncate) (:test) (:js :os-error)))))

(defun io-read-forms ()
  (append
    ;; Reserve a whole fixed-size read even after a prior short transfer. Merely
    ;; clamping to free capacity would still differ from the host's next request.
    '((:label :read) (:load-frame :rax -136) (:add-imm :rax 4096) (:jo :allocation-failed)
      (:load-frame :rcx -104) (:cmp) (:jbe :capacity)
      (:test-rcx) (:jz :first-buffer) (:mov-reg :rax :rcx) (:add) (:jo :allocation-failed)
      (:jmp :grow) (:label :first-buffer) (:imm-rax 4096)
      (:label :grow) (:store-frame -168 :rax)
      ;; Move, do not duplicate, old ownership before acquiring a new mapping.
      (:load-frame :rax -112) (:store-frame -96 :rax) (:load-frame :rax -104) (:store-frame -88 :rax)
      (:imm-rax 0) (:store-frame -112 :rax)
      (:load-frame :rax -168) (:store-out 0 :rax) (:call (:runtime :io.map))
      (:store-frame -112 :rax) (:load-frame :rcx -168) (:store-frame -104 :rcx)
      (:load-frame :rsi -96) (:cmp-imm :rsi 0) (:jz :capacity)
      (:mov-reg :rdi :rax) (:load-frame :rcx -136))
    (copy-forms :grow-copy)
    '((:load-frame :rdi -96) (:load-frame :rsi -88) (:imm-rax 0) (:store-frame -96 :rax)
      (:mov-eax 11) (:syscall) (:test) (:js :os-error)
      (:label :capacity) (:load-frame :rdi -160) (:load-frame :rsi -112) (:load-frame :rax -136)
      (:add-reg :rsi :rax) (:mov-edx 4096)
      (:mov-eax 0) (:syscall) (:cmp-eintr) (:jz :read) (:test) (:js :os-error) (:jz :eof)
      (:store-frame -176 :rax) (:store-out 8 :rax)
      (:load-frame :rax -112) (:load-frame :rcx -136) (:add-reg :rax :rcx) (:store-out 0 :rax)
      (:lea-base :rax :rbp -384) (:store-out 16 :rax) (:call (:runtime :utf8.feed))
      (:test) (:js :invalid-encoding)
      (:load-frame :rax -176) (:load-frame :rcx -136) (:add-reg :rax :rcx)
      (:jo :string-size-overflow) (:store-frame -136 :rax) (:jmp :read)
      (:label :eof) (:load-frame :rax -384) (:test) (:jnz :invalid-encoding)
      (:load-frame :rax -360) (:store-frame -144 :rax) (:jmp :close))))

(defun io-write-forms (argument-offset)
  `((:label :write) (:load-frame :rsi ,argument-offset) (:load-word :rdx :rsi 16)
    (:load-frame :rax -152) (:cmp-reg :rax :rdx) (:jae :close)
    (:sub-reg :rdx :rax) (:add-imm :rsi 32) (:add-reg :rsi :rax) (:load-frame :rdi -160)
    (:mov-eax 1) (:syscall) (:cmp-eintr) (:jz :write) (:test) (:js :os-error) (:jz :zero-write)
    (:load-frame :rcx -152) (:add-reg :rax :rcx) (:store-frame -152 :rax) (:jmp :write)))

(defun io-operation-unit (instruction context)
  (let* ((operation (mognitio.ir:instruction-value instruction))
         (number (position operation '(:read-file :write-file :read-stdin :write-stdout :write-stderr)))
         (file-p (< number 2)) (read-p (member operation '(:read-file :read-stdin)))
         (result (mognitio.ir:instruction-type instruction))
         (error-type (second (mognitio.semantic::canonical-result-arguments context result)))
         (fields (mognitio.semantic:type-info-fields (mognitio.semantic:context-type context error-type)))
         (operation-type (cdar fields)) (kind-type (cdr (second fields)))
         (subject-id (unless file-p
                       (let ((bytes (sb-ext:string-to-octets (nth (- number 2) '("stdin" "stdout" "stderr")) :external-format :utf-8)))
                         (or (position bytes (mognitio.ir:module-literal-pool *runtime-module*)
                                       :key #'mognitio.syntax:text-payload-octets :test #'equalp)
                             (internal-error "Missing standard stream subject"))))))
    (runtime-unit (second (value-helper-name instruction))
      (append (helper-frame 52) (helper-root-link 4)
        `((:load-word :rax :r15 ,+cleanup-head+) (:store-frame ,+io-record-offset+ :rax)
          (:lea-base :rax :rbp ,+io-record-offset+) (:store-word :r15 ,+cleanup-head+ :rax)
          (:imm-rax -1) (:store-frame -120 :rax) (:store-frame -64 :rax))
        (if file-p '((:load-frame :rax 16)) `((:lea-text (:text ,subject-id))))
        '((:store-frame -8 :rax))
        (if file-p (io-path-forms (not read-p))
            `((:imm-rax ,(- number 2)) (:store-frame -160 :rax)))
        (if read-p (io-read-forms) (io-write-forms (if file-p 24 16)))
        '((:label :invalid-path) (:imm-rax 0) (:store-frame -64 :rax) (:jmp :close)
          (:label :unsupported) (:imm-rax 4) (:store-frame -64 :rax) (:jmp :close)
          (:label :invalid-encoding) (:imm-rax 1) (:store-frame -64 :rax) (:jmp :close)
          (:label :zero-write) (:imm-rax 7) (:store-frame -64 :rax) (:jmp :close)
          (:label :os-error) (:store-frame -56 :rax)
          (:label :close) (:lea-base :rax :rbp -128) (:store-out 0 :rax) (:call (:runtime :io.close))
          (:test) (:jz :closed) (:load-frame :rcx -56) (:test-rcx) (:jnz :closed)
          (:load-frame :rcx -64) (:cmp-imm :rcx -1) (:jnz :closed) (:store-frame -56 :rax)
          (:label :closed) (:load-frame :rax -56) (:test) (:jnz :cleanup)
          (:load-frame :rax -64) (:cmp-imm :rax -1) (:jnz :cleanup))
        (when read-p
          (append
            '((:load-frame :rax -136) (:test) (:jz :empty) (:store-out 0 :rax)
              (:load-frame :rax -144) (:store-out 8 :rax) (:call (:runtime :allocate)) (:store-frame -32 :rax)
              (:lea-base :rdi :rax 32) (:load-frame :rsi -112) (:load-frame :rcx -136))
            (copy-forms :text-copy)
            '((:jmp :cleanup) (:label :empty) (:lea-text (:text 0)) (:store-frame -32 :rax))))
        '((:label :cleanup) (:lea-base :rax :rbp -128) (:store-out 0 :rax) (:call (:runtime :io.cleanup))
          (:test) (:jz :cleaned) (:load-frame :rcx -56) (:test-rcx) (:jnz :cleaned)
          (:load-frame :rcx -64) (:cmp-imm :rcx -1) (:jnz :cleaned) (:store-frame -56 :rax)
          (:label :cleaned) (:load-frame :rax -128))
        `((:store-word :r15 ,+cleanup-head+ :rax))
        '((:load-frame :rax -64) (:cmp-imm :rax -1) (:jnz :error-kind)
          (:load-frame :rax -56) (:test) (:jz :ok) (:call (:runtime :io.errno))
          (:label :error-kind) (:store-frame -64 :rax))
        (allocate-object :operation (list :descriptor (second operation-type) number) 2 0 number)
        '((:store-frame -16 :rdx))
        ;; Each no-payload variant has its own verified descriptor.
        (loop for kind below 8 append
          (let ((next (intern (format nil "ERROR-KIND-~D" kind) :keyword)))
            (append `((:load-frame :rax -64) (:cmp-imm :rax ,kind) (:jnz ,next))
                    (allocate-object (intern (format nil "KIND-~D" kind) :keyword) (list :descriptor (second kind-type) kind) 2 0 kind)
                    '((:store-frame -24 :rdx) (:jmp :error-value)) `((:label ,next)))))
        '((:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2) (:label :error-value))
        (allocate-object :error-value (list :descriptor (second error-type) 0) 1 3)
        '((:load-frame :rax -16) (:store-word :rdx 32 :rax) (:load-frame :rax -24) (:store-word :rdx 40 :rax)
          (:load-frame :rax -8) (:store-word :rdx 48 :rax) (:store-frame -32 :rdx))
        (result-construction :err result 1 -32)
        '((:jmp :done) (:label :ok))
        (result-construction :ok result 0 -32)
        '((:label :done)) (helper-root-unlink 4) (helper-return)) :helper)))
