(in-package #:mognitio.native.runtime)

(defun directory-fault-forms (phase syscall)
  ;; Private compiler controls use per-invocation counters, never source, argv,
  ;; environment, or mutable process-wide state in the generated image.
  (let* ((faults (remove-if-not (lambda (fault) (eq phase (first fault))) (option :directory-faults)))
         (slot (- -640 (* 8 (position phase '(:open :scan :child-stat :mkdir :create-stat :root-stat :close :unmap :map))))))
    (if (null faults) syscall
        (append `((:load-frame :r9 ,slot) (:add-imm :r9 1) (:store-frame ,slot :r9))
          (when (eq phase :close) (append syscall `((:load-frame :r9 ,slot))))
          (loop for fault in faults for i from 0 append
            (let ((next (intern (format nil "FAULT-NEXT-~A-~D" phase i) :keyword)))
              (unless (and (= (length fault) 3) (typep (second fault) '(integer 1 *)) (typep (third fault) '(signed-byte 64)))
                (internal-error "Invalid private directory fault"))
              `((:cmp-imm :r9 ,(second fault)) (:jnz ,next) (:imm-rax ,(third fault)) (:jmp :fault-done) (:label ,next))))
          (unless (eq phase :close) syscall) '((:label :fault-done))))))

(defun directory-status-forms (phase &optional (error-label :os-error))
  (append
    '((:test) (:js :status-negative) (:jmp :status-positive) (:label :status-negative))
    ;; Linux errors occupy only [-4095,-1]. Values outside that range, or errors
    ;; impossible for owned descriptors/buffers, signal implementation failure.
    '((:cmp-imm :rax -4095) (:jl :internal))
    (loop for errno in (ecase phase
                        ((:open :mkdir) '(9 14)) ((:create-stat :root-stat) '(9 14 22))
                        ((:scan :child-stat) '(9 14 20 22)) (:close '(9)))
          append `((:cmp-imm :rax ,(- errno)) (:jz :internal)))
    `((:jmp ,error-label) (:label :status-positive))
    (unless (member phase '(:open :scan)) '((:test) (:jnz :internal)))))

(defun directory-syscall-forms (prefix phase setup &optional (error-label :os-error))
  (scoped-forms prefix
    (append '((:label :retry)) (directory-fault-forms phase (append setup '((:syscall))))
      (unless (eq phase :close) '((:cmp-eintr) (:jz :retry)))
      (directory-status-forms phase error-label))))

(defun directory-validate-path-forms (prefix slot relative-p)
  (scoped-forms prefix
    (append `((:load-frame :rsi ,slot) (:load-word :rcx :rsi 16) (:test-rcx) (:jz :invalid)
              (:add-imm :rsi 32))
      (when relative-p '((:load-byte :rax :rsi 0) (:cmp-imm :rax 47) (:jz :invalid)))
      '((:label :loop) (:load-byte :rax :rsi 0) (:test) (:jz :invalid)
        (:add-imm :rsi 1) (:dec-rcx) (:jnz :loop) (:jmp :valid)
        (:label :invalid))
      (when relative-p `((:load-frame :rax ,slot) (:store-frame -8 :rax)))
      '((:jmp :invalid-path) (:label :valid)))))

(defun directory-join-forms (prefix)
  (scoped-forms prefix
    (append
      '((:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-reg :rsi :rcx)
        (:load-byte :rax :rsi 31) (:imm-reg :rdx 0) (:cmp-imm :rax 47) (:jz :separator)
        (:imm-rdx 1) (:label :separator) (:store-frame -520 :rdx)
        (:load-frame :rax -8) (:load-word :rax :rax 24) (:store-out 0 :rax)
        (:load-frame :rax -16) (:load-word :rax :rax 24) (:store-out 8 :rax)
        (:call (:runtime :sum)) (:store-out 0 :rax) (:load-frame :rax -520) (:store-out 8 :rax)
        (:call (:runtime :sum)) (:store-frame -528 :rax))
      (when (option :directory-length-limit)
        `((:imm-rcx ,(option :directory-length-limit)) (:cmp) (:ja :string-size-overflow)))
      '(
        (:load-frame :rax -8) (:load-word :rax :rax 16) (:load-frame :rdx -16) (:load-word :rdx :rdx 16)
        (:add-reg :rax :rdx) (:jb :allocation-failed) (:js :allocation-failed)
        (:load-frame :rdx -520) (:add-reg :rax :rdx) (:jo :allocation-failed)
        (:store-out 0 :rax) (:load-frame :rax -528) (:store-out 8 :rax)
        (:call (:runtime :allocate)) (:store-frame -24 :rax) (:lea-base :rdi :rax 32)
        (:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-imm :rsi 32))
      (copy-forms :left)
      '((:load-frame :rax -520) (:test) (:jz :right) (:imm-rax 47) (:store-byte :rdi 0 :rax)
        (:add-imm :rdi 1) (:label :right) (:load-frame :rsi -16) (:load-word :rcx :rsi 16) (:add-imm :rsi 32))
      (copy-forms :right-copy))))

(defun directory-map-forms (prefix)
  (scoped-forms prefix
    (append
      (if (option :directory-fail-map) '((:imm-rax -12))
          (directory-fault-forms :map '((:call (:runtime :directory.map)))))
      '((:cmp-imm :rax -22) (:jz :internal)
        (:cmp-imm :rax -4095) (:jae :allocation-failed)
        (:test) (:jle :internal)
        (:mov-reg :rdx :rax) (:and-imm :rdx 4095) (:cmp-imm :rdx 0) (:jnz :internal)))))

(defun directory-path-map-forms ()
  (append (directory-validate-path-forms :path -8 nil)
    '((:imm-rax 1) (:store-frame -720 :rax))
    '((:load-frame :rax -8) (:load-word :rax :rax 16) (:add-imm :rax 1) (:jo :allocation-failed)
      (:store-frame -216 :rax) (:store-out 0 :rax))
    (directory-map-forms :path-map)
    '((:store-frame -224 :rax)
      (:mov-reg :rdi :rax) (:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-imm :rsi 32))
    (copy-forms :path-copy) '((:imm-rax 0) (:store-byte :rdi 0 :rax))))

(defun directory-create-stat (prefix flags error-label)
  (directory-syscall-forms prefix :create-stat
    `((:imm-reg :rdi -100) (:load-frame :rsi -224) (:lea-base :rdx :rbp -512)
      (:mov-r10d ,flags) (:mov-eax 262)) error-label))
(defun directory-create-forms ()
  (append (directory-path-map-forms)
    (directory-create-stat :initial-stat 0 :initial-stat-error)
    '((:jmp :check-mode) (:label :initial-stat-error) (:cmp-imm :rax -2) (:jnz :os-error))
    (directory-syscall-forms :mkdir :mkdir
      '((:imm-reg :rdi -100) (:load-frame :rsi -224) (:mov-edx 511) (:mov-eax 258)) :mkdir-error)
    '((:jmp :body-done) (:label :mkdir-error) (:cmp-imm :rax -17) (:jnz :os-error))
    (directory-create-stat :collision-stat 0 :collision-error)
    '((:jmp :check-mode) (:label :collision-error) (:cmp-imm :rax -2) (:jnz :os-error)
      (:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-reg :rsi :rcx)
      (:load-byte :rdx :rsi 31) (:cmp-imm :rdx 47) (:jz :os-error))
    (directory-create-stat :nofollow-stat 256 :os-error)
    '((:label :check-mode) (:load-frame :rax -488) (:and-imm :rax 61440)
      (:cmp-imm :rax 16384) (:jnz :unsupported) (:jmp :body-done))))

(defun directory-grow-forms (prefix current size old old-size used required initial)
  (scoped-forms prefix
    (append
      `((:load-frame :rax ,required) (:load-frame :rcx ,size) (:cmp) (:jbe :ready)
        (:test-rcx) (:jnz :double) (:imm-rcx ,initial)
        (:label :double) (:cmp) (:jbe :capacity) (:add-reg :rcx :rcx) (:jo :allocation-failed) (:jmp :double)
        (:label :capacity) (:store-frame -552 :rcx)
        (:load-frame :rax ,current) (:store-frame ,old :rax) (:load-frame :rax ,size) (:store-frame ,old-size :rax)
        (:imm-rax 0) (:store-frame ,current :rax) (:store-frame ,size :rcx))
      (when (eq prefix (option :directory-fail-growth-before))
        `((:load-frame :rax ,old) (:test) (:jnz :allocation-failed)))
      `((:load-frame :rcx ,size) (:store-out 0 :rcx))
      (directory-map-forms :grow-map)
      `((:store-frame ,current :rax)
        ,@(when (eq prefix (option :directory-fail-growth-after))
            `((:load-frame :rcx ,old) (:test-rcx) (:jnz :allocation-failed)))
        (:load-frame :rsi ,old) (:cmp-imm :rsi 0) (:jz :ready)
        (:mov-reg :rdi :rax) (:load-frame :rcx ,used))
      (copy-forms :copy)
      `((:load-frame :rdi ,old) (:load-frame :rsi ,old-size) (:imm-rax 0) (:store-frame ,old :rax)
        (:mov-eax 11) (:syscall) (:test) (:jz :ready)
        (:cmp-imm :rax -22) (:jz :internal) (:cmp-imm :rax -14) (:jz :internal)
        (:cmp-imm :rax -4095) (:jl :internal) (:test) (:js :os-error) (:jmp :internal) (:label :ready)))))

(defun directory-operation-unit (instruction context)
  (let* ((operation (mognitio.ir:instruction-value instruction))
         (number (ecase operation (:join-path 5) (:read-directory 6) (:create-directory 7)))
         (result (mognitio.ir:instruction-type instruction))
         (args (mognitio.semantic::canonical-result-arguments context result))
         (error-type (second args))
         (fields (mognitio.semantic:type-info-fields (mognitio.semantic:context-type context error-type)))
         (operation-type (cdar fields)) (kind-type (cdr (second fields))) (phase-type (cdr (fourth fields))))
    (runtime-unit (second (value-helper-name instruction))
      (append (helper-frame 100) (helper-root-link 8)
        (loop for record in '(-240 -304 -368) append
          `((:imm-rax -1) (:store-frame ,(+ record 8) :rax)
            (:load-word :rax :r15 272) (:store-frame ,record :rax)
            (:lea-base :rax :rbp ,record) (:store-word :r15 272 :rax)))
        '((:load-frame :rax 16) (:store-frame -8 :rax) (:imm-rax -1) (:store-frame -96 :rax))
        (ecase operation
          (:join-path (append '((:load-frame :rax 24) (:store-frame -16 :rax))
                        (directory-validate-path-forms :base -8 nil)
                        (directory-validate-path-forms :relative -16 t)
                        (directory-join-forms :join) '((:jmp :body-done))))
          (:create-directory (directory-create-forms))
          (:read-directory (directory-read-forms)))
        '((:label :invalid-path) (:imm-rax 0) (:store-frame -96 :rax) (:jmp :body-done)
          (:label :unsupported) (:imm-rax 4) (:store-frame -96 :rax) (:jmp :body-done)
          (:label :invalid-encoding) (:imm-rax 1) (:store-frame -96 :rax) (:jmp :body-done)
          (:label :os-error) (:call (:runtime :directory.errno)) (:store-frame -96 :rax)
          (:label :body-done) (:load-frame :rax -720) (:store-frame -728 :rax)
          (:lea-base :rax :rbp -240) (:store-out 0 :rax))
        (if (eq operation :read-directory)
            (scoped-forms :close-injection (directory-fault-forms :close '((:call (:runtime :io.close)))))
            '((:call (:runtime :io.close))))
        (scoped-forms :close (directory-status-forms :close :close-error))
        '((:jmp :closed) (:label :close-error) (:load-frame :rcx -96) (:cmp-imm :rcx -1) (:jnz :closed)
          (:call (:runtime :directory.errno)) (:store-frame -96 :rax)
          (:imm-rax 3) (:store-frame -728 :rax)
          (:label :closed) (:load-frame :rax -96) (:cmp-imm :rax -1) (:jnz :failure-subject))
        (when (eq operation :read-directory) (directory-materialize-forms (first args) context))
        '((:jmp :cleanup) (:label :failure-subject) (:load-frame :rax -112) (:test) (:jz :cleanup))
        (directory-name-forms -16)
        (directory-join-forms :child-subject)
        '((:load-frame :rax -24) (:store-frame -8 :rax) (:jmp :cleanup)
          (:label :internal) (:imm-rax 1) (:store-frame -104 :rax) (:label :cleanup))
        (case (option :directory-corrupt-record)
          (:zero-size '((:imm-rax 0) (:store-frame -216 :rax)))
          (:unaligned '((:load-frame :rax -224) (:add-imm :rax 1) (:store-frame -224 :rax)))
          (:cycle '((:lea-base :rax :rbp -368) (:store-frame -368 :rax)))
          (:fd '((:imm-rax -2) (:store-frame -232 :rax))))
        (loop for record in '(-368 -304 -240) for i from 0 append
          (scoped-forms (intern (format nil "RELEASE-~D" i) :keyword)
            `((:lea-base :rax :rbp ,record) (:store-out 0 :rax) (:call (:runtime :directory.cleanup))
              (:cmp-imm :rdx 0) (:jz :external) (:store-frame -104 :rdx)
              (:label :external) (:test) (:jz :released)
              (:load-frame :rcx -96) (:cmp-imm :rcx -1) (:jnz :released)
              (:call (:runtime :directory.errno)) (:store-frame -96 :rax)
              (:imm-rax 3) (:store-frame -728 :rax)
              (:label :released)
              ,@(when (/= record -240)
                  `((:load-frame :rax ,record) (:lea-base :rcx :rbp ,(+ record 64))
                    (:cmp) (:jz :link-valid) (:imm-rax 1) (:store-frame -104 :rax)
                    (:lea-base :rax :rbp ,(+ record 64)) (:store-frame ,record :rax) (:label :link-valid)))
              (:load-frame :rax ,record) (:store-word :r15 272 :rax))))
        '((:load-frame :rax -104) (:test) (:jnz (:runtime :directory.internal))
          (:load-frame :rax -96) (:cmp-imm :rax -1) (:jz :ok))
        (allocate-object :operation (list :descriptor (second operation-type) number) 2 0 number)
        '((:store-frame -32 :rdx))
        (loop for kind below 8 append
          (let ((next (intern (format nil "ERROR-KIND-~D" kind) :keyword)))
            (append `((:load-frame :rax -96) (:cmp-imm :rax ,kind) (:jnz ,next))
              (allocate-object next (list :descriptor (second kind-type) kind) 2 0 kind)
              '((:store-frame -40 :rdx) (:jmp :error-value)) `((:label ,next)))))
        '((:jmp (:runtime :directory.internal)) (:label :error-value))
        (io-phase-object-forms phase-type -728 -56)
        (allocate-object :error (list :descriptor (second error-type) 0) 1 4)
        '((:load-frame :rax -32) (:store-word :rdx 32 :rax) (:load-frame :rax -40) (:store-word :rdx 40 :rax)
          (:load-frame :rax -8) (:store-word :rdx 48 :rax)
          (:load-frame :rax -56) (:store-word :rdx 56 :rax) (:store-frame -48 :rdx))
        (result-construction :err result 1 -48)
        '((:jmp :done) (:label :ok)) (result-construction :ok result 0 -24)
        '((:label :done)) (helper-root-unlink 8) (helper-return)) :helper)))
