(in-package #:mognitio.native.runtime)

(defun allocate-bytes-forms (size-slot)
  (let ((limit (option :bytes-length-limit 9223372036854775807)))
    (unless (typep limit '(integer 0 9223372036854775807)) (internal-error "Invalid Bytes test limit"))
    (append
      `((:load-frame :rax ,size-slot) (:imm-rcx ,limit) (:cmp) (:ja :bytes-length-overflow)
        (:test) (:jz :empty-bytes)
        (:imm-rcx 9223372036854775760) (:cmp) (:ja :allocation-failed)
        (:add-imm :rax 8) (:store-out 0 :rax) (:call (:runtime :allocate-block)))
      (scoped-forms :bytes (initialize-object (layout-name '(:bytes)) 7))
      `((:load-frame :rax ,size-slot) (:store-word :rdx 32 :rax) (:mov-reg :rax :rdx)
        (:jmp :bytes-ready) (:label :empty-bytes) (:lea-object ,(static-name :bytes 0))
        (:label :bytes-ready) (:store-frame -8 :rax)))))

(defun copy-octets-forms (prefix)
  ;; RSI/RDI are source/destination, RCX is the exact byte count. No safepoint.
  (scoped-forms prefix
    '((:label :copy) (:test-rcx) (:jz :copied)
      (:load-byte :rax :rsi 0) (:store-byte :rdi 0 :rax)
      (:add-imm :rsi 1) (:add-imm :rdi 1) (:dec-rcx) (:jmp :copy)
      (:label :copied))))

(defun bytes-construction-forms (op)
  (append
    '((:load-frame :rdx 16) (:load-word :rax :rdx 32) (:store-frame -48 :rax) (:store-frame -80 :rax))
    (when (eq op :bytes.from-ints)
      '((:lea-base :r8 :rdx 40) (:imm-reg :r10 0) (:mov-reg :r9 :rax)
        (:label :validate) (:cmp-reg :r10 :r9) (:jae :valid)
        (:load-word :rax :r8 0) (:cmp-imm :rax 255) (:ja :invalid-byte)
        (:add-imm :r8 8) (:add-imm :r10 1) (:jmp :validate)
        (:label :invalid-byte) (:store-frame -56 :r10) (:store-frame -64 :rax) (:jmp :invalid)
        (:label :valid)))
    (allocate-bytes-forms -80)
    '((:lea-base :rdi :rax 40) (:load-frame :rsi 16) (:add-imm :rsi 40)
      (:load-frame :rcx -80) (:label :copy-elements) (:test-rcx) (:jz :elements-ready)
      (:load-word :rax :rsi 0) (:store-byte :rdi 0 :rax)
      (:add-imm :rsi 8) (:add-imm :rdi 1) (:dec-rcx) (:jmp :copy-elements)
      (:label :elements-ready) (:load-frame :rax -8))))

(defun bytes-edit-forms (op)
  (append
    '((:load-frame :rdx 16) (:load-word :rax :rdx 32) (:store-frame -48 :rax))
    (case op
      (:bytes.append '((:add-imm :rax 1)))
      (:bytes.concat '((:load-frame :rdx 24) (:load-word :rcx :rdx 32) (:add)))
      (:bytes.slice
       '((:load-frame :rax 24) (:test) (:js :invalid) (:load-frame :rcx 32)
         (:cmp) (:ja :invalid) (:load-frame :rdx -48) (:cmp-reg :rcx :rdx) (:ja :invalid)
         (:sub-reg :rcx :rax) (:mov-reg :rax :rcx))))
    '((:store-frame -80 :rax))
    (allocate-bytes-forms -80)
    '((:lea-base :rdi :rax 40) (:load-frame :rsi 16) (:add-imm :rsi 40))
    (if (eq op :bytes.slice)
        '((:load-frame :rax 24) (:add-reg :rsi :rax) (:load-frame :rcx -80))
        '((:load-frame :rcx -48)))
    (copy-octets-forms :first)
    (case op
      (:bytes.append '((:load-frame :rax 24) (:store-byte :rdi 0 :rax)))
      (:bytes.concat
       (append '((:load-frame :rsi 24) (:load-word :rcx :rsi 32) (:add-imm :rsi 40))
               (copy-octets-forms :second))))
    '((:load-frame :rax -8))))

(defun bytes-equality-forms (op)
  (append
    '((:load-frame :rsi 16) (:load-frame :rdi 24)
      (:load-word :rax :rsi 32) (:load-word :rcx :rdi 32) (:cmp) (:jnz :different)
      (:add-imm :rsi 40) (:add-imm :rdi 40) (:mov-reg :r9 :rcx)
      (:label :compare) (:cmp-imm :r9 0) (:jz :equal)
      (:load-byte :rax :rsi 0) (:load-byte :rcx :rdi 0) (:cmp) (:jnz :different)
      (:add-imm :rsi 1) (:add-imm :rdi 1) (:add-imm :r9 -1) (:jmp :compare)
      (:label :equal))
    `((:imm-rax ,(if (eq op :bytes.equal) 1 0)) (:jmp :done)
      (:label :different) (:imm-rax ,(if (eq op :bytes.equal) 0 1)) (:label :done))))

(defun bytes-encoding-forms (op width)
  (if (eq op :bits.to-bytes)
      (if (not (zerop (mod width 8))) '((:jmp :invalid))
          (append
            `((:imm-rax ,(/ width 8)) (:store-frame -80 :rax))
            (allocate-bytes-forms -80)
            `((:lea-base :rdi :rax 40) (:imm-reg :r10 1)
              (:load-frame :rdx 24) (:load-word :rcx :rdx 24)
              (:test-rcx) (:jz :ordered) (:add-imm :rdi ,(1- (/ width 8))) (:imm-reg :r10 -1)
              (:label :ordered) (:load-frame :r11 16) (:imm-reg :r9 ,(/ width 8))
              (:label :encode) (:store-byte :rdi 0 :r11) (:imm-rcx 8)
              (:mov-reg :rax :r11) (:shr-cl) (:mov-reg :r11 :rax)
              (:add-reg :rdi :r10) (:add-imm :r9 -1) (:cmp-imm :r9 0) (:jnz :encode)
              (:load-frame :rax -8))))
      (append
        '((:load-frame :rdi 16) (:load-word :rax :rdi 32) (:store-frame -48 :rax))
        (if (not (zerop (mod width 8))) '((:jmp :invalid))
            `((:cmp-imm :rax ,(/ width 8)) (:jnz :invalid)
              (:add-imm :rdi 40) (:imm-reg :r10 1)
              (:load-frame :rdx 24) (:load-word :rcx :rdx 24)
              (:test-rcx) (:jnz :ordered) (:add-imm :rdi ,(1- (/ width 8))) (:imm-reg :r10 -1)
              (:label :ordered) (:imm-rax 0) (:imm-reg :r9 ,(/ width 8))
              (:label :decode) (:imm-rcx 8) (:shl-cl)
              (:load-byte :rcx :rdi 0) (:or-rcx)
              (:add-reg :rdi :r10) (:add-imm :r9 -1) (:cmp-imm :r9 0) (:jnz :decode))))))

(defun binary-operation-unit (inst context)
  (let* ((op (mognitio.ir:instruction-op inst)) (source (mognitio.ir:instruction-value inst))
         (result (mognitio.ir:instruction-type inst))
         (parts (mognitio.semantic::canonical-result-arguments context result))
         (success (first parts)) (error (second parts))
         (width (cond ((eq op :bits.to-bytes) (second (second source)))
                      ((eq op :bytes.to-bits) (second (second success)))))
         (allocating (not (member op '(:bytes.length :bytes.equal :bytes.not-equal)))))
    (runtime-unit (second (value-helper-name inst))
      (append (helper-frame (if allocating 20 2))
        (when allocating (helper-root-link 1))
        (case op
          ((:bytes.from-ints :bytes.from-bits) (bytes-construction-forms op))
          ((:bytes.append :bytes.concat :bytes.slice) (bytes-edit-forms op))
          ((:bytes.equal :bytes.not-equal) (bytes-equality-forms op))
          (:bytes.length '((:load-frame :rdx 16) (:load-word :rax :rdx 32)))
          (:bytes.at
           '((:load-frame :rdx 16) (:load-word :rcx :rdx 32) (:store-frame -48 :rcx)
             (:load-frame :rax 24) (:cmp) (:jae :invalid)
             (:add-reg :rdx :rax) (:load-byte :rax :rdx 40)))
          ((:bits.to-bytes :bytes.to-bits) (bytes-encoding-forms op width)))
        (when parts
          (let ((fields (case op
                          (:bytes.from-ints '(-56 -64)) (:bytes.at '(24 -48))
                          (:bytes.slice '(24 32 -48))
                          (:bits.to-bytes (list (list :constant width)))
                          (:bytes.to-bits (list (list :constant width) -48)))))
            (append
              (unless (eq success :bytes) '((:store-frame -32 :rax)))
              (result-construction :ok result 0 (if (eq success :bytes) -8 -32))
              '((:jmp :done) (:label :invalid))
              (allocate-object :error (list :descriptor (second error) 0) 1 (length fields))
              (loop for field in fields for offset from 32 by 8
                    append (list (if (consp field) (list :imm-rax (second field))
                                     (list :load-frame :rax field))
                                 (list :store-word :rdx offset :rax)))
              '((:store-frame -8 :rdx))
              (result-construction :err result 1 -8)
              '((:label :done)))))
        (when allocating (helper-root-unlink 1))
        (helper-return)) :helper)))
