(in-package #:mognitio.native.runtime)

(defun returning-test-helper-writes (form)
  ;; Closed, independent description of every admitted opcode, including implicit
  ;; destinations. Adding an opcode requires specifying its register effects here.
  (case (first form)
    ((:mov-reg :load-frame :load-word :lea-base :add-imm :add-reg) (list (second form)))
    ((:imm-rax :mov-eax :mul) '(:rax))
    (:imm-rcx '(:rcx))
    ((:imm-rdx :sub-rdx) '(:rdx))
    (:mov-edi '(:rdi))
    (:add-rsi '(:rsi))
    (:syscall '(:rax :rcx :r11))
    ((:push-rbp :push-zero :ret) '(:rsp))
    (:pop-rbp '(:rbp :rsp))
    (:call '(:rsp :rax :rcx :rdx :rsi :rdi :r8 :r9 :r10 :r11))
    ((:label :store-frame :store-word :cmp-eintr :jz :jnz :jle :jmp :test :ud2) nil)
    (otherwise (internal-error "Unsupported effect in returning test helper"))))

(defun verify-returning-test-helper (unit)
  ;; Independent effect/frame check of the actual Machine instructions.
  ;; Neither helper effects nor the register allocator's barrier table are evidence.
  (let* ((name (second (mognitio.object:code-unit-entry unit)))
         (words (ecase name (:test.stage 0) (:test.event 8)))
         (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                          (mognitio.machine:instruction-operands i)))
                        (mognitio.object:code-unit-instructions unit)))
         (labels (loop for f in forms when (eq (car f) :label) collect (second f)))
         (returns 0) (calls 0))
    (unless (and (>= (length forms) (+ 6 words))
                 (equal (subseq forms 0 (+ 3 words))
                        (append (list (list :label (list :helper name)) '(:push-rbp) '(:mov-reg :rbp :rsp))
                                (make-list words :initial-element '(:push-zero)))))
      (internal-error "Invalid returning test helper frame"))
    (loop for tail on forms for f = (first tail) for index from 0 for op = (first f) do
      (let ((writes (returning-test-helper-writes f)))
        (when (intersection writes '(:rbx :r12 :r13 :r14 :r15))
          (internal-error "Returning test helper clobbers a callee save"))
        (when (intersection writes '(:rbp :rsp))
          (unless (case op
                    (:push-rbp (= index 1))
                    (:push-zero (<= 3 index (+ 2 words)))
                    (:mov-reg (or (and (= index 2) (equal f '(:mov-reg :rbp :rsp)))
                                  (and (= index (- (length forms) 3))
                                       (equal tail '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret))))))
                    (:pop-rbp (= index (- (length forms) 2)))
                    (:ret (= index (1- (length forms))))
                    ;; The only admitted call is the independently checked returning
                    ;; event helper. Its balanced call/return temporarily changes RSP.
                    (:call (and (eq name :test.stage) (equal (second f) '(:helper :test.event))
                                (<= (+ 3 words) index (- (length forms) 4)))))
            (internal-error "Returning test helper clobbers its frame registers"))))
      (when (member op '(:store-frame :load-frame))
        (let ((offset (if (eq op :store-frame) (second f) (third f))))
          (unless (and (integerp offset) (zerop (mod offset 8)) (<= (- (* 8 words)) offset -8))
            (internal-error "Helper stack access escapes its frame"))))
      (when (eq op :store-word)
        (unless (equal f (list :store-word :r15 (if (eq name :test.stage) 240 248) :rax))
          (internal-error "Unexpected helper context write")))
      (when (and (member op '(:push-rbp :push-zero)) (>= index (+ 3 words)))
        (internal-error "Unbalanced helper stack"))
      (when (eq op :pop-rbp)
        (unless (and (equal (nth (1- index) forms) '(:mov-reg :rsp :rbp)) (equal (second tail) '(:ret)))
          (internal-error "Unbalanced helper frame pointer")))
      (when (eq op :ret)
        (incf returns)
        (unless (equal (subseq forms (- index 2) (1+ index)) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))
          (internal-error "Invalid returning helper epilogue")))
      (when (eq op :call)
        (incf calls)
        (unless (and (eq name :test.stage) (equal (second f) '(:helper :test.event)))
          (internal-error "Returning test helper calls an allocating or unknown helper")))
      (when (member op '(:jmp :jz :jnz :jle))
        (unless (member (second f) labels :test #'equal) (internal-error "Helper jumps outside its checked body"))))
    (unless (and (= returns 1) (= calls (if (eq name :test.stage) 1 0)))
      (internal-error "Missing returning helper control path")))
  unit)

(defun verified-test-helper-units ()
  (let ((units (test-helper-units)))
    (dolist (unit units)
      (when (member (second (mognitio.object:code-unit-entry unit)) '(:test.stage :test.event))
        (verify-returning-test-helper unit)))
    units))
