(in-package #:mognitio.native.runtime)

(defun scoped-forms (prefix forms)
  (let* ((labels (loop for form in forms when (eq :label (first form)) collect (second form)))
         (map (mapcar (lambda (label) (cons label (intern (format nil "~A-~A" prefix label) :keyword))) labels)))
    (mapcar (lambda (form) (cons (first form) (mapcar (lambda (arg) (or (cdr (assoc arg map)) arg)) (rest form)))) forms)))
(defun helper-root-link (count)
  (let ((header (- (* 8 (+ 2 count)))))
    `((:load-word :rax :r15 0) (:store-frame ,header :rax) (:imm-rax ,count) (:store-frame ,(+ header 8) :rax)
      (:lea-base :rax :rbp ,header) (:store-word :r15 0 :rax))))
(defun helper-root-unlink (count)
  `((:load-frame :rcx ,(- (* 8 (+ 2 count)))) (:store-word :r15 0 :rcx)))
(defun allocate-object (prefix descriptor kind words &optional (variant 0))
  (append `((:imm-rax ,(* 8 (max 1 words))) (:store-out 0 :rax) (:call (:runtime :allocate-block)))
          (scoped-forms prefix (initialize-object descriptor kind variant))))
(defun result-construction (prefix result variant slot)
  (append (allocate-object prefix (list :descriptor (second result) variant) 2 1 variant)
          `((:load-frame :rax ,slot) (:store-word :rdx 32 :rax) (:mov-reg :rax :rdx))))
(defun list-append-unit (inst)
  (let ((type (mognitio.ir:instruction-type inst)))
    (runtime-unit (second (value-helper-name inst))
      (append (helper-frame 2)
        '((:load-frame :rax 16) (:load-word :rax :rax 32) (:imm-rcx 9223372036854775807)
          (:cmp) (:jz :list-length-overflow))
        (allocate-object :node (layout-name (list :list type)) 5 3)
        '((:load-frame :rax 16) (:store-word :rdx 40 :rax) (:load-word :rax :rax 32) (:add-imm :rax 1)
          (:store-word :rdx 32 :rax) (:load-frame :rax 24) (:store-word :rdx 48 :rax) (:mov-reg :rax :rdx))
        (helper-return)) :helper)))
(defun list-at-unit (inst context)
  (let* ((result (mognitio.ir:instruction-type inst)) (args (mognitio.semantic::canonical-result-arguments context result))
         (element (first args)) (error (second args)))
    (runtime-unit (second (value-helper-name inst))
      (append (helper-frame 10) (helper-root-link 1)
        '((:load-frame :rax 24) (:test) (:js :invalid) (:load-frame :rdx 16) (:load-word :rcx :rdx 32)
          (:cmp) (:jae :invalid) (:add-imm :rcx -1) (:sub-reg :rcx :rax)
          (:label :walk) (:test-rcx) (:jz :found) (:load-word :rdx :rdx 40) (:dec-rcx) (:jmp :walk)
          (:label :found) (:load-word :rax :rdx 48) (:store-frame -32 :rax))
        (when (mognitio.semantic:reference-type-p element) '((:store-frame -8 :rax)))
        (result-construction :ok result 0 -32) '((:jmp :done) (:label :invalid))
        (allocate-object :error (list :descriptor (second error) 0) 1 2)
        '((:load-frame :rax 24) (:store-word :rdx 32 :rax) (:load-frame :rax 16) (:load-word :rax :rax 32)
          (:store-word :rdx 40 :rax) (:store-frame -8 :rdx))
        (result-construction :err result 1 -8)
        '((:label :done)) (helper-root-unlink 1) (helper-return)) :helper)))
(defun list-buffer-unit (inst)
  (let ((element (second (mognitio.ir:instruction-type inst))))
    (runtime-unit (second (value-helper-name inst))
      (append (helper-frame 6)
        `((:load-frame :rax 16) (:load-word :rax :rax 32) (:test) (:jz :empty) (:store-frame -8 :rax)
          (:imm-rcx ,(floor (- mognitio.integer:+maximum+ 40) 8)) (:cmp) (:ja :allocation-failed)
          (:add-imm :rax 1) (:imm-rcx 8) (:mul) (:store-out 0 :rax) (:call (:runtime :allocate-block)))
        (initialize-object (layout-name (list :buffer element)) 6)
        '((:load-frame :rcx -8) (:store-word :rdx 32 :rcx) (:mov-reg :r9 :rdx)
          (:mov-reg :rax :rcx) (:imm-rcx 8) (:mul) (:lea-base :r8 :r9 32) (:add-reg :r8 :rax)
          (:load-frame :rdx 16) (:load-frame :rcx -8)
          (:label :fill) (:test-rcx) (:jz :ready) (:load-word :rax :rdx 48) (:store-word :r8 0 :rax)
          (:add-imm :r8 -8) (:load-word :rdx :rdx 40) (:dec-rcx) (:jmp :fill)
          (:label :ready) (:mov-reg :rax :r9) (:jmp :done) (:label :empty))
        `((:lea-object ,(static-name :buffer element)) (:label :done))
        (helper-return)) :helper)))
(defun slice-result-unit (inst context)
  (let* ((result (mognitio.ir:instruction-type inst))
         (error (second (mognitio.semantic::canonical-result-arguments context result))))
    (runtime-unit (second (value-helper-name inst))
      (append (helper-frame 10) (helper-root-link 1)
        '((:load-frame :rax 24) (:test) (:js :invalid) (:load-frame :rcx 32) (:cmp) (:ja :invalid)
          (:load-frame :rdx 16) (:load-word :rdx :rdx 24) (:cmp-reg :rcx :rdx) (:ja :invalid)
          (:load-frame :rax 16) (:store-out 0 :rax) (:load-frame :rax 24) (:store-out 8 :rax)
          (:load-frame :rax 32) (:store-out 16 :rax) (:call (:helper :text.slice)) (:store-frame -8 :rax))
        (result-construction :ok result 0 -8) '((:jmp :done) (:label :invalid))
        (allocate-object :error (list :descriptor (second error) 0) 1 3)
        '((:load-frame :rax 24) (:store-word :rdx 32 :rax) (:load-frame :rax 32) (:store-word :rdx 40 :rax)
          (:load-frame :rax 16) (:load-word :rax :rax 24) (:store-word :rdx 48 :rax) (:store-frame -8 :rdx))
        (result-construction :err result 1 -8)
        '((:label :done)) (helper-root-unlink 1) (helper-return)) :helper)))
