(in-package #:mognitio.native.runtime)

(defun verify-returning-test-helper (unit)
  ;; Independent effect/frame check of the actual Machine instructions.
  ;; Neither helper effects nor the register allocator's barrier table are evidence.
  (let* ((name (second (mognitio.object:code-unit-entry unit)))
         (words (ecase name (:test.stage 0) (:test.event 8)))
         (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                          (mognitio.machine:instruction-operands i)))
                        (mognitio.object:code-unit-instructions unit)))
         (labels (loop for f in forms when (eq (car f) :label) collect (second f)))
         (returns 0) (calls 0))
    (unless (and (equal (subseq forms 0 (+ 3 words))
                        (append (list (list :label (list :helper name)) '(:push-rbp) '(:mov-reg :rbp :rsp))
                                (make-list words :initial-element '(:push-zero)))))
      (internal-error "Invalid returning test helper frame"))
    (loop for tail on forms for f = (first tail) for index from 0 for op = (first f) do
      (unless (member op '(:label :push-rbp :push-zero :mov-reg :store-frame :load-frame :load-word
                           :store-word :imm-rax :imm-rcx :imm-rdx :lea-base :add-imm :add-reg :mul
                           :mov-edi :mov-eax :syscall :cmp-eintr :jz :jnz :jle :jmp :test
                           :add-rsi :sub-rdx :ud2 :pop-rbp :ret :call))
        (internal-error "Unsupported effect in returning test helper"))
      (when (and (member op '(:mov-reg :load-frame :load-word :lea-base :add-imm :add-reg))
                 (member (second f) '(:rbx :r12 :r13 :r14 :r15)))
        (internal-error "Returning test helper clobbers a callee save"))
      (when (and (eq op :mov-reg) (member (second f) '(:rsp :rbp)))
        (unless (or (and (= index 2) (equal f '(:mov-reg :rbp :rsp)))
                    (and (equal f '(:mov-reg :rsp :rbp)) (equal (subseq tail 0 3) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))))
          (internal-error "Invalid helper frame restoration")))
      (when (member op '(:store-frame :load-frame))
        (let ((offset (if (eq op :store-frame) (second f) (third f))))
          (unless (and (integerp offset) (zerop (mod offset 8)) (<= (- (* 8 words)) offset -8))
            (internal-error "Helper stack access escapes its frame"))))
      (when (eq op :store-word)
        (unless (equal f (list :store-word :r15 (if (eq name :test.stage) 240 248) :rax))
          (internal-error "Unexpected helper context write")))
      (when (and (member op '(:push-rbp :push-zero)) (>= index (+ 3 words)))
        (internal-error "Unbalanced helper stack"))
      (when (eq op :pop-rbp)
        (unless (and (equal (nth (1- index) forms) '(:mov-reg :rsp :rbp)) (equal (second tail) '(:ret)))
          (internal-error "Unbalanced helper frame pointer")))
      (when (eq op :ret)
        (incf returns)
        (unless (equal (subseq forms (- index 2) (1+ index)) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))
          (internal-error "Invalid returning helper epilogue")))
      (when (eq op :call)
        (incf calls)
        (unless (and (eq name :test.stage) (equal (second f) '(:helper :test.event)))
          (internal-error "Returning test helper calls an allocating or unknown helper")))
      (when (member op '(:jmp :jz :jnz :jle))
        (unless (member (second f) labels :test #'equal) (internal-error "Helper jumps outside its checked body"))))
    (unless (and (= returns 1) (= calls (if (eq name :test.stage) 1 0)))
      (internal-error "Missing returning helper control path")))
  unit)

(defun verified-test-helper-units ()
  (let ((units (test-helper-units)))
    (dolist (unit units)
      (when (member (second (mognitio.object:code-unit-entry unit)) '(:test.stage :test.event))
        (verify-returning-test-helper unit)))
    units))
