(in-package #:mognitio.backend.native)

(defun verify-native-metadata (module bytes symbols)
  ;; Read encoded words, independently of the descriptor/metadata producer.
  (let ((seen (make-hash-table :test #'equal)) (lists nil)
        (context (mognitio.ir:module-values module)))
    (labels ((ensure (ok) (unless ok (internal-error "Invalid encoded native metadata")))
             (offset (name)
               (let ((symbol (gethash name symbols)))
                 (ensure symbol) (mognitio.object:image-symbol-offset symbol)))
             (address (name)
               (+ mognitio.object::+image-base+ mognitio.object::+code-offset+ (offset name)))
             (record (name words)
               (let ((start (offset name)))
                 (ensure (and (zerop (mod start 8)) (<= (+ start (* 8 (length words))) (length bytes))))
                 (loop for word in words for at from start by 8 do
                   (ensure (= word (loop for i below 8 sum (ash (aref bytes (+ at i)) (* i 8)))))))
               (setf (gethash name seen) t))
             (reference (type)
               (or (eq type :string) (and (consp type) (member (car type) '(:function :list :buffer :struct :enum :interface)))))
             (row (name kind identity variant slots &optional buffer)
               (let ((refs (loop for type in slots for i from 0 when (reference type) collect i)))
                 (record name (append (list kind identity variant (length slots) (length refs)) refs buffer))))
             (note (type)
               (when (consp type)
                 (case (first type)
                   (:list (pushnew type lists :test #'equal) (note (second type)))
                   (:buffer (note (list :list (second type))))
                   (:function (mapc #'note (second type)) (note (third type)))))))
      (loop for info across (mognitio.semantic:value-context-types context)
            for id = (mognitio.semantic:type-info-id info) do
        (mapc (lambda (p) (note (cdr p))) (mognitio.semantic:type-info-fields info))
        (mapc (lambda (v) (mapc #'note (mognitio.semantic:variant-info-types v))) (mognitio.semantic:type-info-variants info))
        (case (mognitio.semantic:type-info-kind info)
          (:struct (row (list :descriptor id 0) 1 id 0 (mapcar #'cdr (mognitio.semantic:type-info-fields info))))
          (:enum (dolist (v (mognitio.semantic:type-info-variants info))
                   (row (list :descriptor id (mognitio.semantic:variant-info-id v)) 2 id
                        (mognitio.semantic:variant-info-id v) (mognitio.semantic:variant-info-types v))))))
      (loop for implementation across (mognitio.semantic:value-context-implementations context)
            for id = (mognitio.semantic:implementation-info-id implementation)
            for contract = (mognitio.semantic:implementation-info-contract implementation) do
        (row (list :layout (list :package id)) 3 id 0 (list (mognitio.semantic:implementation-info-concrete implementation)))
        (let* ((methods (mognitio.semantic:type-info-methods (mognitio.semantic:context-type context contract)))
               (entries (mapcar (lambda (requirement)
                         (let ((signature (cdr (assoc (mognitio.semantic:requirement-name requirement)
                                              (mognitio.semantic:implementation-info-methods implementation) :test #'string=))))
                           (address (list :function (mognitio.semantic:signature-id signature))))) methods)))
          (record (list :method-table id) (append (list id (second contract) (length methods)) entries))))
      (dolist (function (mognitio.ir:module-functions module))
        (let ((id (mognitio.ir:ir-function-id function)) (captures (mognitio.ir::ir-function-capture-types function)))
          (mapc #'note (mognitio.ir:ir-function-parameter-types function))
          (note (mognitio.ir:ir-function-result-type function)) (mapc #'note captures)
          (dolist (block (mognitio.ir:ir-function-blocks function))
            (mapc (lambda (p) (note (cdr p))) (mognitio.ir:basic-block-parameters block))
            (mapc (lambda (i) (note (mognitio.ir:instruction-type i))) (mognitio.ir:basic-block-instructions block)))
          (when (and (plusp id) (null (mognitio.ir:ir-function-method function)))
            (let ((descriptor (list :layout (list :closure id))))
              (row descriptor 4 id 0 (cons :code captures))
              (unless captures
                (record (list :static-object :closure id)
                        (list 40 69 (address descriptor) 0 (address (list :function id)))))))))
      (setf lists (sort lists #'mognitio.semantic::structural-key-before-p))
      (loop for type in lists for id from 0 for element = (second type) do
        (let ((list-name (list :layout (list :list type))) (buffer-name (list :layout (list :buffer element))))
          (row list-name 5 id 0 (list :int type element))
          (row buffer-name 6 id 0 '(:int) (list (if (reference element) 1 0)))
          (record (list :static-object :list type) (list 56 85 (address list-name) 0 0 0 0))
          (record (list :static-object :buffer element) (list 40 101 (address buffer-name) 0 0))))
      (loop for literal across (mognitio.ir:module-literal-pool module) for id from 0
            for payload = (mognitio.syntax:text-payload-octets literal)
            for size = (* 8 (ceiling (+ 32 (length payload)) 8))
            for name = (list :text id) do
        (record name (list size 5 (length payload) (mognitio.syntax:text-payload-scalar-count literal)))
        (ensure (equalp payload (subseq bytes (+ (offset name) 32) (+ (offset name) 32 (length payload))))))
      (maphash (lambda (name symbol)
                 (when (member (mognitio.object:image-symbol-kind symbol) '(:text :metadata :object))
                   (ensure (gethash name seen)))) symbols))
    t))
