(in-package #:mognitio.native.runtime)

(defun publication-stack-string (text offset)
  (let ((bytes (sb-ext:string-to-octets text :external-format :utf-8 :null-terminate t)))
    (loop for start from 0 below (length bytes) by 8 append
      `((:imm-rax ,(numeric-word (loop for j below (min 8 (- (length bytes) start))
                                     sum (ash (aref bytes (+ start j)) (* j 8)))))
        (:store-frame ,(+ offset start) :rax)))))
(defun publication-match-string (text offset failure)
  (loop for byte across (sb-ext:string-to-octets text :external-format :utf-8 :null-terminate t)
        for at from offset append
    `((:load-byte :rax :rbp ,at) (:cmp-imm :rax ,byte) (:jnz ,failure))))

(defun publication-unit (name forms &optional (kind :runtime))
  (let ((serial 0)
        (base (cond ((consp name) -1280) ((eq name :publication.profile) -4800) (t -320)))
        (faults (option :publication-faults)))
    (runtime-unit name
      (loop for form in forms append
        (if (eq (first form) :publication-syscall)
            (let* ((phase (second form)) (number (third form))
                   (rows (remove-if-not (lambda (row) (eq (first row) phase)) faults))
                   (counter (- base (* 8 (incf serial)))))
              (if (null rows) (list (list :mov-eax number) '(:syscall))
                  (scoped-forms (list :fault serial)
                    (append
                      `((:load-frame :rax ,counter) (:add-imm :rax 1) (:store-frame ,counter :rax))
                      (loop for row in rows for index from 0 append
                        (destructuring-bind (at ordinal value &optional after) row
                          (declare (ignore at))
                          (append
                            (unless (zerop ordinal) `((:cmp-imm :rax ,ordinal) (:jnz ,(intern (format nil "NEXT-~D" index) :keyword))))
                            (cond
                              ((eq after :limit)
                               (unless (and (eq phase :write) (plusp value)) (internal-error "Invalid short write fixture"))
                               `((:cmp-imm :rdx ,value) (:jbe :real) (:imm-rdx ,value) (:jmp :real)))
                              (after `((:mov-eax ,number) (:syscall) (:imm-rax ,value) (:jmp :done)))
                              ((member phase '(:close-file :close-probe :close-parent))
                               `((:mov-eax ,number) (:syscall) (:imm-rax ,value) (:jmp :done)))
                              (t `((:imm-rax ,value) (:jmp :done))))
                            `((:label ,(intern (format nil "NEXT-~D" index) :keyword))))))
                      `((:label :real) (:mov-eax ,number) (:syscall) (:label :done))))))
            (list form))) kind)))

(defun publication-profile-unit ()
  ;; The record pointer is the only argument. Probe fd ownership is recorded
  ;; before another syscall. The streaming parser never allocates or decodes text.
  (publication-unit :publication.profile
    (append (helper-frame 640)
      '((:load-frame :rax 16) (:store-frame -8 :rax)
        (:label :filesystem-query) (:load-frame :rax -8) (:load-word :rdi :rax 16) (:lea-base :rsi :rbp -512)
        (:publication-syscall :filesystem 138) (:cmp-eintr) (:jz :filesystem-query) (:test) (:js :done)
        (:load-frame :rax -512) (:imm-rcx 16914836) (:cmp) (:jnz :unsupported)
        (:label :mount-query) (:load-frame :rax -8) (:load-word :rdi :rax 16)
        (:lea-base :rsi :rbp -120) (:lea-base :r8 :rbp -512)
        (:mov-edx 4096) (:mov-r10d 4096) (:publication-syscall :mount-id 332)
        (:cmp-eintr) (:jz :mount-query) (:test) (:js :done) (:load-frame :rax -512) (:and-imm :rax 4096) (:jz :unsupported)
        (:load-frame :rax -368) (:store-frame -16 :rax)
        (:label :kernel-query) (:lea-base :rdi :rbp -512) (:publication-syscall :kernel 63) (:cmp-eintr) (:jz :kernel-query) (:test) (:js :done))
      (publication-match-string "Linux" -512 :unsupported)
      (publication-match-string "7.0.0-38-generic" -382 :unsupported)
      (publication-match-string "#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  4 09:10:14 UTC 2026" -317 :unsupported)
      (publication-match-string "x86_64" -252 :unsupported)
      (publication-stack-string "/proc/self/mountinfo" -120)
      '((:label :open) (:imm-reg :rdi -100) (:lea-base :rsi :rbp -120)
        (:mov-edx 524288) (:mov-r10d 0) (:publication-syscall :open-probe 257)
        (:cmp-eintr) (:jz :open) (:test) (:js :done)
        (:load-frame :rdx -8) (:store-word :rdx 80 :rax)
        (:label :read) (:load-frame :rax -8) (:load-word :rdi :rax 80)
        (:lea-base :rsi :rbp -4608) (:mov-edx 4096) (:publication-syscall :read-probe 0)
        (:cmp-eintr) (:jz :read) (:test) (:js :close) (:jz :eof)
        (:cmp-imm :rax 4096) (:ja (:runtime :directory.internal))
        (:store-frame -64 :rax) (:lea-base :rax :rbp -4608) (:store-frame -72 :rax)
        (:label :byte) (:load-frame :rdx -72) (:load-byte :r8 :rdx 0)
        (:add-imm :rdx 1) (:store-frame -72 :rdx)
        (:cmp-imm :r8 10) (:jz :line)
        (:load-frame :rax -32) (:cmp-imm :rax 0) (:jz :id)
        (:cmp-imm :rax 1) (:jz :separator) (:cmp-imm :rax 2) (:jz :filesystem)
        (:jmp :next)
        (:label :id) (:cmp-imm :r8 32) (:jz :id-done)
        (:cmp-imm :r8 48) (:jb :unsupported) (:cmp-imm :r8 57) (:ja :unsupported)
        (:load-frame :rax -24) (:imm-rcx 10) (:umul) (:cmp-imm :rdx 0) (:jnz :unsupported)
        (:add-imm :r8 -48) (:add-reg :rax :r8) (:jb :unsupported) (:store-frame -24 :rax)
        (:jmp :next)
        (:label :id-done) (:imm-rax 1) (:store-frame -32 :rax) (:store-frame -48 :rax) (:jmp :next)
        (:label :separator) (:load-frame :rax -48) (:cmp-imm :rax 2) (:jz :separator-end)
        (:cmp-imm :r8 32) (:jz :space) (:cmp-imm :rax 1) (:jnz :reset-separator)
        (:cmp-imm :r8 45) (:jnz :reset-separator) (:imm-rax 2) (:store-frame -48 :rax) (:jmp :next)
        (:label :space) (:imm-rax 1) (:store-frame -48 :rax) (:jmp :next)
        (:label :reset-separator) (:imm-rax 0) (:store-frame -48 :rax) (:jmp :next)
        (:label :separator-end) (:cmp-imm :r8 32) (:jnz :reset-separator)
        (:imm-rax 2) (:store-frame -32 :rax) (:jmp :next)
        (:label :filesystem) (:cmp-imm :r8 32) (:jz :filesystem-end)
        (:load-frame :rax -56))
      (loop for byte across #(116 109 112 102 115) for i from 0 append
        `((:cmp-imm :rax ,i) (:jnz ,(intern (format nil "FS-NEXT-~D" i) :keyword))
          (:cmp-imm :r8 ,byte) (:jnz :wrong-filesystem) (:add-imm :rax 1)
          (:store-frame -56 :rax) (:jmp :next)
          (:label ,(intern (format nil "FS-NEXT-~D" i) :keyword))))
      '((:label :wrong-filesystem) (:imm-rax -1) (:store-frame -56 :rax) (:jmp :next)
        (:label :filesystem-end) (:imm-rax 3) (:store-frame -32 :rax) (:jmp :next)
        (:label :line) (:load-frame :rax -24) (:load-frame :rcx -16) (:cmp) (:jnz :line-reset)
        (:load-frame :rax -32) (:cmp-imm :rax 3) (:jnz :unsupported)
        (:load-frame :rax -56) (:cmp-imm :rax 5) (:jnz :unsupported)
        (:load-frame :rax -40) (:add-imm :rax 1) (:store-frame -40 :rax)
        (:label :line-reset) (:imm-rax 0) (:store-frame -24 :rax) (:store-frame -32 :rax)
        (:store-frame -48 :rax) (:store-frame -56 :rax)
        (:label :next) (:load-frame :rax -64) (:add-imm :rax -1) (:store-frame -64 :rax)
        (:test) (:jnz :byte) (:jmp :read)
        (:label :eof) (:load-frame :rax -32) (:test) (:jnz :unsupported)
        (:load-frame :rax -24) (:test) (:jnz :unsupported)
        (:load-frame :rax -40) (:cmp-imm :rax 1) (:jnz :unsupported)
        (:imm-rax 0) (:jmp :close)
        (:label :unsupported) (:imm-rax -95)
        (:label :close) (:store-frame -88 :rax) (:load-frame :rdx -8) (:load-word :rdi :rdx 80)
        (:cmp-imm :rdi -1) (:jz :primary)
        (:imm-rax -1) (:store-word :rdx 80 :rax) (:publication-syscall :close-probe 3)
        (:test) (:jz :primary)
        (:imm-rdx 4) (:jmp :return)
        (:label :primary) (:load-frame :rax -88) (:test) (:jnz :done)
        ;; A certificate refines failure classification; it does not gate execution.
        (:load-frame :rdx -8) (:imm-rax 1) (:store-word :rdx 112 :rax)
        (:label :done) (:cmp-imm :rax -9) (:jz (:runtime :directory.internal))
        (:cmp-imm :rax -14) (:jz (:runtime :directory.internal))
        (:cmp-imm :rax -4095) (:jl (:runtime :directory.internal))
        (:imm-rax 0) (:imm-rdx 0)
        (:label :return))
      (helper-return))))
