(in-package #:mognitio.native.runtime)

(defun publication-path-forms ()
  (append
    '((:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:test-rcx) (:jz :invalid-path)
      (:add-imm :rsi 32) (:imm-reg :r8 -1) (:imm-reg :r9 0)
      (:label :path-byte) (:load-byte :rax :rsi 0) (:test) (:jz :invalid-path)
      (:cmp-imm :rax 47) (:jnz :not-slash) (:mov-reg :r8 :r9)
      (:label :not-slash) (:add-imm :rsi 1) (:add-imm :r9 1) (:dec-rcx) (:jnz :path-byte)
      (:cmp-imm :rax 47) (:jz :invalid-path) (:store-frame -112 :r8)
      (:imm-rax 1) (:store-frame -80 :rax)
      (:mov-reg :rax :r9) (:add-imm :rax 1) (:jo :allocation-failed)
      (:store-frame -216 :rax) (:store-out 0 :rax) (:call (:runtime :io.map))
      (:store-frame -224 :rax) (:mov-reg :rdi :rax)
      (:load-frame :rsi -8) (:load-word :rcx :rsi 16) (:add-imm :rsi 32))
    (copy-octets-forms :path-copy)
    '((:imm-rax 0) (:store-byte :rdi 0 :rax)
      (:load-frame :rdx -224) (:load-frame :rcx -112)
      (:cmp-imm :rcx -1) (:jz :relative)
      (:cmp-imm :rcx 0) (:jz :root)
      (:mov-reg :rsi :rdx) (:add-reg :rdx :rcx) (:store-byte :rdx 0 :rax)
      (:add-imm :rdx 1) (:jmp :parent-ready)
      (:label :relative) (:imm-rax 46) (:store-frame -416 :rax)
      (:lea-base :rsi :rbp -416) (:jmp :parent-ready)
      (:label :root) (:imm-rax 47) (:store-frame -416 :rax)
      (:lea-base :rsi :rbp -416) (:add-imm :rdx 1)
      (:label :parent-ready) (:store-frame -112 :rdx) (:store-frame -160 :rsi)
      (:label :open-parent) (:imm-reg :rdi -100) (:load-frame :rsi -160)
      (:mov-edx 2686976) (:mov-r10d 0) (:publication-syscall :open-parent 257)
      (:cmp-eintr) (:jz :open-parent) (:test) (:js :os-error) (:store-frame -240 :rax)
      (:label :target-stat) (:load-frame :rdi -240) (:load-frame :rsi -112)
      (:lea-base :rdx :rbp -640) (:mov-r10d 256) (:publication-syscall :target-stat 262)
      (:cmp-eintr) (:jz :target-stat) (:test) (:jz :already-exists)
      (:cmp-imm :rax -2) (:jnz :os-error)
      ;; Profile evidence is optional and cannot impose a filename byte limit.
      (:lea-base :rax :rbp -256) (:store-out 0 :rax)
      (:call (:runtime :publication.profile)) (:test) (:jz :profile-ready)
      (:cmp-imm :rdx 4) (:jnz :os-error) (:store-frame -80 :rdx) (:jmp :os-error)
      (:label :profile-ready)
      ;; Keep the NUL-terminated component in a rooted private Bytes object.
      ;; The mapping remains owned until this allocation and copy have completed.
      (:load-frame :rsi -112) (:mov-reg :rax :rsi) (:load-frame :rcx -224)
      (:sub-reg :rax :rcx) (:load-frame :rcx -216) (:sub-reg :rcx :rax)
      (:store-frame -160 :rcx) (:mov-reg :rax :rcx)
      (:imm-rcx 9223372036854775760) (:cmp) (:ja :allocation-failed)
      (:add-imm :rax 8) (:store-out 0 :rax) (:call (:runtime :allocate-block)))
    (scoped-forms :publication-name (initialize-object (layout-name '(:bytes)) 7))
    '((:load-frame :rax -160) (:store-word :rdx 32 :rax) (:store-frame -24 :rdx)
      (:lea-base :rdi :rdx 40) (:load-frame :rsi -112) (:load-frame :rcx -160))
    (copy-octets-forms :final-name)
    '((:load-frame :rax -24) (:add-imm :rax 40) (:store-frame -112 :rax)
      (:load-frame :rdi -224) (:load-frame :rsi -216) (:imm-rax 0) (:store-frame -224 :rax)
      (:publication-syscall :path-unmap 11) (:test) (:jz :path-released)
      (:cmp-imm :rax -22) (:jz :internal) (:cmp-imm :rax -14) (:jz :internal)
      (:imm-rcx 4) (:store-frame -80 :rcx) (:jmp :os-error)
      (:label :path-released))))

(defun publication-temp-forms ()
  (append
    '((:label :random) (:lea-base :rdi :rbp -400) (:load-frame :rax -128)
      (:add-reg :rdi :rax) (:imm-reg :rsi 16) (:sub-reg :rsi :rax)
      (:mov-edx 0) (:publication-syscall :random 318)
      (:cmp-eintr) (:jz :random) (:test) (:js :os-error) (:jz :zero-write)
      (:load-frame :rcx -128) (:add-reg :rax :rcx) (:cmp-imm :rax 16) (:ja :internal)
      (:store-frame -128 :rax) (:jnz :random)
      (:imm-rax 0) (:store-frame -128 :rax))
    (publication-stack-string ".mgn-" -384)
    (loop for i below 32 for input = (+ -400 (floor i 2)) for output from -379 append
      (scoped-forms (intern (format nil "HEX-~D" i) :keyword)
        (append `((:load-byte :rax :rbp ,input))
          (when (evenp i) '((:shr-imm :rax 4)))
          `((:and-imm :rax 15) (:add-imm :rax 48) (:cmp-imm :rax 57) (:jbe :digit)
            (:add-imm :rax 7) (:label :digit) (:store-byte :rbp ,output :rax)))))
    '((:label :temp-candidate))
    (loop for i below 8 for output from -347 append
      (scoped-forms (intern (format nil "SERIAL-~D" i) :keyword)
        `((:load-frame :rax -136) (:shr-imm :rax ,(* 4 (- 7 i)))
          (:and-imm :rax 15) (:add-imm :rax 48) (:cmp-imm :rax 57) (:jbe :digit)
          (:add-imm :rax 7) (:label :digit) (:store-byte :rbp ,output :rax))))
    '((:imm-rax 0) (:store-byte :rbp -339 :rax)
      (:lea-base :rsi :rbp -384) (:load-frame :rdi -112)
      (:label :compare-name) (:load-byte :rax :rsi 0) (:load-byte :rcx :rdi 0)
      (:cmp) (:jnz :open-temp) (:test) (:jz :collision)
      (:add-imm :rsi 1) (:add-imm :rdi 1) (:jmp :compare-name)
      (:label :open-temp) (:load-frame :rdi -240) (:lea-base :rsi :rbp -384)
      (:mov-edx 524481) (:load-frame :r10 -120) (:publication-syscall :open-temp 257)
      (:cmp-eintr) (:jz :open-temp) (:cmp-imm :rax -17) (:jz :collision)
      (:test) (:js :os-error) (:store-frame -232 :rax)
      (:imm-rax 1) (:store-frame -208 :rax)
      (:lea-base :rax :rbp -384) (:store-frame -200 :rax)
      (:label :temp-stat) (:load-frame :rdi -232) (:lea-base :rsi :rbp -640)
      (:publication-syscall :temp-stat 5) (:cmp-eintr) (:jz :temp-stat) (:test) (:js :os-error)
      (:load-frame :rax -640) (:store-frame -192 :rax)
      (:load-frame :rax -632) (:store-frame -184 :rax) (:imm-rax 1) (:store-frame -168 :rax)
      (:imm-rax 2) (:store-frame -80 :rax)
      (:load-frame :rax -616) (:mov-reg :rcx :rax) (:and-imm :rax 61440)
      (:cmp-imm :rax 32768) (:jnz :internal)
      (:mov-reg :rax :rcx) (:and-imm :rax 3584) (:test) (:jz :mode-ready)
      (:and-imm :rcx 511) (:mov-reg :rsi :rcx)
      (:label :mode) (:load-frame :rdi -232) (:publication-syscall :mode 91)
      (:cmp-eintr) (:jz :mode) (:test) (:js :os-error)
      (:label :mode-stat) (:load-frame :rdi -232) (:lea-base :rsi :rbp -640)
      (:publication-syscall :mode-stat 5) (:cmp-eintr) (:jz :mode-stat) (:test) (:js :os-error)
      (:load-frame :rax -616) (:and-imm :rax 3584) (:test) (:jnz :internal)
      (:jmp :mode-ready)
      (:label :collision) (:load-frame :rax -136) (:add-imm :rax 1)
      (:imm-rcx 4294967296) (:cmp) (:jae :exhausted) (:store-frame -136 :rax) (:jmp :temp-candidate)
      (:label :mode-ready))))

(defun publication-barrier-forms ()
  (when (option :publication-barrier)
    '((:imm-rax 1) (:store-frame -1120 :rax)
      (:label :barrier-ready) (:mov-edi 6) (:lea-base :rsi :rbp -1120)
      (:mov-edx 1) (:mov-eax 1) (:syscall) (:cmp-eintr) (:jz :barrier-ready)
      (:cmp-imm :rax 1) (:jnz :internal)
      (:label :barrier-gate) (:mov-edi 7) (:lea-base :rsi :rbp -1120)
      (:mov-edx 1) (:mov-eax 0) (:syscall) (:cmp-eintr) (:jz :barrier-gate)
      (:cmp-imm :rax 1) (:jnz :internal))))

(defun publication-write-commit-forms ()
  (append
    '((:label :write) (:load-frame :rsi -16) (:load-word :rdx :rsi 32)
      (:load-frame :rax -128) (:cmp-reg :rax :rdx) (:jae :close-file)
      (:sub-reg :rdx :rax) (:cmp-imm :rdx 2147479552) (:jbe :chunk)
      (:imm-rdx 2147479552) (:label :chunk) (:store-frame -152 :rdx)
      (:add-imm :rsi 40) (:add-reg :rsi :rax) (:load-frame :rdi -232)
      (:publication-syscall :write 1) (:cmp-eintr) (:jz :write) (:test) (:js :os-error) (:jz :zero-write)
      (:load-frame :rcx -152) (:cmp) (:ja :internal)
      (:load-frame :rcx -128) (:add-reg :rax :rcx) (:store-frame -128 :rax) (:jmp :write)
      (:label :close-file) (:imm-rax 4) (:store-frame -80 :rax)
      (:load-frame :rdi -232) (:imm-rax -1) (:store-frame -232 :rax)
      (:publication-syscall :close-file 3) (:test) (:js :os-error)
      (:imm-rax 3) (:store-frame -80 :rax))
    (publication-barrier-forms)
    '((:load-frame :rdi -240) (:lea-base :rsi :rbp -384)
      (:mov-reg :rdx :rdi) (:load-frame :r10 -112) (:imm-reg :r8 1)
      (:publication-syscall :commit 316) (:test) (:jz :published)
      (:test) (:js :commit-negative) (:jmp :internal) (:label :commit-negative)
      (:cmp-imm :rax -38) (:jz :os-error)
      (:load-frame :rcx -144) (:cmp-imm :rcx 1) (:jnz :unknown))
    (loop for errno in '(1 2 4 11 12 13 16 17 18 20 22 28 30 36 39 40 95 116 122) append
      `((:cmp-imm :rax ,(- errno)) (:jz :os-error)))
    '((:label :unknown) (:imm-rcx 2) (:store-frame -88 :rcx) (:jmp :os-error)
      (:label :published) (:imm-rax 1) (:store-frame -88 :rax)
      (:imm-rax 0) (:store-frame -208 :rax) (:jmp :cleanup))))

(defun publication-enum-forms (type count source target prefix)
  (append
    (loop for index below count append
      (scoped-forms (list prefix index)
        (append `((:load-frame :rax ,source) (:cmp-imm :rax ,index) (:jnz :next))
          (allocate-object :value (list :descriptor (second type) index) 2 0 index)
          `((:store-frame ,target :rdx) (:jmp ,(intern (format nil "~A-READY" prefix) :keyword)) (:label :next)))))
    `((:jmp (:runtime :directory.internal)) (:label ,(intern (format nil "~A-READY" prefix) :keyword)))))

(defun publication-operation-unit (inst context)
  (let* ((result (mognitio.ir:instruction-type inst))
         (error (second (mognitio.semantic::canonical-result-arguments context result)))
         (fields (mapcar #'cdr (mognitio.semantic:type-info-fields (mognitio.semantic:context-type context error)))))
    (publication-unit (second (value-helper-name inst))
      (append (helper-frame 192) (helper-root-link 6)
        `((:load-word :rax :r15 ,+cleanup-head+) (:store-frame -256 :rax)
          (:imm-rax -2) (:store-frame -248 :rax)
          (:imm-rax -1) (:store-frame -240 :rax) (:store-frame -232 :rax)
          (:store-frame -176 :rax) (:store-frame -72 :rax)
          (:lea-base :rax :rbp -256) (:store-word :r15 ,+cleanup-head+ :rax)
          (:load-frame :rax 16) (:store-frame -8 :rax)
          (:load-frame :rax 24) (:store-frame -16 :rax)
          (:load-frame :rdx 32) (:load-word :rax :rdx 24)
          (:cmp-imm :rax 0) (:jz :data-mode) (:cmp-imm :rax 1) (:jnz :internal)
          (:imm-rax 511) (:jmp :mode-set) (:label :data-mode) (:imm-rax 438)
          (:label :mode-set) (:store-frame -120 :rax))
        (publication-path-forms) (publication-temp-forms) (publication-write-commit-forms)
        '((:label :invalid-path) (:imm-rax 0) (:store-frame -72 :rax) (:jmp :cleanup)
          (:label :already-exists) (:imm-rax 1) (:store-frame -72 :rax) (:jmp :cleanup)
          (:label :exhausted) (:imm-rax 5) (:store-frame -72 :rax) (:jmp :cleanup)
          (:label :zero-write) (:imm-rax 6) (:store-frame -72 :rax) (:jmp :cleanup)
          (:label :internal) (:imm-rax 1) (:store-frame -104 :rax) (:jmp :cleanup)
          (:label :os-error) (:cmp-imm :rax -9) (:jz :internal)
          (:cmp-imm :rax -14) (:jz :internal) (:cmp-imm :rax -4095) (:jl :internal)
          (:test) (:js :errno-valid) (:jmp :internal) (:label :errno-valid) (:store-frame -96 :rax)
          (:label :cleanup) (:lea-base :rax :rbp -256) (:store-out 0 :rax)
          (:call (:runtime :publication.cleanup)) (:store-frame -160 :rax)
          (:cmp-imm :rdx 0) (:jz :cleanup-state) (:store-frame -104 :rdx)
          (:label :cleanup-state) (:load-frame :rcx -96) (:test-rcx) (:jnz :cleaned)
          (:load-frame :rcx -72) (:cmp-imm :rcx -1) (:jnz :cleaned)
          (:load-frame :rax -160) (:test) (:jz :cleaned)
          (:store-frame -96 :rax) (:imm-rax 4) (:store-frame -80 :rax)
          (:label :cleaned) (:load-frame :rax -256))
        `((:store-word :r15 ,+cleanup-head+ :rax))
        '((:load-frame :rax -104) (:test) (:jnz (:runtime :directory.internal))
          (:load-frame :rax -72) (:cmp-imm :rax -1) (:jnz :error)
          (:load-frame :rax -96) (:test) (:jz :ok) (:call (:runtime :publication.errno))
          (:store-frame -72 :rax) (:label :error))
        (publication-enum-forms (first fields) 7 -72 -24 :kind)
        (publication-enum-forms (third fields) 5 -80 -32 :phase)
        (publication-enum-forms (fourth fields) 3 -88 -40 :state)
        (allocate-object :error (list :descriptor (second error) 0) 1 4)
        '((:load-frame :rax -24) (:store-word :rdx 32 :rax)
          (:load-frame :rax -8) (:store-word :rdx 40 :rax)
          (:load-frame :rax -32) (:store-word :rdx 48 :rax)
          (:load-frame :rax -40) (:store-word :rdx 56 :rax) (:store-frame -48 :rdx))
        (result-construction :err result 1 -48)
        '((:jmp :done) (:label :ok))
        (result-construction :ok result 0 -48)
        '((:label :done)) (helper-root-unlink 6) (helper-return)) :helper)))
