(in-package #:mognitio.native.runtime)

(defun argument-construction-unit (diagnostic-length)
  (runtime-unit :arguments
    (append (helper-frame 14) (helper-root-link 2)
      `((:lea-object ,(static-name :list '(:list :string))) (:store-frame -8 :rax)
        (:label :restart) (:load-word :rdx :r15 ,+initial-stack+)
        (:load-word :rax :rdx 0) (:add-imm :rax -1) (:store-frame -48 :rax)
        (:add-imm :rdx 16) (:store-frame -40 :rdx)
        (:label :argument) (:load-frame :rax -48) (:test) (:jz :end-pass)
        (:load-frame :rdx -40) (:load-word :rsi :rdx 0) (:store-frame -72 :rsi)
        (:imm-rcx 0) (:mov-reg :r8 :rsi)
        (:label :length) (:load-byte :rax :r8 0) (:test) (:jz :have-length)
        (:add-imm :r8 1) (:add-imm :rcx 1) (:jmp :length)
        (:label :have-length) (:store-frame -56 :rcx) (:store-out 0 :rsi) (:store-out 8 :rcx)
        (:call (:runtime :utf8.count)) (:test) (:js :invalid-argument) (:store-frame -64 :rax)
        (:load-frame :rax -80) (:test) (:jz :advance)
        (:load-frame :rax -56) (:test) (:jz :empty)
        (:store-out 0 :rax) (:load-frame :rax -64) (:store-out 8 :rax)
        (:call (:runtime :allocate)) (:store-frame -16 :rax)
        (:lea-base :rdi :rax 32) (:load-frame :rsi -72) (:load-frame :rcx -56))
      (copy-forms :copy)
      '((:jmp :append) (:label :empty) (:lea-text (:text 0)) (:store-frame -16 :rax)
        (:label :append))
      (allocate-object :argument-list (layout-name (list :list '(:list :string))) 5 3)
      '((:load-frame :rax -8) (:store-word :rdx 40 :rax) (:load-word :rax :rax 32)
        (:add-imm :rax 1) (:store-word :rdx 32 :rax)
        (:load-frame :rax -16) (:store-word :rdx 48 :rax) (:store-frame -8 :rdx)
        (:label :advance) (:load-frame :rax -40) (:add-imm :rax 8) (:store-frame -40 :rax)
        (:load-frame :rax -48) (:add-imm :rax -1) (:store-frame -48 :rax) (:jmp :argument)
        (:label :end-pass) (:load-frame :rax -80) (:test) (:jnz :done)
        (:imm-rax 1) (:store-frame -80 :rax) (:jmp :restart)
        (:label :done) (:load-frame :rax -8))
      `((:store-word :r15 ,+arguments+ :rax))
      (helper-root-unlink 2) (helper-return)
      `((:label :invalid-argument) (:lea-rsi (:data :invalid-argument))
        (:mov-edx ,diagnostic-length) (:mov-r10d 16)
        (:label :report) (:mov-edi 2) (:mov-eax 1) (:syscall) (:cmp-eintr) (:jz :retry)
        (:test) (:jle :exit) (:add-rsi) (:sub-rdx) (:jnz :report) (:jmp :exit)
        (:label :retry) (:dec-r10d) (:jnz :report)
        (:label :exit) (:mov-edi 2) (:mov-eax 60) (:syscall) (:ud2)))))

(defun argument-helper-units ()
  (when (argument-image-p)
    (let ((bytes (sb-ext:string-to-octets (format nil "runtime: invalid UTF-8 runtime argument~%") :external-format :utf-8)))
      (list (utf8-feed-unit) (utf8-count-unit) (argument-construction-unit (length bytes))
            (mognitio.object:make-code-unit :owner :argument-diagnostic
              :instructions
              (list (mognitio.machine:make-instruction :opcode :label :operands '((:data :invalid-argument)))
                    (mognitio.machine:make-instruction :opcode :bytes :operands (coerce bytes 'list))))))))
