(in-package #:mognitio.native.runtime)

(defun gc-workspace-unit ()
  ;; A temporary queue and allocated-start byte index; no managed allocation.
  (runtime-unit :gc.workspace
    (append (helper-frame 12)
      `((:load-word :rax :r15 ,+mapped-bytes+) (:test) (:jz :empty)
        (:mov-reg :rcx :rax) (:shr-imm :rax 2) (:store-frame -8 :rax)
        (:load-word :r8 :r15 ,+arena-head+) (:imm-reg :r9 0) (:imm-reg :r10 0)
        (:label :count) (:cmp-imm :r8 0) (:jz :counted)
        (:load-word :rax :r8 8) (:cmp-imm :rax 4096) (:jb :bad)
        (:add-reg :r10 :rax) (:jb :bad) (:cmp-reg :r10 :rcx) (:ja :bad)
        (:add-imm :r9 1) (:load-word :r8 :r8 0) (:jmp :count)
        (:label :counted) (:cmp-reg :r10 :rcx) (:jnz :bad)
        (:store-frame -32 :r9)
        (:mov-reg :rax :r9) (:imm-rcx 24) (:mul)
        (:load-word :rdx :r15 ,+mapped-bytes+) (:shr-imm :rdx 3)
        (:add-reg :rax :rdx) (:jb :allocation-failed)
        (:load-frame :rdx -8) (:add-reg :rax :rdx) (:jb :allocation-failed)
        (:add-imm :rax 32) (:jb :allocation-failed)
        (:load-word :rcx :r15 ,+page-size+) (:mov-reg :rdx :rcx)
        (:add-imm :rdx -1) (:add-reg :rax :rdx) (:jb :allocation-failed)
        (:imm-rdx 0) (:div-rcx) (:mul) (:store-frame -16 :rax)
        (:imm-reg :rdi 0) (:mov-reg :rsi :rax) (:imm-rdx 3)
        (:imm-reg :r10 34) (:imm-reg :r8 -1) (:imm-reg :r9 0) (:mov-eax 9))
      (if (option :gc-workspace-fail) '((:imm-rax -12)) '((:syscall)))
      '((:cmp-imm :rax -4095) (:jae :allocation-failed) (:store-frame -24 :rax)
        (:load-frame :rdx -16) (:store-word :rax 0 :rdx)
        (:load-frame :rdx -8) (:store-word :rax 8 :rdx)
        (:imm-rdx 0) (:store-word :rax 16 :rdx)
        (:load-frame :rdx -32) (:store-word :rax 24 :rdx)
        (:load-frame :rdx -8) (:add-reg :rax :rdx) (:add-imm :rax 32)
        (:store-frame -40 :rax)
        (:load-frame :rax -32) (:imm-rcx 24) (:mul)
        (:load-frame :rdx -40) (:add-reg :rax :rdx) (:store-frame -48 :rax)
        (:load-word :r8 :r15 8)
        (:label :index-arena) (:cmp-imm :r8 0) (:jz :indexed)
        (:load-frame :rdi -40) (:store-word :rdi 0 :r8)
        (:load-word :r10 :r8 8) (:store-word :rdi 8 :r10)
        (:load-frame :rsi -48) (:store-word :rdi 16 :rsi)
        (:mov-reg :rax :r10) (:shr-imm :rax 3) (:add-reg :rax :rsi)
        (:store-frame -48 :rax) (:add-imm :rdi 24) (:store-frame -40 :rdi)
        (:add-reg :r10 :r8) (:jb :bad) (:lea-base :r9 :r8 32)
        (:label :index-block) (:cmp-reg :r9 :r10) (:jz :index-next-arena) (:ja :bad))
      (when (option :gc-counters) (bump 136))
      '((:load-word :rdx :r9 0) (:cmp-imm :rdx 32) (:jb :bad)
        (:mov-reg :rax :rdx) (:and-imm :rax 7) (:test) (:jnz :bad)
        (:mov-reg :rcx :r9) (:add-reg :rcx :rdx) (:jb :bad)
        (:cmp-reg :rcx :r10) (:ja :bad)
        (:load-word :rax :r9 8) (:test) (:jz :index-next-block)
        (:mov-reg :rax :r9) (:sub-reg :rax :r8) (:shr-imm :rax 3)
        (:add-reg :rax :rsi) (:imm-rdx 1) (:store-byte :rax 0 :rdx)
        (:label :index-next-block) (:mov-reg :r9 :rcx) (:jmp :index-block)
        (:label :index-next-arena) (:load-word :r8 :r8 0) (:jmp :index-arena)
        (:label :indexed) (:load-frame :rax -24) (:jmp :done)
        (:label :empty) (:imm-rax 0) (:label :done))
      (helper-return)
      '((:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2)))))

(defun gc-release-unit ()
  (runtime-unit :gc.release
    '((:load-word :rdi :rsp 8) (:cmp-imm :rdi 0) (:jz :done)
      (:load-word :rsi :rdi 0) (:mov-eax 11) (:syscall) (:test) (:jnz :bad)
      (:label :done) (:imm-rax 0) (:ret)
      (:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2))))

(defun gc-mark-unit ()
  (runtime-unit :gc.mark
    (append (helper-frame 4)
      '((:load-frame :rax 16) (:store-out 0 :rax)
        (:load-frame :rax 24) (:store-out 8 :rax) (:call (:runtime :validate))
        (:cmp-imm :rax 5) (:jz :done)
        (:load-frame :r9 16) (:load-word :rax :r9 8) (:and-imm :rax 2)
        (:test) (:jnz :marked)
        (:load-frame :rdx 24) (:cmp-imm :rdx 0) (:jz :bad)
        (:load-word :rcx :rdx 16) (:load-word :rax :rdx 8)
        (:cmp-reg :rcx :rax) (:jae :bad)
        (:lea-base :r8 :rdx 32) (:add-reg :r8 :rcx) (:store-word :r8 0 :r9)
        (:add-imm :rcx 8) (:store-word :rdx 16 :rcx)
        (:load-word :rax :r9 8) (:or-imm :rax 2) (:store-word :r9 8 :rax)
        (:label :marked) (:imm-rax 1) (:label :done))
      (helper-return)
      '((:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2)))))
