(in-package #:mognitio.native.runtime)

(defun value-helper-name (inst)
  (list :helper (list (mognitio.ir:instruction-op inst) (mognitio.ir:instruction-type inst)
                      (mognitio.ir:instruction-value inst))))
(defun constructor-unit (inst)
  (let* ((name (value-helper-name inst)) (op (mognitio.ir:instruction-op inst))
         (type (mognitio.ir:instruction-type inst)) (data (mognitio.ir:instruction-value inst))
         (count (length (mognitio.ir:instruction-operands inst)))
         (variant (if (eq op :enum.make) data 0))
         (kind (ecase op (:struct.make 1) (:enum.make 2) (:interface.pack 3) (:closure.make 4)))
         (descriptor (case op (:interface.pack (layout-name (list :package data)))
                              (:closure.make (layout-name (list :closure data)))
                              (t (list :descriptor (second type) variant)))))
    (when (and (eq op :closure.make) (zerop count))
      (return-from constructor-unit
        (runtime-unit (second name) `((:lea-object ,(static-name :closure data)) (:ret)) :helper)))
    (runtime-unit (second name)
      (append (helper-frame 2)
        (allocate-object :object descriptor kind (+ count (if (eq op :closure.make) 1 0)) variant)
        (case op
          (:interface.pack `((:lea-meta (:method-table ,data)) (:store-word :rdx 24 :rax)))
          (:closure.make `((:lea-code (:function ,data)) (:store-word :rdx 32 :rax))))
        (loop for i below count for slot = (case op (:struct.make (nth i data)) (:closure.make (1+ i)) (t i)) append
          `((:load-frame :rax ,(+ 16 (* i 8))) (:store-word :rdx ,(+ 32 (* slot 8)) :rax)))
        '((:mov-reg :rax :rdx)) (helper-return)) :helper)))
(defun value-helper-units (module)
  (let ((seen nil) (units nil) (context (mognitio.ir:module-values module)))
    (dolist (function (mognitio.ir:module-functions module))
      (dolist (block (mognitio.ir:ir-function-blocks function))
        (dolist (inst (mognitio.ir:basic-block-instructions block))
          (let ((op (mognitio.ir:instruction-op inst)) (name (value-helper-name inst)))
            (when (and (member op '(:binary.publish :bytes.from-ints :bytes.from-bits :bytes.length :bytes.at :bytes.append :bytes.concat :bytes.slice :bytes.to-bits :bits.to-bytes :bytes.equal :bytes.not-equal :integer.convert :integer.to-bits :bits.integer :bits.length :bits.and :bits.or :bits.xor :bits.not :bits.left :bits.right :bits.at :io.call :struct.make :enum.make :interface.pack :closure.make :list.append :list.at :list.buffer :text.scalars :text.join :text.slice.result))
                       (not (member name seen :test #'equal)))
              (push name seen)
              (push (case op
                      (:binary.publish (publication-operation-unit inst context))
                      ((:bytes.from-ints :bytes.from-bits :bytes.length :bytes.at :bytes.append :bytes.concat :bytes.slice :bytes.to-bits :bits.to-bytes :bytes.equal :bytes.not-equal) (binary-operation-unit inst context))
                      ((:integer.convert :integer.to-bits :bits.integer :bits.length :bits.and :bits.or :bits.xor :bits.not :bits.left :bits.right :bits.at) (numeric-method-unit inst context))
                      (:io.call (io-operation-unit inst context))
                      (:text.scalars (text-scalars-unit inst)) (:text.join (text-join-unit inst))
                      (:list.append (list-append-unit inst)) (:list.at (list-at-unit inst context))
                      (:list.buffer (list-buffer-unit inst)) (:text.slice.result (slice-result-unit inst context))
                      (t (constructor-unit inst))) units))))))
    (nreverse units)))

(defun trace-forms (context)
  (append
    '((:label :trace-pass) (:load-frame :rax -120) (:add-imm :rax 1) (:store-frame -120 :rax))
    (bump +trace-passes+)
    '((:label :trace-work) (:load-frame :r8 -168) (:cmp-imm :r8 0) (:jz :trace-pass-end)
      (:load-word :rcx :r8 16) (:test-rcx) (:jz :trace-pass-end)
      (:add-imm :rcx -8) (:store-word :r8 16 :rcx)
      (:add-reg :r8 :rcx) (:load-word :rdx :r8 32) (:store-frame -64 :rdx))
    (bump +header-visits+)
    '((:load-word :rax :rdx 8) (:mov-reg :rcx :rax) (:and-imm :rcx 11)
      (:cmp-imm :rcx 3) (:jnz :bad) (:or-imm :rax 8) (:store-word :rdx 8 :rax))
    (bump +object-scans+)
    '((:load-word :rax :rdx 8))
    `((:and-imm :rax ,+kind-mask+) (:test) (:jz :trace-next-block))
    '((:load-word :rcx :rdx 16) (:store-frame -80 :rcx))
    (loop for row in (descriptors context) for serial from 0 append
      (destructuring-bind (name kind id variant count refs &optional dynamic) row
        (declare (ignore refs))
        (let ((next (intern (format nil "DESC-~D" serial) :keyword)))
          (append
            `((:lea-meta ,name) (:cmp-reg :rax :rcx) (:jnz ,next)
              (:load-word :rax :rdx 8) (:and-imm :rax ,+kind-mask+) (:cmp-imm :rax ,(* kind 16)) (:jnz :bad)
              (:load-word :rax :rdx 0) (:cmp-imm :rax ,(+ 32 (* 8 (max 1 count)))) (:jb :bad))
            (if (= kind 3)
                `((:load-word :rcx :rdx 24) (:lea-meta (:method-table ,id)) (:cmp-reg :rax :rcx) (:jnz :bad))
                `((:load-word :rax :rdx 24) (:cmp-imm :rax ,variant) (:jnz :bad)))
            (when (= kind 4)
              `((:load-word :rcx :rdx 32) (:lea-code (:function ,id)) (:cmp-reg :rax :rcx) (:jnz :bad)))
            (if (= kind 7)
                '((:load-word :rax :rdx 0) (:add-imm :rax -40)
                  (:load-word :rcx :rdx 32) (:cmp-reg :rcx :rax) (:ja :bad) (:jmp :trace-next-block))
            (if (= kind 6)
                (append
                  '((:load-word :rax :rdx 0) (:add-imm :rax -40) (:shr-imm :rax 3)
                    (:load-word :rcx :rdx 32) (:cmp-reg :rcx :rax) (:ja :bad))
                  (if dynamic
                      '((:store-frame -88 :rcx) (:lea-base :rax :rdx 40) (:store-frame -96 :rax)
                        (:imm-rax 1) (:store-frame -136 :rax) (:jmp :trace-ref))
                      '((:jmp :trace-next-block))))
                '((:load-frame :rax -80) (:load-word :rcx :rax 32) (:store-frame -88 :rcx)
                  (:add-imm :rax 40) (:store-frame -96 :rax) (:imm-rax 0) (:store-frame -136 :rax) (:jmp :trace-ref))))
            `((:label ,next))))))
    '((:jmp :bad)
      (:label :trace-ref) (:load-frame :rcx -88) (:test-rcx) (:jz :trace-next-block)
      (:load-frame :rax -136) (:test) (:jnz :trace-buffer-ref)
      (:load-frame :rax -96) (:load-word :rax :rax 0) (:imm-rcx 8) (:mul)
      (:load-frame :rdx -64) (:add-reg :rdx :rax) (:load-word :rax :rdx 32) (:jmp :trace-mark-ref)
      (:label :trace-buffer-ref) (:load-frame :rax -96) (:load-word :rax :rax 0) (:test) (:jz :trace-next-ref)
      (:label :trace-mark-ref) (:store-frame -112 :rax) (:store-out 0 :rax)
      (:load-frame :rax -168) (:store-out 8 :rax))
    (if (eq (option :mutation) :no-trace)
        '((:call (:runtime :validate)))
        '((:call (:runtime :gc.mark))))
    '((:label :trace-next-ref) (:load-frame :rax -96) (:add-imm :rax 8) (:store-frame -96 :rax)
      (:load-frame :rcx -88) (:dec-rcx) (:store-frame -88 :rcx) (:jmp :trace-ref)
      (:label :trace-next-block) (:jmp :trace-work)
      (:label :trace-pass-end)
      (:load-frame :rax -120) (:load-word :rcx :r15 200) (:cmp) (:jbe :trace-counted)
      (:store-word :r15 200 :rax) (:label :trace-counted) (:jmp :sweep)
      (:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2))))
