(in-package #:mognitio.native.runtime)

(defun value-helper-name (inst)
  (list :helper (list (mognitio.ir:instruction-op inst) (mognitio.ir:instruction-type inst)
                      (mognitio.ir:instruction-value inst))))
(defun constructor-unit (inst)
  (let* ((name (value-helper-name inst)) (op (mognitio.ir:instruction-op inst))
         (type (mognitio.ir:instruction-type inst)) (data (mognitio.ir:instruction-value inst))
         (count (length (mognitio.ir:instruction-operands inst)))
         (variant (if (eq op :enum.make) data 0))
         (kind (ecase op (:struct.make 1) (:enum.make 2) (:interface.pack 3) (:closure.make 4)))
         (descriptor (case op (:interface.pack (layout-name (list :package data)))
                              (:closure.make (layout-name (list :closure data)))
                              (t (list :descriptor (second type) variant)))))
    (when (and (eq op :closure.make) (zerop count))
      (return-from constructor-unit
        (runtime-unit (second name) `((:lea-object ,(static-name :closure data)) (:ret)) :helper)))
    (runtime-unit (second name)
      (append (helper-frame 2)
        (allocate-object :object descriptor kind (+ count (if (eq op :closure.make) 1 0)) variant)
        (case op
          (:interface.pack `((:lea-meta (:method-table ,data)) (:store-word :rdx 24 :rax)))
          (:closure.make `((:lea-code (:function ,data)) (:store-word :rdx 32 :rax))))
        (loop for i below count for slot = (case op (:struct.make (nth i data)) (:closure.make (1+ i)) (t i)) append
          `((:load-frame :rax ,(+ 16 (* i 8))) (:store-word :rdx ,(+ 32 (* slot 8)) :rax)))
        '((:mov-reg :rax :rdx)) (helper-return)) :helper)))
(defun value-helper-units (module)
  (let ((seen nil) (units nil) (context (mognitio.ir:module-values module)))
    (dolist (function (mognitio.ir:module-functions module))
      (dolist (block (mognitio.ir:ir-function-blocks function))
        (dolist (inst (mognitio.ir:basic-block-instructions block))
          (let ((op (mognitio.ir:instruction-op inst)) (name (value-helper-name inst)))
            (when (and (member op '(:io.call :struct.make :enum.make :interface.pack :closure.make :list.append :list.at :list.buffer :text.slice.result))
                       (not (member name seen :test #'equal)))
              (push name seen)
              (push (case op
                      (:io.call (io-operation-unit inst context))
                      (:list.append (list-append-unit inst)) (:list.at (list-at-unit inst context))
                      (:list.buffer (list-buffer-unit inst)) (:text.slice.result (slice-result-unit inst context))
                      (t (constructor-unit inst))) units))))))
    (nreverse units)))

(defun trace-forms (context)
  (append
    '((:label :trace-pass) (:load-frame :rax -120) (:add-imm :rax 1) (:store-frame -120 :rax))
    (bump +trace-passes+)
    '((:imm-rax 0) (:store-frame -104 :rax) (:load-word :rax :r15 8) (:store-frame -56 :rax)
      (:label :trace-arena) (:load-frame :rax -56) (:test) (:jz :trace-pass-end)
      (:load-word :rdx :rax 8) (:add-reg :rdx :rax) (:store-frame -72 :rdx)
      (:add-imm :rax 32) (:store-frame -64 :rax)
      (:label :trace-block) (:load-frame :rdx -64) (:load-frame :rcx -72) (:cmp-reg :rdx :rcx) (:jae :trace-next-arena))
    (bump +header-visits+)
    '((:load-word :rax :rdx 8) (:mov-reg :rcx :rax) (:and-imm :rcx 11)
      (:cmp-imm :rcx 3) (:jnz :trace-next-block) (:or-imm :rax 8) (:store-word :rdx 8 :rax))
    (bump +object-scans+)
    '((:imm-rcx 1) (:store-frame -104 :rcx) (:load-word :rax :rdx 8))
    `((:and-imm :rax ,+kind-mask+) (:test) (:jz :trace-next-block))
    '((:load-word :rcx :rdx 16) (:store-frame -80 :rcx))
    (loop for row in (descriptors context) for serial from 0 append
      (destructuring-bind (name kind id variant count refs &optional dynamic) row
        (declare (ignore refs))
        (let ((next (intern (format nil "DESC-~D" serial) :keyword)))
          (append
            `((:lea-meta ,name) (:cmp-reg :rax :rcx) (:jnz ,next)
              (:load-word :rax :rdx 8) (:and-imm :rax ,+kind-mask+) (:cmp-imm :rax ,(* kind 16)) (:jnz :bad)
              (:load-word :rax :rdx 0) (:cmp-imm :rax ,(+ 32 (* 8 (max 1 count)))) (:jb :bad))
            (if (= kind 3)
                `((:load-word :rcx :rdx 24) (:lea-meta (:method-table ,id)) (:cmp-reg :rax :rcx) (:jnz :bad))
                `((:load-word :rax :rdx 24) (:cmp-imm :rax ,variant) (:jnz :bad)))
            (when (= kind 4)
              `((:load-word :rcx :rdx 32) (:lea-code (:function ,id)) (:cmp-reg :rax :rcx) (:jnz :bad)))
            (if (= kind 6)
                (append
                  '((:load-word :rax :rdx 0) (:add-imm :rax -40) (:shr-imm :rax 3)
                    (:load-word :rcx :rdx 32) (:cmp-reg :rcx :rax) (:ja :bad))
                  (if dynamic
                      '((:store-frame -88 :rcx) (:lea-base :rax :rdx 40) (:store-frame -96 :rax)
                        (:imm-rax 1) (:store-frame -136 :rax) (:jmp :trace-ref))
                      '((:jmp :trace-next-block))))
                '((:load-frame :rax -80) (:load-word :rcx :rax 32) (:store-frame -88 :rcx)
                  (:add-imm :rax 40) (:store-frame -96 :rax) (:imm-rax 0) (:store-frame -136 :rax) (:jmp :trace-ref)))
            `((:label ,next))))))
    '((:jmp :bad)
      (:label :trace-ref) (:load-frame :rcx -88) (:test-rcx) (:jz :trace-next-block)
      (:load-frame :rax -136) (:test) (:jnz :trace-buffer-ref)
      (:load-frame :rax -96) (:load-word :rax :rax 0) (:imm-rcx 8) (:mul)
      (:load-frame :rdx -64) (:add-reg :rdx :rax) (:load-word :rax :rdx 32) (:jmp :trace-mark-ref)
      (:label :trace-buffer-ref) (:load-frame :rax -96) (:load-word :rax :rax 0) (:test) (:jz :trace-next-ref)
      (:label :trace-mark-ref) (:store-frame -112 :rax) (:store-out 0 :rax)
      (:call (:runtime :validate)) (:cmp-imm :rax 5) (:jz :trace-next-ref))
    (unless (eq (option :mutation) :no-trace)
      '((:load-frame :rdx -112) (:load-word :rax :rdx 8) (:or-imm :rax 2) (:store-word :rdx 8 :rax)))
    '((:label :trace-next-ref) (:load-frame :rax -96) (:add-imm :rax 8) (:store-frame -96 :rax)
      (:load-frame :rcx -88) (:dec-rcx) (:store-frame -88 :rcx) (:jmp :trace-ref)
      (:label :trace-next-block) (:load-frame :rdx -64) (:load-word :rax :rdx 0)
      (:add-reg :rdx :rax) (:store-frame -64 :rdx) (:jmp :trace-block)
      (:label :trace-next-arena) (:load-frame :rax -56) (:load-word :rax :rax 0)
      (:store-frame -56 :rax) (:jmp :trace-arena)
      (:label :trace-pass-end) (:load-frame :rax -104) (:test) (:jnz :trace-pass)
      (:load-frame :rax -120) (:load-word :rcx :r15 200) (:cmp) (:jbe :trace-counted)
      (:store-word :r15 200 :rax) (:label :trace-counted) (:jmp :sweep)
      (:label :bad) (:mov-edi 3) (:mov-eax 60) (:syscall) (:ud2))))
