(in-package #:mognitio.native.runtime)

(defun io-helper-writes (form)
  ;; Independent opcode effects include implicit syscall and call clobbers.
  (case (first form)
    ((:mov-reg :load-frame :load-word :load-byte :lea-base :imm-reg :add-imm :and-imm :or-imm :add-reg :sub-reg :shr-imm) (list (second form)))
    ((:imm-rax :mov-eax :mul :add :lea-text :lea-object :lea-meta) '(:rax))
    ((:imm-rcx :dec-rcx) '(:rcx))
    ((:imm-rdx :mov-edx :sub-rdx) '(:rdx))
    (:lea-rsi '(:rsi)) (:add-rsi '(:rsi)) (:mov-edi '(:rdi))
    ((:mov-r10d :dec-r10d) '(:r10))
    (:syscall '(:rax :rcx :r11))
    ((:push-rbp :push-zero :ret) '(:rsp)) (:pop-rbp '(:rbp :rsp))
    (:call '(:rsp :rax :rcx :rdx :rsi :rdi :r8 :r9 :r10 :r11))
    ((:label :store-frame :store-out :store-word :store-byte :cmp :cmp-reg :cmp-imm :cmp-rax-rdx
      :cmp-eintr :test :test-rcx :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo :jmp :ud2) nil)
    (otherwise (internal-error "Unknown I/O helper register effects"))))

(defun verify-io-helper (unit)
  (let* ((entry (mognitio.object:code-unit-entry unit)) (name (second entry))
         (operation-p (and (consp name) (eq (car name) :io.call)))
         (directory-p (and operation-p (member (third name) '(:join-path :read-directory :create-directory))))
         (directory-helper-p (member name '(:directory.map :directory.errno :directory.cleanup :directory.compare :directory.name-compare :directory.sift :directory.sort :directory.internal)))
         (words (if operation-p (if directory-p 100 56) (ecase name
                  (:utf8.feed 0) (:utf8.count 8) (:arguments 14) (:io.signals 4)
                  (:io.map 0) (:io.close 0) (:io.cleanup 8) (:io.cleanup-all 2) (:io.errno 0)
                  (:directory.map 0) (:directory.errno 0) (:directory.cleanup 8) (:directory.compare 0) (:directory.name-compare 0)
                  (:directory.sift 12) (:directory.sort 12) (:directory.internal 12))))
         (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                        (mognitio.machine:instruction-operands i)))
                       (mognitio.object:code-unit-instructions unit)))
         (locals (loop for form in forms when (eq (first form) :label) collect (second form)))
         (fatal '(:allocation-failed :string-size-overflow :list-length-overflow (:runtime :directory.internal))) (returns 0))
    (when (plusp words)
      (unless (equal (subseq forms 0 (+ words 3))
                     (append (list (list :label entry) '(:push-rbp) '(:mov-reg :rbp :rsp))
                             (make-list words :initial-element '(:push-zero))))
        (internal-error "Invalid I/O helper frame")))
    (when (or operation-p (eq name :arguments))
      (let* ((count (if directory-p 8 (if operation-p 4 2))) (header (if directory-p -80 (if operation-p -48 -32)))
             (start (+ words 3)))
        (unless (equal (subseq forms start (+ start 6))
                       (list '(:load-word :rax :r15 0) (list :store-frame header :rax)
                             (list :imm-rax count) (list :store-frame (+ header 8) :rax)
                             (list :lea-base :rax :rbp header) '(:store-word :r15 0 :rax)))
          (internal-error "Invalid I/O helper root publication"))
        (loop for tail on forms when (eq (caar tail) :ret) do
          (let ((at (position (car tail) forms :test #'eq)))
            (unless (equal (subseq forms (- at 4) (- at 2))
                           (list (list :load-frame :rcx header) '(:store-word :r15 0 :rcx)))
              (internal-error "I/O helper retains temporary roots"))))))
    (loop for form in forms for index from 0 for op = (first form) do
      (let ((writes (io-helper-writes form)))
        (when (intersection writes '(:rbx :r12 :r13 :r14 :r15)) (internal-error "I/O helper clobbers a callee save"))
        (when (intersection writes '(:rbp :rsp))
          (unless (case op
                    (:push-rbp (= index 1)) (:push-zero (<= 3 index (+ words 2)))
                    (:mov-reg (or (and (= index 2) (equal form '(:mov-reg :rbp :rsp)))
                                  (and (equal form '(:mov-reg :rsp :rbp))
                                       (equal (subseq forms index (min (length forms) (+ index 3)))
                                              '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret))))))
                    ((:pop-rbp :ret) t) (:call t))
            (internal-error "Unbalanced I/O helper stack"))))
      (when (member op '(:store-frame :load-frame :store-out))
        (let ((offset (if (eq op :load-frame) (third form) (second form))))
          (unless (and (integerp offset) (zerop (mod offset 8))
                       (if (eq op :store-out) (<= 0 offset (if (or directory-p directory-helper-p) 24 16))
                           (or (<= (- (* words 8)) offset -8)
                               (and (eq op :load-frame) (member offset (if (or directory-p directory-helper-p) '(16 24 32 40) '(16 24 32)))))))
            (internal-error "I/O helper frame access escapes its layout"))))
      (when (and (eq op :store-word) (eq (second form) :r15))
        (unless (member (third form) '(0 264 272)) (internal-error "Invalid I/O context store")))
      (when (and (eq op :load-word) (eq (third form) :r15))
        (unless (member (fourth form) '(0 240 272)) (internal-error "Invalid I/O context load")))
      (when (eq op :call)
        (unless (member (second form) '((:runtime :allocate) (:runtime :allocate-block)
                    (:runtime :utf8.feed) (:runtime :utf8.count) (:runtime :io.map)
                    (:runtime :io.close) (:runtime :io.cleanup) (:runtime :io.errno)
                    (:runtime :sum) (:runtime :io.cleanup-all) (:runtime :directory.map) (:runtime :directory.errno) (:runtime :directory.cleanup)
                    (:runtime :directory.compare) (:runtime :directory.name-compare) (:runtime :directory.sift) (:runtime :directory.sort)) :test #'equal)
          (internal-error "Unknown I/O helper call barrier")))
      (when (eq op :ret)
        (incf returns)
        (when (plusp words)
          (unless (equal (subseq forms (- index 2) (1+ index)) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))
            (internal-error "Invalid I/O helper return"))))
      (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
        (unless (or (member (second form) locals :test #'equal) (member (second form) fatal :test #'equal))
          (internal-error "I/O helper jumps outside checked failure paths"))))
    (unless (or (plusp returns) (eq name :directory.internal)) (internal-error "Missing I/O helper return"))
    (when (eq name :directory.internal) (verify-directory-terminal forms))
    (when (eq name :directory.map)
      (unless (equal (rest forms)
                     '((:load-word :rsi :rsp 8) (:imm-reg :rdi 0) (:imm-rdx 3)
                       (:imm-reg :r10 34) (:imm-reg :r8 -1) (:imm-reg :r9 0)
                       (:mov-eax 9) (:syscall) (:ret)))
        (internal-error "Directory mmap adapter does not return the raw syscall result")))
    (when directory-p (verify-directory-ownership forms))
    (when (and operation-p (not directory-p))
      ;; Every reachable normal exit must have published and then removed the
      ;; ownership record. Allocation failures use the independently checked bridge.
      (let ((queue (list (list 0 :absent))) (seen (make-hash-table :test #'equal)))
        (loop while queue for state = (pop queue) unless (gethash state seen) do
          (setf (gethash state seen) t)
          (destructuring-bind (pc ownership) state
            (when (>= pc (length forms)) (internal-error "I/O helper falls through"))
            (let* ((form (nth pc forms)) (op (first form)) (next ownership))
              (when (equal form '(:store-word :r15 272 :rax))
                (setf next (cond ((equal (nth (1- pc) forms) '(:lea-base :rax :rbp -128))
                                 (unless (eq ownership :absent) (internal-error "Duplicate cleanup record")) :owned)
                                ((equal (nth (1- pc) forms) '(:load-frame :rax -128))
                                 (unless (eq ownership :cleaned) (internal-error "Uncleaned I/O record")) :released)
                                (t (internal-error "Forged cleanup link")))))
              (when (equal form '(:call (:runtime :io.cleanup)))
                (unless (eq ownership :owned) (internal-error "Cleanup without ownership")) (setf next :cleaned))
              (when (eq op :ret)
                (unless (eq ownership :released) (internal-error "I/O return retains resources")))
              (when (and (eq op :syscall) (equal (nth (1- pc) forms) '(:mov-eax 60)))
                (unless (eq ownership :released) (internal-error "I/O exits before cleanup")))
              (unless (member op '(:ret :ud2))
                (unless (eq op :jmp) (push (list (1+ pc) next) queue))
                (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
                  (let ((target (position (list :label (second form)) forms :test #'equal)))
                    (when target (push (list target next) queue)))))))))))
  unit)

(defun verify-io-units (units)
  (dolist (unit units)
    (let* ((entry (mognitio.object:code-unit-entry unit)) (name (when (consp entry) (second entry))))
      (when (or (member name '(:utf8.feed :utf8.count :arguments :io.signals :io.map :io.close :io.cleanup :io.cleanup-all :io.errno :directory.map :directory.errno :directory.cleanup :directory.compare :directory.name-compare :directory.sift :directory.sort :directory.internal))
                (and (consp name) (eq (car name) :io.call))) (verify-io-helper unit))
      (when (and (consp name) (eq (car name) :io.call)) (verify-v014-phase-shape unit))
      (when (and (consp name) (eq (car name) :io.call)
                 (member (third name) '(:read-file :write-file :read-stdin :write-stdout :write-stderr)))
        (verify-v014-stream-cleanup-latch unit))
      (when (and (consp name) (member (car name) '(:text.scalars :text.join))) (verify-text-collection-helper unit))))
  (when (io-image-p)
    (let* ((unit (find :runtime units :key #'mognitio.object:code-unit-owner))
           (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i)
                                          (mognitio.machine:instruction-operands i)))
                         (mognitio.object:code-unit-instructions unit))))
      (dolist (kind '(:overflow :division-by-zero :remainder-by-zero :string-index-out-of-bounds
                     :string-size-overflow :list-length-overflow :allocation-failed))
        (let ((position (position (list :label kind) forms :test #'equal)))
          (unless (and position (equal (nth (1+ position) forms) '(:call (:runtime :io.cleanup-all))))
            (internal-error "Runtime failure bypasses I/O cleanup"))))))
  units)
