(in-package #:mognitio.native.runtime)

(defun verify-directory-terminal (forms)
  (unless (and (equal (nth 15 forms) '(:call (:runtime :io.cleanup-all)))
               (= 1 (count :call forms :key #'first))
               (equal (last forms 4) `((:mov-edi ,(if (test-image-p) 123 3)) (:mov-eax 60) (:syscall) (:ud2)))
               (if (test-image-p)
                   (= 1 (count :syscall forms :key #'first))
                   (and (= 2 (count :syscall forms :key #'first))
                        (member '(:imm-reg :r8 8) forms :test #'equal))))
    (internal-error "Invalid nonallocating directory internal terminal")))

(defun verify-directory-latch (forms)
  ;; Independently interpret zero/nonzero facts, not the producer's gate pattern.
  ;; Branch refinement proves that a latched failure cannot reach a value return
  ;; even if a check is moved, inverted, cleared or bypassed by a local jump.
  (let ((code (coerce forms 'vector)) (labels (make-hash-table :test #'equal))
        (queue (list (list 0 :zero :unknown :unknown nil)))
        (seen (make-hash-table :test #'equal)))
    (loop for form across code for pc from 0 when (eq (first form) :label)
          do (setf (gethash (second form) labels) pc))
    (loop while queue for state = (pop queue) unless (gethash state seen) do
      (setf (gethash state seen) t)
      (destructuring-bind (pc latch rax rdx flags) state
        (when (>= pc (length code)) (internal-error "Directory latch path falls through"))
        (let* ((form (aref code pc)) (op (first form)))
          (labels ((fact (reg) (case reg (:rax rax) (:rdx rdx) (otherwise :unknown)))
                   (assign (reg value)
                     ;; MOV preserves flags, but they no longer constrain the
                     ;; overwritten register. Keep the saved comparison result.
                     (when (and flags (eq (first flags) reg))
                       (setf flags (list nil (second flags))))
                     (case reg (:rax (setf rax value)) (:rdx (setf rdx value))))
                   (value-fact (value) (if (zerop value) :zero :nonzero))
                   (enqueue (target zero-test)
                     (unless (and zero-test flags (not (eq (second flags) :unknown))
                                  (not (eq zero-test (second flags))))
                       (let ((a rax) (d rdx))
                         (when (and zero-test flags)
                           (case (first flags) (:rax (setf a zero-test)) (:rdx (setf d zero-test))))
                         (if (integerp target)
                             (push (list target latch a d flags) queue)
                             (when (and (eq latch :nonzero) (not (equal target '(:runtime :directory.internal))))
                               (internal-error "Directory latch escapes through a language failure")))))))
            (when (equal form '(:call (:runtime :io.map)))
              (internal-error "Directory scratch bypasses raw mmap classification"))
            (when (equal form '(:call (:runtime :directory.map)))
              (let* ((tail (loop for i from (1+ pc) below (length code)
                                 unless (eq (first (aref code i)) :label) collect (aref code i)))
                     (target (gethash (second (second tail)) labels)))
                (unless (and (equal (first tail) '(:cmp-imm :rax -22))
                             (eq (first (second tail)) :jz) target
                             (equal (third tail) '(:cmp-imm :rax -4095))
                             (equal (fourth tail) '(:jae :allocation-failed))
                             (< (+ target 2) (length code))
                             (equal (aref code (1+ target)) '(:imm-rax 1))
                             (equal (aref code (+ target 2)) '(:store-frame -104 :rax)))
                  (internal-error "Directory mmap result lacks phase-specific classification"))))
            (when (and (eq latch :nonzero)
                       (or (eq op :ret)
                           (member form '((:call (:runtime :allocate)) (:call (:runtime :allocate-block))) :test #'equal)))
              (internal-error "Directory internal latch reaches ordinary materialization or return"))
            (when (and (eq op :store-frame) (= (second form) -104))
              (let ((value (fact (third form))))
                (when (or (eq value :unknown) (and (eq latch :nonzero) (eq value :zero)))
                  (internal-error "Directory internal latch is unproved or cleared"))
                (setf latch value)))
            (when (and (member op '(:lea-base :store-word :store-byte))
                       (or (and (eq op :lea-base) (equal (cddr form) '(:rbp -104)))
                           (and (member op '(:store-word :store-byte)) (eq (second form) :rbp) (= (third form) -104))))
              (internal-error "Directory latch address escapes checked frame operations"))
            (let ((source (when (eq op :mov-reg) (fact (third form)))))
              (dolist (reg (io-helper-writes form)) (assign reg :unknown))
              (case op
                ((:imm-rax :mov-eax) (assign :rax (value-fact (second form))))
                ((:imm-rdx :mov-edx) (assign :rdx (value-fact (second form))))
                (:imm-reg (assign (second form) (value-fact (third form))))
                (:mov-reg (assign (second form) source))
                (:load-frame (when (= (third form) -104) (assign (second form) latch)))))
            (cond ((eq op :test) (setf flags (list :rax rax)))
                  ((and (eq op :cmp-imm) (zerop (third form)))
                   (setf flags (list (second form) (fact (second form)))))
                  ((member op '(:cmp :cmp-reg :cmp-imm :cmp-rax-rdx :cmp-eintr :test-rcx
                                :add-imm :and-imm :or-imm :add-reg :sub-reg :shr-imm :mul :add
                                :dec-rcx :add-rsi :sub-rdx :dec-r10d :call :syscall))
                   (setf flags nil)))
            (unless (member op '(:ret :ud2))
              (let* ((conditional (member op '(:jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo)))
                     (taken (case op (:jz :zero) (:jnz :nonzero)))
                     (other (case op (:jz :nonzero) (:jnz :zero))))
                (unless (eq op :jmp) (enqueue (1+ pc) other))
                (when (or conditional (eq op :jmp))
                  (enqueue (gethash (second form) labels (second form)) taken))))))))))

(defun verify-directory-ownership (forms)
  (verify-directory-latch forms)
  ;; The checker reconstructs ownership from emitted instructions, independently
  ;; of the lowering's scratch constants. Joins do not hide a live descriptor.
  (let ((queue (list (list 0 nil 0 :closed))) (seen (make-hash-table :test #'equal)))
    (loop while queue for state = (pop queue) unless (gethash state seen) do
      (setf (gethash state seen) t)
      (destructuring-bind (pc stack published fd) state
        (when (>= pc (length forms)) (internal-error "Directory helper falls through"))
        (let* ((form (nth pc forms)) (op (car form))
               (next-stack stack) (next-count published) (next-fd fd))
          (when (equal form '(:store-word :r15 272 :rax))
            (let ((previous (nth (1- pc) forms)))
              (cond
                ((and (eq (car previous) :lea-base) (equal (subseq previous 1 3) '(:rax :rbp)))
                 (let ((record (fourth previous)))
                   (unless (and (< published 3) (= record (nth published '(-240 -304 -368)))
                                (equal (nth (- pc 3) forms) '(:load-word :rax :r15 272))
                                (equal (nth (- pc 2) forms) (list :store-frame record :rax))
                                (equal (nth (- pc 4) forms) (list :store-frame (+ record 8) :rax))
                                (equal (nth (- pc 5) forms) '(:imm-rax -1)))
                     (internal-error "Invalid directory record publication"))
                   (setf next-stack (cons (cons record :owned) stack) next-count (1+ published))))
                ((and (eq (car previous) :load-frame) stack
                      (equal previous (list :load-frame :rax (caar stack))) (eq (cdar stack) :cleaned))
                 (setf next-stack (cdr stack)))
                (t (internal-error "Uncleaned or forged directory ownership link")))))
          (when (equal form '(:call (:runtime :directory.cleanup)))
            (unless (and stack (eq (cdar stack) :owned)
                         (equal (nth (- pc 2) forms) (list :lea-base :rax :rbp (caar stack)))
                         (equal (nth (1- pc) forms) '(:store-out 0 :rax)))
              (internal-error "Directory cleanup does not name the owned record"))
            (setf next-stack (cons (cons (caar stack) :cleaned) (cdr stack)))
            (when (= (caar stack) -240) (setf next-fd :closed)))
          (when (equal form '(:store-frame -232 :rax))
            (setf next-fd (if (equal (nth (1- pc) forms) '(:imm-rax -1)) :closed :owned)))
          (when (equal form '(:call (:runtime :io.close))) (setf next-fd :closed))
          (when (and (eq fd :owned) (member form '((:call (:runtime :allocate)) (:call (:runtime :allocate-block))) :test #'equal))
            (internal-error "Directory materialization begins before close"))
          (when (or (eq op :ret) (and (member op '(:jmp :jnz)) (equal (second form) '(:runtime :directory.internal))))
            (unless (and (= published 3) (null stack)) (internal-error "Directory exit retains ownership")))
          (unless (member op '(:ret :ud2))
            (unless (eq op :jmp) (push (list (1+ pc) next-stack next-count next-fd) queue))
            (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
              (let ((target (position (list :label (second form)) forms :test #'equal)))
                (when target (push (list target next-stack next-count next-fd) queue))))))))))
