(in-package #:mognitio.native.runtime)

;; Publication records share the chain link with I/O records and use fd=-2 as
;; a checked tag. Remaining words own parent/file/probe fds, path map and temp.
(defun publication-cleanup-unit ()
  (publication-unit :publication.cleanup
    (append (helper-frame 64)
      '((:load-frame :rax 16) (:store-frame -8 :rax)
        (:load-word :rcx :rax 48) (:test-rcx) (:jz :identity-ready)
        (:load-word :rcx :rax 88) (:test-rcx) (:jnz :identity-ready)
        (:load-word :rdi :rax 24) (:cmp-imm :rdi 0) (:jl :identity-ready)
        (:label :identity-stat) (:lea-base :rsi :rbp -256) (:publication-syscall :cleanup-identity 5)
        (:cmp-eintr) (:jz :identity-stat) (:test) (:js :identity-failed)
        (:load-frame :rdx -8) (:load-frame :rax -256) (:store-word :rdx 64 :rax)
        (:load-frame :rax -248) (:store-word :rdx 72 :rax) (:imm-rax 1) (:store-word :rdx 88 :rax)
        (:jmp :identity-ready)
        (:label :identity-failed) (:store-frame -16 :rax)
        (:label :identity-ready))
      (loop for offset in '(24 80) for label in '(:file :probe) append
        (scoped-forms label
          `((:load-frame :rdx -8) (:load-word :rdi :rdx ,offset)
            (:cmp-imm :rdi -1) (:jz :done) (:cmp-imm :rdi 0) (:jl :bad)
            (:imm-rax -1) (:store-word :rdx ,offset :rax)
            (:publication-syscall ,(if (eq label :file) :close-file :close-probe) 3) (:test) (:jz :done)
            (:cmp-imm :rax -9) (:jz :bad) (:cmp-imm :rax -4095) (:jl :bad)
            (:load-frame :rcx -16) (:test-rcx) (:jnz :done) (:store-frame -16 :rax) (:jmp :done)
            (:label :bad) (:imm-rax 1) (:store-frame -24 :rax) (:label :done))))
      '((:load-frame :rdx -8) (:load-word :rax :rdx 48) (:test) (:jz :map)
        (:load-word :rax :rdx 88) (:test) (:jz :unowned-name)
        (:label :name-stat) (:load-frame :rdx -8) (:load-word :rdi :rdx 16)
        (:load-word :rsi :rdx 56) (:lea-base :rdx :rbp -256)
        (:mov-r10d 256) (:publication-syscall :cleanup-stat 262)
        (:cmp-eintr) (:jz :name-stat) (:cmp-imm :rax -2) (:jz :removed)
        (:test) (:js :name-error)
        (:load-frame :rdx -8) (:load-word :rcx :rdx 64) (:load-frame :rax -256) (:cmp) (:jnz :unowned-name)
        (:load-word :rcx :rdx 72) (:load-frame :rax -248) (:cmp) (:jnz :unowned-name)
        (:label :unlink) (:load-frame :rdx -8) (:load-word :rdi :rdx 16)
        (:load-word :rsi :rdx 56) (:mov-edx 0) (:publication-syscall :unlink 263)
        (:cmp-eintr) (:jz :unlink) (:test) (:js :name-error)
        (:label :removed) (:load-frame :rdx -8) (:imm-rax 0) (:store-word :rdx 48 :rax) (:jmp :map)
        (:label :unowned-name) (:imm-rax -5)
        (:label :name-error) (:cmp-imm :rax -9) (:jz :bad-name)
        (:cmp-imm :rax -14) (:jz :bad-name) (:cmp-imm :rax -22) (:jz :bad-name)
        (:load-frame :rcx -16) (:test-rcx) (:jnz :map) (:store-frame -16 :rax) (:jmp :map)
        (:label :bad-name) (:imm-rax 1) (:store-frame -24 :rax)
        (:label :map) (:load-frame :rdx -8) (:load-word :rdi :rdx 32)
        (:load-word :rsi :rdx 40) (:cmp-imm :rdi 0) (:jz :parent)
        (:imm-rax 0) (:store-word :rdx 32 :rax) (:publication-syscall :path-unmap 11)
        (:test) (:jz :parent) (:cmp-imm :rax -22) (:jz :bad-map) (:cmp-imm :rax -14) (:jz :bad-map)
        (:load-frame :rcx -16) (:test-rcx) (:jnz :parent) (:store-frame -16 :rax) (:jmp :parent)
        (:label :bad-map) (:imm-rax 1) (:store-frame -24 :rax)
        (:label :parent) (:load-frame :rdx -8) (:load-word :rdi :rdx 16)
        (:cmp-imm :rdi -1) (:jz :done) (:cmp-imm :rdi 0) (:jl :bad-parent)
        (:imm-rax -1) (:store-word :rdx 16 :rax) (:publication-syscall :close-parent 3)
        (:test) (:jz :done) (:cmp-imm :rax -9) (:jz :bad-parent)
        (:load-frame :rcx -16) (:test-rcx) (:jnz :done) (:store-frame -16 :rax) (:jmp :done)
        (:label :bad-parent) (:imm-rax 1) (:store-frame -24 :rax)
        (:label :done) (:load-frame :rax -16) (:load-frame :rdx -24))
      (helper-return))))

(defun publication-errno-unit ()
  (publication-unit :publication.errno
    (append
      (loop for (kind . numbers) in '((1 17 39) (2 2) (3 1 13 30) (4 18 20 22 38 95) (5 12 23 24 28 122)) append
        (loop for number in numbers append
          `((:cmp-imm :rax ,(- number)) (:jz ,(intern (format nil "KIND-~D" kind) :keyword)))))
      '((:imm-rax 6) (:ret))
      (loop for kind from 1 to 5 append
        `((:label ,(intern (format nil "KIND-~D" kind) :keyword)) (:imm-rax ,kind) (:ret))))))
