(in-package #:mognitio.native.runtime)

(defun verify-scalar-root-flow (forms)
  ;; Interpret every local edge, retaining reference identities across stores.
  ;; A saved scalar must survive until node construction and List publication.
  (let ((code (coerce forms 'vector)) (labels (make-hash-table :test #'equal))
        (queue (list (list 0 :idle nil 0 0 0 :unknown :unknown)))
        (seen (make-hash-table :test #'equal)))
    (dolist (f forms)
      (when (or (and (eq (first f) :lea-base) (eq (third f) :rbp) (member (fourth f) '(-8 -16 -24)))
                (and (member (first f) '(:store-word :store-byte)) (eq (second f) :rbp) (member (third f) '(-8 -16 -24))))
        (internal-error "Scalar root slot escapes tracked operations")))
    (loop for f across code for pc from 0 when (eq (first f) :label)
          do (setf (gethash (second f) labels) pc))
    (loop while queue for state = (pop queue) unless (gethash state seen) do
      (setf (gethash state seen) t)
      (destructuring-bind (pc stage linked input partial scalar rax rdx) state
        (when (>= pc (length code)) (internal-error "Scalar helper falls through"))
        (let* ((f (aref code pc)) (op (first f))
               (writes (if (eq op :sub) '(:rax) (io-helper-writes f))))
          (labels ((value (reg) (case reg (:rax rax) (:rdx rdx) (otherwise :unknown)))
                   (save (reg v) (case reg (:rax (setf rax v)) (:rdx (setf rdx v))))
                   (need (ok) (unless ok (internal-error "Scalar reference lifetime is not proved")))
                   (enqueue (next)
                     (when (integerp next)
                       (push (list next stage linked input partial scalar rax rdx) queue))))
            (when (eq op :call)
              (need (and linked (eq input :input) (eq partial :list)))
              (case (second (second f))
                (:allocate (need (eq stage :idle)) (setf stage :produced))
                (:allocate-block
                 (need (and (eq stage :rooted) (eq scalar :scalar)))
                 (setf stage :node))))
            (when (eq op :store-frame)
              (let ((v (value (third f))))
                (case (second f)
                  (-8 (need (eq v :input)) (setf input v))
                  (-16
                   (cond ((eq v :list) (need (eq stage :idle)))
                         ((eq v :node) (need (eq stage :element)) (setf stage :published))
                         (t (need nil)))
                   (setf partial :list))
                  (-24
                   (cond ((eq v :scalar) (need (eq stage :produced)) (setf stage :rooted))
                         ((eql v 0) (need (eq stage :published)) (setf stage :idle))
                         (t (need nil)))
                   (setf scalar v)))))
            (when (and (eq op :store-word) (eq (second f) :rdx) (= (third f) 48))
              (need (and (eq stage :node) (eq rdx :node)
                         (eq scalar :scalar) (eq (value (fourth f)) :scalar)))
              (setf stage :element))
            (when (and (eq op :store-word) (eq (second f) :r15) (= (third f) 0))
              (cond ((equal (aref code (1- pc)) '(:lea-base :rax :rbp -40))
                     (need (not linked)) (setf linked t))
                    ((equal (aref code (1- pc)) '(:load-frame :rcx -40))
                     (need (and linked (eq stage :idle))) (setf linked nil))
                    (t (need nil))))
            (when (eq op :ret) (need (and (not linked) (eq stage :idle))))
            (let ((source (when (eq op :mov-reg) (value (third f)))))
              (dolist (reg writes) (save reg :unknown))
              (case op
                (:mov-reg (save (second f) source))
                (:imm-rax (setf rax (if (zerop (second f)) 0 :other)))
                (:lea-object (setf rax :list))
                (:load-frame
                 (save (second f) (case (third f) (16 :input) (-8 input) (-16 partial) (-24 scalar) (otherwise :unknown))))
                (:call (setf rax (case (second (second f)) (:allocate :scalar) (:allocate-block :node) (otherwise :unknown))))))
            (unless (member op '(:ret :ud2))
              (unless (eq op :jmp) (enqueue (1+ pc)))
              (when (member op '(:jmp :jz :jnz :jae :ja :jb :js :jo :jle :jl :jbe))
                (enqueue (gethash (second f) labels))))))))))
