(in-package #:mognitio.native.runtime)

(defun verify-primary-phase-flow (forms directory)
  ;; Start at the primary snapshot, independently considering no error, a kind
  ;; error, and a raw errno. Follow guards with abstract register/frame facts.
  ;; Adoption may write a new phase once; an existing primary is immutable.
  (let* ((code (coerce forms 'vector)) (labels (make-hash-table :test #'equal))
         (kind-slot (if directory -96 -64)) (errno-slot (unless directory -56))
         (phase-slot (if directory -728 -400))
         (capture (position (list :store-frame phase-slot :rax) forms :test #'equal))
         (end (position '(:store-word :r15 272 :rax) forms :test #'equal :from-end t))
         (registers '(:rax :rcx :rdx :rsi :rdi :r8 :r9 :r10 :r11))
         (queue nil) (seen (make-hash-table :test #'equal)))
    (unless (and capture end (< capture end)) (internal-error "Missing primary flow region"))
    (loop for f across code for pc from 0 when (eq (first f) :label)
          do (setf (gethash (second f) labels) pc))
    (dolist (seed (if directory '((-1 0 nil) (2 0 t)) '((-1 0 nil) (2 0 t) (-1 -2 t))))
      (destructuring-bind (kind errno locked) seed
        (push (list (1+ capture) kind errno locked nil (make-list (length registers) :initial-element :unknown) nil) queue)))
    (loop while queue for state = (pop queue) unless (gethash state seen) do
      (setf (gethash state seen) t)
      (destructuring-bind (pc kind errno locked pending values flags) state
        (when (>= pc (length code)) (internal-error "Primary path falls through"))
        (setf values (copy-list values))
        (let* ((f (aref code pc)) (op (first f)))
          (labels ((value (reg) (let ((i (position reg registers))) (if i (nth i values) :unknown)))
                   (assign (reg v)
                     (let ((i (position reg registers))) (when i (setf (nth i values) v)))
                     (when (and flags (eq reg (first flags))) (setf flags (list nil (second flags) (third flags)))))
                   (equality (a b)
                     (cond ((and (integerp a) (integerp b)) (if (= a b) :yes :no))
                           ((and (eq a :nonzero) (eql b 0)) :no)
                           ((and (eq a :not-minus-one) (eql b -1)) :no)
                           (t :unknown)))
                   (enqueue (next equal-p)
                     (unless (and flags equal-p (not (eq (third flags) :unknown))
                                  (not (eq equal-p (third flags))))
                       (when (integerp next)
                         (let ((saved (copy-list values)))
                           (when (and flags equal-p (first flags))
                             (let ((i (position (first flags) registers)) (n (second flags)))
                               (when i (setf (nth i saved)
                                 (cond ((eq equal-p :yes) n) ((not (eq (nth i saved) :unknown)) (nth i saved)) (t (case n (0 :nonzero) (-1 :not-minus-one) (otherwise :unknown))))))))
                           (push (list next kind errno locked pending saved flags) queue)))))
                   (need (ok) (unless ok (internal-error (format nil "Cleanup primary preservation is unproved at ~D: ~S (kind ~S, errno ~S, locked ~S, pending ~S)" pc f kind errno locked pending)))))
            (cond
              ((= pc end) (need (not pending)))
              (t
               (when (eq op :store-frame)
                 (let ((slot (second f)) (v (value (third f))))
                   (cond ((or (= slot kind-slot) (eql slot errno-slot))
                          (need (and (not locked) (not pending)))
                          (if (= slot kind-slot) (setf kind v) (setf errno v))
                          (setf pending t))
                         ((= slot phase-slot)
                          (need (and (not locked) pending)) (setf locked t pending nil)))))
               (let ((source (when (eq op :mov-reg) (value (third f)))))
                 (dolist (reg (if (eq op :sub) '(:rax) (io-helper-writes f))) (assign reg :unknown))
                 (case op
                   (:mov-reg (assign (second f) source))
                   ((:imm-rax :mov-eax) (assign :rax (second f)))
                   ((:imm-rcx) (assign :rcx (second f)))
                   ((:imm-rdx :mov-edx) (assign :rdx (second f)))
                   (:imm-reg (assign (second f) (third f)))
                   (:load-frame (assign (second f)
                                  (cond ((= (third f) kind-slot) kind)
                                        ((eql (third f) errno-slot) errno) (t :unknown))))
                   (:call (when (member (second f) '((:runtime :io.errno) (:runtime :directory.errno)) :test #'equal)
                            (assign :rax 7)))))
               (cond ((eq op :cmp-imm) (setf flags (list (second f) (third f) (equality (value (second f)) (third f)))))
                     ((eq op :test) (setf flags (list :rax 0 (equality (value :rax) 0))))
                     ((eq op :test-rcx) (setf flags (list :rcx 0 (equality (value :rcx) 0))))
                     ((member op '(:cmp :cmp-reg :cmp-rax-rdx :cmp-eintr :add-imm :and-imm :or-imm :add-reg
                                   :sub-reg :shr-imm :mul :add :sub :dec-rcx :add-rsi :sub-rdx :dec-r10d :call :syscall))
                      (setf flags nil)))
               (when (eq op :ret) (need (not pending)))
               (unless (member op '(:ret :ud2))
                 (unless (eq op :jmp) (enqueue (1+ pc) (case op (:jz :no) (:jnz :yes))))
                 (when (member op '(:jmp :jz :jnz :jae :ja :jb :js :jo :jle :jl :jbe))
                   (enqueue (gethash (second f) labels) (case op (:jz :yes) (:jnz :no)))))))))))))
