(in-package #:mognitio.native.runtime)

(defun verify-publication-unit (unit)
  ;; Independent frame/effect/ownership checks. No emitter is used as oracle.
  (let* ((name (second (mognitio.object:code-unit-entry unit)))
         (operation (and (consp name) (eq (first name) :binary.publish)))
         (words (if operation 192 (ecase name (:publication.profile 640) (:publication.cleanup 64) (:publication.errno 0))))
         (forms (mapcar (lambda (i) (cons (mognitio.machine:instruction-opcode i) (mognitio.machine:instruction-operands i)))
                        (mognitio.object:code-unit-instructions unit)))
         (labels (loop for f in forms when (eq (first f) :label) collect (second f)))
         (fatal '(:allocation-failed (:runtime :directory.internal))))
    (unless (or (zerop words)
                (equal (subseq forms 1 (+ words 3))
                       (append '((:push-rbp) (:mov-reg :rbp :rsp)) (make-list words :initial-element '(:push-zero)))))
      (internal-error "Invalid publication frame"))
    (loop for f in forms for i from 0 for op = (first f) do
      (when (member op '(:store-frame :load-frame :store-out))
        (let ((offset (if (eq op :load-frame) (third f) (second f))))
          (unless (and (integerp offset) (zerop (mod offset 8))
                       (if (eq op :store-out) (<= 0 offset 16)
                           (or (<= (- (* words 8)) offset -8)
                               (and (eq op :load-frame) (member offset (if operation '(16 24 32) '(16)))))))
            (internal-error "Publication frame access escapes layout"))))
      (when (member op '(:load-byte :store-byte))
        (when (eq (if (eq op :load-byte) (third f) (second f)) :rbp)
          (let ((offset (if (eq op :load-byte) (fourth f) (third f))))
            (unless (<= (- (* words 8)) offset -1) (internal-error "Publication byte scratch escapes frame")))))
      (when (and (member op '(:mov-reg :load-frame :load-word :load-byte :lea-base :imm-reg :add-imm :and-imm :or-imm :add-reg :sub-reg :shr-imm))
                 (member (second f) '(:rbx :r12 :r13 :r14 :r15)))
        (internal-error "Publication clobbers callee save"))
      (when (and (eq op :store-word) (eq (second f) :r15))
        (unless (and operation (member (third f) '(0 272))) (internal-error "Invalid publication context store")))
      (when (eq op :call)
        (unless (member (second f)
                  (if operation '((:runtime :allocate-block) (:runtime :io.map) (:runtime :publication.profile)
                                  (:runtime :publication.cleanup) (:runtime :publication.errno)) nil) :test #'equal)
          (internal-error "Publication helper has unapproved call or allocation")))
      (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
        (unless (or (member (second f) labels :test #'equal) (member (second f) fatal :test #'equal))
          (internal-error "Publication jump escapes checked paths")))
      (when (eq op :syscall)
        (unless (eq :mov-eax (first (nth (1- i) forms))) (internal-error "Publication syscall lacks number"))
        (unless (member (second (nth (1- i) forms))
                        (if operation '(257 262 11 318 5 91 0 1 3 316)
                            (case name (:publication.profile '(138 332 63 257 0 3))
                                       (:publication.cleanup '(5 3 262 263 11)))))
          (internal-error "Unexpected publication syscall")))
      (when (and (eq op :ret) (plusp words))
        (unless (equal (subseq forms (- i 2) (1+ i)) '((:mov-reg :rsp :rbp) (:pop-rbp) (:ret)))
          (internal-error "Invalid publication return"))))
    (when operation
      (unless (equal (subseq forms (+ words 3) (+ words 9))
                     '((:load-word :rax :r15 0) (:store-frame -64 :rax) (:imm-rax 6)
                       (:store-frame -56 :rax) (:lea-base :rax :rbp -64) (:store-word :r15 0 :rax)))
        (internal-error "Invalid publication roots"))
      ;; Verify the actual kernel no-replace flag and same-parent argument setup,
      ;; rather than accepting an operation name as proof of nonreplacement.
      (loop for f in forms for i from 0 when (equal f '(:mov-eax 316)) do
        (loop for register in '(:rdi :rsi :rdx :r10 :r8)
              for expected in '((:load-frame :rdi -240) (:lea-base :rsi :rbp -384)
                                (:mov-reg :rdx :rdi) (:load-frame :r10 -112) (:imm-reg :r8 1)) do
          (let ((definition (loop for prior in (reverse (subseq forms 0 i))
                                  when (and (member (first prior) '(:load-frame :lea-base :mov-reg :imm-reg))
                                            (eq register (second prior))) return prior)))
            (unless (equal definition expected) (internal-error "Publication commit violates no-replace ABI")))))
      (let ((pending (list (list 0 :absent))) (seen (make-hash-table :test #'equal)))
        (loop while pending for state = (pop pending) unless (gethash state seen) do
          (setf (gethash state seen) t)
          (destructuring-bind (pc ownership) state
            (when (>= pc (length forms)) (internal-error "Publication falls through"))
            (let* ((f (nth pc forms)) (op (first f)) (next ownership))
              (when (equal f '(:store-word :r15 272 :rax))
                (setf next (cond
                             ((equal (nth (1- pc) forms) '(:lea-base :rax :rbp -256))
                              (unless (eq ownership :absent) (internal-error "Duplicate publication record")) :owned)
                             ((equal (nth (1- pc) forms) '(:load-frame :rax -256))
                              (unless (eq ownership :cleaned) (internal-error "Uncleaned publication record")) :released)
                             (t (internal-error "Forged publication cleanup link")))))
              (when (equal f '(:call (:runtime :publication.cleanup)))
                (unless (eq ownership :owned) (internal-error "Publication cleanup without ownership"))
                (setf next :cleaned))
              (when (equal f '(:call (:runtime :allocate-block)))
                (unless (eq ownership :released) (internal-error "Publication allocates Result before cleanup")))
              (when (eq op :ret)
                (unless (eq ownership :released) (internal-error "Publication return retains resources"))
                (unless (equal (subseq forms (- pc 4) (- pc 2)) '((:load-frame :rcx -64) (:store-word :r15 0 :rcx)))
                  (internal-error "Publication return retains roots")))
              (unless (member op '(:ret :ud2))
                (unless (eq op :jmp) (push (list (1+ pc) next) pending))
                (when (member op '(:jmp :jz :jnz :jle :jl :js :jb :jbe :ja :jae :jo))
                  (let ((target (position (list :label (second f)) forms :test #'equal)))
                    (when target (push (list target next) pending))))))))))
  unit))
