(in-package #:mognitio.native.runtime)

(defun text-counter-forms (slot)
  (when (option :text-counters)
    `((:load-frame :r10 ,slot) (:add-imm :r10 1) (:store-frame ,slot :r10))))
(defun text-copy-forms (label)
  (loop for form in (copy-forms label) append
    (append (list form) (when (eq (first form) :store-byte) (text-counter-forms -96)))))
(defun text-counter-report ()
  (when (option :text-counters)
    '((:store-frame -104 :rax) (:lea-base :rsi :rbp -96)
      (:mov-edx 24) (:mov-edi 2) (:mov-eax 1) (:syscall) (:load-frame :rax -104))))

;; Roots occupy -8..-24, header -40..-32; cursors -48..-72;
;; outgoing arguments occupy -160..-144. No interior pointer crosses allocation.
(defun text-scalars-unit (inst)
  (runtime-unit (second (value-helper-name inst))
    (append (helper-frame 20) (helper-root-link 3)
      '((:load-frame :rax 16) (:store-frame -8 :rax))
      `((:lea-object ,(static-name :list '(:list :string))) (:store-frame -16 :rax))
      '((:label :walk) (:load-frame :rsi -8) (:load-word :rcx :rsi 16)
        (:load-frame :rax -48) (:cmp) (:jae :done) (:add-reg :rsi :rax)
        (:load-byte :rax :rsi 32) (:imm-rcx 1) (:cmp-imm :rax 128) (:jb :width)
        (:imm-rcx 2) (:cmp-imm :rax 224) (:jb :width)
        (:imm-rcx 3) (:cmp-imm :rax 240) (:jb :width) (:imm-rcx 4)
        (:label :width) (:store-frame -56 :rcx) (:store-out 0 :rcx)
        (:imm-rax 1) (:store-out 8 :rax) (:call (:runtime :allocate)) (:store-frame -24 :rax)
        (:lea-base :rdi :rax 32) (:load-frame :rsi -8) (:add-imm :rsi 32)
        (:load-frame :rax -48) (:add-reg :rsi :rax) (:load-frame :rcx -56))
      (text-copy-forms :scalar-copy)
      (text-counter-forms -80)
      (allocate-object :scalar-node (layout-name '(:list (:list :string))) 5 3)
      '((:load-frame :rax -16) (:store-word :rdx 40 :rax) (:load-word :rax :rax 32)
        (:add-imm :rax 1) (:store-word :rdx 32 :rax)
        (:load-frame :rax -24) (:store-word :rdx 48 :rax) (:store-frame -16 :rdx)
        (:imm-rax 0) (:store-frame -24 :rax)
        (:load-frame :rax -48) (:load-frame :rcx -56) (:add) (:store-frame -48 :rax))
      (text-counter-forms -88)
      '((:jmp :walk)
        (:label :done) (:load-frame :rax -16))
      (text-counter-report) (helper-root-unlink 3) (helper-return)) :helper))

(defun join-length-forms (prefix source)
  (scoped-forms prefix
    `((:load-frame :rsi ,source) (:load-word :rcx :rsi 24) (:load-frame :rax -56)
      (:add) (:jo :string-size-overflow) (:store-frame -56 :rax)
      (:load-word :rcx :rsi 16) (:load-frame :rax -48)
      (:add) (:jo :allocation-failed) (:store-frame -48 :rax))))
(defun join-copy-forms (prefix source)
  (scoped-forms prefix
    (append `((:load-frame :rsi ,source) (:load-word :rcx :rsi 16)
              (:load-frame :rax -48) (:sub) (:store-frame -48 :rax)
              (:load-frame :rdi -24) (:add-imm :rdi 32) (:add-reg :rdi :rax) (:add-imm :rsi 32))
            (text-copy-forms :copy))))
(defun text-join-unit (inst)
  (runtime-unit (second (value-helper-name inst))
    (append (helper-frame 20) (helper-root-link 3)
      '((:load-frame :rax 16) (:store-frame -8 :rax) (:store-frame -64 :rax)
        (:load-frame :rax 24) (:store-frame -16 :rax)
        (:label :size) (:load-frame :rdx -64) (:load-word :rax :rdx 32)
        (:test) (:jz :allocate) (:load-word :rax :rdx 48) (:store-frame -72 :rax))
      (text-counter-forms -80)
      (join-length-forms :fragment -72)
      '((:load-frame :rdx -64) (:load-word :rax :rdx 32) (:cmp-imm :rax 1) (:jz :sized))
      (join-length-forms :separator -16)
      '((:label :sized) (:load-frame :rdx -64) (:load-word :rax :rdx 40)
        (:store-frame -64 :rax) (:jmp :size)
        (:label :allocate))
      (when (option :text-length-limit)
        `((:load-frame :rax -56) (:imm-rcx ,(option :text-length-limit)) (:cmp) (:ja :string-size-overflow)))
      '((:load-frame :rax -48) (:test) (:jz :empty) (:store-out 0 :rax)
        (:load-frame :rax -56) (:store-out 8 :rax) (:call (:runtime :allocate)) (:store-frame -24 :rax)
        (:load-frame :rax -8) (:store-frame -64 :rax)
        (:label :fill) (:load-frame :rdx -64) (:load-word :rax :rdx 48) (:store-frame -72 :rax))
      (text-counter-forms -88)
      (join-copy-forms :fragment -72)
      '((:load-frame :rdx -64) (:load-word :rax :rdx 32) (:cmp-imm :rax 1) (:jz :ready))
      (join-copy-forms :separator -16)
      '((:load-frame :rdx -64) (:load-word :rax :rdx 40) (:store-frame -64 :rax) (:jmp :fill)
        (:label :ready) (:load-frame :rax -24) (:jmp :done)
        (:label :empty) (:lea-text (:text 0)) (:label :done))
      (text-counter-report) (helper-root-unlink 3) (helper-return)) :helper))
