(in-package #:mognitio.semantic)

(defun numeric-scalar-p (type)
  (and (consp type)
       (case (first type)
         (:fixed-int (and (= 3 (length type)) (member (third type) '(:signed :unsigned))))
         (:bits (= 2 (length type))))
       (or (value-parameter-p (second type))
           (and (integer-argument-p (second type)) (<= 1 (second (second type)) 64)))))
(defun fixed-integer-p (type) (and (numeric-scalar-p type) (eq :fixed-int (first type))))
(defun bits-type-p (type) (and (numeric-scalar-p type) (eq :bits (first type))))

(defun numeric-failure (span message)
  (if span (fail-at span :type message) (internal-error message)))

(defun require-numeric-width (context argument minimum span)
  (cond
    ((integer-argument-p argument)
     (unless (<= minimum (second argument) 64)
       (numeric-failure span "Numeric width or literal range constraint is not satisfied"))
     nil)
    ((value-parameter-p argument)
     (let* ((table (value-context-width-constraints context)) (old (gethash argument table)))
       (when (> minimum 64) (numeric-failure span "Numeric literal has no valid width"))
       (when (or (null old) (> minimum (first old)))
         (setf (gethash argument table) (list minimum span))
         t)))
    (t (numeric-failure span "Numeric width requires an integer argument"))))

(defun record-numeric-substitution (context parameters arguments span)
  (unless (some #'value-parameter-p parameters) (return-from record-numeric-substitution nil))
  (let ((entry (list parameters arguments span)))
    (pushnew entry (value-context-constraint-edges context) :test #'equal))
  (loop for parameter in parameters for argument in arguments
        for condition = (gethash parameter (value-context-width-constraints context))
        when condition do (require-numeric-width context argument (first condition) (or span (second condition)))))

(defun solve-numeric-constraints (context)
  (loop with changed = t while changed do
    (setf changed nil)
    (dolist (edge (value-context-constraint-edges context))
      (loop for parameter in (first edge) for argument in (second edge)
            for condition = (gethash parameter (value-context-width-constraints context))
            when condition do
              (when (require-numeric-width context argument (first condition) (or (third edge) (second condition)))
                (setf changed t)))))
  context)

(defun same-numeric-constraints-p (a b)
  (let ((left (value-context-width-constraints a)) (right (value-context-width-constraints b)))
    (and (= (hash-table-count left) (hash-table-count right))
         (loop for key being the hash-keys of left using (hash-value value)
               always (eql (first value) (first (gethash key right)))))))

(defun resolve-numeric-constructor (context token binding arguments)
  (let ((*numeric-span* (token-span token)))
    (unless (and arguments (= (length arguments) (if (eq binding :int) 2 1)))
      (fail-at *numeric-span* :type "Numeric constructor requires all arguments"))
    (let* ((width (resolve-integer-argument context (aref arguments 0)))
           (sign (when (eq binding :int) (resolve-type-token context (aref arguments 1)))))
      (require-numeric-width context width 1 *numeric-span*)
      (if (eq binding :bits-constructor) (list :bits width)
          (list :fixed-int width
                (cond ((equal sign (gethash "standard:Std\\Numeric#Signed" (value-context-names context))) :signed)
                      ((equal sign (gethash "standard:Std\\Numeric#Unsigned" (value-context-names context))) :unsigned)
                      (t (fail-at *numeric-span* :type "Signedness requires the standard Signed or Unsigned identity"))))))))

(defun numeric-builtin-declaration-p (node)
  (and (typep node 'data-declaration)
       (eq (mognitio.source::source-origin (span-source (node-span node))) :standard)
       (equal (token-text (data-declaration-name node)) "standard:Std\\Numeric#Bits")))

(defun declare-numeric-builtin (context node)
  (setf (gethash (token-text (data-declaration-name node)) (value-context-names context)) :bits-constructor
        (gethash node (value-context-members context)) (make-member-info :kind :builtin-type))
  :bits-constructor)

(defun verify-numeric-builtin (node stored)
  (v-check (and (eq stored :bits-constructor) (numeric-builtin-declaration-p node)
                (eq :struct (data-declaration-kind node)) (null (data-declaration-target node))
                (zerop (length (data-declaration-members node)))
                (= 1 (length (data-declaration-type-parameters node)))
                (typep (aref (data-declaration-type-parameters node) 0) 'mognitio.syntax::value-parameter-syntax)
                (eq :int (v-resolve (mognitio.syntax::value-parameter-syntax-domain
                                    (aref (data-declaration-type-parameters node) 0)))))
           "Invalid builtin Bits constructor"))

(defun numeric-range (type)
  (let* ((width (second (second type))) (signed (and (fixed-integer-p type) (eq :signed (third type)))))
    (values (if signed (- (ash 1 (1- width))) 0)
            (1- (ash 1 (if signed (1- width) width))))))
(defun numeric-in-range-p (value type)
  (and (integerp value) (numeric-scalar-p type) (integer-argument-p (second type))
       (multiple-value-bind (lo hi) (numeric-range type) (<= lo value hi))))

(defun scalar-literal-value (syntax)
  (let ((value (parse-integer (token-text (mognitio.syntax::value-argument-syntax-digits syntax)))))
    (if (mognitio.syntax::value-argument-syntax-negative syntax) (- value) value)))
(defun check-scalar-literal (context node type)
  (unless (numeric-scalar-p type) (fail-at (node-span node) :type "Typed literal requires a numeric scalar type"))
  (let* ((value (scalar-literal-value (mognitio.syntax::scalar-literal-value node)))
         (signed (and (fixed-integer-p type) (eq :signed (third type))))
         (minimum (if signed
                      (if (minusp value) (1+ (integer-length (1- (- value)))) (1+ (integer-length value)))
                      (if (minusp value) 65 (max 1 (integer-length value))))))
    (require-numeric-width context (second type) minimum (node-span node))
    value))
(defun c-scalar-literal (node)
  (let* ((type (resolve-type-token (c-context) (mognitio.syntax::scalar-literal-type node)))
         (value (check-scalar-literal (c-context) node type)))
    (setf (gethash node (checked-program-literals *checked*)) value)
    (c-summary node type t nil)))
(defun v-scalar-literal (node)
  (let* ((type (v-resolve (mognitio.syntax::scalar-literal-type node)))
         (value (check-scalar-literal (v-context) node type)))
    (v-check (= value (checked-literal (v-program) node)) "Invalid numeric scalar literal")
    (v-finish node type t nil)))

(defun numeric-operator-p (type op unary)
  (if (fixed-integer-p type)
      (if unary (eq op :sub) (member op '(:add :sub :mul :div :rem :eq :ne :lt :le :gt :ge)))
      (and (bits-type-p type) (not unary) (member op '(:eq :ne)))))
(declaim (notinline numeric-arithmetic))
(defun numeric-arithmetic (type op a &optional b)
  (unless (and (numeric-in-range-p a type) (or (eq op :neg) (numeric-in-range-p b type)))
    (internal-error "Invalid fixed-width operand"))
  (when (and (member op '(:div :rem)) (zerop b)) (mognitio.runtime:runtime-error :division-by-zero))
  (let ((value (ecase op (:neg (- a)) (:add (+ a b)) (:sub (- a b)) (:mul (* a b))
                       (:div (truncate a b)) (:rem (nth-value 1 (truncate a b))))))
    (unless (numeric-in-range-p value type) (mognitio.runtime:runtime-error :overflow))
    value))
