(in-package #:mognitio.semantic)

(defun integer-type-p (type) (or (eq type :int) (fixed-integer-p type)))
(defun integer-width (type) (if (eq type :int) '(:integer-value 64) (second type)))
(defun integer-signed-p (type) (or (eq type :int) (eq :signed (third type))))
(defun numeric-method-p (op)
  (member op '(:integer.convert :integer.to-bits :bits.integer :bits.length
               :bits.and :bits.or :bits.xor :bits.not :bits.left :bits.right :bits.at)))
(defun numeric-method-signature (context node type)
  (let* ((name (token-text (method-call-name node)))
         (arguments (mognitio.syntax::method-call-type-arguments node))
         (generic (member name '("convertTo" "asInteger") :test #'string=))
         (target nil))
    (unless (= (length arguments) (if generic 1 0))
      (fail-at (node-span node) :type "Wrong builtin method type argument count"))
    (when generic (setf target (resolve-type-token context (aref arguments 0))))
    (flet ((result (value error-name)
             (let ((error (gethash error-name (value-context-names context))))
               (unless error (fail-at (node-span node) :semantic "Numeric standard module is required"))
               (instantiate-generic-type context (gethash :result (value-context-templates context))
                                         (list value error)))))
      (cond
        ((and (integer-type-p type) (equal name "convertTo"))
         (unless (integer-type-p target) (fail-at (node-span node) :type "Conversion target must be an integer type"))
         (values :integer.convert nil (result target "standard:Std\\Numeric#IntegerConversionError")))
        ((and (integer-type-p type) (equal name "toBits"))
         (values :integer.to-bits nil (list :bits (integer-width type))))
        ((bits-type-p type)
         (cond
           ((equal name "asInteger")
            (let ((sign (cond ((equal target (gethash "standard:Std\\Numeric#Signed" (value-context-names context))) :signed)
                              ((equal target (gethash "standard:Std\\Numeric#Unsigned" (value-context-names context))) :unsigned)
                              (t (fail-at (node-span node) :type "Bit interpretation requires a standard signedness marker")))))
              (values :bits.integer nil (list :fixed-int (second type) sign))))
           ((equal name "length") (values :bits.length nil :int))
           ((equal name "not") (values :bits.not nil type))
           ((assoc name '(("and" . :bits.and) ("or" . :bits.or) ("xor" . :bits.xor)) :test #'equal)
            (values (cdr (assoc name '(("and" . :bits.and) ("or" . :bits.or) ("xor" . :bits.xor)) :test #'equal)) (list type) type))
           ((member name '("shiftLeft" "shiftRight") :test #'equal)
            (values (if (equal name "shiftLeft") :bits.left :bits.right) '(:int)
                    (result type "standard:Std\\Numeric#BitShiftError")))
           ((equal name "at") (values :bits.at '(:int) (result :bool "IndexError")))
           (t (fail-at (node-span node) :semantic "Unknown Bits method"))))
        (t (fail-at (node-span node) :semantic "Unknown integer method"))))))

(defun invoke-numeric-method (op source result error-type &rest arguments)
  (let* ((a (first arguments)) (b (second arguments))
         (width (second (integer-width source))) (mask (1- (ash 1 width))))
    (flet ((ok (value) (mognitio.value:construct result 0 value))
           (err (&rest fields) (mognitio.value:construct result 1 (apply #'mognitio.value:construct error-type 0 fields))))
      (case op
        (:integer.to-bits (logand a mask))
        (:bits.integer (if (and (eq :signed (third result)) (logbitp (1- width) a)) (- a (ash 1 width)) a))
        (:bits.length width)
        (:bits.and (logand a b)) (:bits.or (logior a b)) (:bits.xor (logxor a b))
        (:bits.not (logxor a mask))
        ((:bits.left :bits.right)
         (if (<= 0 b (1- width))
             (ok (logand mask (ash a (if (eq op :bits.left) b (- b))))) (err b width)))
        (:bits.at (if (<= 0 b (1- width)) (ok (logbitp b a)) (err b width)))
        (t (internal-error "Invalid numeric method"))))))
(defun convert-integer-value (value target result error-type)
  (if (if (eq target :int) (mognitio.integer:in-range-p value) (numeric-in-range-p value target))
      (mognitio.value:construct result 0 value)
      (mognitio.value:construct result 1 (mognitio.value:construct error-type 0))))

(in-package #:mognitio.backend.cl)

(defun numeric-method-form (info args context)
  (let* ((op (operation-info-kind info)) (source (first (operation-info-parameter-types info)))
         (result (operation-info-result-type info))
         (parts (mognitio.semantic::canonical-result-arguments context result))
         (error (second parts)))
    (if (eq op :integer.convert)
        (list 'mognitio.semantic::convert-integer-value (first args)
              (list 'quote (first parts)) (list 'quote result) (list 'quote error))
        (append (list 'mognitio.semantic::invoke-numeric-method op (list 'quote source)
                      (list 'quote result) (list 'quote error)) args))))
