(in-package #:mognitio.frontend)

(defun p-declaration-prefix (p top)
  (let ((start (p-peek p)) (attributes nil) (public nil))
    (loop while (eq (p-kind p) :at) do
      (let* ((at (p-take p)) (name (p-expect p :identifier)))
        (push (make-attribute-syntax :name name :span (p-span p at name)) attributes)))
    (when (eq (p-kind p) :public)
      (unless top (fail-at (token-span (p-peek p)) :parse "Public requires module declaration"))
      (setf public (p-take p)))
    (unless (member (p-kind p) '(:type :alias :contract :template :witness :let :var))
      (fail-at (token-span (p-peek p)) :parse "Expected declaration after prefix"))
    (when (and public (eq (p-kind p) :var))
      (fail-at (token-span public) :semantic "Declaration cannot be public"))
    (values (coerce (nreverse attributes) 'vector) (not (null public)) start)))

(defun p-declaration (p top)
  (multiple-value-bind (attributes public start) (p-declaration-prefix p top)
    (declare (ignore public))
    (unless (or top (member (p-kind p) '(:let :var)))
      (fail-at (token-span (p-peek p)) :parse "Compile-time declaration requires top level"))
    (let ((node (case (p-kind p)
                  ((:let :var) (p-binding p)) ((:type :alias) (p-data p))
                  (:contract (p-contract p)) (:template (p-template p)) (:witness (p-implementation p)))))
      (mognitio.syntax::with-declaration-metadata node attributes (p-span p start node)))))
