(in-package #:mognitio.frontend)

(defun p-data (p)
  (let* ((keyword (p-take p)) (name (p-name p)) (parameters (p-type-parameters p))
         (alias (eq (token-kind keyword) :alias)) (members nil) (target nil) (kind :alias))
    (p-expect p :assign)
    (if alias (setf target (p-type p))
        (progn
          (unless (member (p-kind p) '(:product :sum))
            (fail-at (token-span (p-peek p)) :parse "Type requires product or sum"))
          (setf kind (if (eq (token-kind (p-take p)) :product) :struct :enum))
          (p-expect p :left-brace)
          (loop until (eq (p-kind p) :right-brace) do
            (let ((label (p-name p)) (value nil))
              (if (eq kind :struct)
                  (progn (p-expect p :colon) (setf value (p-type p)))
                  (when (eq (p-kind p) :left-paren)
                    (p-take p) (setf value (vector (p-type p))) (p-expect p :right-paren)))
              (push (make-named-member :name label :value value
                                      :span (p-span p label (p-expect p :semicolon))) members)))
          (when (and (eq kind :enum) (null members))
            (fail-at (token-span name) :semantic "Empty sum"))
          (p-expect p :right-brace)))
    (make-data-declaration :name name :kind kind :target target :type-parameters parameters
                          :members (coerce (nreverse members) 'vector)
                          :span (p-span p keyword (p-expect p :semicolon)))))
(defun p-contract (p)
  (let ((keyword (p-take p)) (name (p-name p)) (members nil))
    (p-expect p :left-brace)
    (loop until (eq (p-kind p) :right-brace) do
      (let* ((label (p-name p)) (signature (p-function-tail p label t)))
        (push (make-named-member :name label :value signature :span (p-span p label signature)) members)))
    (make-contract-declaration :name name :methods (coerce (nreverse members) 'vector)
                               :span (p-span p keyword (p-expect p :right-brace)))))
(defun p-implementation (p)
  (let* ((keyword (p-take p)) (target (p-type p)) (methods nil))
    (p-expect p :against)
    (let ((contract (p-type p)))
      (p-expect p :left-brace)
      (loop until (eq (p-kind p) :right-brace) do
        (let* ((name (p-name p)) (function (p-function-tail p name)))
          (push (make-local-binding :name name :mutability :let :initializer function
                                    :span (p-span p name function)) methods)))
      (make-implementation-declaration :target target :contract contract
          :methods (coerce (nreverse methods) 'vector)
          :span (p-span p keyword (p-expect p :right-brace))))))
(defun p-template (p)
  (let* ((keyword (p-take p)) (name (p-name p)) (parameters (p-type-parameters p)))
    (when (zerop (length parameters)) (fail-at (token-span name) :parse "Template requires type parameters"))
    (p-expect p :assign)
    (let* ((function-token (p-expect p :function)) (function (p-function-tail p function-token)))
      (make-template-declaration :name name :parameters parameters :function function
                                 :span (p-span p keyword (p-expect p :semicolon))))))
(defun p-pattern (p)
  (let ((name (p-type p)))
    (p-expect p :scope)
    (let ((variant (p-name p)) (bindings #()) (last nil))
      (when (eq (p-kind p) :left-paren)
        (p-take p) (setf bindings (vector (p-parameter p)) last (p-expect p :right-paren)))
      (make-variant-pattern :name name :variant variant :bindings bindings
                            :span (p-span p name (or last variant))))))
(defun p-branch (p)
  (let* ((keyword (p-take p)) (mode (token-kind (p-take p))) (subject nil))
    (unless (member mode '(:on :when)) (fail-at (token-span keyword) :parse "Expected on or when"))
    (when (eq mode :on)
      (setf subject (p-expression p)))
    (p-expect p :left-brace)
    (let ((arms (p-list p
                  (lambda (p)
                    (let* ((start (p-peek p))
                           (selector (if (eq (p-kind p) :else) (progn (p-take p) nil)
                                         (if (eq mode :on) (p-pattern p) (p-expression p)))))
                      (p-expect p :fat-arrow)
                      (let ((value (p-expression p)))
                        (make-branch-arm :selector selector :value value :span (p-span p start value)))))
                  :right-brace nil)))
      (make-branch-expression :mode mode :subject subject :arms arms
                              :span (p-span p keyword (p-expect p :right-brace))))))
(defun p-named-expression (p)
  (let* ((token (p-peek p)) (category (gethash (token-text token) (parser-headers p)))
         (name (if (and category (eq (token-kind (p-peek p 1)) :lt)) (p-type p) (p-take p))))
    (cond
      ((eq category :template)
       (unless (typep name 'type-syntax)
         (fail-at (token-span name) :semantic "Template requires explicit type arguments"))
       (make-specialization-reference :name (type-syntax-name name) :arguments (type-syntax-arguments name)
                                      :span (form-span name)))
      ((eq (p-kind p) :scope)
       (p-take p)
       (let ((variant (p-name p)) (args #()) (last nil) (parens (eq (p-kind p) :left-paren)))
         (when parens (p-take p) (setf args (vector (p-expression p)) last (p-expect p :right-paren)))
         (make-enum-expression :name name :variant variant :arguments args :parenthesized-p parens
                               :span (p-span p name (or last variant)))))
      ((and category (eq (p-kind p) :left-bracket))
       (p-take p)
       (let ((items (p-list p #'p-expression :right-bracket)))
         (make-list-expression :type name :elements items
                               :span (p-span p name (p-expect p :right-bracket)))))
      ((and category (eq (p-kind p) :left-brace))
       (p-take p)
       (let ((fields (p-list p
                       (lambda (p) (let ((label (p-name p)))
                         (p-expect p :colon)
                         (let ((value (p-expression p)))
                           (make-named-member :name label :value value :span (p-span p label value)))))
                       :right-brace)))
         (make-struct-expression :name name :fields fields
                                 :span (p-span p name (p-expect p :right-brace)))))
      (t (make-variable-reference :name name :span (form-span name))))))
