(in-package #:mognitio.frontend)

(defvar *nesting-limit* nil)
(defvar *syntax-depth* 0)
(defmacro with-syntax-depth ((p) &body body)
  `(let ((*syntax-depth* (1+ *syntax-depth*)))
     (when (and *nesting-limit* (> *syntax-depth* *nesting-limit*))
       (fail-at (token-span (p-peek ,p)) :parse "Syntax nesting budget exceeded"))
     ,@body))

(defstruct parser source tokens (cursor 0) headers)
(defun p-peek (p &optional (ahead 0))
  (let ((at (+ (parser-cursor p) ahead)))
    (if (< at (length (parser-tokens p))) (aref (parser-tokens p) at)
        (aref (parser-tokens p) (1- (length (parser-tokens p)))))))
(defun p-kind (p) (token-kind (p-peek p)))
(defun p-take (p) (prog1 (p-peek p) (incf (parser-cursor p))))
(defun p-at-kind (p kind)
  (or (eq kind (p-kind p)) (and (eq kind :gt) (eq (p-kind p) :ge))))
(defun p-expect (p kind)
  ;; In a type delimiter position, >= closes the type and starts assignment.
  (when (and (eq kind :gt) (eq (p-kind p) :ge))
    (let* ((span (token-span (p-peek p))) (start (span-start span)) (source (span-source span)))
      (setf (aref (parser-tokens p) (parser-cursor p))
            (make-token :kind :assign :span (make-span source (1+ start) (span-end span))))
      (return-from p-expect (make-token :kind :gt :span (make-span source start (1+ start))))))
  (unless (eq kind (p-kind p))
    (fail-at (token-span (p-peek p)) :parse (format nil "Expected ~A" kind)))
  (p-take p))
(defun p-name (p)
  (let ((token (p-expect p :identifier)))
    (when (member (token-text token) '("Function" "Self") :test #'string=)
      (fail-at (token-span token) :semantic "Reserved type syntax name"))
    token))
(defun p-span (p first last)
  (make-span (parser-source p) (span-start (form-span first)) (span-end (form-span last))))
(defun p-list (p reader close &optional (empty t))
  (let ((items nil))
    (when (and (not empty) (p-at-kind p close))
      (fail-at (token-span (p-peek p)) :parse "Empty list is not allowed"))
    (unless (p-at-kind p close)
      (loop
        (push (funcall reader p) items)
        (unless (eq (p-kind p) :comma) (return))
        (p-take p)
        (when (p-at-kind p close) (return))))
    (coerce (nreverse items) 'vector)))
(defun declaration-headers (tokens)
  ;; Collect only top-level headers. Full parsing subsequently checks each body.
  (let ((headers (make-hash-table :test #'equal)) (stack nil))
    (dolist (name '("Int" "Bool" "String" "Unit" "List" "Result" "IndexError" "SliceError"))
      (setf (gethash name headers) :type))
    (loop for i below (length tokens) for token = (aref tokens i)
          for kind = (token-kind token) do
      (when (and (null stack) (member kind '(:type :alias :contract :template))
                 (< (1+ i) (length tokens)))
        (let ((name (aref tokens (1+ i))))
          (when (eq (token-kind name) :identifier)
            ;; Keep the first classification; semantic analysis diagnoses duplicates.
            (unless (gethash (token-text name) headers)
              (setf (gethash (token-text name) headers) kind)))))
      (cond ((member kind '(:left-paren :left-brace :left-bracket)) (push token stack))
            ((member kind '(:right-paren :right-brace :right-bracket))
             (unless (and stack
                          (eq (token-kind (first stack))
                              (ecase kind (:right-paren :left-paren) (:right-brace :left-brace)
                                (:right-bracket :left-bracket))))
               (fail-at (token-span token) :parse "Unmatched delimiter"))
             (pop stack))))
    (when stack (fail-at (token-span (first stack)) :parse "Unclosed delimiter"))
    headers))
(defun p-type (p)
  (with-syntax-depth (p)
  (let ((name (p-expect p :identifier)))
    (if (string= (token-text name) "Function")
        (progn
          (p-expect p :left-paren)
          (let ((parameters (p-list p #'p-type :right-paren)))
            (p-expect p :right-paren) (p-expect p :colon)
            (let ((result (p-type p)))
              (make-function-type-syntax :parameters parameters :result result :span (p-span p name result)))))
        (if (eq (p-kind p) :lt)
            (progn (p-take p)
              (let* ((args (p-list p #'p-type :gt nil)) (last (p-expect p :gt)))
                (make-type-syntax :kind :identifier :name name :arguments args :span (p-span p name last))))
            name)))))
(defun p-type-parameters (p)
  (if (eq (p-kind p) :lt)
      (progn (p-take p)
        (prog1 (p-list p #'p-name :gt nil) (p-expect p :gt)))
      #()))
(defun p-parameter (p)
  (let ((name (p-name p)))
    (p-expect p :colon)
    (let ((type (p-type p)))
      (make-parameter :name name :type type :span (p-span p name type)))))
(defun p-function-tail (p start &optional signature-only)
  (p-expect p :left-paren)
  (let ((parameters (p-list p #'p-parameter :right-paren)))
    (p-expect p :right-paren) (p-expect p :colon)
    (let* ((result (p-type p)) (body (unless signature-only (p-block p)))
           (end (if signature-only (p-expect p :semicolon) body)))
      (make-function-expression :parameters parameters :result-type result :body body
                                :span (p-span p start end)))))

(defun check-syntax-depth (program)
  (when *nesting-limit*
    (let ((stack (list (cons program 0))))
      (loop while stack do
        (destructuring-bind (node . depth) (pop stack)
          (cond
            ((and (vectorp node) (not (stringp node)))
             (map nil (lambda (child) (push (cons child depth) stack)) node))
            ((consp node) (dolist (child node) (push (cons child depth) stack)))
            ((and (typep node 'structure-object)
                  (eq (symbol-package (type-of node)) (find-package :mognitio.syntax)))
             (when (> depth *nesting-limit*)
               (fail-at (form-span node) :parse "Syntax nesting budget exceeded"))
             (dolist (slot (sb-mop:class-slots (class-of node)))
               (let ((name (sb-mop:slot-definition-name slot)))
                 (unless (member (symbol-name name) '("SPAN" "SOURCE" "PROJECT" "MODULES" "PAYLOAD")
                                 :test #'equal)
                   (push (cons (slot-value node name) (1+ depth)) stack))))))))))
  program)
