(in-package #:mognitio.frontend)

(defun p-binding (p)
  (let* ((keyword (p-take p)) (name (p-name p)))
    (p-expect p :colon)
    (let ((type (p-type p)))
      (p-expect p :assign)
      (let ((value (p-expression p)))
        (make-local-binding :name name :annotation type :mutability (token-kind keyword)
                            :initializer value :span (p-span p keyword (p-expect p :semicolon)))))))
(defun p-sequence (p end-kind &optional top)
  (let ((statements nil) (declarations nil) (tail nil) (start (p-peek p)))
    (loop until (eq (p-kind p) end-kind) do
      (when (eq (p-kind p) :eof) (fail-at (token-span (p-peek p)) :parse "Unclosed block"))
      (cond
        ((member (p-kind p) '(:at :public :type :alias :contract :witness :template :let :var))
         (let ((node (p-declaration p top)))
           (if (typep node 'local-binding) (push node statements) (push node declarations))))
        ((eq (p-kind p) :assert)
         (let* ((keyword (p-take p)) (operand (p-expression p)) (end (p-expect p :semicolon)))
           (push (make-assert-statement :operand operand :keyword-span (token-span keyword)
                                       :span (p-span p keyword end)) statements)))
        ((member (p-kind p) '(:return :break :continue :discard))
         (let* ((keyword (p-take p)) (kind (token-kind keyword))
                (value (when (or (member kind '(:return :discard))
                                 (and (eq kind :break) (not (eq (p-kind p) :semicolon))))
                         (p-expression p)))
                (last (p-expect p :semicolon)) (span (p-span p keyword last)))
           (push (case kind
                   (:return (make-return-statement :keyword keyword :value value :span span))
                   (:break (make-break-statement :value value :span span))
                   (:continue (make-continue-statement :span span))
                   (:discard (make-expression-statement :expression value :discard-p t :span span))) statements)))
        (t
         (let ((node (p-expression p)))
           (cond
             ((eq (p-kind p) :assign)
              (unless (typep node 'variable-reference)
                (fail-at (node-span node) :semantic "Assignment requires a variable binding"))
              (p-take p)
              (let ((rhs (p-expression p)))
                (push (make-assignment :name (variable-reference-name node) :rhs rhs
                                      :span (p-span p node (p-expect p :semicolon))) statements)))
             ((eq (p-kind p) :semicolon)
              (push (make-expression-statement :expression node :span (p-span p node (p-take p))) statements))
             (t (setf tail node) (return)))))))
    (let ((last (p-expect p end-kind)))
      (values (make-sequence-node :statements (coerce (nreverse statements) 'vector)
                                  :terminal tail :span (p-span p start last))
              (coerce (nreverse declarations) 'vector)))))
(defun p-block (p)
  (let* ((open (p-expect p :left-brace)) (body (p-sequence p :right-brace)))
    (make-sequence-node :statements (sequence-node-statements body) :terminal (sequence-node-terminal body)
                        :span (p-span p open body))))
(defun p-loop (p)
  (let ((keyword (p-take p)) (condition nil) (target nil) (binder nil))
    (unless (eq (p-kind p) :left-brace)
      (let ((mode (token-kind (p-take p))))
        (unless (member mode '(:while :over))
          (fail-at (token-span keyword) :parse "Expected loop body, while, or over"))
        (p-expect p :left-paren)
        (if (eq mode :while) (setf condition (p-expression p))
            (progn (setf target (p-expression p)) (p-expect p :as) (setf binder (p-parameter p))))
        (p-expect p :right-paren)))
    (let ((body (p-block p)))
      (make-loop-expression :condition condition :target target :binder binder :body body :span (p-span p keyword body)))))
(defun p-primary (p)
  (let ((token (p-peek p)))
    (case (p-kind p)
      ((:true :false) (p-take p) (make-boolean-literal :value (token-kind token) :span (token-span token)))
      (:unit (p-take p) (make-void-literal :span (token-span token)))
      (:integer (p-take p) (make-integer-literal :token token :span (token-span token)))
      (:string-literal (p-take p) (make-string-literal :payload (token-payload token) :span (token-span token)))
      (:identifier
       (when (member (token-text token) '("Function" "Self") :test #'string=)
         (fail-at (token-span token) :semantic "Reserved type syntax name"))
       (p-named-expression p))
      (:left-paren
       (p-take p)
       (let ((child (p-expression p)))
         (make-grouping :expression child :span (p-span p token (p-expect p :right-paren)))))
      (:left-brace (p-block p))
      (:function (p-take p) (p-function-tail p token))
      (:loop (p-loop p))
      (:branch (p-branch p))
      (:panic (p-take p)
       (let ((body (p-block p))) (make-panic-expression :block body :span (p-span p token body))))
      (otherwise (fail-at (token-span token) :parse "Expected expression")))))
(defun p-postfix (p)
  (let ((node (p-primary p)))
    (loop
      (case (p-kind p)
        ((:arrow :left-paren)
         (let ((member (when (eq (p-kind p) :arrow) (p-take p) (p-name p))))
           (if (and member (not (eq (p-kind p) :left-paren)))
               (setf node (make-field-expression :receiver node :name member :span (p-span p node member)))
               (progn
                 (p-expect p :left-paren)
                 (let* ((args (p-list p #'p-expression :right-paren)) (last (p-expect p :right-paren))
                        (span (p-span p node last)))
                   (setf node (if member (make-method-call :receiver node :name member :arguments args :span span)
                                  (make-call-expression :callee node :arguments args :span span))))))))
        (otherwise (return node))))))
(defun p-unary (p)
  (if (member (p-kind p) '(:sub :not :try))
      (let* ((token (p-take p)) (child (p-unary p)) (span (p-span p token child)))
        (if (eq (token-kind token) :try) (make-try-expression :operand child :span span)
            (make-unary-expression :operator token :operand child :span span)))
      (p-postfix p)))
(defun p-binary (p reader operators &optional single)
  (let ((left (funcall reader p)))
    (loop while (member (p-kind p) operators) do
      (let* ((op (p-take p)) (right (funcall reader p)))
        (setf left (make-binary-expression :operator op :left left :right right :span (p-span p left right))))
      (when single (return)))
    left))
(defun p-product (p) (p-binary p #'p-unary '(:mul :div :rem)))
(defun p-sum (p) (p-binary p #'p-product '(:add :sub)))
(defun p-comparison (p) (p-binary p #'p-sum '(:lt :le :gt :ge :eq :ne) t))
(defun p-and (p) (p-binary p #'p-comparison '(:and)))
(defun p-expression (p) (p-binary p #'p-and '(:or)))
(defun parse-program (source tokens &optional headers)
  (let ((p (make-parser :source source :tokens (copy-seq tokens) :headers (or headers (declaration-headers tokens)))))
    (multiple-value-bind (body declarations) (p-sequence p :eof t)
      (unless (= (parser-cursor p) (length tokens)) (internal-error "Tokens after EOF"))
      (make-program :source source :root (sequence-node-terminal body)
                    :statements (sequence-node-statements body) :declarations declarations))))
