(in-package #:mognitio.project)

(defstruct project manifest root name namespace name-span modules entry inputs order)
(defstruct source-module path source namespace tokens imports declarations program names dependencies)
(defstruct module-declaration module name kind public token node key)
(defstruct module-import namespace name alias span target)

(defun escaped-path (bytes)
  (with-output-to-string (s)
    (loop for b across bytes do
      (cond ((= b 92) (write-string "\\\\" s))
            ((<= 32 b 126) (write-char (code-char b) s))
            (t (format s "\\x~2,'0X" b))))))

(defun raw-string (bytes) (map 'string #'code-char bytes))
(defun raw-bytes (string) (map '(vector (unsigned-byte 8)) #'char-code string))
(defun utf8 (string) (sb-ext:string-to-octets string :external-format :utf-8))
(defun strict-path (raw)
  (handler-case (sb-ext:octets-to-string (raw-bytes raw) :external-format :utf-8)
    (error () (input-error (escaped-path (raw-bytes raw)) "Source path is not UTF-8"))))
(defun suffix-p (suffix name)
  (and (>= (length name) (length suffix))
       (string= suffix name :start2 (- (length name) (length suffix)))))
(defun file-id (stat) (cons (sb-posix:stat-dev stat) (sb-posix:stat-ino stat)))

(defun load-project (manifest)
  (handler-case
      (let* ((path (mognitio.artifact::native-path manifest))
             (stat (sb-posix:lstat path))
             (root (sb-ext:native-namestring
                    (truename (uiop:pathname-directory-pathname (sb-ext:parse-native-namestring path)))))
             (inputs (make-hash-table :test #'equal)) (modules nil))
        (unless (and (equal (file-namestring (sb-ext:parse-native-namestring path)) "mognitio.toml")
                     (sb-posix:s-isreg (sb-posix:stat-mode stat)))
          (input-error manifest "Expected a regular mognitio.toml"))
        (setf (gethash (file-id stat) inputs) path)
        (let ((source (handler-case (read-source path)
                        (source-failure () (input-error manifest "Manifest is not valid UTF-8")))))
          (multiple-value-bind (name namespace name-span) (manifest-values source)
            (unless (and (plusp (length name)) (char<= #\a (char name 0) #\z)
                         (every (lambda (c) (or (char<= #\a c #\z) (char<= #\0 c #\9) (eql c #\_))) name)
                         (namespace-parts namespace))
              (input-error manifest "Invalid project name or root namespace"))
            (labels
                ((walk (raw relative)
                   (let* ((sb-alien::*default-c-string-external-format* :latin-1)
                          (stat (sb-posix:lstat raw)) (mode (sb-posix:stat-mode stat)))
                     (cond
                       ((sb-posix:s-islnk mode)
                        (input-error (escaped-path (raw-bytes relative)) "Symlink input is forbidden"))
                       ((sb-posix:s-isdir mode)
                        (let ((stream (sb-posix:opendir raw)) (names nil))
                          (unwind-protect
                               (loop for entry = (sb-posix:readdir stream)
                                     until (sb-alien:null-alien entry)
                                     for entry-name = (sb-posix:dirent-name entry)
                                     unless (member entry-name '("." "..") :test #'equal)
                                       do (push entry-name names))
                            (sb-posix:closedir stream))
                          (dolist (child (sort names #'string<))
                            (walk (concatenate 'string raw "/" child)
                                  (concatenate 'string relative "/" child)))))
                       ((suffix-p ".mgn" relative)
                        (unless (sb-posix:s-isreg mode)
                          (input-error (escaped-path (raw-bytes relative)) "Source must be a regular file"))
                        (let* ((relative (strict-path relative))
                               (physical (strict-path raw))
                               (source-dirs (butlast (rest (uiop:split-string relative :separator '(#\/))))))
                          (unless (every #'identifier-p source-dirs)
                            (input-error relative "Invalid namespace directory"))
                          (when (gethash (file-id stat) inputs) (input-error relative "Duplicate physical input"))
                          (setf (gethash (file-id stat) inputs) physical)
                          (let ((sb-alien::*default-c-string-external-format* :utf-8))
                            (push (make-source-module
                                   :path relative
                                   :namespace (format nil "~{~A~^\\~}" (append (namespace-parts namespace) source-dirs))
                                   :source (decode-source relative (mognitio.source::read-octets physical)))
                                  modules))))))))
              (walk (raw-string (utf8 (concatenate 'string root "src"))) "src"))
            (setf modules (sort modules #'string< :key #'source-module-path))
            (let ((entry (find (format nil "src/~A.mgn" name) modules :key #'source-module-path :test #'equal)))
              (unless entry (fail-at name-span :manifest "Entry source is missing" 'usage-or-io-failure))
              (make-project :manifest path :root root :name name :namespace namespace :name-span name-span
                            :modules modules :entry entry :inputs inputs)))))
    (sb-posix:syscall-error () (input-error manifest "Cannot discover project inputs"))
    (file-error () (input-error manifest "Cannot access project"))))

(defun validate-project-output (project output)
  (let* ((destination (mognitio.artifact::native-path output))
         (parent (uiop:pathname-directory-pathname (sb-ext:parse-native-namestring destination)))
         (actual-parent (handler-case (sb-ext:native-namestring (truename parent))
                          (file-error () (input-error output "Output parent does not exist"))))
         (src (concatenate 'string (project-root project) "src/")))
    (when (and (uiop:string-prefix-p src actual-parent) (suffix-p ".mgn" destination))
      (input-error output "Output would become a project source"))
    (maphash (lambda (id input)
               (unless (equal id (file-id (mognitio.artifact::validated-source-stat input)))
                 (input-error input "Input identity changed"))
               (mognitio.artifact:validate-paths input output))
             (project-inputs project))))
