(in-package #:mognitio.project)

(defun verify-project-structure (program)
  ;; Rebuild names, imports and the execution plan from source headers and AST
  ;; ownership. Do not call the resolver or trust its cached tables.
  (let* ((project (mognitio.syntax::program-project program))
         (modules (project-modules project)) (exports (standard-exports project))
         (environments (make-hash-table)) (edges (make-hash-table)) (order nil))
    (labels ((check (value message) (mognitio.semantic::v-check value message))
             (name-token (node)
               (if (typep node 'local-binding) (local-binding-name node)
                   (mognitio.semantic::declaration-name node)))
             (kind-of (node)
               (typecase node
                 (data-declaration (if (eq (data-declaration-kind node) :alias) :alias :type))
                 (contract-declaration :contract) (template-declaration :template)
                 (implementation-declaration :witness)
                 (local-binding (if (eq (local-binding-mutability node) :var) :var :let)))))
      (verify-standard-catalog project)
      (dolist (module modules)
        (mognitio.syntax:walk-ast (source-module-program module)
          (lambda (node)
            (check (not (typep node '(or mognitio.syntax::runtime-arguments mognitio.syntax::io-expression))) "Argument node in user source"))))
      (check (= (length modules) (length (remove-duplicates modules))) "Duplicate project module")
      (check (equal (mapcar #'source-module-path modules)
                    (sort (remove-duplicates (mapcar #'source-module-path modules) :test #'equal) #'string<))
             "Invalid source identity order")
      (dolist (module modules)
        (let* ((source (source-module-source module)) (body (source-module-program module))
               (tokens (mognitio.frontend:lex-source source))
               (names (make-hash-table :test #'equal))
               (nodes (append (coerce (program-declarations body) 'list) (coerce (program-statements body) 'list))))
          (check (and (eq (mognitio.source::source-origin source) :user) (eq (program-source body) source) (null (program-root body))
                      (equal (source-path source) (source-module-path module))) "Invalid module provenance")
          (check (= (length nodes) (length (source-module-declarations module))) "Missing module declaration")
          (dolist (items (list (program-declarations body) (program-statements body)))
            (let ((positions (map 'list (lambda (node) (span-start (node-span node))) items)))
              (check (equal positions (sort (remove-duplicates positions) #'<)) "Invalid module source order")))
          (let ((depth 0) (positions nil))
            (loop for token across tokens for index from 0 for kind = (token-kind token) do
              (when (and (zerop depth) (member kind '(:type :alias :contract :template :witness :let :var)))
                (push (span-start (token-span (aref tokens (1+ index)))) positions))
              (when (member kind '(:left-brace :left-paren :left-bracket)) (incf depth))
              (when (member kind '(:right-brace :right-paren :right-bracket)) (decf depth)))
            (check (equal (nreverse positions)
                          (mapcar (lambda (decl) (span-start (token-span (module-declaration-token decl))))
                                  (source-module-declarations module))) "Missing source declaration"))
          (dolist (decl (source-module-declarations module))
            (let* ((node (module-declaration-node decl)) (token (name-token node))
                   (name (raw-name token))
                   (index (position (span-start (token-span token)) tokens
                                    :key (lambda (tok) (span-start (token-span tok)))))
                   (public (and index (> index 1) (eq (token-kind (aref tokens (- index 2))) :public))))
              (check (and (member node nodes) (eq (module-declaration-origin decl) :user) (eq (module-declaration-module decl) module)
                          (eq (span-source (token-span token)) source)
                          (eq token (module-declaration-token decl))
                          (eq (kind-of node) (module-declaration-kind decl))
                          (eq (token-kind (aref tokens (1- index))) (module-declaration-kind decl))
                          (equal name (module-declaration-name decl))
                          (equal (module-key module name) (module-declaration-key decl))
                          (eq (not (null public)) (not (null (module-declaration-public decl)))))
                     "Invalid declaration identity or visibility")
              (let ((cursor (- index (if public 3 2))) (prefix nil))
                (loop while (and (>= cursor 1) (eq (token-kind (aref tokens cursor)) :identifier)
                                 (eq (token-kind (aref tokens (1- cursor))) :at)) do
                  (push (cons (aref tokens (1- cursor)) (aref tokens cursor)) prefix)
                  (decf cursor 2))
                (dolist (attributes (list (declaration-attributes node) (module-declaration-attributes decl)))
                  (check (= (length prefix) (length attributes)) "Missing attribute syntax proof")
                  (loop for pair in prefix for attribute across attributes do
                    (let ((span (attribute-syntax-span attribute)) (name (attribute-syntax-name attribute)))
                      (check (and (equal (raw-name name) (raw-name (cdr pair)))
                                  (null (mognitio.syntax::token-resolved-name name))
                                  (eq (span-source span) source)
                                  (= (span-start span) (span-start (token-span (car pair))))
                                  (= (span-end span) (span-end (token-span (cdr pair))))
                                  (= (span-start (token-span name)) (span-start (token-span (cdr pair)))))
                             "Invalid attribute source proof"))))
                (let ((start (span-start (token-span (if prefix (caar prefix) (aref tokens (if public (- index 2) (1- index))))))))
                  (check (and (= start (span-start (declaration-span node)))
                              (= start (span-start (module-declaration-prefix-span decl)))
                              (= (span-end (declaration-span node)) (span-end (node-span node))))
                         "Invalid declaration prefix span")))
              (check (and (not (gethash name names)) (not (member name *predeclared* :test #'equal)))
                     "Conflicting declaration")
              (setf (gethash name names) decl)
              (when public
                (let ((key (cons (source-module-namespace module) name)))
                  (check (not (gethash key exports)) "Duplicate public declaration")
                  (setf (gethash key exports) decl)))))
          (setf (gethash module environments) names)))
      (dolist (module modules)
        (let* ((source (source-module-source module)) (tokens (mognitio.frontend:lex-source source))
               (i 0) (imports nil) (seen nil) (deps nil) (names (gethash module environments)))
          (labels ((kind () (token-kind (aref tokens i)))
                   (take (expected)
                     (check (eq (kind) expected) "Invalid module header proof")
                     (prog1 (aref tokens i) (incf i)))
                   (qualified (group)
                     (let ((parts (list (raw-name (take :identifier)))))
                       (loop while (eq (kind) :backslash) do
                         (incf i)
                         (when (and group (eq (kind) :left-brace)) (return))
                         (push (raw-name (take :identifier)) parts))
                       (format nil "~{~A~^\\~}" (nreverse parts)))))
            (take :namespace)
            (let* ((ns (qualified nil))
                   (dirs (butlast (rest (uiop:split-string (source-module-path module) :separator '(#\/)))))
                   (expected (format nil "~{~A~^\\~}" (append (namespace-parts (project-namespace project)) dirs))))
              (check (and (not (standard-namespace-p ns)) (equal ns expected) (equal ns (source-module-namespace module))) "Invalid namespace proof"))
            (take :semicolon)
            (loop while (eq (kind) :use) do
              (incf i)
              (let ((ns (qualified t)))
                (check (eq (token-kind (aref tokens (1- i))) :backslash) "Invalid group import proof")
                (take :left-brace)
                (loop
                  (let* ((name (take :identifier)) (alias name))
                    (when (eq (kind) :as) (incf i) (setf alias (take :identifier)))
                    (push (list ns (raw-name name) (raw-name alias)
                                (span-start (token-span name)) (span-end (token-span alias))) imports))
                  (unless (eq (kind) :comma) (return))
                  (incf i) (when (eq (kind) :right-brace) (return)))
                (take :right-brace) (take :semicolon)))
            (setf imports (nreverse imports))
            (check (= (length imports) (length (source-module-imports module))) "Missing import proof")
            (loop for row in imports for import in (source-module-imports module) do
              (destructuring-bind (ns name alias start end) row
                (let ((target (gethash (cons ns name) exports)))
                  (check (and target (not (eq (module-declaration-module target) module))
                              (not (member target seen)) (not (gethash alias names))
                              (not (member alias *predeclared* :test #'equal))
                              (eq target (module-import-target import))
                              (equal ns (module-import-namespace import))
                              (equal name (module-import-name import)) (equal alias (module-import-alias import))
                              (= start (span-start (module-import-span import)))
                              (= end (span-end (module-import-span import)))) "Invalid import proof")
                  (push target seen)
                  (when (eq (module-declaration-origin target) :user) (pushnew (module-declaration-module target) deps))
                  (setf (gethash alias names) target))))
            (check (and (= (length deps) (length (source-module-dependencies module)))
                        (subsetp deps (source-module-dependencies module))) "Invalid dependency proof")
            (check (= (hash-table-count names) (hash-table-count (source-module-names module))) "Invalid name table")
            (maphash (lambda (name decl) (check (eq decl (gethash name (source-module-names module))) "Invalid name target")) names)
            (syntax-walk (source-module-program module)
              (lambda (token)
                (let* ((name (raw-name token)) (decl (gethash name names))
                       (expected (cond ((member name *predeclared* :test #'equal) nil)
                                       (decl (module-declaration-key decl)) (t (module-key module name)))))
                  (check (equal expected (mognitio.syntax::token-resolved-name token)) "Invalid lexical name proof"))))
            (setf (gethash module edges) deps))))
      (loop while (< (length order) (length modules)) do
        (let ((ready (find-if (lambda (m) (and (not (member m order)) (subsetp (gethash m edges) order))) modules)))
          (check ready "Cyclic dependency proof") (setf order (append order (list ready)))))
      (check (equal order (project-order project)) "Invalid initialization order")
      (check (equal (mapcar #'source-module-program order) (mognitio.syntax::program-modules program)) "Missing checked module")
      (let* ((policy (mognitio.syntax::program-entry-policy program))
             (selected (mognitio.syntax::program-entry-declaration program))
             (normal-entry (find (format nil "src/~A.mgn" (project-name project)) modules :key #'source-module-path :test #'equal))
             (entry (if (eq policy :test) (and selected (module-declaration-module selected)) normal-entry))
             (main (if (eq policy :test) selected (and entry (gethash "main" (gethash entry environments)))))
             (root (program-root program)) (call (if (eq policy :test) (and (typep root 'sequence-node) (sequence-node-terminal root)) root))
             (reachable nil))
        (check (member policy '(:normal :test-check :test)) "Invalid entry policy")
        (check (eq normal-entry (project-entry project)) "Invalid manifest entry identity")
        (if (eq policy :test-check)
            (check (and (eq (project-entry-policy project) :test-check) (null selected)
                        (typep root 'void-literal) (zerop (length (program-statements program)))) "Invalid checking-only entry")
            (progn
              (check (and entry main (eq selected main) (eq (module-declaration-module main) entry)
                          (member main (source-module-declarations entry))
                          (eq (module-declaration-kind main) :let) (eq (program-source program) (source-module-source entry))
                          (typep call 'call-expression)
                          (if (eq policy :normal)
                              (and (= (length (call-expression-arguments call)) 1)
                                   (typep (aref (call-expression-arguments call) 0) 'mognitio.syntax::runtime-arguments))
                              (zerop (length (call-expression-arguments call))))
                          (typep (call-expression-callee call) 'variable-reference)
                          (eq (variable-reference-name (call-expression-callee call)) (module-declaration-token main))) "Invalid entry proof")
              (when (eq policy :test)
                (let ((attributes (declaration-attributes (module-declaration-node main))))
                  (check (and (= (length attributes) 1) (string= (raw-name (attribute-syntax-name (aref attributes 0))) "test")
                              (= (length (sequence-node-statements root)) 1)
                              (typep (aref (sequence-node-statements root) 0) 'mognitio.syntax::test-stage)) "Invalid test wrapper proof")))
              (labels ((visit (m) (unless (member m reachable) (push m reachable) (mapc #'visit (gethash m edges))))) (visit entry))))
        (check (equal (coerce (program-statements program) 'list)
                      (append (unless (eq policy :test-check) (standard-prelude project))
                        (loop for m in order when (member m reachable)
                            append (coerce (program-statements (source-module-program m)) 'list)))) "Invalid runtime initialization plan")
        (check (equal (coerce (program-declarations program) 'list)
                      (append (standard-declarations project) (loop for m in modules append (coerce (program-declarations (source-module-program m)) 'list))))
               "Invalid compile-time declaration plan")))
    t))
