(in-package #:mognitio.project)

(defun input-error (path message)
  (fail 'usage-or-io-failure nil message :path path))

(defun manifest-values (source)
  ;; Decode only values admitted by the schema, but accept every TOML spelling
  ;; of those values. Unsupported values are schema failures, never Lisp input.
  (let* ((text (source-text source)) (n (length text)) (at 0)
         (values (make-hash-table :test #'equal)) (spans (make-hash-table :test #'equal))
         (table nil) (table-seen nil) (dotted-project nil) (inline-project nil))
    (labels
        ((bad () (fail-at (make-span source (min at n) (min (1+ at) n))
                         :manifest "Invalid project manifest" 'usage-or-io-failure))
         (peek () (when (< at n) (char text at)))
         (take () (or (prog1 (peek) (incf at)) (bad)))
         (is (c) (eql (peek) c))
         (expect (c) (unless (eql (take) c) (bad)))
         (newline ()
           (when (is #\Return) (incf at) (unless (is #\Newline) (bad)))
           (expect #\Newline))
         (space () (loop while (member (peek) '(#\Space #\Tab)) do (incf at)))
         (comment ()
           (when (is #\#)
             (loop while (and (peek) (not (member (peek) '(#\Newline #\Return))))
                   for c = (take) do
                     (when (or (< (char-code c) 32) (= (char-code c) 127))
                       (unless (eql c #\Tab) (bad))))))
         (lines ()
           (loop (space) (comment)
                 (if (member (peek) '(#\Newline #\Return)) (newline) (return))))
         (string-value (&optional key)
           (let* ((quote (take)) (basic (eql quote #\")) (multi nil)
                  (out (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
             (unless (member quote '(#\" #\')) (bad))
             (when (and (not key) (< (1+ at) n)
                        (eql (char text at) quote) (eql (char text (1+ at)) quote))
               (incf at 2) (setf multi t)
               (when (member (peek) '(#\Newline #\Return)) (newline)))
             (labels ((emit (c) (vector-push-extend c out)))
               (loop
                 (let ((c (take)))
                   (cond
                     ((eql c quote)
                      (if (not multi) (return)
                          (let ((count 1))
                            (loop while (eql (peek) quote) do (incf at) (incf count))
                            (when (> count 5) (bad))
                            (dotimes (i (if (>= count 3) (- count 3) count)) (emit quote))
                            (when (>= count 3) (return)))))
                     ((and basic (eql c #\\))
                      (if (and multi (member (peek) '(#\Space #\Tab #\Newline #\Return)))
                          (progn (space)
                            (unless (member (peek) '(#\Newline #\Return)) (bad))
                            (newline)
                            (loop (space)
                                  (if (member (peek) '(#\Newline #\Return)) (newline) (return))))
                          (let ((escape (take)))
                            (case escape
                              (#\b (emit #\Backspace)) (#\t (emit #\Tab))
                              (#\n (emit #\Newline)) (#\f (emit #\Page)) (#\r (emit #\Return))
                              (#\" (emit #\")) (#\\ (emit #\\))
                              ((#\u #\U)
                               (let ((code 0))
                                 (dotimes (i (if (eql escape #\u) 4 8))
                                   (let ((digit (digit-char-p (take) 16)))
                                     (unless digit (bad)) (setf code (+ (* code 16) digit))))
                                 (unless (and (<= code #x10ffff) (not (<= #xd800 code #xdfff))) (bad))
                                 (emit (or (code-char code) (bad)))))
                              (t (bad))))))
                     ((member c '(#\Newline #\Return))
                      (unless multi (bad))
                      (when (eql c #\Return) (expect #\Newline))
                      (emit #\Newline))
                     ((or (< (char-code c) 32) (= (char-code c) 127))
                      (if (eql c #\Tab) (emit c) (bad)))
                     (t (emit c))))))
             out))
         (key-part ()
           (space)
           (if (member (peek) '(#\" #\')) (string-value t)
               (let ((start at))
                 (loop while (and (peek)
                                  (or (find (peek) "_-")
                                      (mognitio.frontend::ascii-letter-p (peek))
                                      (mognitio.frontend::ascii-digit-p (peek))))
                       do (incf at))
                 (when (= start at) (bad))
                 (subseq text start at))))
         (key-path ()
           (let ((parts (list (key-part))))
             (loop (space) (unless (is #\.) (return)) (incf at) (push (key-part) parts))
             (nreverse parts)))
         (binding-value (prefix inline)
           (let* ((start at) (parts (append prefix (key-path))))
             (space) (expect #\=) (space)
             (cond
               ((equal parts '("project"))
                (when (or table-seen dotted-project inline-project) (bad))
                (setf inline-project t)
                (expect #\{) (space)
                (unless (is #\})
                  (loop (binding-value '("project") t) (space)
                        (unless (is #\,) (return)) (incf at) (space)
                        (when (is #\}) (bad))))
                (expect #\}))
               ((and (= (length parts) 2) (equal (first parts) "project")
                     (member (second parts) '("name" "root_namespace") :test #'equal))
                (when (and inline-project (not inline)) (bad))
                (when (and (not prefix) (not inline)) (setf dotted-project t))
                (when (gethash (second parts) values) (bad))
                (setf (gethash (second parts) values) (string-value)
                      (gethash (second parts) spans) (make-span source start at)))
               (t (bad))))))
      (lines)
      (loop while (peek) do
        (if (is #\[)
            (progn
              (incf at)
              (unless (and (equal (key-path) '("project"))
                           (not table-seen) (not dotted-project) (not inline-project)) (bad))
              (space) (expect #\]) (setf table '("project") table-seen t))
            (binding-value table nil))
        (space) (comment)
        (when (peek) (newline)) (lines))
      (unless (and (gethash "name" values) (gethash "root_namespace" values)) (bad))
      (values (gethash "name" values) (gethash "root_namespace" values) (gethash "name" spans)))))

(defun identifier-p (name)
  (and (plusp (length name)) (mognitio.frontend::word-start-p (char name 0))
       (every (lambda (c) (or (mognitio.frontend::word-start-p c)
                             (mognitio.frontend::ascii-digit-p c))) name)
       (not (assoc name mognitio.frontend::*keywords* :test #'equal))))

(defun namespace-parts (name)
  (let ((parts (uiop:split-string name :separator '(#\\))))
    (unless (every #'identifier-p parts) (return-from namespace-parts nil))
    parts))
