(in-package #:mognitio.project)

(defun raw-name (token)
  (let ((span (token-span token)))
    (subseq (source-text (span-source span)) (span-start span) (span-end span))))

(defun module-key (module name) (format nil "~A#~A" (source-module-path module) name))
(defparameter *predeclared* '("Int" "Bool" "String" "Unit" "List" "Result" "IndexError" "SliceError" "Self" "Function"))

(defun module-header (module &key tokens syntax-only)
  (let* ((source (source-module-source module)) (tokens (or tokens (mognitio.frontend:lex-source source)))
         (p (mognitio.frontend::make-parser :source source :tokens tokens))
         (imports nil) (declarations nil) (body nil) (depth 0) (public nil))
    (labels ((take () (mognitio.frontend::p-take p))
             (expect (kind) (mognitio.frontend::p-expect p kind))
             (kind () (mognitio.frontend::p-kind p))
             (namespace-name (group)
               (let ((parts (list (raw-name (expect :identifier)))))
                 (loop while (eq (kind) :backslash) do
                   (take)
                   (when (and group (eq (kind) :left-brace)) (return))
                   (push (raw-name (expect :identifier)) parts))
                 (format nil "~{~A~^\\~}" (nreverse parts)))))
      (expect :namespace)
      (let* ((start (mognitio.frontend::p-peek p)) (ns (namespace-name nil))
             (end (mognitio.frontend::p-peek p)))
        (when (and (not syntax-only) (standard-namespace-p ns))
          (fail-at (token-span start) :semantic "Std namespace is reserved"))
        (unless (or syntax-only (equal ns (source-module-namespace module)))
          (fail-at (make-span source (span-start (token-span start)) (span-start (token-span end)))
                   :semantic "Namespace does not match source directory")))
      (expect :semicolon)
      (loop while (eq (kind) :use) do
        (take)
        (let ((ns (namespace-name t)))
          ;; The immediately preceding token must be the prefix/group separator.
          (unless (eq (token-kind (aref tokens (1- (mognitio.frontend::parser-cursor p)))) :backslash)
            (fail-at (token-span (mognitio.frontend::p-peek p)) :parse "Expected namespace separator"))
          (expect :left-brace)
          (loop
            (let* ((name (expect :identifier)) (alias name))
              (when (eq (kind) :as) (take) (setf alias (expect :identifier)))
              (push (make-module-import :namespace ns :name (raw-name name) :alias (raw-name alias)
                                        :span (make-span source (span-start (token-span name))
                                                         (span-end (token-span alias)))) imports))
            (unless (eq (kind) :comma) (return))
            (take) (when (eq (kind) :right-brace) (return)))
          (expect :right-brace) (expect :semicolon)))
      (let ((attributes #()) (prefix nil))
        (loop until (eq (kind) :eof) do
          (when (and (zerop depth) (member (kind) '(:at :public)))
            (let ((begin (mognitio.frontend::parser-cursor p)))
              (multiple-value-setq (attributes public prefix) (mognitio.frontend::p-declaration-prefix p t))
              (loop for i from begin below (mognitio.frontend::parser-cursor p) do (push (aref tokens i) body))))
          (let* ((token (take)) (k (token-kind token)))
            (when (and (zerop depth) (member k '(:type :alias :contract :template :witness :let :var)))
              (let ((name (mognitio.frontend::p-peek p)))
                (unless (eq (token-kind name) :identifier) (fail-at (token-span name) :parse "Expected declaration name"))
                (push (make-module-declaration :module module :name (raw-name name) :kind k :public public
                        :token name :key (module-key module (raw-name name)) :attributes attributes
                        :prefix-span (token-span (or prefix token))) declarations)
                (setf public nil attributes #() prefix nil)))
            (push token body)
            (when (member k '(:left-brace :left-paren :left-bracket)) (incf depth))
            (when (member k '(:right-brace :right-paren :right-bracket)) (decf depth)))))
      (push (expect :eof) body))
    (setf (source-module-tokens module) (coerce (nreverse body) 'vector)
          (source-module-imports module) (nreverse imports)
          (source-module-declarations module) (nreverse declarations)
          (source-module-names module) (make-hash-table :test #'equal))
    module))

(defun resolve-project (project)
  (setf (project-standard project) (make-io-catalog))
  (verify-standard-catalog project)
  (let ((public (standard-exports project)))
    (dolist (module (project-modules project))
      (module-header module)
      (dolist (decl (source-module-declarations module))
        (let* ((name (module-declaration-name decl))
               (key (cons (source-module-namespace module) name))
               (previous (gethash key public)))
          (when (or (gethash name (source-module-names module)) (member name *predeclared* :test #'equal))
            (fail-at (token-span (module-declaration-token decl)) :semantic "Duplicate or reserved name"))
          (setf (gethash name (source-module-names module)) decl)
          (when (module-declaration-public decl)
            (when previous
              (let ((diagnostic (span-diagnostic (token-span (module-declaration-token decl))
                                                  :semantic "Duplicate public name")))
                (setf (mognitio.diagnostics::diagnostic-related diagnostic)
                      (list (span-diagnostic (token-span (module-declaration-token previous))
                                             :semantic "Previous declaration")))
                (error 'source-failure :diagnostic diagnostic)))
            (setf (gethash key public) decl)))))
    (dolist (module (project-modules project))
      (let ((seen nil))
        (dolist (import (source-module-imports module))
          (let ((decl (gethash (cons (module-import-namespace import) (module-import-name import)) public))
                (alias (module-import-alias import)))
            (unless (and decl (not (eq module (module-declaration-module decl))))
              (fail-at (module-import-span import) :semantic "Import requires another file's public declaration"))
            (when (or (member decl seen) (gethash alias (source-module-names module))
                      (member alias *predeclared* :test #'equal))
              (fail-at (module-import-span import) :semantic "Duplicate import or conflicting name"))
            (push decl seen)
            (setf (module-import-target import) decl (gethash alias (source-module-names module)) decl)
            (when (eq (module-declaration-origin decl) :user)
              (pushnew (module-declaration-module decl) (source-module-dependencies module)))))))
    (let ((pending (copy-list (project-modules project))) (done nil))
      (loop while pending do
        (let ((ready (find-if (lambda (m) (subsetp (source-module-dependencies m) done)) pending)))
          (unless ready (fail-at (make-span (source-module-source (first pending)) 0 0) :semantic "Cyclic module imports"))
          (setf pending (remove ready pending)) (push ready done)))
      (setf (project-order project) (nreverse done)))
    (dolist (module (project-modules project)) (parse-module module))
    project))

(defun syntax-walk (node token-function &optional member-name)
  ;; Field/variant/method spellings are not lexical names.
  (cond
    ((null node))
    ((typep node 'token)
     (when (typep node 'type-syntax)
       (syntax-walk (type-syntax-name node) token-function)
       (syntax-walk (type-syntax-arguments node) token-function))
     (when (and (eq (token-kind node) :identifier) (not member-name) (not (typep node 'type-syntax)))
       (funcall token-function node)))
    ((and (vectorp node) (not (stringp node)))
     (map nil (lambda (child) (syntax-walk child token-function member-name)) node))
    ((and (typep node 'structure-object) (eq (symbol-package (type-of node)) (find-package :mognitio.syntax)))
     (dolist (slot (sb-mop:class-slots (class-of node)))
       (let* ((name (sb-mop:slot-definition-name slot)) (key (symbol-name name))
              (child (slot-value node name)))
         (unless (member key '("SPAN" "SOURCE" "PROJECT" "MODULES" "PAYLOAD" "ATTRIBUTES" "DECLARATION-SPAN" "KEYWORD-SPAN") :test #'equal)
           (if (and (typep node 'implementation-declaration) (equal key "METHODS"))
               (loop for method across child do
                 (syntax-walk (local-binding-initializer method) token-function))
               (syntax-walk child token-function
                 (or (and (equal key "NAME") (typep node '(or named-member method-call field-expression)))
                     (and (equal key "VARIANT") (typep node '(or enum-expression variant-pattern))))))))))))

(defun parse-module (module &key recovery)
  (let ((headers (mognitio.frontend::declaration-headers (source-module-tokens module))))
    (maphash (lambda (name decl)
               (setf (gethash name headers) (case (module-declaration-kind decl)
                                             ((:type :alias :contract :template) (module-declaration-kind decl))
                                             (t nil))))
             (source-module-names module))
    (let ((program (mognitio.frontend:parse-program (source-module-source module)
                                                   (source-module-tokens module) headers)))
      (when (program-root program) (fail-at (node-span (program-root program)) :parse "Module tail is forbidden"))
      (loop for node across (program-statements program) do
        (unless (or (typep node 'local-binding) (and recovery (typep node 'mognitio.syntax::analysis-error-node))) (fail-at (node-span node) :parse "Module requires declarations")))
      (dolist (node (append (coerce (program-declarations program) 'list) (coerce (program-statements program) 'list)))
        (unless (typep node 'mognitio.syntax::analysis-error-node)
        (let* ((token (if (typep node 'local-binding) (local-binding-name node)
                          (mognitio.semantic::declaration-name node)))
               (decl (gethash (raw-name token) (source-module-names module))))
          (when decl (setf (module-declaration-node decl) node)))))
      (syntax-walk program
        (lambda (token)
          (let* ((name (raw-name token)) (decl (gethash name (source-module-names module))))
            (unless (member name *predeclared* :test #'equal)
              (setf (mognitio.syntax::token-resolved-name token)
                    (if decl (module-declaration-key decl) (module-key module name)))))))
      (setf (source-module-program module) program))))

(defun reachable-modules (project &optional (root (project-entry project)))
  (let ((found nil))
    (labels ((visit (module)
               (unless (member module found)
                 (push module found) (mapc #'visit (source-module-dependencies module)))))
      (when root (visit root)))
    (remove-if-not (lambda (m) (member m found)) (project-order project))))

(defun project-program (project &optional selected)
  (let* ((policy (if selected :test (project-entry-policy project)))
         (entry (if selected (module-declaration-module selected) (project-entry project)))
         (decl (or selected (when (and entry (eq policy :normal)) (gethash "main" (source-module-names entry)))))
         (source (if entry (source-module-source entry) (project-manifest-source project)))
         (root nil))
    (when (eq policy :normal)
      (unless (and decl (eq (module-declaration-module decl) entry) (eq (module-declaration-kind decl) :let))
        (let ((import (find "main" (source-module-imports entry) :key #'module-import-alias :test #'equal)))
          (fail-at (cond (import (module-import-span import))
                         (decl (token-span (module-declaration-token decl)))
                         (t (make-span source (length (source-text source)) (length (source-text source)))))
                   :semantic "Entry requires its own let main"))))
    (if (member policy '(:test-check :analysis))
        (setf root (make-void-literal :span (make-span source 0 0)))
        (let* ((token (module-declaration-token decl)) (span (token-span token))
               (call (make-call-expression :callee (make-variable-reference :name token :span span) :arguments (if (eq policy :normal)
                              (vector (mognitio.syntax::make-runtime-arguments :span span)) #()) :span span)))
          (setf root (if (eq policy :test)
                         (make-sequence-node :statements (vector (mognitio.syntax::make-test-stage :span span))
                                             :terminal call :span span)
                         call))))
    (make-program :source source :root root :project project :entry-policy policy :entry-declaration decl
      :modules (mapcar #'source-module-program (project-order project))
      :declarations (coerce (append (standard-declarations project) (loop for m in (project-modules project)
                                 append (coerce (program-declarations (source-module-program m)) 'list))) 'vector)
      :statements (coerce (unless (member policy '(:test-check :analysis))
                            (append (standard-prelude project) (loop for m in (reachable-modules project entry)
                                  append (coerce (program-statements (source-module-program m)) 'list)))) 'vector))))
