(in-package #:mognitio.project)

(defun evidence-visible-p (checked node info)
  (let ((project (mognitio.syntax::program-project (mognitio.semantic:checked-program-program checked))))
    (or (null project)
        (let ((module (find (span-source (node-span node)) (project-modules project)
                            :key #'source-module-source)))
          (and module
               (loop for decl being the hash-values of (source-module-names module)
                     thereis (and (eq :witness (module-declaration-kind decl))
                                  (eq info (mognitio.semantic:member-info-implementation
                                            (mognitio.semantic:checked-member checked (module-declaration-node decl)))))))))))

(defun check-public-signatures (checked)
  (let* ((project (mognitio.syntax::program-project (mognitio.semantic:checked-program-program checked)))
         (context (mognitio.semantic:checked-program-values checked))
         (decls (make-hash-table :test #'equal)))
    (dolist (module (project-modules project))
      (dolist (decl (source-module-declarations module))
        (setf (gethash (module-declaration-key decl) decls) decl)))
    (labels ((expose (type origin seen)
               (unless (member type seen :test #'equal)
                 (let ((seen (cons type seen)))
                   (cond
                     ((mognitio.semantic::generic-template-p type)
                      (when (mognitio.semantic::generic-template-target type)
                        (expose (mognitio.semantic::generic-template-target type) origin seen))
                      (mapc (lambda (p) (expose (cdr p) origin seen)) (mognitio.semantic::generic-template-fields type))
                      (dolist (v (mognitio.semantic::generic-template-variants type))
                        (mapc (lambda (x) (expose x origin seen)) (mognitio.semantic::variant-info-types v))))
                     ((mognitio.semantic:function-type-p type)
                      (mapc (lambda (x) (expose x origin seen)) (append (second type) (list (third type)))))
                     ((mognitio.semantic:list-type-p type) (expose (second type) origin seen))
                     ((mognitio.semantic:nominal-type-p type)
                      (let* ((info (mognitio.semantic:context-type context type))
                             (decl (gethash (mognitio.semantic:type-info-name info) decls)))
                        (when (and decl (not (module-declaration-public decl)))
                          (fail-at (token-span (module-declaration-token origin)) :semantic "Public signature exposes a private type"))
                        (dolist (arg (mognitio.semantic::type-info-arguments info)) (expose arg origin seen))
                        (dolist (field (mognitio.semantic:type-info-fields info)) (expose (cdr field) origin seen))
                        (dolist (variant (mognitio.semantic:type-info-variants info))
                          (dolist (part (mognitio.semantic::variant-info-types variant)) (expose part origin seen)))
                        (dolist (method (mognitio.semantic:type-info-methods info))
                          (mapc (lambda (x) (expose x origin seen))
                                (append (mognitio.semantic::requirement-parameters method)
                                        (list (mognitio.semantic::requirement-result method))))))))))))
      (maphash
       (lambda (key decl)
         (when (module-declaration-public decl)
           (let ((node (module-declaration-node decl)))
             (case (module-declaration-kind decl)
               ((:type :alias :contract)
                (expose (gethash key (mognitio.semantic::value-context-names context)) decl nil))
               (:let (expose (mognitio.semantic:local-symbol-type (mognitio.semantic:checked-symbol checked node)) decl nil))
               (:template
                (expose (mognitio.semantic:signature-type
                         (mognitio.semantic:checked-function checked (template-declaration-function node))) decl nil))
               (:witness
                (let ((info (mognitio.semantic:member-info-implementation (mognitio.semantic:checked-member checked node))))
                  (expose (mognitio.semantic:implementation-info-concrete info) decl nil)
                  (expose (mognitio.semantic:implementation-info-contract info) decl nil)))))))
       decls))))

(defun check-project-bodies (checked) (mognitio.semantic::c-project-bodies checked))
(defun verify-project-bodies (checked) (mognitio.semantic::v-project-bodies checked))

(in-package #:mognitio.semantic)

(defun c-project-bodies (checked)
  (let* ((program (checked-program-program checked))
         (decl (mognitio.syntax::program-entry-declaration program)))
    (when (eq (mognitio.syntax::program-entry-policy program) :normal)
      (let* ((binding (mognitio.project::module-declaration-node decl))
             (type (resolve-type-token (c-context) (local-binding-annotation binding))))
        (unless (equal type '(:function nil :void))
          (fail-at (form-span (local-binding-annotation binding)) :type "main must have type Function(): Unit"))))
    (dolist (module (mognitio.syntax::program-modules program))
      (c-sequence module (program-statements module) nil))
    (let* ((tail (c-expression (program-root program)))
           (children (append (map 'list (lambda (n) (checked-completion checked n)) (program-statements program))
                             (list tail))))
      (c-summary program :void (every #'c-normal children) children))
    (mognitio.project::check-public-signatures checked)))

(defun v-project-bodies (checked)
  (mognitio.project::verify-project-structure (checked-program-program checked))
  (let* ((program (checked-program-program checked))
         (project (mognitio.syntax::program-project program))
         (modules (mognitio.project::project-order project))
         (seen nil))
    ;; Reconstruct dependency ordering instead of trusting the stored plan.
    (dolist (module modules)
      (let ((ready (sort
                    (remove-if (lambda (candidate)
                                 (or (member candidate seen)
                                     (not (subsetp (mognitio.project::source-module-dependencies candidate) seen))))
                               (copy-list (mognitio.project::project-modules project)))
                    #'string< :key #'mognitio.project::source-module-path)))
        (v-check (eq module (first ready)) "Invalid project initialization order"))
      (push module seen))
    (v-check (= (length seen) (length (mognitio.project::project-modules project))) "Missing checked module")
    (dolist (module (mognitio.syntax::program-modules program))
      (v-sequence module (program-statements module) nil))
    (v-visit (program-root program))
    (let ((children (append (coerce (program-statements program) 'list) (list (program-root program)))))
      (v-finish program :void (every #'v-normal children) children))
    (maphash (lambda (node info)
               (v-check (mognitio.project::evidence-visible-p checked node info) "Invisible packaging evidence"))
             (value-context-packs (checked-program-values checked)))
    (mognitio.project::check-public-signatures checked)))
