(in-package #:mognitio.io)

(sb-alien:define-alien-routine ("syscall" publication-syscall) sb-alien:long
  (number sb-alien:long) (a sb-alien:long) (b sb-alien:long) (c sb-alien:long)
  (d sb-alien:long) (e sb-alien:long) (f sb-alien:long))
(defvar *publication-fault-hook* nil)
(defvar *publication-observer* nil)
(defstruct publication-owner parent file probe name device inode
  (phase 0) (state 0) primary (profile nil) (issued nil)
  (scratch (make-array 144 :element-type '(unsigned-byte 8) :initial-element 0)))
(define-condition binary-io-failure (error)
  ((kind :initarg :kind :reader binary-failure-kind)
   (phase :initarg :phase :reader binary-failure-phase)
   (state :initarg :state :reader binary-failure-state)
   (errno :initarg :errno :initform nil :reader binary-failure-errno)))
(defun publication-internal () (mognitio.diagnostics:internal-error "Invalid binary publication state"))
(defun publication-kind (errno)
  (cond ((= errno 17) 1) ((= errno 2) 2) ((member errno '(1 13 30)) 3)
        ((member errno '(20 38 95)) 4) ((member errno '(12 23 24 28 122)) 5) (t 6)))
(defun publication-fail (owner kind &optional errno)
  (error 'binary-io-failure :kind kind :phase (publication-owner-phase owner)
         :state (publication-owner-state owner) :errno errno))
(defun publication-call (phase number a &optional (b 0) (c 0) (d 0) (e 0) (f 0))
  (loop
    (let* ((close-p (member phase '(:close-file :close-parent :close-probe)))
           (injected (and (not close-p) *publication-fault-hook* (funcall *publication-fault-hook* phase)))
           (status (or injected
                     (let ((n (publication-syscall number a b c d e f)))
                       (if (= n -1) (- (sb-sys:sap-ref-32 (directory-errno) 0)) n)))))
      ;; Synthetic close faults follow the real release.
      (when (and close-p *publication-fault-hook*)
        (setf status (or (funcall *publication-fault-hook* phase) status)))
      (when (and *publication-observer* (not (member phase '(:open-parent :open-temp :open-probe))))
        (funcall *publication-observer* phase status))
      (when (or (not (integerp status)) (< status -4095) (member status '(-9 -14)))
        (publication-internal))
      (unless (and (= status -4) (not close-p) (not (eq phase :commit)))
        (return status)))))
(defun publication-status (owner status)
  (when (minusp status) (publication-fail owner (publication-kind (- status)) (- status)))
  status)
(defun publication-octets (string)
  (sb-ext:string-to-octets string :external-format :utf-8 :null-terminate t))
(defun publication-address (bytes) (sb-sys:sap-int (sb-sys:vector-sap bytes)))
(defun publication-word (bytes offset size)
  (loop for i below size sum (ash (aref bytes (+ offset i)) (* i 8))))
(defun publication-close (owner slot phase)
  (sb-sys:without-interrupts
    (let ((fd (ecase slot (:file (publication-owner-file owner))
                       (:parent (publication-owner-parent owner)) (:probe (publication-owner-probe owner)))))
    (when fd
      (ecase slot (:file (setf (publication-owner-file owner) nil))
                  (:parent (setf (publication-owner-parent owner) nil))
                  (:probe (setf (publication-owner-probe owner) nil)))
      (publication-status owner (publication-call phase 3 fd))))))
(defun publication-stat (owner fd name flags phase)
  (let ((data (publication-owner-scratch owner)))
    (sb-sys:with-pinned-objects (name data)
      (let ((status (publication-call phase 262 fd (publication-address name) (publication-address data) flags)))
        (values status data)))))
(defun publication-kernel-p ()
  (let ((data (make-array 390 :element-type '(unsigned-byte 8) :initial-element 0)))
    (sb-sys:with-pinned-objects (data)
      (let ((status (publication-call :kernel 63 (publication-address data))))
        (when (minusp status) (return-from publication-kernel-p status))))
    (flet ((field (offset)
             (sb-ext:octets-to-string data :start offset :end (position 0 data :start offset :end (+ offset 65))
                                      :external-format :latin-1)))
      (and (equal (field 0) "Linux") (equal (field 130) "7.0.0-38-generic")
           (equal (field 195) "#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  4 09:10:14 UTC 2026")
           (equal (field 260) "x86_64")))))
(defun publication-profile (owner)
  (let ((fs (make-array 120 :element-type '(unsigned-byte 8) :initial-element 0))
        (stat (make-array 256 :element-type '(unsigned-byte 8) :initial-element 0))
        (empty (publication-octets "")) (path (publication-octets "/proc/self/mountinfo")))
    (sb-sys:with-pinned-objects (fs stat empty path)
      (publication-status owner (publication-call :filesystem 138 (publication-owner-parent owner) (publication-address fs)))
      (publication-status owner (publication-call :mount-id 332 (publication-owner-parent owner)
                                  (publication-address empty) #x1000 #x1000 (publication-address stat)))
      (unless (and (= (publication-word fs 0 8) #x01021994)
                   (logbitp 12 (publication-word stat 0 4)))
        (publication-fail owner 4))
      (let ((kernel (publication-kernel-p)))
        (when (integerp kernel) (publication-status owner kernel))
        (unless (eq kernel t) (publication-fail owner 4)))
      (sb-sys:without-interrupts
        (setf (publication-owner-probe owner)
              (publication-status owner (publication-call :open-probe 257 -100 (publication-address path) #x80000)))))
    (let* ((data (make-array 4096 :element-type '(unsigned-byte 8)))
           (line (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
           (id (publication-word stat 144 8)) (matches 0))
      (labels ((finish-line ()
                 (let* ((text (sb-ext:octets-to-string line :external-format :latin-1))
                        (fields (uiop:split-string text :separator '(#\Space)))
                        (number (ignore-errors (parse-integer (first fields)))))
                   (when (eql number id)
                     (incf matches)
                     (let ((separator (position "-" fields :test #'equal)))
                       (unless (and separator (equal (nth (1+ separator) fields) "tmpfs"))
                         (publication-fail owner 4)))))
                 (setf (fill-pointer line) 0)))
        (loop for count = (sb-sys:with-pinned-objects (data)
                            (publication-status owner (publication-call :read-probe 0 (publication-owner-probe owner)
                                                        (publication-address data) (length data))))
              until (zerop count) do
          (when (> count (length data)) (publication-internal))
          (dotimes (i count)
            (if (= (aref data i) 10) (finish-line) (vector-push-extend (aref data i) line))))
        (unless (and (zerop (length line)) (= matches 1)) (publication-fail owner 4))))
    (setf (publication-owner-phase owner) 4)
    (publication-close owner :probe :close-probe)
    (setf (publication-owner-phase owner) 1 (publication-owner-profile owner) :ubuntu-7.0.0-38-tmpfs)))

(defun publication-classify-commit (owner status)
  (setf (publication-owner-issued owner) t)
  (cond ((zerop status) (setf (publication-owner-state owner) 1 (publication-owner-name owner) nil))
        ((plusp status) (publication-internal))
        (t
         (setf (publication-owner-state owner)
               (if (or (= status -38)
                       (and (eq (publication-owner-profile owner) :ubuntu-7.0.0-38-tmpfs)
                            (member (- status) '(1 2 4 11 12 13 16 17 18 20 22 28 30 36 39 40 95 116 122))))
                   0 2))
         (publication-fail owner
           (if (member (- status) '(18 22)) 4 (if (= status -39) 1 (publication-kind (- status))))
           (- status)))))

(defun publication-cleanup (owner)
  (setf (publication-owner-phase owner) 4)
  (labels ((attempt (thunk)
             (handler-case (funcall thunk)
               ((or error storage-condition) (condition)
                 (unless (publication-owner-primary owner)
                   (setf (publication-owner-primary owner) condition))))))
    (when (and (publication-owner-name owner) (publication-owner-file owner)
               (null (publication-owner-inode owner)))
      (attempt (lambda ()
        (let ((stat (publication-owner-scratch owner)))
          (sb-sys:with-pinned-objects (stat)
            (publication-status owner (publication-call :cleanup-identity 5 (publication-owner-file owner) (publication-address stat))))
          (setf (publication-owner-device owner) (publication-word stat 0 8)
                (publication-owner-inode owner) (publication-word stat 8 8))))))
    (attempt (lambda () (publication-close owner :file :close-file)))
    (attempt (lambda () (publication-close owner :probe :close-probe)))
    (when (publication-owner-name owner)
      (attempt
        (lambda ()
          (let ((name (publication-owner-name owner)))
            (multiple-value-bind (status data)
                (publication-stat owner (publication-owner-parent owner) name #x100 :cleanup-stat)
              (cond ((= status -2) (setf (publication-owner-name owner) nil))
                    ((minusp status) (publication-status owner status))
                    ((and (publication-owner-inode owner)
                          (= (publication-word data 0 8) (publication-owner-device owner))
                          (= (publication-word data 8 8) (publication-owner-inode owner)))
                     (sb-sys:with-pinned-objects (name)
                       (publication-status owner (publication-call :unlink 263 (publication-owner-parent owner)
                                                   (publication-address name) 0)))
                     (setf (publication-owner-name owner) nil))
                    (t (publication-fail owner 6))))))))
    (attempt (lambda () (publication-close owner :parent :close-parent)))))

(defun publish-file-value (path bytes mode)
  (let* ((input (mognitio.text:text-value-octets path)) (owner (make-publication-owner)))
    (when (or (zerop (length input)) (find 0 input) (= (aref input (1- (length input))) 47))
      (publication-fail owner 0))
    (setf (publication-owner-phase owner) 1)
    (let* ((separator (position 47 input :from-end t))
           (parent (if separator
                       (concatenate '(vector (unsigned-byte 8)) (subseq input 0 (max 1 separator)) #(0))
                       (publication-octets ".")))
           (name (concatenate '(vector (unsigned-byte 8)) (subseq input (if separator (1+ separator) 0)) #(0)))
           (data (mognitio.value::bytes-value-data bytes)))
      (unwind-protect
           (handler-case
               (progn
                 (sb-sys:with-pinned-objects (parent)
                   (sb-sys:without-interrupts
                     (setf (publication-owner-parent owner)
                           (publication-status owner (publication-call :open-parent 257 -100
                                                       (publication-address parent) #x290000)))))
                 (multiple-value-bind (status stat) (publication-stat owner (publication-owner-parent owner) name #x100 :target-stat)
                   (declare (ignore stat))
                   (cond ((zerop status) (publication-fail owner 1))
                         ((/= status -2) (publication-status owner status))))
                 (publication-profile owner)
                 (let ((random (make-array 16 :element-type '(unsigned-byte 8))))
                   (sb-sys:with-pinned-objects (random)
                     (loop with offset = 0 while (< offset 16)
                           for count = (publication-status owner
                                         (publication-call :random 318 (+ (publication-address random) offset) (- 16 offset))) do
                       (unless (<= 1 count (- 16 offset)) (publication-fail owner 6))
                       (incf offset count)))
                   (loop for serial from 0
                         for temp = (publication-octets (format nil ".mgn-~{~2,'0X~}~8,'0X" (coerce random 'list) serial)) do
                     (unless (equalp temp name)
                       (sb-sys:with-pinned-objects (temp)
                         (let ((status (sb-sys:without-interrupts
                                         (let ((fd (publication-call :open-temp 257 (publication-owner-parent owner)
                                                     (publication-address temp) #x800c1
                                                     (if (= (mognitio.value:tag mode) 0) #o666 #o777))))
                                           (when (>= fd 0)
                                             (setf (publication-owner-file owner) fd (publication-owner-name owner) temp))
                                           fd))))
                           (when (>= status 0) (return))
                           (unless (= status -17) (publication-status owner status)))))))
                 (let ((stat (make-array 144 :element-type '(unsigned-byte 8) :initial-element 0)))
                   (sb-sys:with-pinned-objects (stat)
                     (publication-status owner (publication-call :temp-stat 5 (publication-owner-file owner) (publication-address stat)))
                     (setf (publication-owner-device owner) (publication-word stat 0 8)
                           (publication-owner-inode owner) (publication-word stat 8 8))
                     (setf (publication-owner-phase owner) 2)
                     (let ((actual (publication-word stat 24 4)))
                       (unless (= (logand actual #o170000) #o100000) (publication-internal))
                       (when (plusp (logand actual #o7000))
                         (publication-status owner (publication-call :mode 91 (publication-owner-file owner) (logand actual #o777)))
                         (sb-sys:with-pinned-objects (stat)
                           (publication-status owner (publication-call :mode-stat 5 (publication-owner-file owner) (publication-address stat))))
                         (unless (zerop (logand (publication-word stat 24 4) #o7000)) (publication-internal))))))
                 (sb-sys:with-pinned-objects (data)
                   (loop with offset = 0 while (< offset (length data))
                         for remaining = (min #x7ffff000 (- (length data) offset))
                         for count = (publication-status owner
                                       (publication-call :write 1 (publication-owner-file owner)
                                                         (+ (publication-address data) offset) remaining)) do
                     (unless (<= 1 count remaining) (publication-fail owner 6))
                     (incf offset count)))
                 (setf (publication-owner-phase owner) 4)
                 (publication-close owner :file :close-file)
                 (setf (publication-owner-phase owner) 3)
                 (let ((temp (publication-owner-name owner)))
                   (sb-sys:with-pinned-objects (temp name)
                     (sb-sys:without-interrupts
                       (publication-classify-commit owner
                         (publication-call :commit 316 (publication-owner-parent owner) (publication-address temp)
                                           (publication-owner-parent owner) (publication-address name) 1))))))
             ((or error storage-condition) (condition) (setf (publication-owner-primary owner) condition)))
        (sb-sys:without-interrupts (publication-cleanup owner)))
      (when (publication-owner-primary owner) (error (publication-owner-primary owner))))
    mognitio.backend.cl::*void-value*))

(defun invoke-publication (path bytes mode result error-type field-types)
  (handler-case
      (mognitio.value:construct result 0 (publish-file-value path bytes mode))
    (binary-io-failure (condition)
      (mognitio.value:construct result 1
        (mognitio.value:construct error-type 0
          (mognitio.value:construct (first field-types) (binary-failure-kind condition))
          path
          (mognitio.value:construct (third field-types) (binary-failure-phase condition))
          (mognitio.value:construct (fourth field-types) (binary-failure-state condition)))))))
