(in-package #:mognitio.semantic)

(defun c-implementations (program)
  (let ((context (c-context)))
    (loop for node across (program-declarations program)
          when (typep node 'implementation-declaration) do
      (let* ((concrete (resolve-type-token context (implementation-declaration-target node)))
             (contract (resolve-type-token context (implementation-declaration-contract node)))
             (seen nil) (methods nil))
        (unless (and (valid-value-type-p concrete) (not (symbolic-type-p concrete))
                     (nominal-type-p contract :interface))
          (fail-at (node-span node) :semantic "Implementation requires complete types and a contract"))
        (when (find-implementation context concrete contract)
          (fail-at (node-span node) :semantic "Duplicate implementation"))
        (let ((requirements (type-info-methods (context-type context contract))))
          (loop for method across (implementation-declaration-methods node)
                for name = (token-text (local-binding-name method))
                for fn = (local-binding-initializer method) do
            (when (member name seen :test #'string=) (fail-at (node-span method) :semantic "Duplicate method"))
            (push name seen)
            (let ((params (function-expression-parameters fn)))
              (unless (plusp (length params)) (fail-at (node-span fn) :semantic "Missing receiver"))
              (let* ((syntax (parameter-type (aref params 0)))
                     (receiver (if (and (typep syntax 'token) (not (typep syntax 'type-syntax))
                                        (string= (token-text syntax) "Self"))
                                   concrete (resolve-type-token context syntax))))
                (unless (equal concrete receiver) (fail-at (form-span syntax) :type "Receiver type mismatch"))))
            (let* ((sig (c-signature fn nil concrete))
                   (required (find name requirements :key #'requirement-name :test #'string=)))
              (unless (and required (equal (signature-parameter-types sig) (requirement-parameters required))
                           (equal (signature-result-type sig) (requirement-result required)))
                (fail-at (node-span method) :type "Method does not match contract"))
              (setf (signature-method sig) (list concrete contract name))
              (push (cons name sig) methods)))
          (unless (= (length requirements) (length methods))
            (fail-at (node-span node) :semantic "Missing method")))
        (let ((info (make-implementation-info :id (length (value-context-implementations context))
                                            :concrete concrete :contract contract :methods (nreverse methods))))
          (vector-push-extend info (value-context-implementations context))
          (setf (gethash node (value-context-members context)) (make-member-info :kind :implementation :implementation info)))))
    (loop for info across (value-context-implementations context) do
      (dolist (method (implementation-info-methods info))
        (let ((*scopes* nil) (*template-owner* nil))
          (c-function-body (signature-declaration (cdr method)) (cdr method) (implementation-info-concrete info))
          (c-summary (signature-declaration (cdr method)) (signature-type (cdr method)) t nil))))))
(defun c-variant (type token)
  (unless (nominal-type-p type :enum) (fail-at (token-span token) :semantic "Expected sum type"))
  (or (find (token-text token) (type-info-variants (context-type (c-context) type)) :key #'variant-info-name :test #'string=)
      (fail-at (token-span token) :semantic "Unknown variant")))
(defun c-member (node info)
  (setf (gethash node (value-context-members (c-context))) info))
(defun c-product (node)
  (let* ((type (resolve-type-token (c-context) (struct-expression-name node)))
         (fields (when (nominal-type-p type :struct) (type-info-fields (context-type (c-context) type))))
         (indices nil) (children nil))
    (unless (nominal-type-p type :struct) (fail-at (node-span node) :semantic "Expected product type"))
    (loop for field across (struct-expression-fields node)
          for index = (position (token-text (named-member-name field)) fields :key #'car :test #'string=) do
      (unless (and index (not (member index indices))) (fail-at (node-span field) :semantic "Unknown or duplicate field"))
      (let ((child (c-expression (named-member-value field))))
        (c-context-check (named-member-value field) child (cdr (nth index fields)))
        (push child children) (push index indices)))
    (unless (= (length indices) (length fields)) (fail-at (node-span node) :semantic "Missing field"))
    (c-member node (make-member-info :kind :struct :type type :index (nreverse indices)))
    (c-summary node type (every #'c-normal children) (nreverse children))))
(defun c-enum (node)
  (let* ((type (resolve-type-token (c-context) (enum-expression-name node)))
         (variant (c-variant type (enum-expression-variant node)))
         (children (map 'list #'c-expression (enum-expression-arguments node))))
    (unless (and (= (length children) (length (variant-info-types variant)))
                 (eq (not (null (variant-info-types variant))) (not (null (enum-expression-parenthesized-p node)))))
      (fail-at (node-span node) :semantic "Wrong variant payload"))
    (loop for child in children for arg across (enum-expression-arguments node)
          for expected in (variant-info-types variant) do (c-context-check arg child expected))
    (c-member node (make-member-info :kind :enum :type type :variant (variant-info-id variant)))
    (c-summary node type (every #'c-normal children) children)))
(defun c-list (node)
  (let* ((type (resolve-type-token (c-context) (list-expression-type node)))
         (children (map 'list #'c-expression (list-expression-elements node))))
    (unless (list-type-p type) (fail-at (node-span node) :semantic "List literal requires a List type"))
    (loop for child in children for arg across (list-expression-elements node) do (c-context-check arg child (second type)))
    (c-operation node :list.make (coerce (list-expression-elements node) 'list)
                 (make-list (length children) :initial-element (second type)) type)
    (c-summary node type (every #'c-normal children) children)))
(defun c-field (node)
  (let* ((child (c-expression (field-expression-receiver node))) (type (c-structure child))
         (fields (when (nominal-type-p type :struct) (type-info-fields (context-type (c-context) type))))
         (index (position (token-text (field-expression-name node)) fields :key #'car :test #'string=)))
    (unless index (fail-at (node-span node) :semantic "Unknown product field"))
    (c-member node (make-member-info :kind :field :type type :index index))
    (c-summary node (cdr (nth index fields)) (c-normal child) (list child))))
(defun c-package-type (node)
  (when (typep node 'variable-reference)
    (let* ((syntax (variable-reference-name node))
           (binding (gethash (token-text syntax) (value-context-names (c-context)))))
      (when binding
        (let ((type (resolve-type-token (c-context) syntax)))
          (when (nominal-type-p type :interface) type))))))
(defun c-package (node type)
  (unless (= (length (call-expression-arguments node)) 1) (fail-at (node-span node) :semantic "Package requires one value"))
  (let* ((operand (aref (call-expression-arguments node) 0)) (child (c-expression operand))
         (implementation (find-implementation (c-context) (c-structure child) type)))
    (unless (and implementation (mognitio.project::evidence-visible-p *checked* node implementation))
      (fail-at (node-span node) :semantic "No visible packaging evidence"))
    (setf (gethash node (value-context-packs (c-context))) implementation)
    (c-summary node type (c-normal child) (list child))))
(defun c-result-type (value error)
  (instantiate-generic-type (c-context) (gethash :result (value-context-templates (c-context))) (list value error)))
(defun c-method (node)
  (let* ((receiver (method-call-receiver node)) (head (c-expression receiver)) (type (c-structure head))
         (args (coerce (method-call-arguments node) 'list)) (children (mapcar #'c-expression args))
         (name (token-text (method-call-name node))) (parameters nil) (result nil) (op nil))
    (cond
      ((nominal-type-p type :struct)
       (let* ((fields (type-info-fields (context-type (c-context) type)))
              (index (position name fields :key #'car :test #'string=))
              (function (when index (cdr (nth index fields)))))
         (unless (function-type-p function) (fail-at (node-span node) :type "Selected field is not a Function"))
         (setf parameters (second function) result (third function))
         (c-member node (make-member-info :kind :field-call :type type :index index))
         (setf (gethash node (checked-program-calls *checked*))
               (make-call-info :type function :owner *owner*))))
      ((or (list-type-p type) (eq type :string))
       (cond
         ((string= name "length") (setf result :int op (if (list-type-p type) :list.length :text.length)))
         ((and (list-type-p type) (string= name "append"))
          (setf result type parameters (list (second type)) op :list.append))
         ((and (list-type-p type) (string= name "at"))
          (setf result (c-result-type (second type) (gethash "IndexError" (value-context-names (c-context))))
                parameters '(:int) op :list.at))
         ((and (eq type :string) (string= name "slice"))
          (setf result (c-result-type :string (gethash "SliceError" (value-context-names (c-context))))
                parameters '(:int :int) op :text.slice.result))
         (t (fail-at (node-span node) :semantic "Unknown builtin method")))
       (c-operation node op (cons receiver args) (cons type parameters) result))
      ((nominal-type-p type :interface)
       (let* ((methods (type-info-methods (context-type (c-context) type)))
              (index (position name methods :key #'requirement-name :test #'string=)))
         (unless index (fail-at (node-span node) :semantic "Unknown contract method"))
         (setf parameters (requirement-parameters (nth index methods)) result (requirement-result (nth index methods)))
         (c-member node (make-member-info :kind :interface-call :type type :contract type :index index))
         (setf (gethash node (checked-program-calls *checked*))
               (make-call-info :type (list :function parameters result) :owner *owner*
                  :targets (loop for info across (value-context-implementations (c-context))
                                 when (equal type (implementation-info-contract info))
                                 collect (signature-id (cdr (assoc name (implementation-info-methods info) :test #'string=))))))))
      (t (fail-at (node-span node) :semantic "Receiver has no method structure")))
    (unless (= (length args) (length parameters)) (fail-at (node-span node) :semantic "Wrong method arity"))
    (loop for arg in args for child in children for expected in parameters do (c-context-check arg child expected))
    (c-summary node result (every #'c-normal (cons head children)) (cons head children))))
