(in-package #:mognitio.semantic)

(defun c-literal (node &optional negative)
  (multiple-value-bind (value valid)
      (mognitio.integer:decimal-magnitude (token-text (integer-literal-token node)) negative)
    (unless valid (fail-at (node-span node) :type "Integer literal out of range")) value))
(defun c-primitive-rule (node op children unary)
  (let* ((candidates (cond
                       (unary (if (eq op :not) '(:bool) '(:int)))
                       ((member op '(:and :or)) '(:bool))
                       ((eq op :add) '(:int :string))
                       ((member op '(:eq :ne)) '(:int :bool :string :void))
                       (t '(:int))))
         (matches (remove-if-not
                    (lambda (type) (every (lambda (child) (or (null (c-structure child))
                                                             (equal type (c-structure child)))) children))
                    candidates)))
    (unless (= (length matches) 1) (fail-at (node-span node) :type "Operator rule is not uniquely determined"))
    (let* ((operand (first matches))
           (result (if (or (member op '(:eq :ne :lt :le :gt :ge :and :or :not))) :bool operand))
           (kind (if (eq operand :string)
                     (ecase op (:add :text.concat) (:eq :text.equal) (:ne :text.not-equal)) op)))
      (values operand result kind))))
(defun c-unary (node)
  (let* ((op (token-kind (unary-expression-operator node))) (child (unary-expression-operand node))
         (literal child) (groups nil))
    (when (eq op :sub)
      (loop while (typep literal 'grouping) do (push literal groups) (setf literal (grouping-expression literal)))
      (when (and (typep literal 'integer-literal) (= (c-literal literal t) (- mognitio.integer:+minimum+)))
        (setf (gethash node (checked-program-literals *checked*)) mognitio.integer:+minimum+)
        (dolist (consumed (cons literal groups))
          (setf (gethash consumed (checked-program-consumed *checked*)) t)
          (c-summary consumed :int nil nil))
        (return-from c-unary (c-summary node :int t nil))))
    (let ((summary (c-expression child)))
      (multiple-value-bind (operand result kind) (c-primitive-rule node op (list summary) t)
        (c-context-check child summary operand)
        (c-operation node kind (list child) (list operand) result)
        (c-summary node result (c-normal summary) (list summary))))))
(defun c-binary (node)
  (let* ((a-node (binary-expression-left node)) (b-node (binary-expression-right node))
         (a (c-expression a-node)) (b (c-expression b-node)) (op (token-kind (binary-expression-operator node))))
    (multiple-value-bind (operand result kind) (c-primitive-rule node op (list a b) nil)
      (c-context-check a-node a operand) (c-context-check b-node b operand)
      (c-operation node kind (list a-node b-node) (list operand operand) result)
      (c-summary node result (and (c-normal a) (or (member op '(:and :or)) (c-normal b))) (list a b)))))
(defun c-call (node)
  (let ((package (c-package-type (call-expression-callee node))))
    (when package (return-from c-call (c-package node package))))
  (let* ((callee (c-expression (call-expression-callee node))) (type (c-structure callee))
         (args (call-expression-arguments node)) (children (map 'list #'c-expression args)))
    (unless (function-type-p type) (fail-at (node-span node) :type "Callee requires Function structure"))
    (unless (= (length children) (length (second type))) (fail-at (node-span node) :semantic "Wrong call arity"))
    (loop for node across args for child in children for expected in (second type) do (c-context-check node child expected))
    (setf (gethash node (checked-program-calls *checked*)) (make-call-info :type type :owner *owner*))
    (c-summary node (third type) (every #'c-normal (cons callee children)) (cons callee children))))
(defun c-binding (node)
  (let* ((type (resolve-type-token (c-context) (local-binding-annotation node)))
         (symbol (c-declare node (local-binding-name node) (local-binding-mutability node) type t))
         (child (c-expression (local-binding-initializer node))))
    (c-context-check (local-binding-initializer node) child type)
    (setf (cdr (c-lookup (local-symbol-name symbol))) :visible)
    (c-summary node :void (c-normal child) (list child))))
(defun c-expression (node)
  (typecase node
    (boolean-literal (c-summary node :bool t nil))
    (void-literal (c-summary node :void t nil))
    (integer-literal
     (setf (gethash node (checked-program-literals *checked*)) (c-literal node))
     (c-summary node :int t nil))
    (string-literal (c-summary node :string t nil))
    (variable-reference (c-summary node (local-symbol-type (c-reference node (variable-reference-name node))) t nil))
    (function-expression (c-function node))
    (specialization-reference (c-specialization node))
    (list-expression (c-list node))
    (struct-expression (c-product node))
    (enum-expression (c-enum node))
    (field-expression (c-field node))
    (method-call (c-method node))
    (call-expression (c-call node))
    (branch-expression (c-branch node))
    (loop-expression (c-loop node))
    ((or break-statement continue-statement) (c-control node))
    (return-statement (c-return node))
    (try-expression (c-try node))
    (panic-expression (c-panic node))
    (unary-expression (c-unary node))
    (binary-expression (c-binary node))
    (grouping
     (let ((child (c-expression (grouping-expression node))))
       (c-summary node (c-structure child) (c-normal child) (list child))))
    (sequence-node
     (let ((*scopes* (cons (make-hash-table :test #'equal) *scopes*)))
       (c-sequence node (sequence-node-statements node) (sequence-node-terminal node))))
    (local-binding (c-binding node))
    (assignment
     (let* ((symbol (c-reference node (assignment-name node))) (child (c-expression (assignment-rhs node))))
       (unless (and (eq (local-symbol-mutability symbol) :var) (= *owner* (local-symbol-owner symbol)))
         (fail-at (node-span node) :semantic "Cannot assign immutable or captured binding"))
       (c-context-check (assignment-rhs node) child (local-symbol-type symbol))
       (c-summary node :void (c-normal child) (list child))))
    (expression-statement
     (let* ((child (c-expression (expression-statement-expression node))) (normal (completion-normal-type child)))
       (if (expression-statement-discard-p node)
           (unless (and normal (not (eq normal :void)) (not (rigid-type-p normal)))
             (fail-at (node-span node) :type "Discard requires a definitely non-Unit normal result"))
           (when (and normal (not (eq normal :void)))
             (fail-at (node-span node) :type "Expression statement requires Unit or non-completion")))
       (c-summary node :void (c-normal child) (list child))))
    (t (internal-error "Unsupported AST node"))))
(defun check-program (program)
  (unless (typep program 'program) (internal-error "Expected Program"))
  (let* ((*checked* (%make-checked-program :program program
                   :summaries (make-hash-table :test #'eq) :symbols (make-hash-table :test #'eq)
                   :literals (make-hash-table :test #'eq) :consumed (make-hash-table :test #'eq)
                   :bindings (make-array 0 :adjustable t :fill-pointer 0)
                   :signatures (make-array 0 :adjustable t :fill-pointer 0)
                   :calls (make-hash-table :test #'eq) :returns (make-hash-table :test #'eq)
                   :functions (make-hash-table :test #'eq) :loops (make-hash-table :test #'eq)
                   :controls (make-hash-table :test #'eq) :operations (make-hash-table :test #'eq)
                   :values (make-value-context) :node-owners (make-hash-table :test #'eq)))
         (*owner* 0) (*loops* nil) (*template-owner* nil) (*template-edges* (make-hash-table))
         (*scopes* (list (make-hash-table :test #'equal))))
    (vector-push-extend (make-signature :id 0 :result-type :bool) (checked-program-signatures *checked*))
    (prepare-value-declarations (c-context) program)
    (c-template-signatures program)
    (c-implementations program)
    (c-template-bodies program)
    (let ((summary (c-sequence program (program-statements program) (program-root program))))
      (c-context-check (or (program-root program) program) summary :bool))
    (check-call-graph (loop for sig across (checked-program-signatures *checked*)
                           when (signature-template-node sig) collect (signature-id sig))
                      *template-edges* (lambda (span) (fail-at span :semantic "Cyclic template reference")))
    (loop for sig across (checked-program-signatures *checked*) do
      (setf (signature-captures sig) (sort (signature-captures sig) #'< :key #'local-symbol-id)))
    *checked*))
(defun checked-string-literals (checked)
  (sort (loop for node being the hash-keys of (checked-program-summaries checked)
              when (typep node 'string-literal) collect node)
        #'< :key (lambda (node) (span-start (node-span node)))))
