(in-package #:mognitio.semantic)

(defun c-branch (node)
  (let* ((on (eq (branch-expression-mode node) :on))
         (subject (when on (c-expression (branch-expression-subject node))))
         (type (when subject (c-structure subject))) (seen nil) (fallback nil)
         (normal-types nil) (structures nil) (normal nil) (reachable (if on (c-normal subject) t))
         (exits (when subject (copy-list (completion-exits subject)))))
    (when (and on (not (nominal-type-p type :enum)))
      (fail-at (node-span node) :semantic "Branch target requires sum structure"))
    (loop for arm across (branch-expression-arms node)
          for selector = (branch-arm-selector arm) do
      (when fallback (fail-at (node-span arm) :semantic "Else must be last"))
      (let ((*scopes* (cons (make-hash-table :test #'equal) *scopes*)))
        (cond
          (on
           (unless selector (fail-at (node-span arm) :semantic "Sum branch does not permit else"))
           (let* ((selected (resolve-type-token (c-context) (variant-pattern-name selector)))
                  (variant (c-variant selected (variant-pattern-variant selector)))
                  (binders (variant-pattern-bindings selector)))
             (unless (equal selected type) (fail-at (node-span selector) :type "Pattern sum identity mismatch"))
             (when (member (variant-info-id variant) seen) (fail-at (node-span selector) :semantic "Duplicate variant"))
             (push (variant-info-id variant) seen)
             (c-member selector (make-member-info :kind :pattern :type type :variant (variant-info-id variant)))
             (when (plusp (length binders))
               (unless (= (length binders) (length (variant-info-types variant)))
                 (fail-at (node-span selector) :semantic "Payload-free case cannot bind a value"))
               (loop for binder across binders for expected in (variant-info-types variant)
                     for actual = (resolve-type-token (c-context) (parameter-type binder)) do
                 (unless (equal actual expected) (fail-at (node-span binder) :type "Payload annotation mismatch"))
                 (c-declare binder (parameter-name binder) :pattern expected)
                 (c-summary binder expected t nil)))))
          ((null selector) (setf fallback t))
          (t
           (let ((condition (c-expression selector)))
             (c-context-check selector condition :bool)
             (when reachable
               (setf exits (union exits (completion-exits condition) :test #'equal)
                     reachable (c-normal condition))))))
        (let ((summary (c-expression (branch-arm-value arm))))
          (when (c-normal summary) (pushnew (completion-normal-type summary) normal-types :test #'equal))
          (push (c-structure summary) structures)
          (when reachable
            (setf normal (or normal (c-normal summary))
                  exits (union exits (completion-exits summary) :test #'equal))))))
    (when (rest normal-types) (fail-at (node-span node) :type "Branch normal result types differ"))
    (if on
        (unless (= (length seen) (length (type-info-variants (context-type (c-context) type))))
          (fail-at (node-span node) :semantic "Nonexhaustive sum branch"))
        (unless fallback (fail-at (node-span node) :semantic "When branch requires final else")))
    (c-member node (make-member-info :kind :branch :type type))
    (c-summary node (or (first normal-types)
                        (when (and (first structures) (every (lambda (s) (equal s (first structures))) structures))
                          (first structures)))
               normal nil exits)))
(defun c-loop (node)
  (let* ((info (make-loop-info :id (hash-table-count (checked-program-loops *checked*)) :owner *owner* :node node))
         (binder (loop-expression-binder node))
         (*scopes* (cons (make-hash-table :test #'equal) *scopes*))
         (type (when binder (resolve-type-token (c-context) (parameter-type binder))))
         (symbol (when binder (c-declare binder (parameter-name binder) :element type t)))
         (target (or (loop-expression-target node) (loop-expression-condition node)))
         (head (progn (setf (gethash node (checked-program-loops *checked*)) info)
                      (when target (c-expression target)))))
    (when head (c-context-check target head (if binder (list :list type) :bool)))
    (when binder
      (setf (cdr (c-lookup (local-symbol-name symbol))) :visible)
      (c-summary binder type t nil))
    (let* ((*loops* (cons info *loops*)) (body (c-expression (loop-expression-body node)))
           (body-exits (completion-exits body))
           (break-types (remove-duplicates
                          (loop for e in body-exits
                                when (and (eq (first e) :break) (= (second e) (loop-info-id info)))
                                  collect (third e)) :test #'equal))
           (structure (if target :void (first break-types)))
           (normal (if head (c-normal head) (not (null break-types)))))
      (c-context-check (loop-expression-body node) body :void)
      (when (rest break-types) (fail-at (node-span node) :type "Loop break result types differ"))
      (setf (loop-info-normal-type info) (when normal structure))
      (c-summary node structure normal nil
        (union (when head (completion-exits head))
               (when (or (null head) (c-normal head))
                 (remove-if (lambda (e) (and (member (first e) '(:break :continue))
                                            (= (second e) (loop-info-id info)))) body-exits))
               :test #'equal)))))
(defun c-control (node)
  (unless *loops* (fail-at (node-span node) :semantic "Loop control has no target"))
  (let* ((info (first *loops*)) (loop (loop-info-node info))
         (break-p (typep node 'break-statement))
         (value (when break-p (break-statement-value node)))
         (valued-loop (not (or (loop-expression-target loop) (loop-expression-condition loop)))))
    (when (and break-p (not (eq (not (null value)) valued-loop)))
      (fail-at (node-span node) :semantic "Break operand does not match loop form"))
    (let ((child (when value (c-expression value))))
      (setf (gethash node (checked-program-controls *checked*)) info)
      (c-summary node nil nil (when child (list child))
        (when (or (null child) (c-normal child))
          (list (list (if break-p :break :continue) (loop-info-id info)
                      (if child (completion-normal-type child) :void) nil)))))))
(defun c-return (node)
  (when (zerop *owner*) (fail-at (node-span node) :semantic "Return requires a function"))
  (let* ((child (c-expression (return-statement-value node)))
         (signature (aref (checked-program-signatures *checked*) *owner*)))
    (c-context-check (return-statement-value node) child (signature-result-type signature))
    (setf (gethash node (checked-program-returns *checked*)) *owner*)
    (c-summary node nil nil (list child) (when (c-normal child) (list (list :return *owner* nil nil))))))
(defun c-try (node)
  (when (zerop *owner*) (fail-at (node-span node) :semantic "Try requires a function"))
  (let* ((child (c-expression (try-expression-operand node)))
         (arguments (canonical-result-arguments (c-context) (c-structure child)))
         (returned (signature-result-type (aref (checked-program-signatures *checked*) *owner*)))
         (target (canonical-result-arguments (c-context) returned)))
    (unless (and arguments target (equal (second arguments) (second target)))
      (fail-at (node-span node) :type "Try requires canonical Result with identical error types"))
    (setf (gethash node (checked-program-errors *checked*))
          (make-error-info :kind :try :operand-type (c-structure child) :result-type (first arguments)
                           :return-type returned :owner *owner*))
    (c-summary node (first arguments) (c-normal child) (list child)
               (when (c-normal child) (list (list :return *owner* nil nil))))))
(defun c-panic (node)
  (let ((child (c-expression (panic-expression-block node))))
    (c-context-check (panic-expression-block node) child :string)
    (setf (gethash node (checked-program-errors *checked*))
          (make-error-info :kind :panic :operand-type (c-structure child) :owner *owner*))
    (c-summary node nil nil (list child) (when (c-normal child) (list (list :failure *owner*))))))
