(in-package #:mognitio.semantic)

(defvar *checked*)
(defvar *owner* 0)
(defvar *scopes*)
(defvar *loops* nil)
(defvar *template-owner* nil)
(defvar *template-edges*)
(defun c-context () (checked-program-values *checked*))
(defun c-normal (summary) (not (null (completion-normal-type summary))))
(defun c-structure (summary) (completion-structure summary))
(defun c-summary (node structure normal children &optional extra-exits)
  (let ((reachable t) (exits nil))
    (dolist (child children)
      (when reachable (setf exits (union exits (completion-exits child) :test #'equal)))
      (unless (c-normal child) (setf reachable nil)))
    (setf exits (union exits extra-exits :test #'equal))
    (when (and normal (null structure)) (internal-error "Normal result requires structure"))
    (setf (gethash node (checked-program-node-owners *checked*)) *owner*
          (gethash node (checked-program-summaries *checked*))
          (make-completion :structure structure :normal-type (when normal structure)
                           :may-return (not (null (find :return exits :key #'first))) :exits exits))))
(defun c-context-check (node summary expected)
  (check-adaptation (c-context) node (completion-normal-type summary) expected))
(defun c-operation (node kind operands parameters result)
  (setf (gethash node (checked-program-operations *checked*))
        (make-operation-info :kind kind :operands operands :parameter-types parameters :result-type result)))
(defun c-lookup (name)
  (loop for scope in *scopes* for entry = (gethash name scope) when entry return entry))
(defun c-declare (node token mutability type &optional reserved)
  (let ((name (token-text token)) (context (c-context)))
    (when (or (c-lookup name) (gethash name (value-context-names context))
              (gethash name (value-context-declarations context))
              (member name '("Self" "Function") :test #'string=))
      (fail-at (token-span token) :semantic "Name is declared or reserved"))
    (let ((symbol (make-local-symbol :id (length (checked-program-bindings *checked*)) :owner *owner*
                                    :name name :mutability mutability :type type :span (token-span token))))
      (vector-push-extend symbol (checked-program-bindings *checked*))
      (setf (gethash name (first *scopes*)) (cons symbol (if reserved :reserved :visible))
            (gethash node (checked-program-symbols *checked*)) symbol)
      symbol)))
(defun c-reference (node token)
  (let ((entry (c-lookup (token-text token))))
    (unless (and entry (eq (cdr entry) :visible))
      (fail-at (token-span token) :semantic "Name is not visible"))
    (let ((symbol (car entry)))
      (loop for owner = *owner* then (signature-parent (aref (checked-program-signatures *checked*) owner))
            until (= owner (local-symbol-owner symbol)) do
        (when (zerop owner) (internal-error "Capture escaped its lexical boundary"))
        (pushnew symbol (signature-captures (aref (checked-program-signatures *checked*) owner)) :test #'eq))
      (setf (gethash node (checked-program-symbols *checked*)) symbol))))
(defun c-sequence (node statements tail)
  (let ((children nil) (reachable t))
    (loop for statement across statements do
      (unless reachable (fail-at (node-span statement) :semantic "Unreachable sequence element"))
      (let ((summary (c-expression statement))) (push summary children) (setf reachable (c-normal summary))))
    (when tail
      (unless reachable (fail-at (node-span tail) :semantic "Unreachable tail"))
      (push (c-expression tail) children))
    (c-summary node (if tail (c-structure (first children)) (when reachable :void))
               (and reachable (or (null tail) (c-normal (first children)))) (reverse children))))
(defun c-signature (node &optional (parameters nil) receiver)
  (let* ((id (length (checked-program-signatures *checked*)))
         (source-parameters (coerce (function-expression-parameters node) 'list))
         (types (mapcar (lambda (p) (resolve-type-token (c-context) (parameter-type p)))
                        (if receiver (rest source-parameters) source-parameters)))
         (signature (make-signature :id id :declaration node :parent *owner*
                      :parameter-types types :result-type (resolve-type-token (c-context) (function-expression-result-type node))
                      :type-parameters parameters :lexical-parameters (visible-type-parameters (c-context)))))
    (vector-push-extend signature (checked-program-signatures *checked*))
    (setf (gethash node (checked-program-functions *checked*)) signature)
    signature))
(defun c-function-body (node signature &optional receiver-type)
  (let ((*owner* (signature-id signature)) (*loops* nil)
        (*scopes* (cons (make-hash-table :test #'equal) *scopes*)))
    (let ((parameters (coerce (function-expression-parameters node) 'list)))
      (when receiver-type
        (let* ((p (pop parameters)) (binding (c-declare p (parameter-name p) :receiver receiver-type)))
          (setf (signature-receiver signature) binding)
          (c-summary p receiver-type t nil)))
      (loop for p in parameters for type in (signature-parameter-types signature) do
        (c-declare p (parameter-name p) :parameter type) (c-summary p type t nil))
      (let ((body (c-expression (function-expression-body node))))
        (c-context-check (function-expression-body node) body (signature-result-type signature)))))
  signature)
(defun c-function (node)
  (let ((signature (c-signature node)))
    (c-function-body node signature)
    (c-summary node (signature-type signature) t nil)))
(defun c-template-signatures (program)
  (loop for declaration across (program-declarations program)
        when (typep declaration 'template-declaration) do
    (let* ((node (template-declaration-function declaration))
           (id (length (checked-program-signatures *checked*))))
      (call-with-type-parameters (c-context) (template-declaration-parameters declaration) (list :function id)
        (lambda (parameters)
          (let ((signature (c-signature node parameters)))
            (setf (signature-template-node signature) declaration
                  (gethash (token-text (template-declaration-name declaration))
                           (value-context-function-templates (c-context))) signature)))))))
(defun c-template-bodies (program)
  (loop for declaration across (program-declarations program)
        when (typep declaration 'template-declaration) do
    (let* ((node (template-declaration-function declaration))
           (signature (gethash node (checked-program-functions *checked*)))
           (*scopes* nil) (*template-owner* (signature-id signature)))
      (call-with-type-parameters (c-context) (template-declaration-parameters declaration)
          (list :function (signature-id signature))
        (lambda (parameters)
          (declare (ignore parameters))
          (c-function-body node signature)
          (c-summary node (signature-type signature) t nil))))))
(defun c-specialization (node)
  (let* ((signature (gethash (token-text (specialization-reference-name node))
                            (value-context-function-templates (c-context)))))
    (unless signature (fail-at (node-span node) :semantic "Unknown template"))
    (let* ((arguments (resolve-function-type-arguments (c-context) signature (specialization-reference-arguments node) node))
           (type (substitute-generic-type (c-context) (signature-type signature)
                                         (pairlis (signature-type-parameters signature) arguments))))
      (when *template-owner*
        (push (cons (signature-id signature) (node-span node)) (gethash *template-owner* *template-edges*)))
      (setf (gethash node (checked-program-calls *checked*))
            (make-call-info :type type :owner *owner* :template (signature-id signature)
                            :type-arguments arguments :targets (list (signature-id signature))))
      (c-summary node type t nil))))
