(in-package #:mognitio.semantic)

(defun verify-specialization-internal (checked)
  (let* ((proof (checked-program-specialization checked)) (source (specialization-proof-source proof))
         (instances (specialization-proof-instances proof)) (context (copy-instantiation-context (checked-program-values source)))
         (mapping (specialization-proof-type-map proof)) (actual (checked-program-values checked))
         (visited (make-hash-table :test #'eq)) (seen-locals (make-hash-table :test #'eq))
         (keys (make-hash-table :test #'equal)) (free (derive-function-free-parameters source)))
    (verify-checked-program source)
    (labels ((ensure (ok message) (unless ok (internal-error message)))
             (runtime-type (type)
               (cond ((null type) nil)
                     ((function-type-p type) (list :function (mapcar #'runtime-type (second type)) (runtime-type (third type))))
                     ((list-type-p type) (list :list (runtime-type (second type))))
                     ((nominal-type-p type) (or (gethash type mapping) (internal-error "Missing concrete type correspondence")))
                     ((symbolic-type-p type) (internal-error "Symbolic type escaped specialization"))
                     (t type)))
             (subtype (type instance)
               (runtime-type (substitute-generic-type context type (function-instance-environment instance))))
             (require-instance (id instance &optional arguments)
               (let* ((signature (aref (checked-program-signatures source) id))
                      (args (or arguments (mapcar (lambda (p) (cdr (assoc p (function-instance-environment instance) :test #'equal)))
                                                  (signature-type-parameters signature))))
                      (env (instance-environment source context free id args (function-instance-environment instance)))
                      (key (canonical-function-instance-key source context free id args env)))
                 (or (gethash key keys) (internal-error "Missing concrete function correspondence"))))
             (binding (old instance)
               (let ((owner (require-instance (local-symbol-owner old) instance)))
                 (or (gethash (local-symbol-id old) (function-instance-locals owner)) (internal-error "Missing capture or local mapping"))))
             (loop-id (old instance)
               (loop-info-id (or (gethash old (function-instance-loops instance)) (internal-error "Missing loop mapping"))))
             (exits (old instance)
               (mapcar (lambda (exit)
                         (ecase (first exit)
                           (:failure (list :failure (function-instance-id instance)))
                           (:return (list :return (function-instance-id instance) nil nil))
                           ((:break :continue) (list (first exit) (loop-id (second exit) instance) (subtype (third exit) instance) nil))))
                       old))
             (node-map (old instance) (gethash old (function-instance-nodes instance)))
             (function-target (node instance)
               (typecase node
                 (function-expression (require-instance (signature-id (checked-function source node)) instance))
                 (specialization-reference
                  (let ((call (checked-call source node)))
                    (require-instance (call-info-template call) instance
                      (mapcar (lambda (type) (substitute-generic-type context type (function-instance-environment instance))) (call-info-type-arguments call)))))))
             (verify-node (old new instance root)
               (ensure (and new (eq new (node-map old instance)) (not (gethash new visited))
                            (equalp (node-span old) (node-span new))) "Invalid node correspondence")
               (setf (gethash new visited) t)
               (let ((target (unless root (function-target old instance)))
                     (before (gethash old (checked-program-summaries source)))
                     (after (gethash new (checked-program-summaries checked))))
                 (if target
                     (ensure (and (typep new 'concrete-function-reference)
                                  (= (concrete-function-reference-target new) (function-instance-id target))
                                  (eq (checked-function checked new) (function-instance-signature target))) "Invalid closure code reference")
                     (progn
                       (ensure (eq (type-of old) (type-of new)) "Changed specialized syntax category")
                       (dolist (slot (sb-mop:class-slots (class-of old)))
                         (let* ((name (sb-mop:slot-definition-name slot)) (a (slot-value old name)) (b (slot-value new name)))
                           (cond
                             ((and root (member name '(mognitio.syntax::body mognitio.syntax::parameters))) nil)
                             ((member name (syntax-child-slots old))
                              (cond ((null a) (ensure (null b) "Unexpected child"))
                                    ((and (vectorp a) (not (stringp a)))
                                     (ensure (= (length a) (length b)) "Changed child arity")
                                     (loop for child across a for copy across b do (verify-node child copy instance nil)))
                                    (t (verify-node a b instance nil))))
                             ((member name '(mognitio.syntax::declarations mognitio.syntax::type-parameters)) (ensure (zerop (length b)) "Un-erased declaration"))
                             (t (ensure (equalp a b) "Changed source field")))))))
                 (ensure (eql (not (null before)) (not (null after))) "Changed summary coverage")
                 (when before
                   (ensure (and (equal (subtype (completion-structure before) instance) (completion-structure after))
                                (equal (subtype (completion-normal-type before) instance) (completion-normal-type after))
                                (equal (completion-targets before) (completion-targets after))
                                (eql (completion-may-return before) (completion-may-return after))
                                (v-set-equal (exits (completion-exits before) instance) (completion-exits after))
                                (= (function-instance-id instance) (gethash new (checked-program-node-owners checked))))
                           "Changed symbolic flow proof"))
                 (let ((symbol (gethash old (checked-program-symbols source))))
                   (ensure (if symbol (eq (binding symbol instance) (gethash new (checked-program-symbols checked)))
                               (null (gethash new (checked-program-symbols checked)))) "Invalid binding substitution"))
                 (multiple-value-bind (value found) (gethash old (checked-program-literals source))
                   (ensure (and (eql found (checked-literal-p checked new)) (or (not found) (= value (checked-literal checked new)))) "Changed literal"))
                 (ensure (eql (gethash old (checked-program-consumed source)) (gethash new (checked-program-consumed checked))) "Changed consumed literal")
                 (let ((operation (checked-operation source old)) (copy (checked-operation checked new)))
                   (ensure (if operation
                     (and copy (eq (operation-info-kind operation) (operation-info-kind copy))
                          (equal (mapcar (lambda (x) (node-map x instance)) (operation-info-operands operation)) (operation-info-operands copy))
                          (equal (mapcar (lambda (x) (subtype x instance)) (operation-info-parameter-types operation)) (operation-info-parameter-types copy))
                          (equal (subtype (operation-info-result-type operation) instance) (operation-info-result-type copy))) (null copy))
                     "Changed selected symbolic operation"))
                 (let ((error (checked-error source old)) (copy (checked-error checked new)))
                   (ensure (if error (and copy (eq (error-info-kind error) (error-info-kind copy))
                                          (= (function-instance-id instance) (error-info-owner copy))
                                          (equal (subtype (error-info-operand-type error) instance) (error-info-operand-type copy))
                                          (equal (subtype (error-info-result-type error) instance) (error-info-result-type copy))
                                          (equal (subtype (error-info-return-type error) instance) (error-info-return-type copy))) (null copy)) "Invalid error substitution"))
                 (let ((member (checked-member source old)) (copy (checked-member checked new)))
                   (ensure (if member (and copy (eq (member-info-kind member) (member-info-kind copy))
                                           (equal (subtype (member-info-type member) instance) (member-info-type copy))
                                           (equal (subtype (member-info-contract member) instance) (member-info-contract copy))
                                           (equal (member-info-index member) (member-info-index copy))
                                           (eql (member-info-variant member) (member-info-variant copy))) (null copy)) "Invalid member substitution"))
                 (let ((call (gethash old (checked-program-calls source))) (copy (gethash new (checked-program-calls checked))))
                   (ensure (if call (and copy (equal (subtype (call-info-type call) instance) (call-info-type copy))
                                         (= (function-instance-id instance) (call-info-owner copy))
                                         (null (call-info-template copy)) (null (call-info-type-arguments copy))
                                         (equal (mapcar (lambda (id)
                                           (function-instance-id (require-instance id instance
                                             (when (call-info-template call)
                                               (mapcar (lambda (x) (substitute-generic-type context x (function-instance-environment instance))) (call-info-type-arguments call))))))
                                           (call-info-targets call)) (call-info-targets copy))) (null copy)) "Invalid call substitution"))
                 (ensure (if (gethash old (checked-program-returns source))
                             (eql (function-instance-id instance) (gethash new (checked-program-returns checked)))
                             (null (gethash new (checked-program-returns checked)))) "Invalid return substitution")
                 (let ((control (gethash old (checked-program-controls source))))
                   (ensure (if control
                               (eq (gethash (loop-info-id control) (function-instance-loops instance))
                                   (gethash new (checked-program-controls checked)))
                               (null (gethash new (checked-program-controls checked)))) "Invalid control substitution"))
                 (let ((loop (gethash old (checked-program-loops source)))
                       (copy (gethash new (checked-program-loops checked))))
                   (ensure (if loop
                     (and (eq copy (gethash (loop-info-id loop) (function-instance-loops instance)))
                          (eq (loop-info-node copy) new) (= (loop-info-owner copy) (function-instance-id instance))
                          (equal (subtype (loop-info-normal-type loop) instance) (loop-info-normal-type copy))
                          (eql (loop-info-plain loop) (loop-info-plain copy))
                          (eql (loop-info-valued loop) (loop-info-valued copy))
                          (equal (mapcar (lambda (x) (subtype x instance)) (loop-info-types loop)) (loop-info-types copy)))
                     (null copy)) "Invalid loop substitution"))
                 (let ((pack (checked-pack source old)) (copy (checked-pack checked new)))
                   (ensure (if pack (and copy (= (implementation-info-id pack) (implementation-info-id copy))) (null copy)) "Invalid evidence substitution")))))
      (ensure (= (length instances) (length (checked-program-signatures checked))) "Invalid instance count")
      (loop for instance in instances for id from 0 do
        (ensure (and (= id (function-instance-id instance)) (not (gethash (function-instance-key instance) keys))) "Duplicate instance")
        (setf (gethash (function-instance-key instance) keys) instance)
        (ensure (equal (function-instance-key instance)
                       (canonical-function-instance-key source context free (function-instance-declaration instance)
                         (function-instance-arguments instance) (function-instance-environment instance))) "Invalid instance key"))
      ;; Body-only generic applications may not exist in the symbolic context.
      ;; Recreate their identities from original templates and explicit arguments,
      ;; never from the producer's cached fields or payload layouts.
      (let ((recorded (specialization-proof-type-context proof)))
        (loop for id from (length (value-context-types context)) below (length (value-context-types recorded))
              for proposed = (aref (value-context-types recorded) id)
              for template = (gethash (type-info-origin proposed) (value-context-templates context)) do
          (ensure (and template (notany #'symbolic-type-p (type-info-arguments proposed))) "Invalid concrete type origin")
          (dolist (argument (type-info-arguments proposed)) (concrete-type-key context argument))
          (let ((derived (instantiate-generic-type context template (type-info-arguments proposed))))
            (ensure (equal derived (canonical-type proposed)) "Invalid concrete type identity"))))
      (maphash (lambda (original target)
        (let ((a (context-type context original)) (b (context-type actual target)))
          (ensure (and (eq (type-info-kind a) (type-info-kind b))
                        (string= (type-info-name a) (type-info-name b))
                        (eql (type-info-origin a) (type-info-origin b))
                        (eql (or (type-info-source-id a) (type-info-id a)) (type-info-source-id b))
                        (equal (mapcar #'runtime-type (type-info-arguments a)) (type-info-arguments b))
                        (equal (mapcar (lambda (m) (list (requirement-name m) (mapcar #'runtime-type (requirement-parameters m)) (runtime-type (requirement-result m)))) (type-info-methods a))
                               (mapcar (lambda (m) (list (requirement-name m) (requirement-parameters m) (requirement-result m))) (type-info-methods b)))
                        (equal (mapcar (lambda (p) (cons (car p) (runtime-type (cdr p)))) (type-info-fields a)) (type-info-fields b))
                        (equal (mapcar (lambda (v) (list (variant-info-id v) (variant-info-name v) (mapcar #'runtime-type (variant-info-types v)))) (type-info-variants a))
                               (mapcar (lambda (v) (list (variant-info-id v) (variant-info-name v) (variant-info-types v))) (type-info-variants b))))
                   "Invalid concrete layout"))) mapping)
      (ensure (= (hash-table-count mapping) (length (value-context-types actual))
                 (length (remove-duplicates (loop for type being the hash-values of mapping collect type) :test #'equal)))
              "Unexpected or aliased runtime type identity")
      (ensure (= (length (value-context-implementations actual))
                 (length (value-context-implementations (checked-program-values source)))) "Unexpected implementation table")
      (loop for old across (value-context-implementations (checked-program-values source))
            for copy across (value-context-implementations actual) do
        (ensure (and (= (implementation-info-id old) (implementation-info-id copy))
                     (equal (runtime-type (implementation-info-concrete old)) (implementation-info-concrete copy))
                     (equal (runtime-type (implementation-info-contract old)) (implementation-info-contract copy))
                     (equal (mapcar (lambda (p) (cons (car p) (function-instance-signature
                                     (require-instance (signature-id (cdr p)) (first instances))))) (implementation-info-methods old))
                            (implementation-info-methods copy))) "Invalid concrete dispatch table"))
      (dolist (instance instances)
        (let* ((id (function-instance-declaration instance)) (old (aref (checked-program-signatures source) id))
               (sig (function-instance-signature instance)))
          (ensure (and (eq sig (aref (checked-program-signatures checked) (function-instance-id instance)))
                        (= (signature-id sig) (function-instance-id instance))
                        (null (signature-type-parameters sig)) (null (signature-lexical-parameters sig))
                        (eql (signature-parent sig) (if (zerop id) 0 (function-instance-id (require-instance (signature-parent old) instance))))
                        (eq (signature-receiver sig) (when (signature-receiver old) (binding (signature-receiver old) instance)))
                        (equal (signature-method sig) (when (signature-method old)
                          (list (runtime-type (first (signature-method old))) (runtime-type (second (signature-method old))) (third (signature-method old)))))
                        (equal (mapcar (lambda (x) (subtype x instance)) (signature-parameter-types old)) (signature-parameter-types sig))
                        (equal (subtype (signature-result-type old) instance) (signature-result-type sig))
                        (equal (mapcar (lambda (x) (binding x instance)) (signature-captures old)) (signature-captures sig)))
                   "Invalid concrete signature or captures")
          (maphash (lambda (old-id new)
            (let ((original (aref (checked-program-bindings source) old-id)))
              (ensure (and (not (gethash new seen-locals)) (= (local-symbol-owner original) id)
                            (= (local-symbol-owner new) (function-instance-id instance))
                            (eq new (aref (checked-program-bindings checked) (local-symbol-id new)))
                            (equal (local-symbol-type new) (subtype (local-symbol-type original) instance))
                            (eq (local-symbol-mutability new) (local-symbol-mutability original))
                            (equal (local-symbol-name new) (local-symbol-name original))
                            (equalp (local-symbol-span new) (local-symbol-span original))) "Invalid concrete binding")
              (setf (gethash new seen-locals) t))) (function-instance-locals instance))
          (if (zerop id) (verify-node (checked-program-program source) (checked-program-program checked) instance nil)
              (progn
                ;; Function declarations belong to their code instance; creation
                ;; expressions elsewhere become closure references.
                (verify-node (signature-declaration old) (signature-declaration sig) instance t)
                (loop for a across (function-expression-parameters (signature-declaration old))
                      for b across (function-expression-parameters (signature-declaration sig)) do (verify-node a b instance nil))
                (verify-node (function-expression-body (signature-declaration old)) (function-expression-body (signature-declaration sig)) instance nil)))))
      (ensure (= (length (checked-program-bindings checked)) (hash-table-count seen-locals)) "Unexpected concrete local")
      (ensure (= (hash-table-count visited) (reduce #'+ instances :key (lambda (i) (hash-table-count (function-instance-nodes i))))) "Unexpected node mapping")
      (dolist (table (list (checked-program-summaries checked) (checked-program-symbols checked)
                          (checked-program-literals checked) (checked-program-consumed checked)
                          (checked-program-calls checked) (checked-program-returns checked)
                          (checked-program-functions checked) (checked-program-loops checked)
                          (checked-program-controls checked) (checked-program-operations checked)
                          (checked-program-errors checked) (checked-program-node-owners checked)
                          (value-context-members actual) (value-context-packs actual)))
        (maphash (lambda (node value) (declare (ignore value))
                   (ensure (gethash node visited) "Metadata outside verified syntax")) table))
      checked)))
(defun verify-specialization (checked)
  (handler-case (verify-specialization-internal checked)
    (internal-failure (condition) (error condition))
    (error () (internal-error "Malformed monomorphic program"))))
(defun prepare-runtime-program (checked)
  (unless (typep checked 'checked-program) (internal-error "Expected a checked program"))
  (if (checked-program-specialization checked) (verify-specialization checked)
      (verify-specialization (specialize-program checked))))
