(in-package #:mognitio.testing)

(defun verify-test-plan (plan)
  (let ((expected nil) (seen (make-hash-table :test #'eq))
        (project (test-plan-project plan)) (checked (test-plan-checked plan)))
    (mognitio.semantic:verify-checked-program checked)
    (unless (and (eq project (mognitio.syntax::program-project (mognitio.semantic:checked-program-program checked)))
                 (eq :test-check (mognitio.project::project-entry-policy project)))
      (internal-error "Test plan does not own a fully checked project"))
    (dolist (module (mognitio.project::project-modules project))
      (dolist (decl (mognitio.project::source-module-declarations module))
        (when (find "test" (mognitio.syntax:declaration-attributes (mognitio.project::module-declaration-node decl))
                    :test #'string= :key (lambda (a) (mognitio.syntax:token-text (mognitio.syntax:attribute-syntax-name a))))
          (push decl expected))))
    (loop with previous = nil for test across (test-plan-cases plan) for ordinal from 0
          for decl = (test-case-declaration test) for module = (mognitio.project::module-declaration-module decl)
          for span = (mognitio.syntax:declaration-span (mognitio.project::module-declaration-node decl))
          for path = (mognitio.project::source-module-path module) do
      (unless (and (member decl expected) (not (gethash decl seen)) (= ordinal (test-case-ordinal test))
                   (eq span (test-case-span test))
                   (equal (test-case-identity test)
                          (format nil "~A::~A::~A" path (mognitio.project::source-module-namespace module)
                                  (mognitio.project::module-declaration-name decl)))
                   (or (null previous) (string< (car previous) path)
                       (and (string= (car previous) path) (< (cdr previous) (mognitio.source:span-start span)))))
        (internal-error "Invalid test discovery identity or order"))
      (setf (gethash decl seen) t previous (cons path (mognitio.source:span-start span))))
    (unless (= (hash-table-count seen) (length expected)) (internal-error "Incomplete test discovery")))
  plan)
