(in-package #:mognitio.testing)

;; Private wire enums. The record size is independent of all received fields.
(defconstant +record-size+ 40)
(defconstant +internal-child-status+ 123)
(defconstant +transport-child-status+ 124)
(defconstant +protocol-version+ 3)
(defparameter *event-tags* '((:ready . 1) (:stage . 2) (:terminal . 3)))
(defparameter *event-stages* '((:not-started . 0) (:initialization . 1) (:body . 2)))
(defparameter *event-kinds*
  '((:success . 0) (:assertion . 1) (:panic . 2) (:overflow . 3)
    (:division-by-zero . 4) (:remainder-by-zero . 5) (:string-index-out-of-bounds . 6)
    (:string-size-overflow . 7) (:list-length-overflow . 8) (:allocation-failed . 9)))
(defun event-number (table name)
  (or (cdr (assoc name table)) (internal-error "Unknown private event enum")))
(defun word-at (bytes offset width)
  (loop for i below width sum (ash (aref bytes (+ offset i)) (* 8 i))))

(defstruct event-reader ordinal site-count (sequence 0) (stage 0) ready terminal
  (buffer (make-array 40 :element-type '(unsigned-byte 8))) (used 0) eof)
(defun accept-event (reader)
  (let* ((bytes (event-reader-buffer reader)) (tag (word-at bytes 6 2))
         (stage (word-at bytes 24 4)) (kind (word-at bytes 28 4)) (site (word-at bytes 32 8)))
    (unless (and (= (word-at bytes 0 4) #x544e474d) (= (word-at bytes 4 2) +protocol-version+)
                 (= (word-at bytes 8 8) (event-reader-ordinal reader))
                 (= (word-at bytes 16 8) (event-reader-sequence reader))
                 (not (event-reader-terminal reader)))
      (internal-error "Invalid test event header or sequence"))
    (cond
      ((= tag (event-number *event-tags* :ready))
       (unless (and (not (event-reader-ready reader)) (zerop stage) (zerop kind) (= site #xffffffffffffffff))
         (internal-error "Invalid ready event"))
       (setf (event-reader-ready reader) t))
      ((= tag (event-number *event-tags* :stage))
       (unless (and (event-reader-ready reader) (= stage (1+ (event-reader-stage reader)))
                    (<= 1 stage 2) (zerop kind) (= site #xffffffffffffffff))
         (internal-error "Invalid test stage transition"))
       (setf (event-reader-stage reader) stage))
      ((= tag (event-number *event-tags* :terminal))
       (unless (and (event-reader-ready reader) (<= 1 stage 2) (= stage (event-reader-stage reader))
                    (rassoc kind *event-kinds*) (or (plusp kind) (= stage 2))
                    (if (= kind 1) (< site (event-reader-site-count reader)) (= site #xffffffffffffffff)))
         (internal-error "Invalid terminal event"))
       (setf (event-reader-terminal reader) (cons kind site)))
      (t (internal-error "Unknown test event tag")))
    (incf (event-reader-sequence reader))))
(defun feed-events (reader bytes count)
  (dotimes (i count)
    (setf (aref (event-reader-buffer reader) (event-reader-used reader)) (aref bytes i))
    (when (= (incf (event-reader-used reader)) +record-size+)
      (accept-event reader) (setf (event-reader-used reader) 0))))
